featurebyte/api/feature.py
featurebyte/common/documentation/gen_ref_pages_docs_builder.py
featurebyte/core/accessor/feature_string.py
featurebyte/core/accessor/string.py

Add feature string accessor, similar to https://github.com/featurebyte/featurebyte/pull/1253
https://featurebyte.atlassian.net/browse/DEV-1651 …

docs: add feature string accessor

---

CHANGELOG.md
featurebyte/datasets/healthcare.sql

Update to the latest version of healthcare demo dataset.

[DEV-1688] Update healthcare datasets

---

README.md

* use absolute urls for images in README
* update license badge
Cherry-pick from [#1279](https://github.com/featurebyte/featurebyte/pull/1279) …

Use absolute urls for images in README

---

featurebyte/api/base_table.py
featurebyte/api/feature.py
featurebyte/api/feature_list.py
featurebyte/api/source_table.py

This PR adds more examples into docstrings for reference!
https://featurebyte.atlassian.net/browse/DEV-1651
https://featurebyte.atlassian.net/browse/DEV-1659 …

[chore] docs: add more examples to docstrings

---

README.md

@kchua78 Here is a PR to update the first example in README. This is using the same table name as in the tutorials. I am also using the term basket instead of inventory.

documentation: update example for consistency with the doc

---

.github/workflows/dependencies.yml

```diff
--- branch.PKG-INFO	2023-05-11 08:56:15.614157079 +0000
+++ main.PKG-INFO	2023-05-11 08:56:18.546184214 +0000
@@ -33,7 +33,7 @@
Requires-Dist: requests (>=2.27.1,<3.0.0)
Requires-Dist: rich (>=13.3.4,<14.0.0)
Requires-Dist: sasl (>=0.3.1,<0.4.0) ; extra == "server"
-Requires-Dist: smart-open[azure,gcs] (>=6.3.0,<7.0.0) ; extra == "server"
+Requires-Dist: smart-open (>=6.3.0,<7.0.0) ; extra == "server"
Requires-Dist: snowflake-connector-python (>=3.0.3,<4.0.0) ; extra == "server"
Requires-Dist: sqlglot (>=10.1.3,<10.4)
Requires-Dist: thrift-sasl (>=0.4.3,<0.5.0) ; extra == "server"
```
The below seems more right to me
```diff
--- main.PKG-INFO	2023-05-11 08:56:18.546184214 +0000
+++ branch.PKG-INFO	2023-05-11 08:56:15.614157079 +0000
@@ -33,7 +33,7 @@
Requires-Dist: requests …
```

[chore] make dependencies workflow show changes from main to PR

---

CHANGELOG.md
featurebyte/api/view.py
featurebyte/query_graph/node/generic.py
tests/fixtures/sdk_code/event_view_with_tz_offset_column.py
tests/unit/api/test_scd_view.py
tests/unit/api/test_view.py
tests/unit/query_graph/test_graph_pruning.py

Update feature definition for join operation by specifying `on` parameter explicitly.

[DEV-1271] Update SDK code to pass `on` parameter to  explicitly

---

featurebyte/api/base_table.py

https://featurebyte.atlassian.net/browse/DEV-1701

[chore] docs: update example for column_cleaning_operations

---

featurebyte/session/snowflake.py

This fixes snowflake logging which is producing excessive debug logs in integration tests. This avoids the issue by using `logging.getLogger` directly. …

[chore] Fix snowflake logging level

---

.github/workflows/daily-cron.yml
.github/workflows/dependencies.yml
.github/workflows/documentation.yml
.github/workflows/lint.yml
.github/workflows/publish-dev.yml
.github/workflows/publish-public.yml
.github/workflows/test.yml

+ https://github.com/actions/python-versions/blob/main/versions-manifest.json python 3.8.0 not supported in newer ubuntu version
~~+ use 4-core cpu for slow test [Public repo unable to support gh selfhosted large runners]~~
+ use ubuntu-latest runner
+ removed python-dev dependency. Refer to: https://github.com/lewagon/data-setup/issues/219
| …

chore: base python set 3.8.12 | upgrade to ubuntu-latest

---

CHANGELOG.md
featurebyte/api/view.py
featurebyte/common/documentation/documentation_layout.py
tests/unit/api/base_view_test.py

This PR introduces `column_cleaning_operations` property to view object.

[DEV-1387] Add `column_cleaning_operations` to view object

---

CHANGELOG.md
featurebyte/api/feature.py
featurebyte/api/feature_list.py
tests/unit/api/test_feature.py
tests/unit/api/test_feature_list.py

This PR updates feature's & feature list's `list_versions` object methods.

[DEV-1408] Add `is_default` column to feature's & feature list's `list_versions` object methods

---

CHANGELOG.md
featurebyte/api/base_table.py
featurebyte/api/view.py
featurebyte/common/documentation/documentation_layout.py
tests/unit/api/base_table_test.py
tests/unit/api/base_view_test.py

Add `cleaning_operations` property to `TableColumn` & `ViewColumn` objects to display cleaning operations associated with the specified column. …

[DEV-1703] Add `cleaning_operations` property to `TableColumn` & `ViewColumn` objects

---

.changelog/DEV-1734.yaml
featurebyte/api/feature.py
featurebyte/models/feature.py
featurebyte/query_graph/graph.py
featurebyte/query_graph/model/graph.py
featurebyte/schema/feature.py
tests/fixtures/request_payloads/feature_iet.json
tests/fixtures/request_payloads/feature_item_event.json
tests/fixtures/request_payloads/feature_non_time_based.json
tests/fixtures/request_payloads/feature_sum_2h.json
tests/fixtures/request_payloads/feature_sum_30m.json
tests/unit/routes/test_feature.py

This PRs update feature creation logic by relying on query graph to derive entity IDs.

[DEV-1734] Remove `entity_ids` from feature creation payload

---

.changelog/DEV-1736.yaml
featurebyte/api/event_view.py
featurebyte/api/feature.py
featurebyte/query_graph/graph.py
tests/unit/api/conftest.py
tests/unit/api/test_event_view.py
tests/unit/api/test_feature.py
tests/unit/api/test_request_column.py
tests/unit/conftest.py
tests/unit/query_graph/test_query_graph.py

This PR simplifies SDK `Feature` class by removing redundant inheritance.

[DEV-1736] Refactor `Feature` class to remove redundant inheritance

---

.changelog/DEV-1745.yaml
featurebyte/api/feature.py
featurebyte/api/feature_list.py
featurebyte/models/feature_list.py
tests/unit/api/test_api_object.py
tests/unit/api/test_feature_list.py
tests/unit/migration/conftest.py
tests/unit/migration/test_run.py

Similar to previous PR (https://github.com/featurebyte/featurebyte/pull/1336). This PR removes `FrozenFeatureListModel` inheritance relationship from `FeatureList` class to make the code clearer and easier to maintain. …

[DEV-1745] Refactor `FeatureList` class to drop `FrozenFeatureListModel` inheritance

---

.github/workflows/daily-cron_gen.yaml

Fix the daily cron workflow to take a list of `cron` settings.
This looks to be the correct format from https://github.com/featurebyte/featurebyte/commit/f467f0126f9c4d763168884c730f5cdb4e6c19a0#diff-71d24066386cef9e3791f8beb0fbb6a608dbe2ed88d43e7eb64f679f26fed803L5
| …

[chore] workflows: fix daily cron workflow

---

.github/workflows/publish-dev_gen.yaml

Fix a small typo in a github action.

[chore] workflows: fix typo in github actions

---

.github/workflows/publish-dev_gen.yaml

Small fix to the publish-dev workflow that was missing a step.

[chore] fix publish-dev workflow that was missing a step when migrated

---

.github/workflows/test_gen.yaml

Another small fix to the workflow.

[chore] workflows/test: fix publish due to bad commit hash

---

.github/workflows/publish-dev_gen.yaml

[chore] workflow test/fix

---

featurebyte/common/progress.py
featurebyte/query_graph/sql/feature_historical.py
featurebyte/tile/manager.py
tests/unit/common/progress.py
tests/unit/query_graph/test_feature_historical.py

This adds support for more granular progress update when computing historical features. This also adds a `get_ranged_progress_callback` helper function to simplify progress update of potentially nested steps. …

[DEV-1757] Support more granular progress update when computing historical features

---

.changelog/DEV-1454.yaml
featurebyte/exception.py
featurebyte/middleware.py
featurebyte/routes/common/base.py
featurebyte/service/feature_store_warehouse.py
tests/unit/api/test_event_table.py
tests/unit/api/test_feature_store.py
tests/unit/api/test_observation_table.py
tests/unit/conftest.py
tests/unit/routes/test_feature_store.py
tests/unit/session/test_snowflake_session.py

Provide more informative message for dataSource.list_tables() and list_schemas() when provided database or schema does not exist.
https://featurebyte.atlassian.net/browse/DEV-1454
| …

[DEV-1454] More informative message for dataSource.list_tables() and list_schemas() 

---

.github/workflows/daily-cron_gen.yaml
.github/workflows/dependencies_gen.yaml
.github/workflows/documentation_gen.yaml
.github/workflows/lint_gen.yaml
.github/workflows/publish-dev_gen.yaml
.github/workflows/publish-public_gen.yaml
.github/workflows/test_gen.yaml
CONTRIBUTING.md

[chore] upgrade poetry version to 1.5.1 to improve dependency resolution

---

featurebyte/datasets/creditcard.sql
featurebyte/datasets/grocery.sql

Update credit card dataset with latest
Update SQL scripts to specify column names during select to avoid selecting wrong columns in views
Cherry-pick from https://github.com/featurebyte/featurebyte/pull/1269
https://featurebyte.atlassian.net/browse/DEV-1677
| …

[DEV-1677] Update creditcard dataset (Cherry-pick)

---

featurebyte/api/feature_list.py
tests/unit/api/test_feature_list.py

This PR aims to fix the two flaky tests due to `mock_execute_query` fixture.

[chore] fix flaky feature list get_feature_jobs_status tests

---

.changelog/DEV-1777.yaml
docker/entrypoint.sh
featurebyte/worker/start.py
featurebyte/worker/task_executor.py

Refactor task executor to import tasks explicitly for easier maintenance.
Tasks are also re-written as classes that can be extended more easily.
https://featurebyte.atlassian.net/browse/DEV-1777
| …

[DEV-1777] Refactor task executor to import tasks explicitly

---

.github/workflows/documentation_gen.yaml
.github/workflows/lint_gen.yaml
.github/workflows/notify_gen.yaml
.github/workflows/publish-dev_gen.yaml
.github/workflows/publish-public_gen.yaml
.github/workflows/test_gen.yaml

Pickup recent changes to workflows in `infrastructure` repo.

[chore] workflows: update workflows to pickup changes

---

.changelog/chester-docker-fix.yaml
docker/entrypoint.sh

featurebyte worker cpu is using the wrong runtime

bug: fix dockerfile startup command for worker:cpu

---

.changelog/DEV-1796.yaml
featurebyte/session/base.py
featurebyte/session/base_spark.py

This fixes a bug that causes duplicate entries in the metadata schema for Spark and Databricks. This also bumps the working schema version so that existing installation can pick up recent changes in UDF.
| …

[DEV-1796] Fix duplicate entries in metadata schema for Spark and Databricks

---

.changelog/DEV-1797.yaml
featurebyte/models/feature.py
tests/unit/api/test_feature.py

This PR aims to reduce the time to deserialize feature model & add test to check it.
Script used
```
from datetime import datetime
from bson import ObjectId
import featurebyte as fb
from featurebyte.config import Configurations
catalog_name = "Grocery V1 - playground (spark)"
feature_list_id = "648076beb865d66ab47590e2"
catalog = fb.activate_and_get_catalog(name=catalog_name)
client = Configurations().get_client()
for page in range(1, 4):
start = datetime.now()
response = client.get(
url="/feature", params={"feature_list_id": feature_list_id, "page_size": 100, "page": page}
)
elapsed = datetime.now() - start
print(f"page: {page}, elapsed: {elapsed}")
start = datetime.now()
feature_list = catalog.get_feature_list_by_id(ObjectId(feature_list_id))
print(f"Time taken to load feature list: …
```

enhancement: optimize time to deserialize feature model

---

featurebyte/sql/base.py
featurebyte/sql/tile_schedule_online_store.py
tests/integration/conftest.py
tests/integration/query_graph/test_online_serving.py

This adds a test to perform concurrent writes to the same online store table to reproduce concurrency issues.

[DEV-1770] Add test to perform concurrent writes to online store table

---

.changelog/DEV-1774.yaml
.changelog/DEV-1793.yaml
featurebyte/config.py
featurebyte/service/deploy.py
tests/conftest.py
tests/unit/conftest.py
tests/unit/test_config.py

Cherry-pick fixes into release 0.3
https://featurebyte.atlassian.net/browse/DEV-1774
https://featurebyte.atlassian.net/browse/DEV-1793 …

[chore] Cherry-pick Fixes into release 0.3

---

.changelog/DEV-1799.yaml
featurebyte/routes/feature_list/controller.py
featurebyte/service/feature_list.py
featurebyte/service/mixin.py
tests/unit/api/test_feature_list.py
tests/unit/service/test_feature_list.py

Fix feature list deletion endpoint to update associated features' `feature_list_ids` attribute.

bugfix: `feature_list_ids` of feature model not update properly after associated feature list is deleted

---

featurebyte/query_graph/node/metadata/operation.py
tests/unit/api/test_event_view.py

This PR updates current column hash computation (that is used in operation structure extraction) to reduce computation time.

[chore] enhancement: optimize column hash computation

---

featurebyte/query_graph/node/input.py
featurebyte/query_graph/node/metadata/operation.py
tests/unit/models/test_feature.py
tests/unit/query_graph/test_extract_operation_structure.py
tests/unit/query_graph/test_graph_node.py
tests/unit/query_graph/test_graph_pruning.py
tests/unit/query_graph/test_metadata_operation.py
tests/unit/query_graph/test_nested_graph_pruning.py
tests/unit/query_graph/util.py

This PR removes pydantic `BaseModel` from `*DataColumn` & `*AggregationColumn` (used by operation structure extraction) to optimize operation structure extraction runtime.
command: `sudo -E py-spy record -o profile.svg --  pytest -vv tests/integration/api/test_event_view_operations.py -k test_datetime_operations --source-types=snowflake`
main:
current branch:
Time to save 204 new features drops from 12.5min to 12min.
Time to save a feature list from 204 created features & the feature list drops from 45sec to 40sec.
|       `enhancement`, `feature`        | …

[chore] optimize `*DataColumn` and `*AggregationColumn` construction time in `metadata/operation.py`

---

featurebyte/query_graph/node/base.py
featurebyte/query_graph/node/metadata/operation.py
featurebyte/query_graph/node/nested.py
tests/unit/query_graph/util.py

This PR removes pydantic BaseModel from `OperationStruction` to optimize operation structure extraction runtime.
command: `sudo -E py-spy record -o profile.svg --  pytest -vv tests/integration/api/test_event_view_operations.py -k test_datetime_operations --source-types=snowflake`
main:
current branch:
Time to save 204 new features drops from 12min to 11.5min.
Time to save a feature list from 204 created features & the feature list drops from 40sec to 35sec.
https://github.com/featurebyte/featurebyte/pull/1415
|       `enhancement`, `feature`        |          🚀 …

[chore] optimize `OperationStructure` construction time

---

docker/Dockerfile

1.3.1 => 1.5.1 poetry version. This is only used for installing dependency packages. 
Actual image does not have poetry installed.

[chore] bump Dockerfile poetry version

---

featurebyte/query_graph/model/graph.py
featurebyte/query_graph/transform/pruning.py
featurebyte/query_graph/transform/reconstruction.py
featurebyte/routes/credential/controller.py
featurebyte/routes/feature/controller.py
featurebyte/routes/feature_list/controller.py
featurebyte/routes/feature_list_namespace/controller.py
featurebyte/routes/feature_namespace/controller.py
featurebyte/routes/feature_store/controller.py
featurebyte/service/base_document.py
featurebyte/service/base_table_document.py
featurebyte/service/credential.py
featurebyte/service/feature.py
featurebyte/service/feature_list.py
featurebyte/worker/task/batch_feature_create.py
featurebyte/worker/task/feature_job_setting_analysis.py

This PR updates add pruning sensitive operation & change `json_dict` to `dict(alias=True)`.

[chore] optimize add pruning sensitive operation & change `json_dict` to `dict(alias=True)`

---

featurebyte/query_graph/graph.py
featurebyte/query_graph/model/graph.py
featurebyte/query_graph/transform/flattening.py
featurebyte/query_graph/transform/pruning.py
featurebyte/query_graph/transform/reconstruction.py
tests/unit/core/conftest.py

This PR optimizes query graph's adding node operation by removing redundant node serialization & deserialization steps.
Script used (feature list contains 204 features)
```
from datetime import datetime
import featurebyte as fb
from featurebyte.common.model_util import get_version
from featurebyte.models.base import VersionIdentifier
from featurebyte.models.feature_list import FeatureListModel
from featurebyte.schema.feature import BatchFeatureCreate, FeatureCreate
fb.list_catalogs()
catalog = fb.activate_and_get_catalog("Grocery V1 - playground (spark)")
feature_list_id = catalog.list_feature_lists()["id"].iloc[0]
feature_list = catalog.get_feature_list_by_id(feature_list_id)
def profile_runtime(feature_list: FeatureListModel):
start, next_start = datetime.now(), datetime.now() …
```

[chore] optimize graph add node operation

---

featurebyte/service/base_document.py
featurebyte/service/feature_list.py
tests/unit/api/test_feature_list.py

This PR updates Feature document's `feature_list_ids` update logic when a feature list is created or deleted.

[chore] replace multiple mongo updates with single batch update when saving feature list

---

.changelog/ISSUES-1436.yaml
.github/workflows/daily-cron_gen.yaml
.github/workflows/documentation_gen.yaml
.github/workflows/lint_gen.yaml
.github/workflows/publish-dev_gen.yaml
.github/workflows/publish-public_gen.yaml
.github/workflows/test_gen.yaml

https://github.com/featurebyte/infrastructure/pull/12 adds them to the template. This PR was create via running gen-workflows from that branch. …

[ISSUES-1436] Update workflows with new packages for kerberos support

---

featurebyte/api/api_object.py
featurebyte/api/api_object_util.py
featurebyte/api/feature_group.py
featurebyte/api/feature_list.py
tests/unit/api/test_feature_list.py

This PR extracts logics from feature group's & feature list's `root_validator` into a normal python class method to make it easy to be reused by feature group in the later work.
The plan is to make feature group to follow feature list saving flow. In stead of saving the feature in feature group one by one, for the new flow,
1) create a temporary feature list for the feature group to be saved
2) save the feature list
3) retrieve the features using the temporary feature list id (using batch feature retrieval rather than retrieving the feature one by one)
4) update local feature state & delete the temporary feature list
implementation for the new saving feature group workflow: https://github.com/featurebyte/featurebyte/pull/1439
Label this pull request to place it under the correct category …

[chore] Refactor feature group & feature list

---

.changelog/DEV-1802.yaml
featurebyte/api/feature.py
featurebyte/api/feature_list.py
featurebyte/routes/feature/controller.py
featurebyte/routes/feature_list/api.py
featurebyte/routes/feature_list/controller.py
featurebyte/schema/feature.py
featurebyte/schema/feature_list.py
tests/unit/api/test_feature.py
tests/unit/api/test_feature_list.py
tests/unit/routes/test_feature.py
tests/unit/routes/test_feature_list.py

This PR updates `list_versions` method & documentation.

enhancement: update feature's & feature list's `list_versions` method

---

tests/unit/conftest.py
tests/unit/service/conftest.py
tests/unit/service/test_observation_table.py
tests/unit/service/test_static_source_table.py

Minor refactor to use `app_container` to initialize all services in tests for consistency.

[chore] conftest: use app_container for service def in tests

---

.changelog/DEV-1792.yaml
featurebyte/routes/registry.py
featurebyte/routes/target/controller.py
featurebyte/schema/target.py
featurebyte/service/context.py
featurebyte/service/entity.py
featurebyte/service/feature_list.py
featurebyte/service/info.py
featurebyte/service/relationship.py
featurebyte/service/table_columns_info.py
tests/unit/migration/test_run.py
tests/unit/service/conftest.py
tests/unit/service/test_info.py

Add some basic properties to `TargetInfo`, and return them.
https://featurebyte.atlassian.net/wiki/spaces/DEV/pages/30048265/Target+Info+display …

[DEV-1792] target/info: impl basic info for target

---

featurebyte/routes/common/base.py
featurebyte/routes/feature/controller.py
featurebyte/routes/feature_list_namespace/controller.py
featurebyte/routes/feature_namespace/controller.py
featurebyte/routes/registry.py

Small refactor to allow for better encapsulation, and make dependencies clearer.

[chore] refactor DerivePrimaryEntityHelper for better encapsulation

---

.changelog/DEV-1861.yaml
featurebyte/api/aggregator/forward_aggregator.py
featurebyte/api/target.py
featurebyte/models/target.py
featurebyte/query_graph/node/generic.py
featurebyte/routes/target/controller.py
featurebyte/schema/target.py
tests/unit/api/aggregator/test_forward_aggregator.py
tests/unit/api/test_target.py
tests/unit/models/test_target.py
tests/unit/query_graph/sql/aggregator/test_forward.py
tests/unit/service/test_info.py
tests/unit/test_generate_payload_fixtures.py

This was initially added in the spec, but we realized that it isn't needed. As such, we can remove it here.

[DEV-1861] target: remove blind_spot as it isn't needed 

---

.github/workflows/test_gen.yaml

+ Increase the spark functional test runner to 4 CPU
+ Reduced test from 45 => 30min

[Workflow] sync with infrastructure + upgrade to larger runner

---

.github/workflows/test_gen.yaml

This PR aims to skip databrick integration tests due to access issue (https://github.com/featurebyte/featurebyte/actions/runs/5469868106/jobs/9959836395):
```
=========================== short test summary info ============================
ERROR tests/integration/api/test_event_view_operations.py::test_event_view_ops[databricks] - featurebyte.exception.RecordCreationException: Error during request to server: : Invalid access token.
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
======================== 24 warnings, 1 error in 21.68s ========================
task: Failed to run task "test-integration-databricks": exit status 1
```
|        **Pull Request Label**         | …

[DEV-1886] Temporary skip databrick integration tests

---

featurebyte/api/user_defined_function.py
featurebyte/routes/user_defined_function/controller.py
featurebyte/schema/user_defined_function.py
featurebyte/service/user_defined_function.py
tests/unit/api/test_user_defined_function.py
tests/unit/routes/test_user_defined_function.py

This PR introduces `UserDefinedFunction` update methods to allow user to update user defined function interface after it is created. …

[chore] Implement `UserDefinedFunction` update methods

---

.github/workflows/test_gen.yaml

Reverts featurebyte/featurebyte#1480

Revert "[DEV-1886] Temporary skip databrick integration tests"

---

featurebyte/models/user_defined_function.py
featurebyte/routes/user_defined_function/controller.py
featurebyte/schema/user_defined_function.py
featurebyte/service/user_defined_function.py
tests/unit/models/test_user_defined_function.py
tests/unit/routes/test_user_defined_function.py

This PR fix the bugs where UDF function signature is not updated after attribute get updated.

[chore] Fix signature not updated after `UserDefinedFunction` update

---

featurebyte/feature_manager/model.py
tests/unit/conftest.py

This removes the `ExtendedFeatureListModel` class and related code which is now unused.

[chore] Remove unused ExtendedFeatureListModel

---

featurebyte/api/aggregator/forward_aggregator.py
featurebyte/api/feature_namespace.py
featurebyte/api/target.py
featurebyte/models/feature.py
featurebyte/models/feature_namespace.py
featurebyte/models/target.py
featurebyte/models/target_namespace.py
featurebyte/routes/target/controller.py
featurebyte/schema/target.py
featurebyte/schema/target_namespace.py
featurebyte/service/target.py
tests/fixtures/request_payloads/target.json
tests/unit/api/aggregator/test_forward_aggregator.py
tests/unit/api/test_api_object.py
tests/unit/api/test_feature.py
tests/unit/api/test_target.py
tests/unit/models/test_target.py
tests/unit/routes/test_target.py
tests/unit/service/test_info.py
tests/unit/test_generate_payload_fixtures.py

Revise `TargetModel` & `TargetNamespaceModel` to make it closer to `FeatureModel` & `FeatureNamespaceModel`.

[chore] Revise `TargetModel` & `TargetNamespaceModel`

---

.changelog/DEV-1791.yaml
featurebyte/routes/registry.py
featurebyte/schema/target.py
featurebyte/service/target.py
featurebyte/service/target_helper/compute_target.py
featurebyte/worker/task/historical_feature_table.py
featurebyte/worker/task/target_table.py
featurebyte/worker/util/observation_set_helper.py
tests/integration/api/test_target_correctness.py
tests/unit/routes/test_target_table.py

This PR implements the `compute_target` endpoint, and allows us to fully materialize a target, with a dataframe observation set.
https://featurebyte.atlassian.net/browse/DEV-1791
| …

[DEV-1791] target: implement compute_target

---

featurebyte/routes/observation_table/controller.py
featurebyte/routes/registry.py
featurebyte/service/validator/materialized_table_delete.py
featurebyte/worker/task/materialized_table_delete.py
tests/unit/routes/test_target_table.py

Unskip test that was initially skipped during development. Do this by adding to the observation table delete validation check to make sure that no observation tables are referenced in the target tables.
https://featurebyte.atlassian.net/browse/DEV-1915
| …

[DEV-1915][chore] test_target_table: unskip test for observation table validation

---

featurebyte/routes/app_container_config.py

This PR adds a more explicit error message if a dep is unable to find, with some possible next steps of what to do if you get this error. …

[chore] app_container_config: add explicit error message with call to action

---

featurebyte/api/aggregator/forward_aggregator.py
featurebyte/api/groupby.py
featurebyte/api/target.py
featurebyte/models/target.py
featurebyte/models/target_namespace.py
featurebyte/query_graph/graph.py
featurebyte/query_graph/node/generic.py
featurebyte/query_graph/sql/aggregator/forward.py
featurebyte/routes/target/controller.py
featurebyte/schema/target.py
featurebyte/schema/target_namespace.py
featurebyte/service/target.py
tests/fixtures/request_payloads/target.json
tests/integration/api/test_target_correctness.py
tests/unit/api/aggregator/test_forward_aggregator.py
tests/unit/api/test_target.py
tests/unit/conftest.py
tests/unit/models/test_target.py
tests/unit/query_graph/conftest.py
tests/unit/query_graph/sql/aggregator/test_forward.py
tests/unit/routes/test_target.py
tests/unit/service/test_info.py

Rename the current horizon to window, as horizon will be derived in the future when we add an offset parameter too.
https://featurebyte.atlassian.net/browse/DEV-1931 …

[DEV-1931][chore] target: rename horizon to window

---

featurebyte/api/aggregator/forward_aggregator.py
featurebyte/query_graph/node/generic.py
tests/unit/api/aggregator/test_forward_aggregator.py

Remove unused `table_details` param that isn't needed.

[chore] node/generic: rm unused table_details from params

---

tests/integration/migration/test_data_warehouse_migration.py

This PR updates integration test so that it is not sensitive to test coupling issue.

Fix integration test

---

featurebyte/query_graph/graph.py
featurebyte/query_graph/node/metadata/operation.py
featurebyte/service/view_construction.py

This PR moves the logic to extract table ID to column name mapping to graph so that it can reused later without importing module stored at service level. …

[chore] Move logic to extract table ID to column name mapping to graph

---

featurebyte/query_graph/graph.py
featurebyte/query_graph/node/generic.py
tests/unit/api/test_version.py
tests/unit/query_graph/test_extract_operation_structure.py
tests/unit/query_graph/test_graph_pruning.py

Previous PR (https://github.com/featurebyte/featurebyte/pull/1524) causes bug in identifying source table of the event timestamp column. This PR aims to fix the issue. …

[DEV-1953] Fix bugs in identifying table of the source event timestamp column

---

.changelog/DEV-1948.yaml
featurebyte/api/target.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/common/documentation/gen_ref_pages_docs_builder.py
featurebyte/core/accessor/feature_datetime.py
featurebyte/core/accessor/feature_string.py
featurebyte/core/accessor/target_datetime.py
featurebyte/core/accessor/target_string.py
scripts/test-docs-setup.py

Add the string and date time transformation accessors into the `Target` API object.
https://featurebyte.atlassian.net/browse/DEV-1948 …

[DEV-1948] api/target: add string and datetime accessors

---

featurebyte/models/tile_registry.py
featurebyte/service/feature_manager.py
featurebyte/service/tile/tile_task_executor.py
featurebyte/service/tile_registry_service.py
featurebyte/sql/tile_generate.py
tests/integration/feature_manager/test_feature_manager.py
tests/integration/tile/test_schedule_generate_tile.py
tests/unit/service/tile/test_tile_registry.py

This renames the `LastTileMetadata` model to `LastRunMetadata` and some field names to avoid confusion.

[chore] Rename LastTileMetadata model and field names to avoid confusion

---

.changelog/DEV-1960.yaml
featurebyte/service/feature_readiness.py
tests/unit/api/test_version.py

Fix improper feature readiness comparison bug.

[DEV-1960] Fix feature readiness bug & add tests

---

tests/unit/api/base_materialize_table_test.py
tests/unit/api/test_batch_feature_table.py
tests/unit/api/test_batch_request_table.py
tests/unit/api/test_historical_feature_table.py
tests/unit/api/test_observation_table.py
tests/unit/api/test_target_table.py

Refactor materialized table API object tests for reuse.
https://featurebyte.atlassian.net/browse/DEV-1913

[chore][DEV-1913] test_(*)_table: refactor tests to base class for reuse

---

featurebyte/api/feature.py
featurebyte/api/target.py
featurebyte/api/templates/series_doc.py

Update a couple of docstrings in the `Target` API object that `Feature` also overrides from `Series`.
https://featurebyte.atlassian.net/browse/DEV-1952 …

[chore][DEV-1952] target: update docstrings for a couple of series fns

---

.changelog/DEV-1963.yaml
featurebyte/models/tile_job_log.py
featurebyte/service/tile/tile_task_executor.py

This adds formatted traceback to tile job log documents for troubleshooting failed tile jobs.

[DEV-1963] Add traceback to tile job log for troubleshooting

---

featurebyte/api/feature.py
notebooks/prebuilt_catalogs.py

One minor indent fix, and one small fix to add a target to the prebuilt catalog in the notebook.

[chore] api/feature: minor fix to indent

---

CHANGELOG.md

[chore] yanked 0.4.0 and adding dates Changelog.md

---

Taskfile.yaml
featurebyte/routes/feature/controller.py
featurebyte/routes/feature_namespace/controller.py
featurebyte/routes/registry.py
featurebyte/service/feature_facade.py

This PR aims to refactor feature related services using facade design pattern. The main purpose of this refactoring work is to isolate the logics to orchestra high level feature service at service level (some of these works currently is at controller level) so that it can be reused other service (like approval request service).
| …

[chore] Refactor feature related services

---

pyproject.toml

+ Bumping dev versions to 0.4.1

[chore] setting version to 0.4.1

---

tests/integration/session/test_thread_safety.py

It seems the test can sometimes hang on CI. Skip for now while troubleshooting.
https://featurebyte.atlassian.net/browse/DEV-1984

[chore] Mark test_threadsafety_api_object as skip

---

featurebyte/service/tile_manager.py
tests/unit/tile/test_unit_snowflake_tile.py

This fixes an issue that causes the progress update to be non-responsive when generating tiles on demand.

[chore] Fix progress update when generating tiles on demand

---

.changelog/DEV-1983.yaml
featurebyte/api/api_handler/base.py
featurebyte/api/api_handler/catalog.py
featurebyte/api/api_object_util.py
featurebyte/api/catalog.py
featurebyte/api/catalog_decorator.py
featurebyte/api/feature.py
featurebyte/api/feature_list.py
featurebyte/feature_utility.py
tests/unit/api/base_materialize_table_test.py
tests/unit/api/conftest.py
tests/unit/api/test_api_object.py
tests/unit/api/test_batch_feature_table.py
tests/unit/api/test_batch_request_table.py
tests/unit/api/test_catalog.py
tests/unit/api/test_credential.py
tests/unit/api/test_deployment.py
tests/unit/api/test_entity.py
tests/unit/api/test_feature.py
tests/unit/api/test_feature_job_setting_analysis.py
tests/unit/api/test_feature_list.py
tests/unit/api/test_feature_store.py
tests/unit/api/test_observation_table.py
tests/unit/api/test_static_source_table.py
tests/unit/api/test_user_defined_function.py

Under certain `ipython` notebook environment, it will call `df.to_json()` to display the dataframe object. To handle this issue, this PR revises existing `catalog.list_*()` output so that it is JSON serializable. …

[DEV-1983] Make sure catalog.list_*() output dataframe is JSON serializable

---

.changelog/DEV-1985.yaml
featurebyte/api/base_table.py
featurebyte/middleware.py
featurebyte/query_graph/model/column_info.py
featurebyte/routes/common/base_table.py
featurebyte/routes/dimension_table/api.py
featurebyte/routes/event_table/api.py
featurebyte/routes/item_table/api.py
featurebyte/routes/scd_table/api.py
featurebyte/schema/info.py
featurebyte/schema/table.py
tests/unit/api/test_change_view.py
tests/unit/api/test_dimension_table.py
tests/unit/api/test_event_table.py
tests/unit/api/test_item_table.py
tests/unit/api/test_scd_table.py
tests/unit/api/test_table_column.py
tests/unit/core/test_frame.py
tests/unit/models/test_dimension_table.py
tests/unit/models/test_event_table.py
tests/unit/models/test_scd_table.py
tests/unit/query_graph/model/test_table_data.py
tests/unit/routes/base.py

Support updating column descriptions with the python API
https://featurebyte.atlassian.net/browse/DEV-1985

[DEV-1985] Add support for updating column descriptions

---

featurebyte/common/progress.py
featurebyte/models/task.py
featurebyte/query_graph/sql/feature_historical.py
featurebyte/schema/task.py
featurebyte/service/deploy.py
featurebyte/service/historical_features.py
featurebyte/service/target_helper/base_feature_or_target_computer.py
featurebyte/service/task_manager.py
featurebyte/service/tile_cache.py
featurebyte/service/tile_manager.py
featurebyte/tile/tile_cache.py
featurebyte/utils/messaging.py
featurebyte/worker/__init__.py
featurebyte/worker/task/base.py
featurebyte/worker/task/batch_feature_create.py
featurebyte/worker/task/feature_job_setting_analysis.py
featurebyte/worker/task/feature_list_batch_feature_create.py
featurebyte/worker/task/test_task.py
featurebyte/worker/task_executor.py
tests/integration/conftest.py
tests/integration/tile/test_tile_scheduler.py
tests/integration/worker/test_task_manager.py
tests/unit/conftest.py
tests/unit/query_graph/test_feature_historical.py
tests/unit/service/test_task_manager.py
tests/unit/tile/test_unit_snowflake_tile.py
tests/unit/worker/task/base.py
tests/unit/worker/test_task_executor.py
tests/util/task.py

Store start time and last progress in mongo task documents
https://featurebyte.atlassian.net/browse/DEV-1971

[DEV-1971] Store more information in celery task results

---

.changelog/DEV-1939.yaml
featurebyte/query_graph/enum.py
featurebyte/query_graph/graph.py
featurebyte/query_graph/node/generic.py
featurebyte/query_graph/node/metadata/operation.py
featurebyte/query_graph/sql/specs.py
featurebyte/query_graph/transform/entity_extractor.py

Reuse the lookup node's logic, and created a new lookup target node.
https://featurebyte.atlassian.net/browse/DEV-1939

[DEV-1939] node/generic: add lookup target node

---

featurebyte/routes/lazy_app_container.py
featurebyte/service/base_document.py
tests/unit/service/test_base_document.py

This PR add option to `BaseDocumentService` & `app_container` to disable block modification check.

[DEV-1999] Add option to disable block modification check

---

featurebyte/common/documentation/autodoc_processor.py

Cherry-pick fix for broken links in documentation.

docs: fix links

---

tests/integration/api/test_feature_correctness.py

Add an integration test that covers using the target as an observation table that is passed into `compute_historical_features_table`.
https://featurebyte.atlassian.net/browse/DEV-1997
| …

[DEV-1997][chore] target: add integration test for target and feature compute

---

Taskfile.yaml

Skip vulnerability for cryptography package to unblock artifact publication.

[CHORE] skip vulnerability for cryptography package

---

.changelog/DEV-2024.yaml
featurebyte/api/aggregator/base_aggregator.py
featurebyte/api/aggregator/forward_aggregator.py
featurebyte/api/groupby.py
featurebyte/query_graph/node/generic.py
tests/unit/api/aggregator/test_forward_aggregator.py
tests/unit/api/test_target.py

This is used in tutorials, and adding this will also keep `forward_aggregate` consistent with other aggregators.
https://featurebyte.atlassian.net/browse/DEV-2024 …

[DEV-2024] forward_aggregate: add fill_value and skip_fill_na

---

featurebyte/worker/task/base.py
featurebyte/worker/task/feature_job_setting_analysis.py
featurebyte/worker/task/tile_task.py
featurebyte/worker/task_executor.py
tests/integration/conftest.py
tests/unit/conftest.py
tests/unit/worker/task/base.py
tests/unit/worker/test_task_executor.py

This PR refactors task executor & `BaseTask` so that we could inject `app_container` into the `BaseTask` at the `featurebyte-app`.

[DEV-1907] Refactor task executor

---

.changelog/DEV-1939-2.yaml
featurebyte/api/aggregator/base_aggregator.py
featurebyte/api/aggregator/forward_aggregator.py
featurebyte/api/event_view.py
featurebyte/api/item_view.py
featurebyte/api/scd_view.py
featurebyte/api/view.py
featurebyte/api/window_validator.py
tests/unit/api/test_dimension_view.py

Add the `as_target` method into the `ViewColumn`. This currently doesn't do anything, and only adds the `lookup_target` node to the graph.
I'll add more unit tests later for other view types, but plan to refactor some of it together with the unit tests for `as_feature`. As such, just adding a basic one first to `dimension_view`.
https://featurebyte.atlassian.net/browse/DEV-1939
|       `build`, `ci`, `testing`        | …

[DEV-1939] api/view: add as_target to view column

---

.changelog/DEV-1983.yaml
featurebyte/api/api_handler/base.py
featurebyte/api/api_handler/catalog.py
featurebyte/api/api_object_util.py
featurebyte/api/feature.py
featurebyte/api/feature_list.py
featurebyte/feature_utility.py
tests/unit/api/base_materialize_table_test.py
tests/unit/api/conftest.py
tests/unit/api/test_api_object.py
tests/unit/api/test_batch_feature_table.py
tests/unit/api/test_batch_request_table.py
tests/unit/api/test_catalog.py
tests/unit/api/test_credential.py
tests/unit/api/test_deployment.py
tests/unit/api/test_entity.py
tests/unit/api/test_feature.py
tests/unit/api/test_feature_job_setting_analysis.py
tests/unit/api/test_feature_list.py
tests/unit/api/test_feature_store.py
tests/unit/api/test_observation_table.py
tests/unit/api/test_static_source_table.py
tests/unit/api/test_user_defined_function.py

Cherry-pick from https://github.com/featurebyte/featurebyte/pull/1576
https://github.com/featurebyte/featurebyte/pull/1576

[DEV-1983] Make sure catalog.list_*() output dataframe is JSON serializable (Cherry-pick to 0.4)

---

Taskfile.yaml
tests/integration/api/test_online_enable.py

Cherry-pick #1616 to release/0.4.

[0.4][chore] Fix app fixture teardown hanging

---

notebooks/prebuilt_catalogs.py

Was updating some notebooks, and noticed that some of the code could be simplified. These changes should be safe to make as long as test-notebooks pass. …

[chore] prebuilt_catalogs: refactor prebuilt catalogs to simplify code reuse

---

.changelog/DEV-2038.yaml
featurebyte/service/feature_manager.py

This fixes a bug where feature job sometimes starts running while the feature is still being enabled. This can cause conflict and cause the deployment process to fail. …

[DEV-2038] Delay scheduling of periodic tasks until backfill steps are complete

---

featurebyte/models/feature_job_setting_analysis.py
featurebyte/service/feature_job_setting_analysis.py
featurebyte/worker/task/feature_job_setting_analysis.py
tests/unit/routes/test_feature_job_setting_analysis.py
tests/unit/worker/task/test_feature_job_setting_analysis_backtest.py

Track backtest summaries in feature job setting analyses
https://featurebyte.atlassian.net/issues/DEV-2035

[DEV-2035] Track backtest summary in feature job setting analyses

---

pyproject.toml

[chore] bumping pyproject to 0.4.2 version

---

featurebyte/routes/common/base_table.py
featurebyte/routes/dimension_table/controller.py
featurebyte/routes/event_table/controller.py
featurebyte/routes/item_table/controller.py
featurebyte/routes/lazy_app_container.py
featurebyte/routes/registry.py
featurebyte/routes/scd_table/controller.py
featurebyte/service/table_facade.py
tests/unit/routes/test_lazy_app_container.py

This PR
*  refactors table service for approval request workflow
* fixes bug in `disable_block_modification_check` in app_container. …

[chore] Refactor table service for approval request workflow

---

.changelog/DEV-2044.yaml
featurebyte/models/feature.py
featurebyte/routes/common/feature_metadata_extractor.py
featurebyte/routes/feature/controller.py
featurebyte/routes/target/controller.py
tests/unit/api/conftest.py
tests/unit/api/test_scd_view.py

This fixes an error when generating info for features in some edge cases caused by the behaviour of the `keep_all_source_columns` flag. This is a workaround that prevents the error and will be cleaned up later. …

[DEV-2044] Fix error when retrieving feature info for some features

---

featurebyte/core/timedelta.py

Update examples as per https://featurebyte.slack.com/archives/C042PLEC8D9/p1691638368764129?thread_ts=1691631419.084899&cid=C042PLEC8D9. …

[chore] to_timedelta: update examples

---

README.md

Mention the Hosted Tutorial Server as an option for completing the tutorials.

[DEV-1851] Update README to mention hosted tutorials

---

.changelog/DEV-2087.yaml
featurebyte/enum.py
featurebyte/routes/common/base_table.py
featurebyte/routes/dimension_table/controller.py
featurebyte/routes/event_table/controller.py
featurebyte/routes/item_table/controller.py
featurebyte/routes/scd_table/controller.py
featurebyte/service/table_info.py
tests/unit/api/test_change_view.py
tests/unit/api/test_dimension_table.py
tests/unit/api/test_event_table.py
tests/unit/api/test_item_table.py
tests/unit/api/test_scd_table.py
tests/unit/routes/test_dimension_table.py
tests/unit/routes/test_event_table.py
tests/unit/routes/test_item_table.py
tests/unit/routes/test_scd_table.py

Tag semantics for all special columns during table creation.
https://featurebyte.atlassian.net/browse/DEV-2087

[DEV-2087] Tag semantics for all special columns during table creation

---

.changelog/DEV-2077.yaml
featurebyte/query_graph/sql/aggregator/asat.py
featurebyte/query_graph/sql/aggregator/forward.py
featurebyte/query_graph/sql/aggregator/item.py
featurebyte/query_graph/sql/ast/groupby.py
featurebyte/query_graph/sql/groupby_helper.py
featurebyte/query_graph/sql/specs.py
featurebyte/query_graph/sql/tiling.py
featurebyte/session/base_spark.py
tests/unit/query_graph/sql/aggregator/test_forward.py
tests/unit/query_graph/sql/test_groupby_helper.py
tests/unit/query_graph/test_asat_aggregator.py
tests/unit/query_graph/test_feature_compute.py
tests/unit/query_graph/test_item_aggregator.py

[DEV-2077] groupby_helper: take in parent_dtype

---

featurebyte/service/online_store_cleanup_scheduler.py

Scheduling of online store cleanup job can fail due to mongo database unique index
https://featurebyte.atlassian.net/browse/DEV-2105 …

[DEV-2105] Skip scheduling of duplicate online store cleanup job with a warning

---

featurebyte/routes/common/schema.py
featurebyte/schema/common/base.py
tests/unit/routes/base.py

Increase pagination page size limit

[chore] Increase page size limit to 500

---

featurebyte/persistent/mongo.py

This PR uses global client to enforce connection throttling.

[chore] Use global client for mongodb

---

featurebyte/api/feature.py
featurebyte/common/documentation/custom_nav.py
featurebyte/common/documentation/documentation_layout.py
tests/unit/common/documentation/test_documentation_layout.py

Make a few docs changes
- expose `feature.online_enabled` 
- consolidate `TargetNamespace#create` in the `Target` section
- mv `Target` to be above `Feature` in the nav list
https://featurebyte.atlassian.net/browse/DEV-2130 …

[chore] target: some minor updates to target and feature docs

---

featurebyte/api/feature.py
featurebyte/api/source_table.py
featurebyte/common/documentation/custom_nav.py
featurebyte/common/documentation/documentation_layout.py
tests/unit/common/documentation/test_documentation_layout.py

Cherry-pick some docs updates that can get rolled out when we do another version bump.

[chore] docs: cherry-pick docs updates

---

featurebyte/worker/task/batch_feature_create.py

This PR relaxes graph inconsistency check & update logging logic for error.

[chore] Relax graph consistency check

---

featurebyte/query_graph/node/generic.py
featurebyte/routes/common/feature_metadata_extractor.py
tests/unit/api/test_item_view.py
tests/unit/conftest.py
tests/unit/service/test_info.py

This PR aims to fix feature metadata extraction bug & add `aggregation_type` to the aggregation column in feature metadata.

[DEV-2152] Fix feature metadata extraction bug

---

.changelog/DEV-2069.yaml
featurebyte/session/enum.py
featurebyte/session/snowflake.py
featurebyte/sql/snowflake/F_VECTOR_AGGREGATE_AVG.sql
featurebyte/sql/snowflake/F_VECTOR_AGGREGATE_MAX.sql
featurebyte/sql/snowflake/F_VECTOR_AGGREGATE_SUM.sql
tests/integration/udf/test_vector_aggregate.py
tests/unit/session/test_snowflake_session.py

This PR adds the snowflake UDTFs for max, avg and sum. We will create the average UDTF that will be used in tiling in a follow-up as well.
Note that the output currently returns the results in a string format as well. We will fix that in a follow-up.
For reference, the following are some screenshots on the query being used to get the results in the tests.
```
select * from test_table;
```
```
select a.array_col, a.id_col, b.VECTOR_AGG_RESULT 
from test_table as a, table(VECTOR_AGGREGATE_MAX(ARRAY_COL) over (partition by id_col)) as b;
```
As such, we select the row where the `array_col` (the input vector column) is null to get the final aggregated result.
https://featurebyte.atlassian.net/browse/DEV-2069
https://featurebyte.atlassian.net/browse/DEV-2070 …

vector_aggregation: add snowflake UDTFs for max, avg and sum

---

featurebyte/models/batch_feature_table.py
featurebyte/models/batch_request_table.py
featurebyte/models/catalog.py
featurebyte/models/context.py
featurebyte/models/credential.py
featurebyte/models/deployment.py
featurebyte/models/entity.py
featurebyte/models/feature.py
featurebyte/models/feature_job_setting_analysis.py
featurebyte/models/feature_list.py
featurebyte/models/feature_namespace.py
featurebyte/models/feature_store.py
featurebyte/models/historical_feature_table.py
featurebyte/models/observation_table.py
featurebyte/models/semantic.py
featurebyte/models/static_source_table.py
featurebyte/models/task.py
featurebyte/models/use_case.py
featurebyte/models/user_defined_function.py
tests/unit/models/test_index.py

Include description in text index

[chore] Include description in text indexing

---

.changelog/DEV-2161.yaml
featurebyte/session/snowflake.py
featurebyte/sql/snowflake/F_VECTOR_AGGREGATE_AVG.sql
featurebyte/sql/snowflake/F_VECTOR_AGGREGATE_MAX.sql
featurebyte/sql/snowflake/F_VECTOR_AGGREGATE_SUM.sql
tests/integration/udf/test_vector_aggregate.py

Only return one row per partition when calling the snowflake UDTF.
```
select * from test_table;
```
```
select a.array_col, a.id_col, b.VECTOR_AGG_RESULT 
from test_table as a, table(VECTOR_AGGREGATE_MAX(ARRAY_COL) over (partition by id_col)) as b;
```
Now only returns the aggregated value.
https://featurebyte.atlassian.net/browse/DEV-2161
| …

vector_aggregation: only return one row per partition

---

.changelog/DEV-2156.yaml
featurebyte/query_graph/algorithm.py
featurebyte/query_graph/model/graph.py
featurebyte/query_graph/sql/feature_compute.py
tests/fixtures/expected_feature_sql_combined_simple_aggregate_and_window_aggregate.sql
tests/integration/api/test_features.py
tests/unit/api/test_event_table.py
tests/unit/conftest.py
tests/unit/query_graph/sql/test_complex_feature.py
tests/unit/query_graph/test_algorithm.py

Cherry pick #1675 to release/0.4.
This fixes an error (invalid identifier) caused by invalid generated sql when a feature combines both simple aggregate and window aggregate features.
| …

[0.4][DEV-2156] Fix invalid identifier error when combining simple aggregate and window aggregate features 

---

.changelog/DEV-2162.yaml
featurebyte/query_graph/node/generic.py
tests/unit/api/test_sdk_code.py

Cherry pick https://github.com/featurebyte/featurebyte/pull/1676.
This fixes an error during feature saving caused by conditional assignment SDK generation bug. …

[0.4][DEV-2162] Fix conditional assignment sdk code generation bug

---

featurebyte/feature_manager/model.py
featurebyte/models/tile.py
featurebyte/query_graph/sql/interpreter/tile.py
tests/unit/feature_manager/test_model.py
tests/unit/query_graph/interpreter/test_interpreter.py

This PR includes more groupby node parameters to tile spec so that it can be used to show tile information in approval workflow.

[chore] Add more groupby parameters to tile spec

---

featurebyte/api/base_table.py
featurebyte/api/view.py
featurebyte/query_graph/node/cleaning_operation.py
tests/unit/api/test_sdk_code.py
tests/unit/query_graph/test_critical_data_info.py
tests/unit/service/validator/test_production_ready_validator.py

This PR revises cleaning operation object representation as they are used in approval request response.

[chore] Fix cleaning operation representation

---

featurebyte/__init__.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/common/documentation/gen_ref_pages_docs_builder.py
featurebyte/list_utility.py

Cherry-pick another docs change so that it can get released when we rollout another version.

[DEV-2174][chore] docs: add list_deployment docs (#1685)

---

featurebyte/__init__.py
tests/unit/test_init.py

Support profile registration using python client

[chore] support profile registration using python client

---

featurebyte/__init__.py
tests/unit/test_init.py

Support profile registration using python client
Cherry-pick from
https://github.com/featurebyte/featurebyte/pull/1690

[chore] support profile registration using python client (#1690) [0.4]

---

.changelog/DEV-2166.yaml
featurebyte/__init__.py
featurebyte/api/api_object_util.py
featurebyte/api/catalog.py
featurebyte/api/catalog_get_by_id_mixin.py
featurebyte/api/use_case.py
featurebyte/models/use_case.py
featurebyte/routes/use_case/api.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/use_case.py
featurebyte/service/use_case.py
scripts/test-docs-setup.py
tests/unit/api/test_catalog.py
tests/unit/api/test_use_case.py
tests/unit/common/documentation/test_documentation_layout.py
tests/unit/conftest.py
tests/unit/routes/test_use_case.py

This PR is Part 2 of the Use Case component. It implements the API Object for UseCase. 
Note: The API Object of Context, which is one of the UseCase requirements, is not ready yet. It will be implemented in the subsequent PR …

[DEV-2166] Implement API Object for UseCase

---

Taskfile.yaml

Parallelize darglint processing

[chore] improving darglint processing time

---

Taskfile.yaml

[chore] removing nproc dependency

---

.changelog/DEV-2198.yaml
Taskfile.yaml
featurebyte/api/source_table.py
featurebyte/api/target.py
featurebyte/api/use_case.py
featurebyte/api/view.py
featurebyte/models/use_case.py
featurebyte/routes/use_case/api.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/use_case.py
featurebyte/service/use_case.py
scripts/test-docs-setup.py
tests/unit/api/test_context.py
tests/unit/api/test_use_case.py
tests/unit/conftest.py
tests/unit/routes/test_use_case.py

[DEV-2198] Integrate Context API Object into UseCase

---

.changelog/DEV-2200.yaml
featurebyte/api/feature_list.py
featurebyte/api/use_case.py
featurebyte/models/deployment.py
featurebyte/routes/deployment/controller.py
featurebyte/routes/use_case/api.py
featurebyte/schema/deployment.py
featurebyte/schema/info.py
featurebyte/schema/worker/task/deployment_create_update.py
featurebyte/service/deploy.py
featurebyte/worker/task/deployment_create_update.py
tests/unit/api/conftest.py
tests/unit/api/test_deployment.py
tests/unit/api/test_use_case.py
tests/unit/routes/test_deployment.py
tests/unit/routes/test_use_case.py

[DEV-2200] Associate Deployment with UseCase

---

.changelog/DEV-2206.yaml
featurebyte/api/feature.py
featurebyte/api/feature_list.py
featurebyte/api/target.py
tests/unit/api/base_feature_or_target_test.py
tests/unit/api/test_feature_list.py

Rename update description SDK functions for versioned assets.
`update_namespace_description` -> `update_description`
`update_description` -> `update_version_description`
https://featurebyte.atlassian.net/browse/DEV-2206 …

[DEV-2206] make update_description update namespaces for versioned assets

---

.changelog/DEV-2206.yaml
featurebyte/api/feature.py
featurebyte/api/feature_list.py
featurebyte/api/target.py
tests/unit/api/base_feature_or_target_test.py
tests/unit/api/test_feature_list.py

Rename update description SDK functions for versioned assets.
update_namespace_description -> update_description
update_description -> update_version_description
Cherry-pick from https://github.com/featurebyte/featurebyte/pull/1704
https://featurebyte.atlassian.net/browse/DEV-2206
|              `breaking`               |      💥 Breaking Changes …

[DEV-2206] make update_description update namespaces for versioned assets [0.4]

---

.changelog/DEV-2167.yaml
featurebyte/query_graph/sql/adapter/base.py
featurebyte/query_graph/sql/adapter/snowflake.py
featurebyte/query_graph/sql/aggregator/window.py
featurebyte/query_graph/sql/ast/tile.py
featurebyte/query_graph/sql/tiling.py
tests/integration/api/test_vector_aggregation_operations.py

This PR makes some final changes to enable vector aggregations for the sum and max tiling aggregate functions. 
This is done by making a few small changes, the most notable one being that we pass in a new `quote_vector_agg_aliases` parameter to determine whether we want to quote the final alias values that are being returned out of the group by query.
We will fix the average tiling aggregations in a follow-up PR.
| …

[DEV-2167] enable vector aggregations for tile aggregates (sum and max)

---

featurebyte/api/deployment.py
featurebyte/common/documentation/documentation_layout.py

Expose another doc item for get_feature_jobs_status under deployment.
https://featurebyte.atlassian.net/browse/DEV-2209

[chore][DEV-2209] deployment: add get_feature_jobs_status docs

---

featurebyte/api/deployment.py
featurebyte/common/documentation/documentation_layout.py

Cherry-pick a documentation update so that it can get released whenever we bump featurebyte's version.

[chore][DEV-2209] deployment: add get_feature_jobs_status docs (#1708)

---

.changelog/DEV-2198_3.yaml
featurebyte/api/source_table.py
featurebyte/api/view.py
tests/unit/conftest.py

[DEV-2198] Use Context name instead of Context id for the API signature

---

.changelog/DEV-2215.yaml
featurebyte/exception.py
featurebyte/middleware.py
tests/unit/service/test_base_document.py
tests/unit/test_middleware.py

[DEV-2215] Organize exceptions to reduce verbosity in middleware

---

.changelog/DEV-2167-2.yaml
featurebyte/query_graph/sql/adapter/snowflake.py
featurebyte/query_graph/sql/aggregator/window.py
featurebyte/query_graph/sql/ast/tile.py
featurebyte/query_graph/sql/groupby_helper.py
featurebyte/session/snowflake.py
tests/integration/api/test_vector_aggregation_operations.py
tests/unit/query_graph/sql/adapter/base_adapter_test.py
tests/unit/query_graph/sql/test_groupby_helper.py

Add support for snowflake AVG vector agg function.
We unskip the integration test to show that it works.

[DEV-2167] vector_agg: add support for snowflake avg function

---

.changelog/DEV-2195.yaml
featurebyte/api/use_case.py
featurebyte/routes/use_case/api.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/info.py
featurebyte/service/user_service.py
tests/unit/api/test_use_case.py
tests/unit/routes/test_use_case.py

[DEV-2195] Implement UseCase info

---

featurebyte/query_graph/sql/adapter/snowflake.py

Add a docstring to snowflake adapter's `group_by` override.

[chore] adapter/snowflake: add docstring to group_by

---

featurebyte/routes/deployment/controller.py
featurebyte/routes/feature_namespace/controller.py
featurebyte/service/base_document.py
featurebyte/service/feature.py
featurebyte/service/feature_list.py
featurebyte/service/feature_readiness.py
featurebyte/service/validator/production_ready_validator.py
featurebyte/service/working_schema.py
tests/unit/service/test_feature_readiness.py

Feature readiness service throws mongo transaction error when updating feature/feature list readiness. This PR revises existing feature & feature list services' document iterator call by using `list_documents_as_dict_iterator` instead of using `list_documents_iterator`.
| …

[chore] Optimize feature & feature list service retrieval

---

.github/workflows/publish-dev_gen.yaml

+ Not actively working on featurebyte docker image => Removing building docker image to quicken the publish step.

[chore][workflow] remove building docker image to artifact registry

---

.changelog/chore-optimize-feature-readiness-service.yaml
featurebyte/service/base_document.py
featurebyte/service/feature.py
featurebyte/service/feature_list.py
tests/unit/service/test_feature.py
tests/unit/service/test_feature_list.py
tests/unit/service/test_feature_readiness.py

This PR implements block modification checks for
* feature readiness update;
* feature list readiness distribution update
which were introduced in previous PR (https://github.com/featurebyte/featurebyte/pull/1720). …

[chore] Add block modification checks for readiness & readiness distribution update

---

featurebyte/app.py
featurebyte/routes/base_materialized_table_router.py
featurebyte/routes/static_source_table/api.py
featurebyte/routes/target_table/api.py

Prototype out some base classes to reuse routers, so that there's less duplication of code.
Will follow-up with a few more refactors to move more methods into base classes / base routers, but just wanted to demonstrate as a proof of concept first. …

[chore] routes/api: prototype classes to reuse methods

---

.changelog/chore-optimize-feature-readiness-service.yaml
featurebyte/routes/deployment/controller.py
featurebyte/routes/feature_namespace/controller.py
featurebyte/service/base_document.py
featurebyte/service/feature.py
featurebyte/service/feature_list.py
featurebyte/service/feature_readiness.py
featurebyte/service/validator/production_ready_validator.py
tests/unit/service/test_feature.py
tests/unit/service/test_feature_list.py
tests/unit/service/test_feature_readiness.py

This PR optimize feature readiness computation by skipping feature & feature list deserialization.
Cherry-picked:
https://github.com/featurebyte/featurebyte/pull/1720
https://github.com/featurebyte/featurebyte/pull/1722 …

[chore][Cherrypick] Optimize feature readiness computation

---

.changelog/DEV-2230.yaml
featurebyte/api/catalog.py
featurebyte/api/context.py
featurebyte/api/observation_table.py
featurebyte/api/source_table.py
featurebyte/api/use_case.py
featurebyte/api/use_case_or_context_mixin.py
featurebyte/api/view.py
featurebyte/exception.py
featurebyte/models/context.py
featurebyte/routes/context/api.py
featurebyte/routes/context/controller.py
featurebyte/routes/observation_table/api.py
featurebyte/routes/observation_table/controller.py
featurebyte/schema/context.py
featurebyte/schema/observation_table.py
featurebyte/service/observation_table.py
featurebyte/service/use_case.py
tests/unit/api/test_catalog.py
tests/unit/api/test_context.py
tests/unit/api/test_use_case.py
tests/unit/routes/test_observation_table.py
tests/unit/routes/test_use_case.py

[DEV-2230] Include observation table operation into Context API Object

---

featurebyte/config.py
pyproject.toml
tests/unit/conftest.py
tests/unit/test_config.py

Add retry for api client to make server requests more robust 

[chore] Add request retry for api client

---

.changelog/DEV-2241.yaml
featurebyte/api/use_case.py
featurebyte/models/use_case.py
featurebyte/routes/use_case/api.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/use_case.py
featurebyte/service/use_case.py
featurebyte/service/validator/materialized_table_delete.py
tests/unit/routes/test_use_case.py

[DEV-2241] Remove direct observation table reference from UseCase

---

featurebyte/service/feature_store_warehouse.py
featurebyte/session/base.py
tests/unit/api/test_observation_table.py
tests/unit/api/test_static_source_table.py
tests/unit/routes/test_feature_store.py

Use exception instead of listing to check for database / schema / table existence to support spark limitations for third-party catalogs …

[chore] Improve data warehouse asset validation

---

featurebyte/session/base_spark.py
featurebyte/session/snowflake.py
featurebyte/sql/snowflake/F_VECTOR_COSINE_SIMILARITY.sql
tests/integration/udf/snowflake/util.py
tests/integration/udf/spark/util.py
tests/integration/udf/test_vector_cosine_similarity.py

Add explicit None type handling for cosine similarity into snowflake.

[chore] cosine_similarity: add null array handling

---

.changelog/api-client.yaml
.changelog/error-validation.yaml
.changelog/hive-connection.yaml

Refer to https://github.com/featurebyte/featurebyte/pull/1737

[chore] adding missing changelogs

---

featurebyte/config.py
featurebyte/service/feature_store_warehouse.py
featurebyte/session/base.py
featurebyte/session/hive.py
pyproject.toml
tests/unit/api/test_observation_table.py
tests/unit/api/test_static_source_table.py
tests/unit/conftest.py
tests/unit/routes/test_feature_store.py
tests/unit/test_config.py

https://github.com/featurebyte/featurebyte/pull/1731
Fix hive connection for service where spark is not default catalog #1731
https://github.com/featurebyte/featurebyte/pull/1733
Add request retry for api client #1733
https://github.com/featurebyte/featurebyte/pull/1735
Fix spark connection for non-default catalog #1735
https://github.com/featurebyte/featurebyte/pull/1739
Improve data warehouse asset validation
| …

[chore] Cherry pick fixes to 0.5

---

.changelog/api-client.yaml
.changelog/error-validation.yaml
.changelog/hive-connection.yaml

(cherry picked from commit ea52654476280fb76392c80b38610fa44790e179)

adding missing changelogs

---

featurebyte/routes/lazy_app_container.py
tests/unit/routes/test_lazy_app_container.py

Provide an additional, more type safe way, to get an object from the app container.
Adding this to refactor some code in `featurebyte-app`. …

[chore] lazy_app_container: add ability to get by passing in type

---

featurebyte/query_graph/sql/adapter/snowflake.py
featurebyte/session/base_spark.py
featurebyte/session/snowflake.py
featurebyte/sql/snowflake/F_VECTOR_COSINE_SIMILARITY.sql
hive-udf/lib/src/main/java/com/featurebyte/hive/udf/VectorCosineSimilarity.java
tests/integration/udf/snowflake/util.py
tests/integration/udf/spark/util.py
tests/integration/udf/test_vector_cosine_similarity.py
tests/unit/query_graph/sql/adapter/base_adapter_test.py
tests/unit/query_graph/sql/adapter/test_snowflake.py

Cherry pick some vector tweaks onto release branch.

[chore] cherry pick vector items onto release/0.5

---

.changelog/DEV-2242.yaml
featurebyte/core/series.py
featurebyte/query_graph/enum.py
featurebyte/query_graph/node/unary.py
featurebyte/query_graph/sql/ast/unary.py
tests/integration/api/test_event_view_operations.py
tests/unit/core/test_series.py

Add `cos`, `sin`, `tan`, `acos`, `asin`, and `atan` functions onto the `Series`.
https://featurebyte.atlassian.net/browse/DEV-2242

[DEV-2242] series: add trigo functions to sql generation

---

.changelog/DEV-1517.yaml
featurebyte/api/feature_list.py
featurebyte/schema/feature_list.py
featurebyte/service/version.py
tests/unit/api/test_feature_list.py
tests/unit/routes/test_feature.py
tests/unit/routes/test_feature_list.py

Update feature list create new avoid to avoid throwing error when the new version is exactly the same as the original feature list.

[DEV-1517] Update feature list create new version

---

.changelog/DEV-2311.yaml
featurebyte/models/feature.py
featurebyte/service/feature.py
featurebyte/service/tile/tile_task_executor.py
tests/unit/api/test_feature.py
tests/unit/models/test_feature.py
tests/unit/service/test_feature.py

* Add last_updated_at in FeatureModel to indicate when feature value is last updated

[DEV-2311] Add last_updated_at in FeatureModel

---

.changelog/DEV-2321.yaml
featurebyte/routes/use_case/controller.py
tests/unit/routes/test_use_case.py

[DEV-2321] Validate non-existent Target and Context when creating Use Case

---

featurebyte/api/feature.py

This PR fixes feature saving conflict resolution issue when the server is `featurebyte-app`.

[DEV-2322] Fix feature conflict resolution

---

featurebyte/service/feature_facade.py
featurebyte/service/version.py
tests/unit/service/test_version.py

This PR introduces an `to_save` parameter to feature facade service for feature impact service used by approval request at `featurebyte-app`. …

Add option to create new version without saving the feature

---

featurebyte/routes/batch_feature_table/api.py
featurebyte/routes/batch_request_table/api.py
featurebyte/routes/common/base_materialized_table.py
featurebyte/routes/feature_list/api.py
featurebyte/routes/feature_list/controller.py
featurebyte/routes/historical_feature_table/api.py
featurebyte/routes/observation_table/api.py
featurebyte/routes/static_source_table/api.py
featurebyte/routes/target_table/api.py
featurebyte/service/feature_preview.py
featurebyte/service/preview.py
tests/unit/conftest.py
tests/unit/service/test_preview.py

Remove a few more unused `get_credential` parameters.

[chore] materialized_table: rm more unused get_credential parameters

---

.changelog/DEV-2324.yaml
featurebyte/api/context.py
featurebyte/routes/context/api.py
featurebyte/routes/context/controller.py
featurebyte/schema/info.py
tests/unit/api/test_context.py
tests/unit/api/test_use_case.py

[DEV-2334] Add Context Info method into both Context API Object and Route

---

.changelog/DEV-2324_2.yaml
featurebyte/routes/context/controller.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/info.py
tests/unit/api/test_context.py
tests/unit/api/test_use_case.py
tests/unit/routes/test_use_case.py

[DEV-2324] Use EntityBriefInfoList for entity info for both UseCase and Context

---

.changelog/DEV-2325.yaml
featurebyte/api/context.py
featurebyte/api/target_namespace.py
scripts/test-docs-setup.py
tests/unit/api/test_context.py
tests/unit/api/test_target_namespace.py

[DEV-2325] Use primary entity parameter in Target and Context creation

---

featurebyte/query_graph/model/feature_job_setting.py
tests/unit/query_graph/model/test_feature_job_setting.py

This PR revises `TableIdFeatureJobSetting` to simplify handling at featurebyte-app side.

[chore] Revise `TableIdFeatureJobSetting`

---

.changelog/DEV-2334.yaml
featurebyte/common/utils.py
featurebyte/session/spark.py

Fix bug due to null values when handling variant types from database session client
https://featurebyte.atlassian.net/browse/DEV-2334 …

[DEV-2334] Handle null values when converting string to variant types

---

.changelog/DEV-2335.yaml
featurebyte/api/context.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/models/context.py
featurebyte/routes/context/api.py
featurebyte/routes/context/controller.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/context.py
featurebyte/schema/info.py
featurebyte/service/context.py
featurebyte/service/observation_table.py
featurebyte/service/use_case.py
tests/fixtures/request_payloads/context.json
tests/unit/api/test_context.py
tests/unit/conftest.py
tests/unit/routes/test_context.py
tests/unit/routes/test_use_case.py
tests/unit/service/test_context.py
tests/unit/test_generate_payload_fixtures.py

[DEV-2354] Context entity renamed to primary_entity & Add Validation when Creation

---

featurebyte/common/documentation/documentation_layout.py

Add 2 items to documentation.
https://featurebyte.atlassian.net/browse/DEV-2362
https://featurebyte.atlassian.net/browse/DEV-2363

[chore] docs: add key_with_(lowest|highest)_value

---

.changelog/DEV-2355.yaml
featurebyte/query_graph/sql/feature_compute.py

Feature list with many complex features might trigger the "maximum recursion depth exceed" error when generating sql query. This increases the default limit to fix the error. …

[DEV-2355] Fix maximum recursion depth exceeded error in complex queries

---

.changelog/DEV-2356.yaml
featurebyte/query_graph/node/generic.py
featurebyte/query_graph/node/metadata/sdk_code.py
featurebyte/query_graph/node/mixin.py
tests/integration/api/test_lookup_target_operations.py
tests/unit/api/test_target.py
tests/unit/query_graph/test_sdk_code_generation.py

We didn't implement the SDK code generation for lookup target's which was causing the generated code to look weird.
This fixes it to use the proper code generation.
```
from bson import ObjectId
from featurebyte import DimensionTable
dimension_table = DimensionTable.get_by_id(ObjectId("651a69ea8dc64a05766c1b8c"))
dimension_view = dimension_table.get_view(
view_mode="manual", drop_column_names=[], column_cleaning_operations=[]
)
target = dimension_view.as_target(
target_name="ItemTypeTargetDimensionView", offset=None
)
target_1 = target["ItemTypeTargetDimensionView"]
output = target_1
```
https://featurebyte.atlassian.net/browse/DEV-2356 …

[DEV-2356] target: fix definition file generation for lookup target

---

.changelog/DEV-2352.yaml
featurebyte/routes/context/controller.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/use_case.py
featurebyte/service/target.py
tests/unit/routes/test_context.py
tests/unit/routes/test_target.py
tests/unit/routes/test_use_case.py

[DEV-2352] Entity Validation for Context, Target and UseCase

---

.changelog/DEV-2366.yaml
Taskfile.yaml
featurebyte/models/use_case.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/info.py
featurebyte/schema/use_case.py
tests/unit/routes/test_use_case.py

[DEV-2366] UseCase creation to accept TargetNameSpace id as parameter

---

.changelog/DEV-2385.yaml
featurebyte/service/use_case.py

[DEV-2385] validate null target_id when adding observation table to use case

---

.changelog/DEV-2385_2.yaml
Taskfile.yaml
featurebyte/models/context.py
tests/unit/models/test_context.py

[chore] Handle old Context records with entity_ids attribute in the database

---

.changelog/DEV-2395.yaml
featurebyte/api/context.py
featurebyte/api/use_case.py

Documentation for UseCase and Context

---

featurebyte/api/base_table.py
tests/unit/api/test_event_table.py

Add description property to table column so that it is easier for user to retrieve column description.

[chore] Add description property to table column

---

.changelog/DEV-2408.yaml
featurebyte/api/feature_list.py
featurebyte/routes/historical_feature_table/controller.py
featurebyte/schema/feature_list.py
featurebyte/service/feature_list.py
featurebyte/service/feature_preview.py
featurebyte/service/historical_features.py
tests/unit/routes/test_historical_feature_table.py
tests/unit/service/test_historical_features.py

[DEV-2408] make feature_clusters optional when creating historical feature table

---

tests/integration/api/materialized_table/utils.py
tests/integration/api/test_observation_table.py
tests/integration/api/test_static_source_table.py

Small refactor to reuse some test helpers.

[chore] materialized_table: refactor test helpers for reuse

---

featurebyte/query_graph/node/base.py
featurebyte/query_graph/node/binary.py
featurebyte/query_graph/node/generic.py
featurebyte/query_graph/node/mixin.py
featurebyte/query_graph/sql/ast/aggregate.py
featurebyte/query_graph/transform/base.py
featurebyte/query_graph/transform/definition.py
featurebyte/query_graph/util.py
tests/unit/query_graph/conftest.py
tests/unit/query_graph/test_definition.py
tests/unit/query_graph/test_extract_operation_structure.py
tests/util/helper.py

This PR introduces `DefinitionHashExtractor` class that will be used to generate feature definition hash on saved feature graph.

[DEV-2349] Add `DefinitionHashExtractor` to extract feature definition hash

---

featurebyte/models/observation_table.py
featurebyte/models/use_case.py
featurebyte/routes/context/api.py
featurebyte/routes/context/controller.py
featurebyte/routes/use_case/controller.py
tests/unit/conftest.py
tests/unit/routes/test_context.py
tests/unit/routes/test_use_case.py

Add endpoints to support context deletion & update use case deletion.

[DEV-2351] Implement context delete & update use case delete

---

featurebyte/routes/lazy_app_container.py

Small cleanup to remove a method from an earlier change.

[chore] app_container: rm method thats moved to handler

---

.changelog/DEV-2435_2.yaml
featurebyte/api/use_case.py
featurebyte/routes/context/controller.py
featurebyte/routes/observation_table/api.py
featurebyte/routes/observation_table/controller.py
featurebyte/routes/use_case/api.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/use_case.py
featurebyte/service/observation_table.py
featurebyte/service/use_case.py
featurebyte/service/validator/materialized_table_delete.py
tests/unit/api/test_use_case.py
tests/unit/routes/conftest.py
tests/unit/routes/test_observation_table.py
tests/unit/routes/test_use_case.py

[DEV-2435] enable observation table to be associated with multiple use cases

---

.github/workflows/changelog_gen.yaml
.github/workflows/daily-cron_gen.yaml
.github/workflows/dependencies_gen.yaml
.github/workflows/documentation_gen.yaml
.github/workflows/lint_gen.yaml
.github/workflows/notify_gen.yaml
.github/workflows/publish-dev_gen.yaml
.github/workflows/publish-public_gen.yaml
.github/workflows/test-notebooks_gen.yaml
.github/workflows/test_gen.yaml

Bump actions dependencies

---

.changelog/DEV-2449.yaml
Taskfile.yaml
featurebyte/api/use_case.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/use_case.py
tests/unit/api/test_use_case.py
tests/unit/routes/test_use_case.py

[DEV-2449] Implement delete observation table from use case

---

Taskfile.yaml
featurebyte/models/catalog.py
featurebyte/routes/catalog/api.py
featurebyte/routes/catalog/controller.py
featurebyte/schema/catalog.py
featurebyte/service/catalog.py
tests/unit/api/test_catalog.py
tests/unit/routes/test_catalog.py

Add endpoint to support catalog soft delete.

[DEV-2447] Implement catalog soft delete

---

featurebyte/routes/deployment/api.py
featurebyte/routes/deployment/controller.py
featurebyte/routes/feature/api.py
featurebyte/routes/feature/controller.py
featurebyte/routes/feature_list/api.py
featurebyte/routes/feature_list/controller.py
featurebyte/routes/registry.py
featurebyte/routes/target/api.py
featurebyte/routes/target/controller.py
featurebyte/schema/feature_list.py
featurebyte/service/entity_serving_names.py
featurebyte/service/feature.py
featurebyte/service/feature_list.py
featurebyte/service/target.py
poetry.lock
tests/unit/api/test_deployment.py
tests/unit/routes/test_feature.py
tests/unit/routes/test_feature_list.py
tests/unit/routes/test_target.py
tests/unit/service/test_feature.py

Provide request for sample entity serving names for feature and target

[chore] Support request sample entity serving names for feature and target

---

Taskfile.yaml
featurebyte/routes/batch_request_table/controller.py
featurebyte/routes/common/base.py
featurebyte/routes/common/base_materialized_table.py
featurebyte/routes/context/api.py
featurebyte/routes/context/controller.py
featurebyte/routes/observation_table/controller.py
featurebyte/routes/static_source_table/controller.py
featurebyte/routes/use_case/api.py
featurebyte/routes/use_case/controller.py
featurebyte/routes/user_defined_function/api.py
featurebyte/routes/user_defined_function/controller.py
featurebyte/service/feature_preview.py
tests/unit/api/test_user_defined_function.py
tests/unit/routes/test_batch_feature_table.py
tests/unit/routes/test_context.py
tests/unit/routes/test_historical_feature_table.py
tests/unit/routes/test_use_case.py
tests/unit/routes/test_user_defined_function.py

This PR refactors asset deletion logic so that it can be reused for all assets.

[chore] Refactor asset deletion operation

---

featurebyte/worker/task_executor.py

Make `get_app_container` async function so that we can make async call within the function in `featurebyte-app`.

[chore] Make `get_app_container` async

---

poetry.lock
pyproject.toml
tests/unit/test_app.py

This bumps fastapi version to 0.96.0 to pick up https://github.com/tiangolo/fastapi/pull/4645 to see if there is any improvements in runtime.
Testing locally, `get_app()` timing in `test_get_app__loading_time` is around 10X faster (from around 8s to 0.8s).
Before:
```
============================= slowest 50 durations =============================
31.02s call     tests/unit/test_app.py::test_get_app__loading_time
25.93s call     tests/unit/api/test_feature.py::test_list_unsaved_features
21.03s call     tests/unit/api/test_feature_list.py::test_deploy
16.71s call     tests/unit/api/test_feature_list.py::test_save_feature_group
15.73s call     tests/unit/api/test_version.py::test_feature_and_feature_list_version
```
After:
```
============================= slowest 50 durations …
```

[chore] Bump fastapi version to speed up get_app

---

featurebyte/api/deployment.py
featurebyte/api/feature_job_setting_analysis.py
featurebyte/api/savable_api_object.py
featurebyte/api/user_defined_function.py
featurebyte/routes/deployment/api.py
featurebyte/routes/deployment/controller.py
featurebyte/routes/feature_job_setting_analysis/api.py
tests/unit/api/test_deployment.py
tests/unit/api/test_feature_job_setting_analysis.py
tests/unit/routes/test_batch_feature_table.py
tests/unit/routes/test_deployment.py
tests/unit/routes/test_feature_job_setting_analysis.py

This PRs update feature job setting analysis & deployment to support deletion.

[DEV-2450][DEV-2451] Add feature job setting analysis & deployment deletion support

---

featurebyte/api/feature_list.py
featurebyte/models/feature_list.py
featurebyte/schema/info.py
featurebyte/service/feature_list.py
featurebyte/service/feature_list_facade.py
featurebyte/service/feature_list_namespace.py
tests/unit/api/test_feature_list.py
tests/unit/models/test_feature_list.py
tests/unit/routes/test_feature_list.py
tests/unit/routes/test_feature_list_namespace.py
tests/unit/service/conftest.py
tests/unit/service/test_feature_list_namespace.py

Cleanup feature list default version mode as it is no longer required.

[chore] Cleanup feature list default version mode

---

featurebyte/routes/dimension_table/api.py
featurebyte/routes/event_table/api.py
featurebyte/routes/item_table/api.py
featurebyte/routes/scd_table/api.py

This PR refactors table API routers.

[chore] Refactor table API routers

---

featurebyte/api/base_table.py
featurebyte/routes/common/base_table.py
featurebyte/routes/dimension_table/api.py
featurebyte/routes/dimension_table/controller.py
featurebyte/routes/event_table/api.py
featurebyte/routes/event_table/controller.py
featurebyte/routes/item_table/api.py
featurebyte/routes/item_table/controller.py
featurebyte/routes/scd_table/api.py
featurebyte/routes/scd_table/controller.py
tests/unit/api/base_table_test.py
tests/unit/api/test_event_table.py
tests/unit/routes/test_dimension_table.py
tests/unit/routes/test_event_table.py
tests/unit/routes/test_feature.py
tests/unit/routes/test_feature_job_setting_analysis.py
tests/unit/routes/test_item_table.py
tests/unit/routes/test_scd_table.py

This PR adds deletion support for
* event table
* item table
* dimension table
* SCD table

[DEV-2456] Add table deletion support

---

featurebyte/enum.py
featurebyte/routes/feature/api.py
featurebyte/routes/feature/controller.py
featurebyte/routes/observation_table/controller.py
featurebyte/routes/target/api.py
featurebyte/routes/target/controller.py
featurebyte/schema/preview.py
featurebyte/schema/worker/task/observation_table_upload.py
featurebyte/service/feature_preview.py
featurebyte/service/observation_table.py
featurebyte/worker/task/observation_table.py
featurebyte/worker/task/observation_table_upload.py
tests/unit/routes/test_feature.py
tests/unit/routes/test_target.py
tests/unit/worker/task/test_observation_table.py
tests/unit/worker/task/test_observation_table_upload.py

Simplify feature/target preview payload

[chore] Simplify feature/target preview payload

---

featurebyte/api/entity.py
featurebyte/api/feature_store.py
featurebyte/routes/entity/api.py
featurebyte/routes/entity/controller.py
featurebyte/routes/feature_store/api.py
featurebyte/routes/feature_store/controller.py
tests/unit/api/test_entity.py
tests/unit/api/test_feature_store.py
tests/unit/routes/test_context.py
tests/unit/routes/test_entity.py
tests/unit/routes/test_event_table.py
tests/unit/routes/test_feature.py
tests/unit/routes/test_feature_store.py
tests/unit/routes/test_target.py

This PR implements delete endpoint & adds delete method for 
* entity
* feature store

[DEV-2458][DEV-2459] Add entity & feature store deletion support

---

.changelog/DEV-2467.yaml
featurebyte/api/use_case.py
featurebyte/api/use_case_or_context_mixin.py
featurebyte/routes/context/controller.py
featurebyte/schema/context.py
featurebyte/schema/observation_table.py
featurebyte/service/observation_table.py
tests/unit/api/test_context.py
tests/unit/api/test_use_case.py
tests/unit/routes/conftest.py
tests/unit/routes/test_context.py

[DEV-2467] Implement remove observation table from context

---

featurebyte/routes/common/base_table.py
featurebyte/routes/dimension_table/api.py
featurebyte/routes/event_table/api.py
featurebyte/routes/item_table/api.py
featurebyte/routes/scd_table/api.py
featurebyte/schema/table.py
tests/unit/routes/base.py

Remove unused column semantic update routes

[chore] Remove unused column semantic update routes

---

featurebyte/routes/item_table/controller.py
tests/unit/routes/base.py
tests/unit/routes/test_context.py
tests/unit/routes/test_item_table.py

This PR updates item table creation logic by checking existence of event table first.

[DEV-2470] Verify event table ID during item table creation

---

.changelog/DEV-2474.yaml
featurebyte/api/context.py
featurebyte/api/use_case.py
featurebyte/routes/use_case/api.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/use_case.py
tests/unit/api/test_use_case.py
tests/unit/routes/test_use_case.py

[DEV-2474] Implement removal of default preview & eda table for use case

---

featurebyte/models/feature.py
featurebyte/models/feature_list.py
featurebyte/routes/registry.py
featurebyte/service/entity_relationship_extractor.py
featurebyte/service/feature.py
featurebyte/service/feature_list.py
tests/unit/api/test_feature.py
tests/unit/models/test_feature.py
tests/unit/routes/test_feature.py
tests/unit/service/test_feature.py

This PR updates feature service to include relationships info.

[DEV-2477] Add relationships info to feature model

---

.changelog/DEV-2491.yaml
featurebyte/worker/task/feature_job_setting_analysis.py
tests/unit/worker/task/test_feature_job_setting_analysis.py

Fix Feature Job Settings Analysis failing for DataBricks feature store.

[DEV-2491] Fix Feature Job Settings Analysis failing for DataBricks Feature Store

---

featurebyte/exception.py
featurebyte/routes/registry.py
featurebyte/service/entity_relationship_extractor.py
featurebyte/service/feature_list.py
featurebyte/service/validator/entity_relationship_validator.py
tests/unit/api/test_feature_list.py
tests/unit/service/validator/test_entity_relationship_validator.py

This PR introduces additional feature list validation check on frozen entity relationships stored at the feature level.

[DEV-2478] Add feature list validation to check conflicting frozen entity relationships

---

.changelog/DEV-2490.yaml
featurebyte/api/context.py
featurebyte/api/use_case.py
featurebyte/api/use_case_or_context_mixin.py
featurebyte/routes/context/controller.py
featurebyte/routes/use_case/api.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/context.py
featurebyte/schema/use_case.py
tests/unit/api/test_context.py
tests/unit/routes/test_context.py
tests/unit/routes/test_use_case.py

[DEV-2490] implement remove default preview/eda table for context

---

featurebyte/app.py
featurebyte/migration/run.py
featurebyte/routes/app_container_config.py
featurebyte/routes/registry.py
featurebyte/worker/task_executor.py
tests/integration/conftest.py
tests/unit/conftest.py
tests/unit/routes/relationship_info/test_api.py
tests/unit/routes/test_lazy_app_container.py
tests/unit/service/conftest.py

[chore] mv get redis

---

featurebyte/app.py
featurebyte/migration/run.py
featurebyte/routes/app_container_config.py
featurebyte/routes/lazy_app_container.py
featurebyte/routes/registry.py
featurebyte/worker/task_executor.py
tests/integration/conftest.py
tests/unit/conftest.py
tests/unit/routes/relationship_info/test_api.py
tests/unit/routes/test_app_container_config.py
tests/unit/routes/test_lazy_app_container.py
tests/unit/service/conftest.py

Add another way to register dependencies to simplify the app container initialization.

[chore] app_container: add register_factory to register factory methods

---

featurebyte/api/catalog_decorator.py

Add a log line to try to prevent a common user error path.
Example
- user has catalogs A and B
- current active catalog is A
- user does some stuff, forgets current active catalog is A
- user calls `b.list_entities` to see what entities there are in B
- user tries to use entities found in B, gets error …

[chore] catalog_decorator: log when calling commands and not in active catalog

---

featurebyte/models/feature.py
featurebyte/models/feature_list.py
featurebyte/routes/common/base_table.py
featurebyte/routes/dimension_table/controller.py
featurebyte/routes/entity/controller.py
featurebyte/routes/event_table/controller.py
featurebyte/routes/item_table/controller.py
featurebyte/routes/scd_table/controller.py
tests/unit/api/test_table.py

This PR aims to fix table & entity deletion check by checking feature's & feature list's relationship info.

[chore] Fix deletion check for table & entity

---

featurebyte/migration/service/feature.py
featurebyte/service/entity_relationship_extractor.py
featurebyte/service/feature_list.py
tests/unit/service/entity_relationship/test_entity_relationship_extractor.py
tests/unit/service/test_feature_list.py

This PR revises current feature list relationships info extraction logic by keeping only descendent of the feature primary entity.
**Current** feature list relationships info extraction logics contains all the entity relationship that are relevant to any of the feature's entity.
**New** feature list relationships info extraction logics only contains the descendent relationship of the feature's primary entity.
| …

[DEV-2518] Update feature list relationships info extraction logic

---

featurebyte/models/feature_list.py
featurebyte/service/entity_relationship_extractor.py
featurebyte/service/feature_list.py
tests/unit/api/test_feature_list.py
tests/unit/models/test_feature_list.py
tests/unit/service/entity_relationship/test_entity_relationship_extractor.py

This PR introduces `supported_serving_entity_ids` to feature list model.

[DEV-2505] Add `supported_serving_entity_ids` to feature list model

---

.changelog/DEV-2525.yaml
featurebyte/models/target.py
tests/unit/models/test_target.py

Add logic to derive window for lookup targets as well.

[DEV-2525] target: derive window for lookup targets as well

---

featurebyte/models/feature_list.py

Update feature list model indices so that mongo indices build properly.

[chore] Update feature list model indices

---

featurebyte/persistent/base.py
featurebyte/persistent/mongo.py
featurebyte/routes/common/base.py
featurebyte/routes/deployment/controller.py
featurebyte/routes/feature/controller.py
featurebyte/routes/feature_list/controller.py
featurebyte/routes/feature_namespace/controller.py
featurebyte/routes/user_defined_function/controller.py
featurebyte/schema/feature_list.py
featurebyte/service/base_document.py
featurebyte/service/deploy.py
featurebyte/service/feature.py
featurebyte/service/feature_facade.py
featurebyte/service/feature_list.py
featurebyte/service/feature_list_namespace.py
featurebyte/service/feature_manager.py
featurebyte/service/feature_readiness.py
featurebyte/service/online_store_compute_query_service.py
featurebyte/service/online_store_table_version.py
featurebyte/service/relationship.py
featurebyte/service/validator/materialized_table_delete.py
featurebyte/service/validator/production_ready_validator.py
featurebyte/worker/task/feature_list_make_production_ready.py
featurebyte/worker/util/batch_feature_creator.py
tests/unit/persistent/test_mongo.py
tests/unit/routes/test_feature_list.py
tests/unit/service/test_base_document.py

This PR updates persistent & document service to support query result field projection.

[chore] Update persistent & document service to support query projection

---

.changelog/DEV-2518.yaml
featurebyte/api/feature.py
featurebyte/api/feature_list.py
featurebyte/api/feature_or_target_mixin.py
featurebyte/api/target.py
featurebyte/routes/feature_list_namespace/controller.py
featurebyte/service/base_document.py
featurebyte/service/entity.py
featurebyte/service/entity_serving_names.py
featurebyte/service/feature_list_namespace.py
tests/unit/api/test_feature_list.py

This PR
* cleans up primary entity logic for feature & feature list (to retrieve it from the record rather than derive it on the fly)
* rename `primary_entities` to `primary_entity` in feature list catalog listing …

[DEV-2518] Change feature list catalog output column name from `primary_entities` to `primary_entity`

---

.changelog/DEV-2526.yaml
.github/workflows/test_gen.yaml
Taskfile.yaml
docker/docker-compose.yml
featurebyte/query_graph/sql/adapter/databricks.py
featurebyte/session/base_spark.py
featurebyte/session/spark.py
poetry.lock
tests/fixtures/expected_preview_sql_databricks.sql
tests/integration/service/test_working_schema_service.py
tests/unit/query_graph/interpreter/test_interpreter.py

Fix session failure with spark 3.4.1 and later

[DEV-2526] Fix session failure with spark 3.4.1 and later

---

featurebyte/worker/util/batch_feature_creator.py
tests/unit/routes/test_feature.py
tests/unit/routes/test_feature_list.py

This PR updates batch feature saving task by iterating all features even if some of the features encounter document inconsistency error. …

[DEV-2539] Update batch feature saving task logic

---

featurebyte/api/feature_list.py
featurebyte/migration/service/feature_list.py
featurebyte/models/feature_list.py
featurebyte/routes/feature_list/controller.py
featurebyte/routes/feature_list_namespace/controller.py
featurebyte/routes/registry.py
featurebyte/schema/feature_list_namespace.py
featurebyte/service/feature_list.py
featurebyte/service/feature_list_namespace.py
featurebyte/service/feature_readiness.py
tests/unit/api/test_api_object.py
tests/unit/api/test_feature_list.py
tests/unit/models/test_feature_list.py
tests/unit/routes/test_feature_list.py
tests/unit/service/conftest.py
tests/unit/service/test_feature_list_namespace.py
tests/unit/service/test_feature_readiness.py
tests/unit/service/test_info.py

This PR adds feature list migration script for `table_ids` and cleans up feature list namespace model by removing unused attributes. …

[DEV-2536] Add feature list migration for `table_ids` & clean up `FeatureListNamespaceModel`

---

.github/workflows/changelog_gen.yaml
.github/workflows/documentation_gen.yaml
.github/workflows/lint_gen.yaml
.github/workflows/publish-dev_gen.yaml
.github/workflows/test-notebooks_gen.yaml
.github/workflows/test_gen.yaml

syncing workflows with infrastructure repo

[chore] syncing workflow with infra repo

---

.changelog/DEV-2568.yaml
featurebyte/query_graph/sql/interpreter/preview.py
tests/fixtures/expected_describe_request.sql
tests/fixtures/query_graph/expected_describe_snowflake.sql
tests/fixtures/query_graph/expected_describe_spark.sql
tests/integration/api/test_view_describe.py

This fixes a division by zero error in sql query when calling describe on empty views.

[DEV-2568] Fix division by zero error when calling describe on empty views

---

tests/integration/udf/test_count_dict_entropy.py
tests/integration/udf/test_count_dict_num_unique.py

This PR adds a couple simple integration tests for a couple UDFs. This is a small prep PR before we convert some of the databricks UDFs from their jar form to python UDFs. …

[chore] udf: add a couple integration tests for UDFs

---

featurebyte/api/feature_group.py
featurebyte/models/feature_list.py
featurebyte/query_graph/pruning_util.py

Optimize feature list model creation time.

Optimize feature list creation

---

.github/workflows/dependencies_gen.yaml
.github/workflows/documentation_gen.yaml

[chore] sync workflow

---

featurebyte/migration/service/feature.py
featurebyte/models/feature.py
featurebyte/query_graph/graph.py
featurebyte/routes/registry.py
tests/unit/api/test_feature.py
tests/unit/models/test_feature.py

This PR add
* `table_id_column_names`
* `table_id_feature_job_settings`
* `table_id_cleaning_operations`
into feature model to avoid deriving these attributes on the fly when listing feature.
| …

[DEV-2613] Add `table_id_*` query graph derived attribute to feature model

---

tests/integration/udf/conftest.py
tests/integration/udf/test_cosine_similarity.py
tests/integration/udf/test_count_dict_entropy.py
tests/integration/udf/test_count_dict_num_unique.py
tests/integration/udf/test_get_rank.py
tests/integration/udf/test_get_relative_frequency.py
tests/integration/udf/test_least_frequent.py
tests/integration/udf/test_most_frequent.py
tests/integration/udf/test_timestamp_to_index.py
tests/integration/udf/test_timezone_offset_to_second.py
tests/integration/udf/test_vector_aggregate.py
tests/integration/udf/test_vector_cosine_similarity.py
tests/source_types.py

Update UDF integration tests by adding spark/databricks to most of them.

[chore] integration/udf: add databricks to all udf tests

---

featurebyte/api/target.py
featurebyte/routes/target/api.py
featurebyte/routes/target/controller.py
tests/unit/api/test_target.py
tests/unit/routes/test_observation_table.py
tests/unit/routes/test_target.py
tests/unit/routes/test_use_case.py

This PR implements target deletion.

[DEV-2614] Add target delete support

---

.github/workflows/changelog_gen.yaml
.github/workflows/daily-cron_gen.yaml
.github/workflows/dependencies_gen.yaml
.github/workflows/documentation_gen.yaml
.github/workflows/lint_gen.yaml
.github/workflows/notify_gen.yaml
.github/workflows/publish-dev_gen.yaml
.github/workflows/publish-public_gen.yaml
.github/workflows/test-notebooks_gen.yaml
.github/workflows/test_gen.yaml
featurebyte/api/feature_list.py
featurebyte/api/mixin.py
featurebyte/routes/deployment/api.py
tests/unit/routes/base.py
tests/unit/routes/test_feature_list.py

This PR updates deployment patch route status code. When an async task is created, 202 is returned.

Update deployment patch route status code

---

.github/workflows/test_gen.yaml
Taskfile.yaml

This PR disables databrick integration tests.

Skip databrick integration tests

---

featurebyte/models/feature.py
featurebyte/query_graph/graph.py
featurebyte/routes/deployment/api.py
tests/unit/api/test_feature.py

This PR updates feature model's root validator to generate `table_id_feature_job_settings` without duplicated table IDs.

[chore] Update `FeatureModel` to skip duplicated table when generating `table_id_feature_job_settings`

---

featurebyte/common/documentation/documentation_layout.py

Simple PR to add another item to docs.
https://featurebyte.atlassian.net/browse/DEV-2620

[chore] docs: add TableColumn#update_description to docs

---

docker/Dockerfile

[chore] bumping build and runtime Docker image to 3.10

---

.github/workflows/test_gen.yaml

Enable databrick integration tests.

Enable databrick integration tests

---

CHANGELOG.md

[chore] Changelog for 0.6.1

---

.changelog/DEV-2656.yaml
docs/notebooks/quick start model training - final.ipynb
featurebyte/api/view.py
tests/integration/api/test_event_view_operations.py
tests/integration/api/test_observation_table.py
tests/unit/api/test_event_view.py
tests/unit/api/test_observation_table.py
tests/unit/conftest.py

Update create observation table check so that
* the primary entity IDs are inferred from the view
* the primary entity IDs must not be empty …

[DEV-2656] Update create observation table check

---

featurebyte/models/feature.py
featurebyte/models/feature_list.py
featurebyte/query_graph/enum.py
featurebyte/query_graph/model/entity_relationship_info.py
featurebyte/query_graph/node/date.py
featurebyte/query_graph/node/nested.py
featurebyte/query_graph/transform/offline_ingest_extractor.py
featurebyte/service/base_feature_service.py
featurebyte/service/entity_relationship_extractor.py
featurebyte/service/feature_list.py
featurebyte/service/validator/entity_relationship_validator.py
tests/unit/api/test_feature.py
tests/unit/api/test_request_column.py
tests/unit/service/entity_relationship/test_entity_relationship_validator.py
tests/util/helper.py

This PR implements `OfflineStoreIngestQueryGraphExtractor` class which is used to construct offline store ingest query graph. The extractor is used to decompose a feature graph if the graph contains multiple entity from different entity universes. …

[DEV-266] Implement offline store ingest query graph(s) construction

---

featurebyte/__init__.py
featurebyte/api/feature.py
featurebyte/api/feature_list.py
featurebyte/api/feature_or_target_mixin.py
featurebyte/api/observation_table.py
featurebyte/api/primary_entity_mixin.py
featurebyte/api/target.py
featurebyte/api/templates/entity_doc.py
featurebyte/api/templates/feature_or_target_doc.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/models/observation_table.py
tests/unit/api/base_feature_or_target_test.py
tests/unit/api/test_catalog.py
tests/unit/api/test_observation_table.py

This PR refactors entity related api object properties to improve consistency.

[DEV-2680][DEV-2691] Refactor `ObservationTable` api object

---

.changelog/DEV-2694.yaml
docker/entrypoint.sh
featurebyte/schema/worker/task/feature_job_setting_analysis.py
featurebyte/worker/task_executor.py

Change feature job settings analysis task to use cpu worker since there are pandas dataframe operations which can utilize significant cpu and memory when the data is large …

[DEV-2694] Update feature job settings analysis task to use cpu worker

---

featurebyte/models/feature.py
featurebyte/query_graph/node/nested.py
featurebyte/query_graph/transform/offline_ingest_extractor.py
tests/unit/api/test_feature.py
tests/unit/api/test_request_column.py
tests/unit/models/test_feature.py

This PR adds output column name to offline store ingest query output so that it can be used to name the offline store feature component. …

[DEV-2700] Add offline store ingest query output column name

---

featurebyte/feast/utils/registry_construction.py
featurebyte/models/feature.py
featurebyte/models/mixin.py
featurebyte/models/offline_store_feature_table.py
featurebyte/models/offline_store_ingest_query.py
featurebyte/query_graph/node/nested.py
featurebyte/service/offline_store_feature_table_manager.py
tests/unit/api/test_feature.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/models/test_feature.py

This PR revises `FeatureModel` for the feast on demand feature view construction work.

[DEV-2757] Revise `FeatureModel` to store offline store information

---

featurebyte/query_graph/model/column_info.py
featurebyte/routes/feature_store/api.py
featurebyte/routes/feature_store/controller.py
featurebyte/service/feature_store_warehouse.py
featurebyte/service/materialized_table.py
featurebyte/session/base.py
featurebyte/session/base_spark.py
featurebyte/session/snowflake.py
featurebyte/session/sqlite.py
tests/integration/session/test_spark.py
tests/unit/api/test_dimension_table.py
tests/unit/api/test_event_table.py
tests/unit/conftest.py
tests/unit/models/test_request_input.py
tests/unit/routes/base.py
tests/unit/routes/test_feature_store.py
tests/unit/service/test_observation_table.py
tests/unit/session/test_base.py
tests/unit/session/test_databricks_session.py
tests/unit/session/test_snowflake_session.py
tests/unit/session/test_sqlite_session.py

Pull column descriptions from DFH comment fields. 
[DEV-2722](https://featurebyte.atlassian.net/browse/DEV-2722)
[DEV-2722]: …

[DEV-2722] pull column descriptions from DWH

---

featurebyte/models/feature_list.py
featurebyte/models/offline_store_feature_table.py
featurebyte/query_graph/model/graph.py
featurebyte/service/feature_materialize.py
tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
tests/fixtures/feature_materialize/initialize_new_columns_new_table.sql
tests/fixtures/feature_materialize/materialize_features_queries.sql
tests/fixtures/feature_materialize/scheduled_materialize_features_queries.sql
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/service/test_feature_materialize.py

This updates FeatureMaterializeService to handle new columns initialization and scheduled updates. 

[DEV-2764] Update FeatureMaterializeService to handle initialization and scheduled updates

---

featurebyte/query_graph/node/base.py
featurebyte/query_graph/node/function.py
featurebyte/query_graph/node/generic.py
featurebyte/query_graph/node/input.py
featurebyte/query_graph/node/metadata/operation.py
featurebyte/query_graph/node/mixin.py
featurebyte/query_graph/node/nested.py
featurebyte/query_graph/node/request.py
featurebyte/query_graph/transform/operation_structure.py
featurebyte/query_graph/transform/pruning.py
tests/fixtures/sdk_code/complex_event_item_feature.py
tests/fixtures/sdk_code/complex_multi_table_feature.py
tests/fixtures/sdk_code/feature_fraction.py
tests/unit/api/test_event_view.py
tests/unit/query_graph/test_extract_operation_structure.py

This PR aims to fix the feature creation bug due to the weird behaviour between aggregation mixin & join feature node.

[DEV-2775] Fix simple aggregate vs its window aggregate feature creation bug

---

featurebyte/feast/model/registry.py
featurebyte/feast/service/registry.py
featurebyte/service/feature_list.py
featurebyte/service/offline_store_feature_table_manager.py
tests/integration/api/test_scd_view_operations.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/service/test_offline_store_feature_table_manager.py

This updates OfflineStoreFeatureTableManagerService to create or update feast registry when handling online enabled or disabled features. …

[DEV-2772] Create or update feast registry in offline store feature table manager

---

featurebyte/enum.py
featurebyte/feast/enum.py
featurebyte/feast/model/feature_store.py
featurebyte/feast/service/feature_store.py
featurebyte/feast/utils/registry_construction.py
featurebyte/query_graph/node/schema.py

This PR aims to remove `feast` dependencies for `featurebyte` SDK client.

Remove `feast` dependencies from `enum.py` and `query_graph/node/schema.py`

---

featurebyte/query_graph/sql/feature_historical.py
featurebyte/service/historical_features.py
featurebyte/service/target_helper/compute_target.py
tests/unit/query_graph/test_feature_historical.py

Change progress message for target compute
[DEV-2800](https://featurebyte.atlassian.net/browse/DEV-2800)
[DEV-2800]: …

[DEV-2800] change progress message for target compute

---

.github/workflows/dependencies_gen.yaml
Taskfile.yaml
poetry.lock
pyproject.toml

This helps prevent issues when specifying dependencies in pyproject.toml and make sure poetry.lock is in sync.

[chore] Add checks to ensure validity of pyproject.toml and poetry.lock

---

featurebyte/feast/utils/registry_construction.py
featurebyte/models/feature.py
featurebyte/models/offline_store_feature_table.py
featurebyte/service/entity_serving_names.py
featurebyte/service/feature.py
featurebyte/service/offline_store_feature_table_manager.py
tests/unit/api/test_feature.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/api/test_request_column.py
tests/unit/feast/conftest.py
tests/util/helper.py

This PR updates feature service so that it generates offline store info whenever the feast integration feature flag is enabled.

Update feature service feast integration

---

README.md

[DEV-2843] Update README

---

featurebyte/feast/enum.py
featurebyte/query_graph/node/binary.py
featurebyte/query_graph/node/count_dict.py
featurebyte/query_graph/node/metadata/templates/on_demand_view.tpl
featurebyte/query_graph/node/nested.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/feast/utils/test_register_construction.py
tests/unit/query_graph/odfv/test_binary.py
tests/unit/query_graph/odfv/test_count_dict.py
tests/unit/query_graph/test_metadata_sdk_code.py
tests/util/helper.py

This PR implements on-demand-feature-view support for count-dictionary-node-related operations.

[DEV-2797] Add on-demand-feature-view support for count dictionary nodes

---

featurebyte/enum.py
featurebyte/feast/enum.py
featurebyte/query_graph/node/distance.py
featurebyte/query_graph/node/nested.py
featurebyte/query_graph/node/vector.py
featurebyte/query_graph/sql/adapter/snowflake.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/query_graph/odfv/test_distance.py
tests/unit/query_graph/odfv/test_vector.py
tests/unit/query_graph/test_sdk_code_generation.py
tests/util/helper.py

This PR implements the on-demand-feature-view function construction for vector & distance related nodes.

[DEV-2797] Add on-demand-feature-view support for vector & distance related nodes

---

featurebyte/feast/utils/on_demand_view.py
featurebyte/feast/utils/registry_construction.py
featurebyte/models/feature.py
featurebyte/models/offline_store_ingest_query.py
featurebyte/query_graph/transform/offline_store_ingest.py
featurebyte/query_graph/transform/on_demand_view.py
featurebyte/service/online_serving.py
tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
tests/fixtures/feature_materialize/initialize_new_columns_new_table.sql
tests/fixtures/feature_materialize/materialize_features_queries.sql
tests/fixtures/feature_materialize/scheduled_materialize_features_queries.sql
tests/fixtures/offline_store_feature_table/feature_cluster_disabled_one_feature.json
tests/fixtures/offline_store_feature_table/feature_cluster_one_feature.json
tests/fixtures/offline_store_feature_table/feature_cluster_two_features.json
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/api/test_feature.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/api/test_request_column.py
tests/unit/feast/utils/test_register_construction.py
tests/unit/models/test_feature.py
tests/unit/service/test_feature_materialize.py
tests/unit/service/test_offline_store_feature_table_manager.py
tests/unit/service/test_online_serving_feast.py
tests/util/helper.py

This PR introduces feature version into offline/online feature table column name to avoid name collision.

[DEV-2905] Add feature version to offline feature table column name

---

featurebyte/__init__.py
featurebyte/api/feature_list.py
featurebyte/models/feature_list.py
featurebyte/models/feature_list_namespace.py
featurebyte/routes/feature_list_namespace/controller.py
featurebyte/schema/feature_list_namespace.py
featurebyte/schema/info.py
featurebyte/service/deploy.py
featurebyte/service/feature_list.py
featurebyte/service/feature_list_facade.py
featurebyte/service/feature_list_namespace.py
featurebyte/service/feature_list_status.py
featurebyte/service/feature_readiness.py
tests/unit/api/test_feature_list.py
tests/unit/models/test_feature_list.py
tests/unit/service/test_feature_list_namespace.py
tests/unit/service/test_feature_list_status.py

This PR moves `FeatureListNamespaceModel` into separate module to reduce the number of lines in `feature_list.py`. This is for the preparation of introducing DataBricks features lookup definition in `FeatureListModel`. …

[chore] Move `FeatureListNamespaceModel` to `feature_list_namespace.py`

---

featurebyte/query_graph/node/nested.py
featurebyte/query_graph/node/request.py
tests/fixtures/on_demand_function/req_col_ttl_and_non_ttl.sql
tests/unit/api/test_offline_ingest_query_graph.py

This PR aims to fix the on-demand feature view construction bug.

[DEV-2915] Fix Feast on-demand feature view & DataBricks UDF construction bug

---

featurebyte/logging.py
tests/unit/api/test_source_table.py

Update customer logger class to store extra field in log record

[chore] Update customer logger class to handle extra field

---

featurebyte/api/target.py
featurebyte/routes/target/api.py
featurebyte/schema/target.py

This cleans up the way type casting in done in routes/target/api.py so that is more type safe and easier to navigate to controller's code in the IDE. …

[chore] Clean up casting in routes/target/api.py

---

featurebyte/exception.py
featurebyte/routes/observation_table/controller.py
featurebyte/service/observation_table.py
featurebyte/worker/task/observation_table_upload.py
tests/unit/routes/test_observation_table.py

Validate required column names are provided in uploaded observation set.

[chore] Validate required column names in uploaded observation set

---

featurebyte/models/feature_list.py
featurebyte/models/feature_list_store_info.py
featurebyte/service/feature_manager.py
featurebyte/service/online_enable.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/api/test_offline_ingest_query_graph.py

This PR updates the online enable service to register/remove DataBricks UDFs used for on-demand feature(s).

[DEV-2939] Register/remove DataBricks UDF for on-demand feature during feature online enable/disable

---

featurebyte/models/entity_universe.py
featurebyte/models/offline_store_feature_table.py
featurebyte/routes/registry.py
featurebyte/service/feature_materialize.py
featurebyte/service/offline_store_feature_table_construction.py
featurebyte/service/offline_store_feature_table_manager.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/models/test_entity_universe.py

This adds support for features that require parent entity lookup when computing features to be stored in offline feature tables. The entity universe construction logic needs to be updated to handle this.
| …

[DEV-2826] Support features that require parent entity lookup in offline feature table

---

featurebyte/models/feature_list_store_info.py
featurebyte/models/offline_store_ingest_query.py
featurebyte/query_graph/node/metadata/config.py
featurebyte/query_graph/transform/on_demand_function.py
tests/fixtures/on_demand_function/req_col_ttl_and_non_ttl.sql
tests/unit/api/test_offline_ingest_query_graph.py

This PR fixes bugs in current DataBricks feature specs definition.

[DEV-2950] Fix bugs in DataBricks feature specs definition

---

.changelog/DEV-2125.yaml
featurebyte/api/source_table.py
featurebyte/routes/common/base_table.py
featurebyte/schema/table.py
poetry.lock
tests/fixtures/request_payloads/dimension_table.json
tests/fixtures/request_payloads/event_table.json
tests/fixtures/request_payloads/item_table.json
tests/fixtures/request_payloads/scd_table.json
tests/integration/conftest.py
tests/unit/api/test_event_table.py
tests/unit/api/test_source_table.py
tests/unit/conftest.py
tests/unit/routes/base.py
tests/unit/service/test_info.py

Support description specification during table creation

[DEV-2125] Support description specification during table creation

---

featurebyte/models/feature.py
featurebyte/query_graph/node/generic.py
featurebyte/query_graph/node/mixin.py
featurebyte/query_graph/transform/decompose_point.py
featurebyte/query_graph/transform/offline_store_ingest.py
tests/integration/api/test_event_view_operations.py
tests/unit/api/test_dimension_view.py
tests/unit/api/test_event_view.py
tests/unit/api/test_item_view.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/api/test_scd_view.py
tests/unit/feast/conftest.py
tests/unit/feast/utils/test_registry_construction.py
tests/unit/service/test_offline_store_feature_table_manager.py

This PR consolidates the logic to extract feature job setting from aggregation node & add default job setting for aggregations require update task. …

[DEV-2961] Fix feature job setting of offline store table

---

featurebyte/query_graph/model/table.py
featurebyte/routes/common/base_table.py
featurebyte/service/feature_store_warehouse.py
featurebyte/session/base.py
featurebyte/session/base_spark.py
featurebyte/session/snowflake.py
tests/unit/conftest.py
tests/unit/session/test_snowflake_session.py
tests/unit/session/test_spark.py
tests/unit/session/test_sqlite_session.py

Refactor table description retrieval:
- Fetch more datawarehouse specific details
- Support retrieval of table description for DataBricks and Spark …

[chore] Refactor table description retrieval

---

featurebyte/models/entity_lookup_feature_table.py
featurebyte/session/base.py
featurebyte/session/base_spark.py
featurebyte/session/databricks.py
featurebyte/session/snowflake.py
featurebyte/session/sqlite.py
tests/integration/session/test_comment.py
tests/unit/session/test_base.py

This adds methods in BaseSession to support adding comments to tables or columns in the data warehouse.

[DEV-2965] Add BaseSession methods to comment on tables or columns

---

.changelog/DEV-2972.yaml
featurebyte/query_graph/sql/interpreter/preview.py
tests/unit/routes/test_deployment.py

Retrieve only sample entity serving values that is not empty.

[DEV-2972] Fix getting sample entity serving values fail when entity has null values

---

featurebyte/feast/utils/registry_construction.py
featurebyte/session/databricks.py
featurebyte/session/spark.py
poetry.lock
pyproject.toml
tests/integration/feature_store_integration/test_feature_materialize.py

[vuln] Bump pyarrow to 14.0.2

---

Taskfile.yaml
featurebyte/schema/dimension_table.py
featurebyte/schema/event_table.py
featurebyte/schema/item_table.py
featurebyte/schema/scd_table.py
featurebyte/schema/table.py
poetry.lock
tests/unit/routes/base.py

Validate that special columns specified in table creation payload exists

[chore] Add validation of special columns in table create payload schema

---

featurebyte/service/feature_table_cache.py
tests/integration/service/test_feature_table_cache.py
tests/unit/service/test_feature_table_cache.py

When building eda plot for a feature there is no point to create a view every time. 
We just need to read data from table. 
Adding method for direct read from feature table cache.  
https://featurebyte.atlassian.net/browse/DEV-2964 …

[DEV-2964] read from feature table cache for EDA

---

featurebyte/schema/user_defined_function.py
tests/fixtures/request_payloads/user_defined_function.json
tests/unit/routes/test_user_defined_function.py
tests/unit/test_generate_payload_fixtures.py

Add UDF description during creation
https://featurebyte.atlassian.net/browse/DEV-2969

[DEV-2969] Add UDF description during creation

---

featurebyte/feast/utils/registry_construction.py
featurebyte/query_graph/sql/entity.py
featurebyte/query_graph/sql/online_serving.py
featurebyte/service/feature_materialize.py
featurebyte/service/offline_store_feature_table_manager.py
featurebyte/service/online_serving.py
tests/fixtures/feature_materialize/materialize_features_queries_composite_entity.sql
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/conftest.py
tests/unit/service/conftest.py
tests/unit/service/test_feature_materialize.py

This adds special handling for features with composite entity so that they work with feast which doesn't support entity with multiple join keys. In the offline store feature tables, serving names of the composite entity are concatenated as a new column which will be used as the entity's join key. …

[DEV-2985] Add special handling for features with composite entity

---

featurebyte/service/offline_store_feature_table_manager.py

When online enabling features, the feast registry is updated repeatedly but a single update is sufficient.

[chore] Fix redundant feast registry updates when online enabling features

---

featurebyte/feast/service/registry.py
featurebyte/service/offline_store_feature_table_manager.py
tests/unit/service/test_feature_materialize.py

This PR updates feast registry creation logic by removing the logic to skip registry construction.

[DEV-2988] Always create feast registry when enable deployment

---

featurebyte/query_graph/node/generic.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/query_graph/on_demand_function/test_generic.py

Current filtering node will throw runtime error when the filtering operation is used in on-demand feature view code. This PR aims to fix it by implementing the filtering operation ODFV code construction.
| …

[chore] Fix filter node for on-demand feature view code generation

---

featurebyte/models/feature.py

Add an index on `definition_hash` for `FeatureModel` since that is used in some queries in the app.

[chore] Add definition_hash index for FeatureModel

---

featurebyte/query_graph/model/entity_lookup_plan.py
featurebyte/service/online_serving.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/api/test_feature.py
tests/unit/query_graph/model/test_entity_lookup_plan.py

This fixes a bug in the entity lookup logic for composite entities (see the added test cases to reproduce).

[DEV-2984] Fix entity lookup logic for composite entities

---

featurebyte/service/deploy.py

Update deployment flow so that feature's offline store info is not updated when 
* Feast integration feature flag is off
* deployment is disabled from enabled status …

[chore] Conditionally update offline store info

---

featurebyte/service/deploy.py
featurebyte/service/offline_store_feature_table_comment.py
featurebyte/service/offline_store_feature_table_manager.py

As per title suggests, this PR updates deployment task update progress message so that it is clearer to end-user what is happening behind the scene. …

[chore] Update deployment progress update

---

featurebyte/query_graph/sql/entity.py
featurebyte/service/online_serving.py
tests/integration/feature_store_integration/test_feature_materialize.py

This fixes the handling of non-existent entity when looking up parent entity. Without this change, conversion to and from pandas can cause types to change when there are missing values (mainly. from int to float) and cause the lookup to return incorrect results.
| …

[DEV-2996] Fix handling of non-existent entity when looking up parent entity

---

featurebyte/service/catalog.py
tests/integration/worker/test_task_manager.py

Fix up https://github.com/featurebyte/featurebyte/pull/2116. This is covered in featurebyte-app tests.

[DEV-2998] Set user_id in CatalogOnlineStoreInitializeTaskPayload

---

.github/workflows/daily-cron_gen.yaml
.github/workflows/dependencies_gen.yaml
.github/workflows/documentation_gen.yaml
.github/workflows/lint_gen.yaml
.github/workflows/notify_gen.yaml
.github/workflows/publish-dev_gen.yaml
.github/workflows/publish-public_gen.yaml
.github/workflows/test-notebooks_gen.yaml
.github/workflows/test_gen.yaml

Update github actions dependencies

[chore] Update github actions dependencies

---

featurebyte/session/base.py
tests/unit/session/test_base.py

Raise exception in thread on timeout when executing a non-async function using `to_thread`.
This reduces built-up of threads in the threadpool when functions execute for long duration beyond timeout.
| …

[chore] Raise exception in thread on timeout

---

featurebyte/exception.py
featurebyte/routes/task/api.py
featurebyte/routes/task/controller.py
featurebyte/schema/task.py
featurebyte/schema/worker/task/base.py
featurebyte/schema/worker/task/test.py
featurebyte/service/task_manager.py
featurebyte/worker/task/base.py
featurebyte/worker/task/test_task.py
featurebyte/worker/task_executor.py
featurebyte/worker/test_util/random_task.py
tests/integration/conftest.py
tests/integration/worker/conftest.py
tests/integration/worker/test_task_manager.py
tests/unit/routes/test_task.py
tests/unit/service/test_task_manager.py
tests/unit/worker/test_task_executor.py

Add support to revoke a task is it is supported.
A task that supports revocation will need to handle TaskRevokeExceptions and implement any required cleanup  …

[chore] Support revocation of supported tasks

---

featurebyte/models/tile_job_log.py

Disable audit for tile job log collection since it's an internally used collection and doesn't require auditing.

[chore] Disable audit for tile job log collection

---

featurebyte/schema/worker/progress.py
featurebyte/worker/util/task_progress_updater.py
tests/unit/worker/test_util.py

This PR update progress update interface to consume task specific metadata.

[chore] Update progress updater

---

.changelog/DEV-3024.yaml
featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py
tests/fixtures/query_graph/expected_describe_batches_0.sql
tests/fixtures/query_graph/expected_describe_batches_1.sql
tests/integration/api/test_view_describe.py
tests/unit/query_graph/interpreter/test_preview.py
tests/unit/routes/test_feature_store.py
tests/unit/service/test_observation_table.py

This updates `PreviewService` to compute data description in batches of columns to better handle very wide datasets and avoid timeout. …

[DEV-3024] Compute data description in batches of columns

---

featurebyte/common/utils.py
featurebyte/core/generic.py
featurebyte/query_graph/graph.py
featurebyte/query_graph/model/graph.py
featurebyte/query_graph/transform/quick_pruning.py
featurebyte/worker/util/batch_feature_creator.py
tests/conftest.py
tests/integration/conftest.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/integration/feature_store_integration/test_update_online_store.py
tests/unit/conftest.py
tests/unit/query_graph/test_query_graph.py

Optimize batch feature saving by
* regularly clearing up the global query & operation structure cache
* cache `sorted_node_names` at `QueryGraphModel` level …

[chore] Optimize batch feature saving

---

featurebyte/worker/util/batch_feature_creator.py

This PR adds metadata to batch feature creation task so that parent task can use it to aggregate total number of features created.

[chore] Add metadata to batch feature creation task

---

.changelog/DEV-3035.yaml
featurebyte/api/aggregator/asat_aggregator.py
featurebyte/query_graph/sql/aggregator/asat.py
featurebyte/query_graph/sql/aggregator/lookup_target.py
featurebyte/query_graph/sql/offset.py
featurebyte/query_graph/sql/scd_helper.py
featurebyte/query_graph/sql/specs.py
tests/fixtures/expected_preview_sql_aggregate_asat_offset.sql
tests/integration/api/test_scd_view_operations.py
tests/unit/api/test_aggregate_asat.py
tests/unit/query_graph/conftest.py
tests/unit/query_graph/test_feature_preview.py

This adds support for offset parameter for aggregate asat.

[DEV-3035] Support offset parameter for aggregate asat

---

featurebyte/api/aggregator/window_aggregator.py
featurebyte/core/generic.py
featurebyte/query_graph/graph.py
featurebyte/query_graph/transform/reconstruction.py

This PR updates `QueryObject` to cache operation structure info so that we could reuse this reduce when there are multiple groupby aggregate over of the same view node. …

[DEV-3043] Cache operation structure info

---

featurebyte/routes/registry.py
featurebyte/service/deploy.py
featurebyte/worker/task/deployment_create_update.py
tests/unit/routes/test_deployment.py
tests/unit/service/test_deploy.py

Refactor `DeployService` to improve readability & deployment stability.

[DEV-3407] Refactor `DeployService`

---

featurebyte/feast/model/registry.py
featurebyte/models/feature_job_setting_analysis.py
featurebyte/models/materialized_table.py
featurebyte/models/offline_store_feature_table.py

Skip adding audit logs for internal used models.

[chore] Make auditable `False` for internal used models

---

featurebyte/schema/worker/task/scheduled_feature_materialize.py

Task type for `SCHEDULED_FEATURE_MATERIALIZE` task should be `CPU_TASK` since it involves blocking operations.

[chore] Update SCHEDULED_FEATURE_MATERIALIZE task type to be CPU_TASK

---

featurebyte/feast/service/registry.py
featurebyte/schema/worker/task/deployment_create_update.py
featurebyte/session/databricks.py
tests/integration/conftest.py
tests/integration/feature_store_integration/test_feast_registry.py
tests/integration/feature_store_integration/test_feature_materialize.py

Add redis lock to Feast registry storage update.

[DEV-3062] Add redis lock to Feast registry storage update

---

featurebyte/service/feature_materialize.py

This adds redis lock for offline store table write operations. This is to prevent concurrent writes to the same offline store table between scheduled task and manually triggered deployment task.
| …

[DEV-3065] Add redis lock for offline store table writes

---

featurebyte/models/feature_list_store_info.py
featurebyte/query_graph/node/metadata/templates/databricks_feature_spec.tpl
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/models/test_feature_list_store_info.py

Update DataBricks feature definition specs by removing training model step from the template.

[DEV-3061] Revise Databricks feature specs

---

featurebyte/service/feature_list.py

This PR optimizes feature list creation insertion validation to avoid hitting transaction timeout when the feature list number is large. …

[chore] Optimize feature list creation validation

---

featurebyte/persistent/base.py
featurebyte/persistent/mongo.py
featurebyte/service/base_document.py
tests/unit/service/test_base_document.py

Support using pipeline with base document service document iterator

[chore] support pipeline in document list iterator

---

featurebyte/api/feature_group.py
featurebyte/api/feature_list.py
featurebyte/routes/feature/controller.py
featurebyte/schema/feature.py
featurebyte/schema/feature_list.py
featurebyte/worker/task/feature_list_batch_feature_create.py
tests/unit/routes/test_feature_list.py

Revise feature list saving logic by splitting existing tasks into
* batch feature saving task(s), maximum feature number is set to 500
* feature list creation. …

[DEV-3069] Revise feature list save logic

---

featurebyte/schema/feature_list.py
tests/unit/schema/test_feature_list.py
tests/unit/schema/test_target_table.py

This updates feature list schema to bypass batch feature validation check if `skip_batch_feature_creation` is `True`.

[chore] Fix feature list task payload schema

---

featurebyte/service/feature_list.py

Update feature list service & add logs.

[chore] Optimize feature mongo query in feature list service

---

featurebyte/routes/feature_list/controller.py
featurebyte/schema/worker/task/feature_list_batch_feature_create.py
featurebyte/service/feature_list.py
tests/unit/routes/test_feature_list.py

This PR optimizes feature list Mongo transaction by moving out long running statements from the transaction context.

[chore] Optimize feature list Mongo transaction

---

featurebyte/routes/feature_list/controller.py
featurebyte/service/feature_list.py
featurebyte/service/feature_list_facade.py
featurebyte/worker/task/feature_list_batch_feature_create.py
tests/unit/service/test_feature_list.py

This PR removes feature list creation Mongo transaction to fix Mongo timeout issue.

[chore] Remove feature list Mongo transaction

---

featurebyte/models/periodic_task.py
featurebyte/models/task.py

Do not add audit log for task models.

[chore] Skip adding audit log for task models

---

tests/integration/api/test_serving_parent_features.py

Update `test_serving_parent_features.py` to cover more complex cases with parent child relationships within a single feature.

[chore] Update test_serving_parent_features.py to cover more complex features

---

featurebyte/worker/task/feature_list_create.py

This PR pass progress update callback to feature list document creation method.

[chore] Pass progress update to feature list create task

---

featurebyte/api/source_table.py
featurebyte/enum.py
featurebyte/query_graph/sql/materialisation.py
featurebyte/routes/batch_feature_table/controller.py
featurebyte/routes/batch_request_table/controller.py
featurebyte/routes/common/base_materialized_table.py
featurebyte/routes/common/feature_or_target_table.py
featurebyte/routes/feature_store/api.py
featurebyte/routes/feature_store/controller.py
featurebyte/routes/historical_feature_table/controller.py
featurebyte/routes/observation_table/controller.py
featurebyte/routes/static_source_table/controller.py
featurebyte/routes/target_table/controller.py
featurebyte/schema/worker/task/historical_feature_table.py
featurebyte/service/feature_store_warehouse.py
featurebyte/service/preview.py
featurebyte/session/base.py
featurebyte/session/base_spark.py
featurebyte/session/manager.py
tests/integration/conftest.py
tests/unit/api/test_feature_store.py
tests/unit/api/test_source_table.py
tests/unit/conftest.py
tests/unit/routes/base.py
tests/unit/routes/test_feature_store.py
tests/unit/service/conftest.py
tests/unit/service/test_feature_store_warehouse.py
tests/unit/service/test_preview.py

- Avoid multiple datawarehouse calls when getting table schema
- Use simpler SQL for getting shape and preview for source tables
- Exclude featurebyte internal tables in table listing
- Exclude timeout from session cache hash
- Use CPU worker for historical features computation …

[chore] reduce / simplify queries for source table operations

---

featurebyte/service/base_document.py
featurebyte/service/feature_list.py
featurebyte/service/feature_list_facade.py
tests/unit/api/test_entity.py
tests/unit/routes/test_feature_list.py
tests/unit/service/test_feature_list.py

This PR removes mongo transaction from feature list delete operation.

[chore] Remove mongo transaction from feature list delete

---

featurebyte/models/feature_list.py
featurebyte/models/feature_list_store_info.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/models/test_feature_list.py
tests/unit/models/test_feature_list_store_info.py

This PR updates feature list store info to include the information whether Feast integration is enabled when the feature list is online enabled. …

[chore] Update feature list store info

---

featurebyte/api/batch_request_table.py
featurebyte/api/materialized_table.py
featurebyte/api/observation_table.py
featurebyte/api/static_source_table.py
featurebyte/query_graph/model/table.py
featurebyte/query_graph/sql/common.py
featurebyte/session/base.py
featurebyte/session/base_spark.py
featurebyte/session/databricks_unity.py
featurebyte/session/snowflake.py
tests/unit/conftest.py
tests/unit/session/test_snowflake_session.py
tests/unit/session/test_spark.py
tests/unit/session/test_sqlite_session.py

- update schema listing sql queries to support fetching larger list of tables in Snowflake and DataBricks
- expose fully qualified table name in table details
- add function to get spark dataframe from a materialized table …

[chore] Fix schema listing

---

featurebyte/service/feature_table_cache.py

This adds progress update and logs timing for feature table cache.

[chore] Add progress update and log timing for feature table cache

---

featurebyte/schema/worker/task/base.py
featurebyte/schema/worker/task/batch_feature_table.py
featurebyte/schema/worker/task/batch_request_table.py
featurebyte/schema/worker/task/online_store_cleanup.py
featurebyte/schema/worker/task/scheduled_feature_materialize.py
featurebyte/schema/worker/task/tile.py
tests/unit/service/test_task_manager.py
tests/unit/worker/test_task_executor.py

- Set default task priority as 2
- Use highest priority for production workload tasks

[chore] Use different task priority for production workload

---

.changelog/DEV-3093.yaml
featurebyte/__init__.py
featurebyte/api/materialized_table.py
scripts/enforce_import_rules.py

* fix databricks integration in SDK
* fix databricks integration in SDK

[DEV-3093] Fix databricks integration in SDK (Cherry-pick to 1.0)

---

featurebyte/exception.py
featurebyte/feast/enum.py
featurebyte/feast/utils/materialize_helper.py
tests/integration/query_graph/test_online_serving.py
tests/integration/service/test_working_schema_service.py
tests/unit/feast/utils/test_registry_construction.py

This PR fixes feature materialization issue (through Feast) during deployment enablement.

[DEV-3109] Fix feature materialization error during deployment enablement

---

.changelog/DEV-3105.yaml
featurebyte/service/observation_table.py
tests/integration/api/test_observation_table.py
tests/unit/service/test_observation_table.py

This adds a validation in observation table creation task to ensure that there is no missing values in the point in time and entity columns. …

[DEV-3105] Validate point in time and entity columns for missing values

---

docker/docker-compose.yml
featurebyte/api/materialized_table.py
featurebyte/api/utils.py
featurebyte/common/utils.py
featurebyte/core/accessor/count_dict.py
featurebyte/core/accessor/datetime.py
featurebyte/enum.py
featurebyte/exception.py
featurebyte/routes/feature_store/api.py
featurebyte/session/base.py
featurebyte/session/base_spark.py
featurebyte/session/databricks.py
featurebyte/session/snowflake.py
featurebyte/session/spark.py
scripts/enforce_import_rules.py
tests/integration/api/test_event_view_operations.py
tests/integration/api/test_feature_correctness.py
tests/integration/api/test_item_view_operations.py
tests/integration/api/test_scd_view_operations.py
tests/integration/api/test_table_column_critical_data_info.py
tests/integration/api/test_target_correctness.py
tests/integration/conftest.py
tests/integration/feature_manager/test_feature_manager.py
tests/integration/session/test_base.py
tests/integration/udf/test_object_agg.py
tests/unit/routes/base.py
tests/unit/session/test_databricks_session.py
tests/unit/session/test_snowflake_session.py

- Use cursor descriptions as source of truth for query return schema
- Standardize data format for pyarrow record batches for different warehouses …

[chore] Handle schema inconsistency between query fetch batches

---

featurebyte/models/feature.py
featurebyte/service/base_feature_service.py
featurebyte/service/entity_relationship_extractor.py
featurebyte/service/feature.py
featurebyte/service/feature_list.py
featurebyte/service/feature_offline_store_info.py
tests/unit/api/test_feature.py
tests/unit/models/test_feature.py

This PR updates feature & feature list creation logic to optimize time to create feature list.

[DEV-3097] Update feature & feature list creation logic

---

featurebyte/service/preview.py

This PR updates shape endpoint of the feature store to include performance & query graph size information to the log.

[chore] Add log to view shape endpoint for troubleshooting performance issue

---

featurebyte/query_graph/node/base.py
featurebyte/query_graph/node/nested.py
featurebyte/query_graph/node/request.py
tests/fixtures/on_demand_function/req_col_ttl_and_non_ttl.sql
tests/unit/api/conftest.py
tests/unit/api/test_null_filling_value.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/query_graph/test_node.py
tests/util/helper.py

DataBricks UDF treats datetime null value as `None` rather than `NaT`. This PR updates the DataBricks UDFs to handle the datetime null value properly. …

[DEV-3138] Fix DataBricks UDF datetime column null value handling

---

featurebyte/api/view.py

Update the docstring of `as_target` method to be more accurate.

[DEV-3139] Update as_target docstring

---

featurebyte/query_graph/sql/scd_helper.py

Optimize the `augment_table_with_effective_timestamp` method to reduce SCD join related SQL construction runtime. 

[chore] Optimize `augment_table_with_effective_timestamp` method

---

featurebyte/feast/service/registry.py
featurebyte/service/base_document.py
featurebyte/service/context.py
featurebyte/service/credential.py
featurebyte/service/offline_store_feature_table.py
featurebyte/service/offline_store_feature_table_manager.py
featurebyte/service/online_enable.py
featurebyte/service/table.py
tests/unit/feast/service/test_registry.py
tests/unit/service/test_feast_registry.py
tests/unit/service/test_offline_store_feature_table.py
tests/unit/service/test_relationship.py

This PR revises existing feature & feature list mongo operations during deployment enablement/disablement. 

[DEV-3140] Optimize mongo operations to avoid transaction timeout during deployment enablement/disablement

---

tests/unit/api/test_batch_feature_table.py

This updates the `test_batch_feature_table.py` tests to explicitly invoke the required mocks instead of implicitly relying on other tests to do so.
Fixes errors like this locally (or one day on CI when unlucky):
```
ERROR tests/unit/api/test_batch_feature_table.py::TestBatchFeatureTable::test_get - featurebyte.exception.RecordUpdateException: Traceback (most recent call last):
ERROR tests/unit/api/test_batch_feature_table.py::TestBatchFeatureTable::test_list - featurebyte.exception.RecordUpdateException: Traceback (most recent call last):
ERROR tests/unit/api/test_batch_feature_table.py::TestBatchFeatureTable::test_delete - featurebyte.exception.RecordUpdateException: Traceback (most recent call last):
ERROR tests/unit/api/test_batch_feature_table.py::TestBatchFeatureTable::test_info - …
```

[chore] Fix test_batch_feature_table.py to explicitly use required mocks

---

featurebyte/models/deployment.py
featurebyte/service/deploy.py
tests/unit/routes/test_catalog.py
tests/unit/routes/test_deployment.py

Track feature list namespace id in deployments

[chore] Track feature list namespace id in deployments

---

.github/workflows/changelog_gen.yaml
.github/workflows/daily-cron_gen.yaml
.github/workflows/dependencies_gen.yaml
.github/workflows/documentation_gen.yaml
.github/workflows/lint_gen.yaml
.github/workflows/publish-dev_gen.yaml
.github/workflows/publish-public_gen.yaml
.github/workflows/test-notebooks_gen.yaml
.github/workflows/test_gen.yaml

Bumping: 
+ github action: Taskfile
+ github action: upload-artifact
+ python runtime: poetry version
Using group runners instead of an individual one:
```
runs-on:
group: Public Runners
```
| …

[CICD] bumping cicd actions

---

featurebyte/feast/patch.py
featurebyte/service/online_serving.py

This PR patch Feast `OnDemandFeatureView.get_transformed_features_id` to fix pandas performance issue due to highly fragmented dataframe. …

[chore] Patch Feast `OnDemandFeatureView.get_transformed_features_df`

---

.changelog/DEV-3111.yaml
featurebyte/query_graph/sql/aggregator/base.py
featurebyte/query_graph/sql/scd_helper.py
featurebyte/service/historical_features_and_target.py
featurebyte/service/tile_cache.py
featurebyte/session/session_helper.py
featurebyte/tile/tile_cache.py
tests/integration/api/test_event_view_operations.py
tests/integration/tile/test_tile_cache.py
tests/unit/service/test_historical_features.py
tests/unit/service/tile/test_tile_cache.py

This updates tile cache to creating working tables in parallel when there are multiple batches of tracking tables to process. More places in sql generation are also updated to set copy to False when possible to avoid unnecessary copies. …

[DEV-3111] Create tile cache working tables in parallel

---

Taskfile.yaml
docker/Dockerfile

databricks-sql-connector and databricks-sdk mutates a particular file during installation. It could cause file corruption when poetry installs them in parallel.
**This is a sample error**
```bash
File "/home/runner/work/documentation/documentation/.venv/lib/python3.10/site-packages/featurebyte/session/databricks.py", line 23, in <module>
from databricks import sql as databricks_sql
File "/home/runner/work/documentation/documentation/.venv/lib/python3.10/site-packages/databricks/__init__.py", line 3
__path__ = __import__('pkgutil').extend_path(__path__, __name__)").extend_path(__path__, __name__)
^
SyntaxError: unterminated string literal (detected at line 3)
```
Testing out installing 1 of them to see if the problem goes away.
Label this pull request to place it under the correct category …

[bug] fixing bad installation of databricks

---

featurebyte/models/feature_list_store_info.py
featurebyte/query_graph/node/metadata/templates/on_demand_function_sql.tpl
tests/fixtures/on_demand_function/req_col_ttl_and_non_ttl.sql
tests/fixtures/on_demand_function/ttl_and_non_ttl.sql
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/query_graph/test_metadata_sdk_code.py

This PR updates DataBricks UDF function to return `None` value rather than `np.nan`.

[DEV-3176] Replace null value with None for DataBricks UDF

---

.github/workflows/test-notebooks_gen.yaml
.github/workflows/test_gen.yaml

Downgrading runners to lower cost

[chore] downgrade runners for some pipelines

---

pyproject.toml

[chore] version sync to 1.0.2

---

.changelog/DEV-3197.yaml
featurebyte/session/databricks_unity.py
featurebyte/sql/databricks_unity/F_COUNT_DICT_ENTROPY.sql
tests/integration/udf/test_count_dict_entropy.py

Fix entropy udf for DataBricks to return 0 when all counts are 0.

[DEV-3197] Fix entropy udf for DataBricks

---

.changelog/DEV-3201.yaml
featurebyte/api/catalog.py
featurebyte/api/credential.py
featurebyte/api/deployment.py
featurebyte/api/feature_list.py
featurebyte/api/historical_feature_table.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/models/observation_table.py
tests/unit/api/base_materialize_table_test.py
tests/unit/api/test_batch_feature_table.py
tests/unit/api/test_batch_request_table.py
tests/unit/api/test_deployment.py
tests/unit/api/test_historical_feature_table.py
tests/unit/api/test_observation_table.py

This PR introduces several feature table associated attributes to the object.

[DEV-3201] Add historical feature table associated attributes

---

.changelog/DEV-3202.yaml
featurebyte/session/databricks_unity.py
featurebyte/sql/databricks_unity/F_GET_RELATIVE_FREQUENCY.sql
tests/integration/udf/test_get_relative_frequency.py

Fix databricks relative udf raising division by zero exception when counts sum to zero

[/DEV-3202] Fix databricks relative frequency udf division by zero

---

featurebyte/session/manager.py

Add a `parameters` field to `SessionManager` to allow additional parameters to be set during session creation time

[chore] Support additional parameters for session creation

---

featurebyte/service/feature_list_facade.py
featurebyte/service/offline_store_feature_table_manager.py
featurebyte/worker/task/feature_list_make_production_ready.py

This PR revises make production ready task progress update.

[DEV-3209] Revise progress update for make features production ready task

---

featurebyte/feast/patch.py
featurebyte/feast/service/feature_store.py
featurebyte/service/feature_materialize.py
featurebyte/worker/task/catalog_online_store_update.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/feast/service/test_registry.py
tests/unit/feast/test_patch.py
tests/unit/service/test_offline_store_feature_table_manager.py

This PR optimizes the runtime to get online features. A feature list with 306 features is used to benchmark the runtime performance.
Current main branch takes about 14s to retrieves all online features.
This branch takes about 6-7s to retrieves all online features.
| …

[chore] Optimize get online features

---

featurebyte/api/historical_feature_table.py
scripts/enforce_import_rules.py
tests/unit/api/test_historical_feature_table.py

This PR updates get historical feature table method to include mlflow tracking information.

[DEV-3211] Update get historical feature table to track dataset using mlflow

---

featurebyte/service/preview.py
featurebyte/session/session_helper.py
featurebyte/utils/async_helper.py

Experimental PR to add concurrency limit to parallel query execution using asyncio

[chore] Support concurrency with asyncio gather

---

featurebyte/feast/service/feature_store.py
featurebyte/service/feature_materialize.py
tests/integration/feature_store_integration/test_feature_materialize.py

This PR introduces caching mechanism for Feast feature store to improve get online features runtime performance.
Before caching Feast feature store (takes about 7s to get online features of 306 features):
https://drive.google.com/file/d/14th4i7N2oQyYclddp-zi9MBnKRonQ-97/view?usp=drive_link
After caching Feast feature store (takes about 3.5s to get online features of 306 features):
https://drive.google.com/file/d/1JL78ER6njcjcZGFIEKiKON0MzTxbA-_E/view?usp=drive_link
| `bug`, `refactoring`, …

[chore] Cache feast feature store

---

.changelog/vuln-fix.yaml
poetry.lock
pyproject.toml

+ Bump vulnerable pillow and pymongo versions

[chore] bump pillow and pymongo

---

featurebyte/service/offline_store_feature_table_comment.py
tests/unit/service/test_offline_feature_store_comment.py

This PR handles apply comment exceptions so that it won't block deployment enablement process if any error happens.

[chore] Handle apply comments error

---

featurebyte/models/context.py
featurebyte/models/feature_list_namespace.py
featurebyte/routes/deployment/controller.py
featurebyte/routes/use_case/api.py
featurebyte/routes/use_case/controller.py
featurebyte/schema/context.py
tests/integration/api/test_serving_parent_features.py
tests/unit/api/test_databricks.py
tests/unit/api/test_deployment.py

This PR 
* updates use case listing to support filtering by feature list ID
* adds deployment's use case validation

[DEV-3229] Add use case filtering by feature ID support & implement deployment use case validation 

---

featurebyte/__init__.py
featurebyte/api/accessor/databricks.py
featurebyte/query_graph/node/metadata/templates/databricks_feature_spec.tpl
tests/unit/api/test_databricks.py
tests/unit/models/test_feature_list_store_info.py

This PR revises `databricks` accessor to fix existing bugs.

[chore] Revise `databricks` accessor

---

featurebyte/query_graph/sql/batch_helper.py
featurebyte/tile/tile_cache.py

Reduce nodes processing batch size for historical features to limit the complexity of individual queries.

[chore] Reduce nodes processing batch size for historical features

---

featurebyte/feast/model/registry.py
featurebyte/feast/schema/registry.py
featurebyte/feast/service/feature_store.py
featurebyte/feast/service/registry.py
featurebyte/models/deployment.py
featurebyte/models/offline_store_feature_table.py
featurebyte/routes/deployment/controller.py
featurebyte/schema/deployment.py
featurebyte/service/deploy.py
featurebyte/service/deployment.py
featurebyte/service/feature_materialize.py
featurebyte/service/offline_store_feature_table.py
featurebyte/service/offline_store_feature_table_manager.py
featurebyte/worker/task/catalog_online_store_update.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/feast/service/test_registry.py
tests/unit/routes/test_deployment.py
tests/unit/service/conftest.py
tests/unit/service/test_feast_registry.py
tests/unit/service/test_feature_materialize.py
tests/unit/service/test_offline_store_feature_table_manager.py
tests/unit/service/test_online_serving_feast.py
tests/unit/service/test_registry.py
tests/util/helper.py

This PR updates Feast registry to make it deployment specific.

[DEV-3241] Make Feast registry deployment specific

---

featurebyte/feast/service/feature_store.py
featurebyte/feast/utils/registry_construction.py
featurebyte/service/feature_materialize.py
featurebyte/worker/task/catalog_online_store_update.py
tests/integration/feature_store_integration/test_feature_materialize.py

This PR aims to fix Feast feature store used for feature materialization https://github.com/featurebyte/featurebyte/pull/2298#pullrequestreview-2007793902. …

[DEV-3241] Fix feast feature store used for materialization

---

featurebyte/models/entity_universe.py
tests/unit/conftest.py
tests/unit/models/test_entity_universe.py

This fixes a bug when constructing the entity universe for complex window aggregations.

[chore] Fix entity universe for complex window aggregates

---

featurebyte/session/base.py
featurebyte/session/sqlite.py
tests/unit/api/test_event_table.py
tests/unit/conftest.py
tests/unit/session/test_base.py
tests/unit/session/test_manager.py

Log failed sql queries to facilitate debugging

[chore] Log failed sql queries

---

featurebyte/feast/utils/on_demand_view.py
tests/unit/feast/service/test_registry.py

Fix Feast On-demand Feature View (ODFV) construction bug

[DEV-3295] Fix Feast ODFV construction bugs

---

featurebyte/worker/task_executor.py

Specify event loop explicitly in helper function to run async task in task executor

[chore] Specify event loop explicitly

---

.changelog/DEV-3306.yaml
featurebyte/models/offline_store_feature_table.py
featurebyte/service/feature_materialize.py
featurebyte/service/offline_store_feature_table.py
featurebyte/service/offline_store_feature_table_manager.py
tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table_missing_column.sql
tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
tests/unit/service/conftest.py
tests/unit/service/test_feature_materialize.py
tests/unit/service/test_online_serving_feast.py

This attempts to improve the handling of precomputed lookup feature tables to be more resilient to unexpected errors:
1. Split deployment enable and disable handling into different methods. This is so that when disabling a deployment, there is no way we will try to do things like re-initializing a missing lookup feature table (e.g on bad state), and vice versa.
2. In feature materialize service's `_get_latest_from_feature_table()`, handle the case where the data warehouse feature table is missing some expected columns based on our mongo records. This prevents it from failing immediately, and we have a chance to recover when `initialize_new_columns()` is called subsequently on the table.
|        **Pull …

[DEV-3306] Improve precomputed lookup feature tables handling

---

featurebyte/feast/utils/registry_construction.py
featurebyte/models/entity_lookup_feature_table.py
featurebyte/models/offline_store_feature_table.py
featurebyte/service/entity_lookup_feature_table.py
featurebyte/service/offline_store_feature_table.py
featurebyte/service/offline_store_feature_table_comment.py
featurebyte/service/offline_store_feature_table_manager.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/feast/conftest.py
tests/unit/feast/utils/test_registry_construction.py
tests/unit/service/test_offline_feature_store_comment.py
tests/unit/service/test_offline_store_feature_table_manager.py

This removes code related to dynamic entity lookup feature tables which are no longer used after https://github.com/featurebyte/featurebyte/pull/2314. Existing tables will be cleaned up when deployment is updated. …

[DEV-3230] Remove code related to dynamic entity lookup feature tables

---

featurebyte/feast/utils/registry_construction.py
tests/unit/feast/service/test_registry.py

This PR updates `RepoConfig` construction to address `entity_key_serialization_version` warning.

[chore] Fix Feast `entity_key_serialization_version` warning

---

featurebyte/models/feature_list.py
featurebyte/schema/feature_list.py
featurebyte/service/deploy.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/api/test_feature_list.py
tests/unit/models/test_feature_list.py
tests/unit/service/test_offline_store_feature_table_manager.py

This field is now no longer used anywhere and can be removed.

[chore] Remove unused enabled_serving_entity_ids in FeatureListModel 

---

featurebyte/worker/task_executor.py

Add logging to event loop health checker to facilitate troubleshooting

[chore] Add logging to event loop health checker for troubleshooting

---

featurebyte/models/offline_store_feature_table.py
featurebyte/models/precomputed_lookup_feature_table.py
featurebyte/query_graph/sql/entity.py
featurebyte/service/entity_lookup_feature_table.py
featurebyte/service/feature_materialize.py
featurebyte/service/online_serving.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/service/test_offline_store_feature_table_manager.py

This fixes the handling of composite entity in precomputed lookup feature tables. Previously, the case where only a subset of the entities in a composite entity undergo entity lookup was not handled properly and would trigger an error. …

[DEV-3294] Fix handling of composite entity in precomputed lookup feature tables

---

featurebyte/service/task_manager.py
featurebyte/worker/__init__.py
featurebyte/worker/start.py
featurebyte/worker/task_executor.py
tests/unit/worker/test_task_executor.py

Refactor io worker to use execution delay to detect worker responsiveness

[chore] Track worker responsiveness using execution delay

---

featurebyte/schema/worker/task/observation_table.py
featurebyte/schema/worker/task/observation_table_upload.py
featurebyte/session/base.py

Change observation creation task to CPU task.

[chore] Change observation creation task to cpu task

---

featurebyte/api/accessor/databricks.py
featurebyte/models/feature_list.py
featurebyte/models/feature_list_store_info.py
featurebyte/service/deploy.py
featurebyte/service/feature_list.py
featurebyte/service/offline_store_feature_table.py
featurebyte/service/offline_store_feature_table_manager.py
tests/unit/api/test_databricks.py
tests/unit/service/test_deploy.py
tests/unit/service/test_offline_store_feature_table_manager.py

Update DataBricks feature specs generation logic using precomputed lookup feature table.

[DEV-3334] Update DataBricks feature specs generation for precomputed lookup feature table

---

.changelog/pyopenssl-required.yaml
.github/workflows/dependencies.yaml
poetry.lock
pyproject.toml

+ Adding pyopenssl as a dependency

[Deps] Adding pyopenssl as a main dependency

---

featurebyte/models/offline_store_ingest_query.py
featurebyte/query_graph/node/metadata/config.py
featurebyte/query_graph/node/nested.py
featurebyte/service/deploy.py
featurebyte/service/feature_manager.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/api/test_databricks.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/util/helper.py

This PR
* updates null filling logic for DataBricks UDF;
* updates DataBricks UDF input signature for dictionary & array types.

[DEV-3343][DEV-3363] Implement null filling for DataBricks UDF

---

tests/integration/feature_store_integration/test_feature_materialize.py

Update functional test to check UDF with count dictionary input.

[chore] Update functional test to check DataBricks UDF

---

tests/integration/api/test_features.py

This adds a test case for relative frequency function with non-string keys to check that it works.

[chore] Add test case for relative frequency with non-string keys

---

featurebyte/query_graph/node/count_dict.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/query_graph/on_demand_function/test_count_dict.py

This PR fixes count dictionary feature retrieval when the dictionary is constructed from integer column. The key is converted to string before used for retrieval. …

[DEV-3381] Fix count dictionary key retrieval in on demand function

---

featurebyte/query_graph/node/function.py
featurebyte/query_graph/node/metadata/config.py
featurebyte/query_graph/transform/null_filling_value.py
tests/unit/api/test_user_defined_function.py

This PR updates null filling value extraction logic for UDF functions so that it won't block deployment enablement.

[chore] Update null filling value extraction logic for UDF

---

featurebyte/routes/context/controller.py
featurebyte/routes/feature_list/controller.py
featurebyte/routes/registry.py
featurebyte/routes/semantic/api.py
featurebyte/routes/semantic/controller.py
featurebyte/routes/target_namespace/controller.py
featurebyte/service/table.py
tests/unit/routes/test_batch_request_table.py
tests/unit/routes/test_event_table.py
tests/unit/routes/test_feature_list.py
tests/unit/routes/test_historical_feature_table.py
tests/unit/routes/test_observation_table.py
tests/unit/routes/test_semantic.py

This PR fix bugs in
* feature list deletion reference check;
* context deletion reference check;
* target namespace deletion reference check;
* semantic deletion reference check.
| …

[chore] Fix feature list deletion reference checking bug

---

.changelog/DEV-2983.yaml
featurebyte/api/feature.py
featurebyte/api/user_defined_function_injector.py
featurebyte/models/feature.py
featurebyte/query_graph/graph.py
featurebyte/query_graph/model/graph.py
featurebyte/service/feature.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/api/test_user_defined_function.py

This PR revises UDF input validation logic to prevent user to create UDF features that requires on-demand-function during deployment. …

[DEV-2983] Prevent user to create UDF feature that is not deployable

---

.changelog/DEV-3405.yaml
featurebyte/api/event_table.py
featurebyte/api/scd_table.py
featurebyte/models/scd_table.py
featurebyte/routes/common/base_table.py
featurebyte/routes/scd_table/api.py
featurebyte/routes/scd_table/controller.py
featurebyte/schema/backward_compatible/table.py
featurebyte/schema/event_table.py
featurebyte/schema/scd_table.py
tests/fixtures/request_payloads/scd_table.json
tests/unit/api/test_change_view.py
tests/unit/api/test_scd_table.py
tests/unit/models/test_scd_table.py
tests/unit/routes/test_scd_table.py

This PR adds default feature job setting support to `SCDTable`.

[DEV-3405] Add default feature job setting to `SCDTable`

---

featurebyte/session/base.py
featurebyte/session/base_spark.py

This reverts commit 21c147bf09e7915a57dea51931a8e19afe212b62.
It's still used externally outside this codebase.

[chore] Revert "Remove unused register_table_with_query"

---

featurebyte/schema/worker/task/base.py
featurebyte/schema/worker/task/batch_feature_create.py
featurebyte/schema/worker/task/batch_feature_table.py
featurebyte/schema/worker/task/batch_request_table.py
featurebyte/schema/worker/task/data_description.py
featurebyte/schema/worker/task/deployment_create_update.py
featurebyte/schema/worker/task/feature_job_setting_analysis.py
featurebyte/schema/worker/task/feature_list_batch_feature_create.py
featurebyte/schema/worker/task/feature_list_create.py
featurebyte/schema/worker/task/feature_list_make_production_ready.py
featurebyte/schema/worker/task/historical_feature_table.py
featurebyte/schema/worker/task/materialized_table_delete.py
featurebyte/schema/worker/task/observation_table.py
featurebyte/schema/worker/task/observation_table_upload.py
featurebyte/schema/worker/task/online_store_cleanup.py
featurebyte/schema/worker/task/online_store_initialize.py
featurebyte/schema/worker/task/scheduled_feature_materialize.py
featurebyte/schema/worker/task/static_source_table.py
featurebyte/schema/worker/task/target_table.py
featurebyte/schema/worker/task/test.py
featurebyte/schema/worker/task/tile.py
featurebyte/worker/test_util/random_task.py

This PR revises existing worker task payload schema to make it explicit between class variables and instance variables. This is part of the efforts to prepare for upgrading pydantic to v2.
| …

[chore] Fix worker task payload schema

---

featurebyte/session/base.py
tests/integration/session/test_base.py
tests/unit/session/test_base.py

This PR revise SQL query execution error logging to fix the issue that error query is not logged properly.

[chore] Revise SQL query error logging logic

---

featurebyte/api/feature_store.py
featurebyte/models/credential.py
featurebyte/models/online_store.py
featurebyte/models/user_defined_function.py
featurebyte/query_graph/model/feature_job_setting.py
featurebyte/query_graph/node/base.py
featurebyte/query_graph/node/binary.py
featurebyte/query_graph/node/cleaning_operation.py
featurebyte/query_graph/node/generic.py
featurebyte/query_graph/node/schema.py
featurebyte/schema/feature_list.py

This PR makes class variables explicit in `query_graph/node` directory.

[chore] Make class variables explicit in `query_graph/node` directory

---

.changelog/DEV-3507.yaml
featurebyte/api/feature_store.py
featurebyte/query_graph/node/schema.py
featurebyte/routes/feature_store/api.py
featurebyte/routes/feature_store/controller.py
featurebyte/schema/feature_store.py
tests/unit/api/test_feature_store.py
tests/unit/routes/test_feature_store.py

Add route and SDK API to update feature store details

[DEV-3507] Add route to update feature store details

---

tests/unit/query_graph/test_critical_data_info.py
tests/unit/query_graph/test_definition.py
tests/unit/query_graph/test_extract_operation_structure.py
tests/unit/query_graph/test_graph_node.py
tests/unit/query_graph/test_graph_pruning.py
tests/unit/query_graph/test_nested_graph_pruning.py
tests/util/helper.py

For Pydantic V2, equality comparison behaviour is changed. This PR revises existing pydantic object comparison in unique tests.

[chore] Revise tests

---

featurebyte/service/base_document.py
tests/integration/api/test_event_view_operations.py
tests/unit/service/test_base_document.py

This adds support for batch document creation and deletion in `BaseDocumentService`.

[DEV-3523] Support batch document creation and deletion

---

featurebyte/query_graph/sql/feature_compute.py
tests/unit/query_graph/test_feature_compute.py

Clean up a method in FeatureExecutionPlan that is not needed and only called in test.

[chore] Clean up unused method in FeatureExecutionPlan

---

featurebyte/routes/feature_store/controller.py
featurebyte/service/session_manager.py
tests/conftest.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/integration/feature_store_integration/test_update_online_store.py
tests/unit/api/test_databricks.py
tests/unit/api/test_dimension_view.py
tests/unit/api/test_event_view.py
tests/unit/api/test_feature.py
tests/unit/api/test_item_view.py
tests/unit/api/test_null_filling_value.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/api/test_request_column.py
tests/unit/api/test_scd_view.py
tests/unit/conftest.py
tests/unit/feast/conftest.py
tests/unit/routes/conftest.py
tests/unit/routes/test_batch_feature_table.py
tests/unit/routes/test_feature_store.py
tests/unit/service/test_feast_registry.py
tests/unit/service/test_feature_materialize.py
tests/unit/service/test_offline_feature_store_comment.py
tests/unit/service/test_offline_store_feature_table_manager.py
tests/unit/service/test_online_serving_feast.py

Fix updating feature store details validation always fails due to validation test. 

[DEV-3507] Fix update feature store details validation

---

featurebyte/api/feature_group.py
featurebyte/models/feature_list.py
featurebyte/models/historical_feature_table.py
featurebyte/schema/constant.py
featurebyte/schema/feature.py
featurebyte/schema/feature_list.py
featurebyte/service/historical_feature_table.py
featurebyte/worker/task/historical_feature_table.py
tests/fixtures/request_payloads/historical_feature_table.json
tests/unit/api/test_historical_feature_table.py
tests/unit/routes/test_feature_list.py

This PR adds attributes to track features used in historical feature table.

[DEV-3555] Add attributes to track feature ID & name used in historical feature table computation

---

featurebyte/models/historical_feature_table.py
featurebyte/worker/task/historical_feature_table.py
tests/integration/api/test_event_view_operations.py

This PR revises historical feature table model to include features information.

[chore] Revise historical feature table model

---

featurebyte/query_graph/sql/aggregator/window.py
featurebyte/query_graph/sql/ast/tile.py
featurebyte/query_graph/sql/feature_compute.py
featurebyte/query_graph/sql/online_store_compute_query.py

This avoids unnecessary deepcopies in sqlglot when constructing complex queries.

[chore] Set more copy=False when possible in sqlglot

---

featurebyte/worker/task/historical_feature_table.py

Fix the issue where old historical feature table payload failed.

[chore] Handle old historical feature table payload

---

Taskfile.yaml
featurebyte/storage/webdav.py
tests/integration/storage/base.py
tests/integration/storage/test_webdav_storage.py

+ Adding webdav support (transparent to client)

[DEV-3565] adding webdav support

---

featurebyte/api/accessor/databricks.py
featurebyte/models/feature_list_store_info.py
tests/unit/api/test_databricks.py

This PR introduces an option to skip certain columns to be excluded from feature specs.

[chore] Add skip exclude column parameters to get feature spec method

---

.changelog/DEV-3572.yaml
featurebyte/api/aggregator/asat_aggregator.py
featurebyte/api/aggregator/base_aggregator.py
featurebyte/api/aggregator/simple_aggregator.py
featurebyte/api/aggregator/window_aggregator.py
featurebyte/enum.py
featurebyte/query_graph/node/agg_func.py
featurebyte/query_graph/node/metadata/operation.py
featurebyte/query_graph/sql/groupby_helper.py
tests/integration/api/test_feature_correctness.py
tests/unit/api/test_aggregate_over.py
tests/unit/query_graph/sql/test_groupby_helper.py

This adds support for a new aggregation method `count_distinct` which counts the number of distinct values in a column. For window aggregates (aggretate_over), this is supported by the new non-tile window aggregate node type. …

[DEV-3572] Support count_distinct aggregation method

---

featurebyte/api/aggregator/simple_aggregator.py
featurebyte/api/base_table.py
featurebyte/api/catalog.py
featurebyte/api/feature.py
featurebyte/api/feature_job.py
featurebyte/api/feature_list.py
featurebyte/api/groupby.py
featurebyte/api/observation_table.py
featurebyte/api/relationship.py
featurebyte/api/user_defined_function.py
tests/unit/api/test_groupby.py
tests/unit/api/test_relationship.py

This PR revises `typechecked` for enum type to make it compatible with the latest typechecked.

[chore] Update `typechecked` for enum type

---

tests/unit/api/base_view_test.py
tests/unit/api/test_change_view.py
tests/unit/api/test_credential.py
tests/unit/api/test_event_table.py
tests/unit/api/test_event_view.py
tests/unit/api/test_feature.py
tests/unit/api/test_scd_table.py
tests/unit/api/test_table_column.py
tests/unit/conftest.py
tests/unit/core/test_series.py
tests/unit/models/test_feature_list.py
tests/unit/models/test_user_defined_function.py
tests/unit/query_graph/model/test_table_data.py
tests/unit/routes/test_feature.py
tests/unit/schema/test_feature_list.py
tests/unit/schema/test_target_table.py
tests/unit/service/test_base_document.py
tests/unit/service/test_context.py
tests/unit/service/test_table_columns_info.py
tests/unit/service/test_version.py
tests/unit/test_generate_payload_fixtures.py
tests/unit/worker/task/test_static_source_table.py

This PR updates pydantic object comparison used in tests.

[chore] Revise tests for preparation of pydantic update

---

featurebyte/models/entity_universe.py
featurebyte/query_graph/graph.py
featurebyte/query_graph/sql/adapter/base.py
featurebyte/query_graph/sql/adapter/databricks.py
featurebyte/query_graph/sql/adapter/snowflake.py
featurebyte/query_graph/transform/decompose_point.py
featurebyte/service/feature_offline_store_info.py
tests/fixtures/offline_store_feature_table/count_distinct_window_aggregate_universe.sql
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/conftest.py
tests/unit/service/test_offline_store_feature_table_manager.py

This makes the required changes to support deploying features using non-tile window aggregate nodes. Changes:
1. Implement entity universe for non-tile window aggregate node
2. Update `has_ttl` handling - non-tile window aggregate node features should have ttl
| …

[DEV-3578] Update deployment workflows to handle non-tile window aggregate nodes

---

featurebyte/worker/task/catalog_online_store_update.py

Task name was not logged correctly.

task/catalog_online_store_update: Fix task logging message

---

.changelog/DEV-3594.yaml
featurebyte/routes/common/feature_metadata_extractor.py
featurebyte/routes/feature/controller.py
featurebyte/routes/target/controller.py
tests/unit/api/test_feature.py

This PR aims to fix the `KeyError` exception when referencing column not found in the `reference_map` dictionary.

[DEV-3594] Fix feature metadata extraction `KeyError` exception

---

tests/unit/migration/test_run.py

[chore] fixing unit-tests

---

featurebyte/common/date_util.py
featurebyte/models/feature_materialize_prerequisite.py
featurebyte/routes/registry.py
featurebyte/service/feature_materialize_prerequisite.py
featurebyte/service/feature_materialize_sync.py
tests/unit/service/test_feature_materialize_prerequisite.py
tests/unit/service/test_feature_materialize_sync.py

This implements the services required for coordinating the execution of feature materialize task and dependent tile tasks.
There is no functional changes yet as the services are not yet used when enabling deployments. …

[DEV-3586] Implement services for feature materialize task coordination

---

featurebyte/service/feature_materialize_prerequisite.py
featurebyte/service/feature_materialize_sync.py
tests/unit/service/test_feature_materialize_prerequisite.py

Some minor changes to address comments in https://github.com/featurebyte/featurebyte/pull/2448.

[DEV-3586] Minor improvements for FeatureMaterializePrerequisiteService

---

featurebyte/service/tile/tile_task_executor.py
tests/unit/service/tile/test_tile_task_executor.py

This updates tile task to report completion status for feature materialisation.

[DEV-3589] Update tile task to report completion status

---

featurebyte/schema/table.py
featurebyte/service/table_columns_info.py
featurebyte/sql/tile_generate.py
tests/unit/api/test_event_table.py

This PR updates table columns info update logic so that it works for pydantic V2 when the imputed value is `None`.

[chore] Update `table columns_info` update

---

.github/workflows/expire-tags.yaml
.github/workflows/lint.yaml
.github/workflows/publish-dev.yaml
.github/workflows/publish-public.yaml
.github/workflows/test-notebooks.yaml
.github/workflows/test.yaml

+ Adding a workflow to development releases to check whether an installation would work
+ Reducing slack calls to find which channel-id to send message to. This will now be a static file that must be updated when a new person joins.
```
curl -X POST \
-H "Authorization: Bearer $TOKEN" \
-H 'Content-type: application/json; charset=utf-8' \
https://slack.com/api/users.list  |\
jq -r '.members[] | select(.is_bot == false) | .profile.email + "," + .id' 
```
| `bug`, `refactoring`, `bugfix`, `fix` …

[chore] Adding test to validate client install works

---

featurebyte/migration/model.py
featurebyte/migration/run.py
featurebyte/migration/service/mixin.py
featurebyte/persistent/base.py
tests/unit/persistent/test_mongo.py

This updates the migration framework to be more customisable. Changes:
* Support defining additional migration services not in `migration/service/`
* Make `migrate_func` async to support more complex migration that requires async operations …

[chore] Update migration framework to be more customisable

---

featurebyte/migration/run.py
tests/unit/migration/test_run.py

Follow up to https://github.com/featurebyte/featurebyte/pull/2470.

[chore] Relax constraints on migration versions

---

featurebyte/service/preview.py
featurebyte/warning.py
tests/unit/service/test_preview.py

Add `QueryNoLimitWarning` so that we could capture issue earlier when calling the service methods without setting limit.

[chore] Add QueryNoLimitWarning

---

.github/workflows/test.yaml

Reverts featurebyte/featurebyte#2476

Revert "[chore] Update `test.yaml` for post release"

---

.github/workflows/test-notebooks.yaml
.github/workflows/test.yaml

Fix workflow referencing old job for slack output

[chore] slack output remove missing integration test job

---

.github/workflows/publish-dev.yaml

Automate publishing of dev packages for post release branch (or branches if there are more instances like this in the future).

[chore] Publish dev packages for post release branch

---

.github/workflows/publish-dev.yaml

[chore][cherry-pick] Publish dev packages for post release branch

---

.github/workflows/publish-dev.yaml

[chore][fix] missing $ in publish workflow

---

.github/workflows/publish-dev.yaml

[chore][fix] another missing $ in publish workflow

---

.github/workflows/publish-dev.yaml

[chore][fix] missing $

---

featurebyte/query_graph/sql/aggregator/non_tile_window.py
tests/integration/api/test_event_view_operations.py
tests/integration/conftest.py

This PR addresses potential duplicated parent names during non-tile aggregation.

[DEV-3632] Fix potential duplicated parent names in non-tile aggregate

---

featurebyte/query_graph/sql/common.py
featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py
tests/integration/api/conftest.py
tests/integration/api/test_view_describe.py
tests/integration/api/test_view_sample.py
tests/unit/query_graph/interpreter/test_interpreter.py
tests/unit/routes/test_feature_store.py

This adds clipping to timestamp columns when retrieving sample and preview to prevent out of bound timestamp issues during conversion to arrow / pandas. …

[DEV-3628] Clip timestamp columns in sample and preview

---

featurebyte/query_graph/sql/aggregator/non_tile_window.py
tests/integration/api/test_event_view_operations.py
tests/integration/conftest.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2484

[DEV-3632] Fix potential duplicated parent names in non-tile aggregate (#2484)

---

featurebyte/tile/tile_cache.py

Fix progress update percentage so that it is less than 100.

[chore] Fix progress update percentage

---

featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py
tests/fixtures/query_graph/expected_value_counts_sampled_data.sql
tests/unit/query_graph/interpreter/test_preview.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2497

[DEV-3642][cherry-pick] Update PreviewService to do value counts without sorting full table (#2497)

---

featurebyte/tile/tile_cache.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2499

[chore][cherry-pick] Fix progress update percentage (#2499)

---

featurebyte/query_graph/node/cleaning_operation.py
featurebyte/session/manager.py
tests/unit/models/test_scd_table.py
tests/unit/session/test_manager.py

Fix bugs due to recent pydantic upgrade.

[DEV-3648] Fix bugs due to pydantic upgrade

---

featurebyte/routes/common/base_table.py
featurebyte/service/table_columns_info.py
featurebyte/service/table_facade.py
featurebyte/service/table_info.py
tests/unit/routes/test_event_table.py

This PR updates table update endpoint to conditionally skip semantic check.

[DEV-3621] Update table columns info update endpoint to conditionally skip semantic check

---

featurebyte/common/progress.py
tests/unit/common/test_progress.py

This PR revises progress update signature to allow user to clip progress update at the beginning of the update.

[chore] Revise progress update to give a smoother total runtime estimate

---

.github/workflows/test-notebooks.yaml
.github/workflows/test.yaml
featurebyte/query_graph/node/date.py
featurebyte/query_graph/sql/parent_serving.py
poetry.lock
pyproject.toml
tests/integration/api/test_event_view_operations.py
tests/integration/api/test_feature_correctness.py
tests/integration/feature_store_integration/test_feature_materialize.py
tests/unit/common/test_validator.py
tests/unit/query_graph/on_demand_function/test_date.py
tests/unit/query_graph/util.py

This PR revises the statements generation logic for UDF so that it is compatible with pandas 1.5 & 2.0.

[DEV-3659] Revise week datetime extraction for pandas 2.0

---

.changelog/DEV-3662.yaml
featurebyte/models/base.py
featurebyte/models/entity.py
tests/unit/models/test_base.py

Tighten asset name limit to leave room for internal use.

[DEV-3662] Tighten asset name limit

---

featurebyte/query_graph/node/input.py
featurebyte/query_graph/sql/ast/input.py
featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py
tests/fixtures/query_graph/expected_primary_table_sampled_data.sql
tests/unit/query_graph/interpreter/test_preview.py

Update `PreviewService` describe method to support sampling on primary table.

[chore] Update `PreviewService` to support sampling on primary table

---

featurebyte/query_graph/model/graph.py
featurebyte/query_graph/sql/interpreter/preview.py
tests/unit/api/test_item_view.py
tests/unit/api/test_view.py

This PR fixes table selection logic used for preview service's describe method.

[chore] Fix table selection logic used in describe

---

featurebyte/models/user_defined_function.py
featurebyte/query_graph/sql/ast/base.py
featurebyte/query_graph/sql/ast/input.py
featurebyte/query_graph/sql/ast/tile.py
featurebyte/query_graph/sql/builder.py
featurebyte/query_graph/sql/common.py
featurebyte/query_graph/sql/entity_filter.py
featurebyte/query_graph/sql/interpreter/tile.py
tests/fixtures/expected_historical_requests_multiple_batches_feature_set_0.sql
tests/fixtures/expected_historical_requests_multiple_batches_feature_set_2.sql
tests/fixtures/expected_preview_sql_all_types.sql
tests/fixtures/expected_tile_sql_on_demand.sql
tests/fixtures/expected_tile_sql_on_demand_complex_composite.sql
tests/fixtures/expected_tile_sql_on_demand_simple.sql
tests/integration/api/test_feature_correctness.py
tests/integration/api/test_features.py
tests/integration/api/test_scd_view_operations.py
tests/unit/query_graph/conftest.py
tests/unit/query_graph/interpreter/test_interpreter.py
tests/unit/query_graph/sql/test_tile.py
tests/unit/query_graph/test_definition.py
tests/unit/query_graph/test_extract_operation_structure.py
tests/unit/query_graph/test_join.py
tests/unit/query_graph/test_sql.py

This implements filtering for input table based on selected entities when building tiles on demand. This filter is applied at the InputNode level before other operations such as joins.
| …

[DEV-3671] Filter input table based on selected entities when building tiles on demand

---

featurebyte/query_graph/model/graph.py
featurebyte/query_graph/sql/interpreter/preview.py
tests/unit/api/test_item_view.py
tests/unit/api/test_view.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2519

[chore] Fix table selection logic used in describe (#2519)

---

featurebyte/query_graph/sql/interpreter/preview.py
tests/fixtures/query_graph/expected_filtered_table_primary_table_sampled_data.sql
tests/fixtures/query_graph/expected_item_table_join_event_table_primary_table_sampled_data.sql
tests/fixtures/query_graph/expected_primary_table_sampled_data.sql
tests/unit/query_graph/interpreter/test_preview.py

This PR revises existing primary table sampling logic by oversample the primary table when the query graph containing
* filtering operation with join operation
* inner join operation
| …

[chore] Revise primary table sampling logic

---

featurebyte/service/task_manager.py
featurebyte/worker/task_executor.py
featurebyte/worker/test_util/random_task.py
tests/integration/tile/test_tile_scheduler.py
tests/unit/worker/test_task_executor.py

This PR revises task executor to conditionally provide last update.

[chore] Revise task executor

---

featurebyte/service/preview.py

Reduce describe sql batch size to limit UDF usage in a single SQL query

[DEV-3689] reduce describe sql batch size

---

featurebyte/sql/bigquery/F_COUNT_DICT_COSINE_SIMILARITY.sql
featurebyte/sql/bigquery/F_COUNT_DICT_ENTROPY.sql
featurebyte/sql/bigquery/F_COUNT_DICT_LEAST_FREQUENT.sql
featurebyte/sql/bigquery/F_COUNT_DICT_MOST_FREQUENT.sql
featurebyte/sql/bigquery/F_COUNT_DICT_MOST_FREQUENT_KEY_VALUE.sql
featurebyte/sql/bigquery/F_COUNT_DICT_MOST_FREQUENT_VALUE.sql
featurebyte/sql/bigquery/F_GET_RANK.sql
featurebyte/sql/bigquery/F_GET_RELATIVE_FREQUENCY.sql
featurebyte/sql/bigquery/F_TIMEZONE_OFFSET_TO_SECOND.sql
tests/integration/conftest.py
tests/integration/udf/bigquery/util.py
tests/integration/udf/test_cosine_similarity.py
tests/integration/udf/test_count_dict_entropy.py
tests/integration/udf/test_get_rank.py
tests/integration/udf/test_get_relative_frequency.py
tests/integration/udf/test_least_frequent.py
tests/integration/udf/test_most_frequent.py
tests/integration/udf/test_timezone_offset_to_second.py
tests/unit/session/test_bigquery_session.py

Implement more UDFs for BigQuery.

[DEV-3684] BigQuery: Implement more UDFs

---

featurebyte/migration/service/data_warehouse.py
featurebyte/migration/service/mixin.py
featurebyte/session/base.py
tests/unit/session/test_base.py

Reverts featurebyte/featurebyte#2536

Revert "[DEV-3682] Add retry to sql execution on timeout"

---

featurebyte/feature_manager/model.py
featurebyte/models/feature.py
featurebyte/query_graph/sql/adapter/base.py
featurebyte/query_graph/sql/adapter/bigquery.py
featurebyte/query_graph/sql/ast/binary.py
featurebyte/query_graph/sql/ast/count_dict.py
featurebyte/query_graph/sql/ast/datetime.py
featurebyte/query_graph/sql/ast/literal.py
featurebyte/query_graph/sql/ast/string.py
featurebyte/query_graph/sql/ast/vector.py
featurebyte/query_graph/sql/groupby_helper.py
featurebyte/session/bigquery.py
featurebyte/sql/bigquery/F_OBJECT_DELETE.sql
featurebyte/worker/task/observation_table_upload.py
tests/integration/api/test_event_view_operations.py
tests/integration/conftest.py
tests/unit/core/accessor/test_string.py
tests/unit/core/test_series.py
tests/unit/models/test_user_defined_function.py
tests/unit/query_graph/sql/adapter/base_adapter_test.py
tests/unit/query_graph/sql/test_groupby_helper.py
tests/unit/session/test_bigquery_session.py
tests/util/helper.py

This adds fixes to make more event view operations compatible with BigQuery.

[DEV-3698] BigQuery: Support event view operations

---

.github/workflows/test.yaml
featurebyte/query_graph/sql/adapter/base.py
featurebyte/query_graph/sql/adapter/bigquery.py
featurebyte/query_graph/sql/adapter/snowflake.py
tests/integration/api/test_distance_operations.py
tests/integration/api/test_scd_view_operations.py
tests/integration/conftest.py
tests/integration/service/test_feature_table_cache.py

This adds support for distance operations and enable more integration tests for BigQuery.

[DEV-3712] BigQuery: Support distance operations and enable more tests

---

.changelog/DEV-3709.yaml
Taskfile.lint.yaml
featurebyte/app.py

+ Manage websocket closure properly
+ Convert fastapi startup/shutdown events to the new fastapi syntax
+ Linting task fixes

[DEV-3709] handing application lifecycle

---

poetry.lock
pyproject.toml

https://openssl-library.org/news/secadv/20240903.txt

[chore] bump vuln package cryptography

---

featurebyte/common/date_util.py
featurebyte/models/entity_universe.py
featurebyte/models/precomputed_lookup_feature_table.py
featurebyte/query_graph/sql/ast/tile.py
featurebyte/service/feature_manager.py
tests/fixtures/feature_manager/enable_new_feature.sql
tests/fixtures/feature_manager/enable_new_feature_offset.sql
tests/fixtures/feature_manager/enable_second_feature_later_date.sql
tests/fixtures/feature_manager/enable_second_feature_much_later_date.sql
tests/fixtures/feature_manager/enable_with_backfill_metadata.sql
tests/fixtures/feature_manager/enable_without_last_run_metadata.sql
tests/integration/feature_manager/test_feature_manager.py

This fixes timestamps handling in tile sql and entity universe so that they are compatible with BigQuery.

[DEV-3713] BigQuery: Fix timestamps handling in tile sql and entity universe

---

featurebyte/api/source_table.py
tests/unit/api/test_event_table.py
tests/unit/api/test_scd_table.py

Fix `get_or_create_*_table` method signature.

[chore] Fix `get_or_create_*_table` signature

---

featurebyte/schema/info.py
tests/unit/api/test_event_table.py
tests/unit/api/test_item_table.py
tests/unit/api/test_scd_table.py

Fix `SCDTable` info when `natural_key_column` is `None`.

[chore] Fix `SCDTable` info

---

featurebyte/query_graph/sql/adapter/bigquery.py
featurebyte/query_graph/sql/ast/count_dict.py
featurebyte/session/bigquery.py
featurebyte/sql/bigquery/F_GET_VALUE.sql
tests/integration/api/test_datetime.py
tests/integration/udf/test_get_value.py
tests/unit/query_graph/test_sql.py

Adding 3 commits to post-release branch
```
* 0ddaa816 - (tag: 2.0.1.dev4, origin/main, origin/HEAD) [DEV-3734] BigQuery: Fix errors in F_GET_VALUE and PARSE_JSON (#2579) (46 minutes ago) <Yung Siang Lia>
* 4274b045 - (tag: 2.0.1.dev3) [DEV-3731] BigQuery: Handle date type preview and add datetime diff tests (#2575) (2 hours ago) <Yung Siang Liau>
* a247fbff - (tag: 2.0.1.dev2) [DEV-3732] BigQuery: Cast key to string in get_value (#2576) (3 hours ago) <Yung Siang Liau>
```
| `bug`, …

[chore] Bumping post-release branch

---

featurebyte/common/doc_util.py
featurebyte/common/utils.py
featurebyte/models/base.py
featurebyte/query_graph/algorithm.py
featurebyte/query_graph/graph.py
featurebyte/query_graph/model/graph.py
featurebyte/query_graph/sql/builder.py
featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/query_graph/transform/pruning.py
featurebyte/query_graph/transform/sdk_code.py
featurebyte/session/base.py
featurebyte/session/snowflake.py
tests/unit/query_graph/test_query_graph.py

Pydantic upgrade has caused defaultdict warning, removing defaultdict in global graph removes the warning in backend.
```
task: [local:api] poetry run uvicorn entry:app --host=0.0.0.0 --port=5000 --timeout-keep-alive=300 --loop=asyncio --log-level=info
{"time": "2024-09-16T06:05:30Z", "message": "Running startup tasks", "level": "INFO"}
{"time": "2024-09-16T06:05:30Z", "message": "Waiting for persistent to be ready", "level": "INFO"}
{"time": "2024-09-16T06:05:30Z", "message": "Persistent is ready", "level": "INFO"}
{"time": "2024-09-16T06:05:30Z", "message": "Completed startup tasks", "level": "INFO"}
{"time": "2024-09-16T06:05:32Z", "message": "OK", "level": "INFO", "request_id": "43ab6ae5-0601-42f8-af6f-2ec18ebb4cf4", "time_elapsed": 0.00041, "url": …
```

[chore] removing deprecated functions

---

featurebyte/query_graph/node/input.py
featurebyte/query_graph/sql/interpreter/preview.py
tests/unit/models/test_scd_table.py

This PR aims to fix pydantic related warnings.

[chore] Fix pydantic related warnings

---

.changelog/DEV-3740.yaml
featurebyte/service/table_facade.py
tests/unit/routes/base.py
tests/unit/routes/test_event_table.py

This PR update table status update logic to remove entity tagging after table is deprecated.

[DEV-3740] Remove entity tagging after table is deprecated

---

.changelog/DEV-3740.yaml
featurebyte/service/table_facade.py
tests/unit/routes/test_event_table.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2590

[DEV-3740] Remove entity tagging after table is deprecated (#2590)

---

.github/workflows/publish-dev.yaml
poetry.lock
pyproject.toml

+ After bumping feast, we can support python 3.12

[chore] supporting python3.12

---

featurebyte/api/api_handler/base.py
tests/unit/api/test_feature_store.py

This PR revises SDK api object listing logic so that it skips item with pydantic validation error.

[DEV-3747] Skip validation error during SDK api object listing

---

featurebyte/models/offline_store_ingest_query.py
featurebyte/query_graph/transform/on_demand_view.py
tests/unit/api/test_deployment.py
tests/unit/api/test_null_filling_value.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/feast/utils/test_registry_construction.py

This PR revises feature's ODFV construction logic to fix pandas warning.

[chore] Fix Feast ODFV function's pandas warning

---

featurebyte/exception.py
featurebyte/query_graph/sql/aggregator/base_asat.py
featurebyte/query_graph/sql/asat_helper.py
featurebyte/routes/registry.py
featurebyte/service/scd_table_validation.py
tests/fixtures/scd_table_validation/no_end_timestamp.sql
tests/fixtures/scd_table_validation/with_end_timestamp.sql
tests/integration/service/test_scd_table_validation.py
tests/unit/api/test_source_table.py
tests/unit/service/test_scd_table_validation.py

This adds `SCDTableValidationService` to be used to validate that an SCD table is properly configured as part of the table registration guadrails. …

[DEV-3768] Add SCDTableValidationService for table registration guardrails

---

featurebyte/models/task.py
featurebyte/worker/util/task_progress_updater.py
tests/unit/models/test_task.py
tests/unit/worker/test_util.py

This PR updates task progress updater to store history of progress update.

[DEV-3772] Add `progress_history` to task document

---

featurebyte/schema/task.py
featurebyte/service/task_manager.py
tests/integration/worker/test_task_manager.py

This PR updates `get_task` so that it exposes progress history.

[DEV-3772] Update `get_task` to expose progress_history

---

.changelog/DEV-3745.yaml
featurebyte/feast/utils/materialize_helper.py
featurebyte/query_graph/node/schema.py
featurebyte/session/base.py
featurebyte/session/bigquery.py
featurebyte/session/databricks.py
featurebyte/session/manager.py
featurebyte/session/snowflake.py
featurebyte/session/spark.py
featurebyte/session/sqlite.py
tests/integration/session/test_base.py
tests/integration/session/test_bigquery.py
tests/unit/session/test_base.py
tests/unit/session/test_bigquery_session.py

Cancel sql query on timeout or task cancellation to avoid unnecessary data warehouse costs.

[DEV-3745] Cancel sql query on timeout or task cancellation

---

.changelog/DEV-3808.yaml
featurebyte/models/feature_store.py
featurebyte/routes/feature_store/api.py
featurebyte/routes/feature_store/controller.py
featurebyte/schema/feature_store.py
featurebyte/service/feature_materialize.py
featurebyte/service/historical_features_and_target.py
featurebyte/service/online_serving.py
featurebyte/service/preview.py
featurebyte/service/tile_cache.py
featurebyte/service/tile_manager.py
featurebyte/session/session_helper.py
featurebyte/tile/tile_cache.py
tests/fixtures/request_payloads/feature_store.json
tests/integration/tile/test_tile_cache.py
tests/unit/api/test_feature_store.py
tests/unit/routes/test_feature_store.py
tests/unit/session/test_session_helper.py
tests/unit/tile/test_unit_snowflake_tile.py

Add route to update query concurrency for a feature store

[DEV-3808] support configuring query concurrency for feature store

---

pyproject.toml

This prevents mypy error when using featurebyte as a dependency.

[chore] Add py.typed marker for type annotations

---

.changelog/DEV-3827.yaml
featurebyte/tile/tile_cache.py
tests/integration/tile/test_tile_cache.py

[DEV-3827] Improve tile cache working table query efficiency in BigQuery

---

pyproject.toml

This reverts commit 47b1d277580e6e203e6314582e113a8e6f087d45.

Revert "[chore] Add py.typed marker for type annotations (#2642)"

---

featurebyte/feast/service/registry.py
featurebyte/migration/service/event_table.py
featurebyte/migration/service/feature.py
featurebyte/migration/service/feature_job_setting_analysis.py
featurebyte/migration/service/feature_list.py
featurebyte/migration/service/mixin.py
featurebyte/migration/service/offline_store_feature_table.py
featurebyte/service/base_document.py
featurebyte/service/base_table_document.py
featurebyte/service/credential.py
featurebyte/service/feature.py
featurebyte/service/feature_list.py
featurebyte/service/feature_materialize_prerequisite.py
featurebyte/service/target_table.py
featurebyte/service/user_defined_function.py
tests/unit/service/test_base_document.py
tests/unit/service/test_relationship.py

[chore] revert service changes to queryfilter

---

featurebyte/schema/worker/task/test.py

Update test task payloads to enable unit testing on new fields 

[chore] Update test task payloads

---

featurebyte/session/databricks_unity.py
tests/integration/tile/test_tile_cache.py

Changes:
1. Update tile cache integration tests to include all source types.
2. Fix listing of tables in `databricks_unity` since schema identifiers are converted to lowercase. This affected listing of entity tracker tables in tile cache. …

[chore] Fix tile cache entity tracker tables listing in databricks_unity 

---

featurebyte/utils/async_helper.py

Handle lost of sempahore lock ownership due to timeout
- set a longer timeout for the lock to enfore semaphore limits
- ignore error due to lock timeout on release …

[chore] Handle lost of sempahore lock ownership

---

featurebyte/service/feature_manager.py
featurebyte/service/tile/tile_task_executor.py
featurebyte/service/tile_manager.py
featurebyte/sql/tile_generate.py
tests/integration/tile/test_generate_tile.py
tests/integration/tile/test_tile_manager.py

Refactor `TileGenerate` to centralize placeholder date replacement. This is mainly to prepare for an upcoming change.

[chore] Refactor TileGenerate to centralize placeholder date replacement

---

.changelog/DEV-3863.yaml
featurebyte/api/batch_feature_table.py
featurebyte/api/batch_request_table.py
featurebyte/api/feature_job_setting_analysis.py
featurebyte/api/historical_feature_table.py
featurebyte/api/materialized_table.py
featurebyte/api/observation_table.py
featurebyte/api/static_source_table.py
tests/unit/api/base_materialize_table_test.py
tests/unit/api/test_feature_job_setting_analysis.py
tests/unit/conftest.py

Add overwrite option to file downloads via SDK

[DEV-3863] Add overwrite option to file downloads via SDK

---

featurebyte/models/system_metrics.py
featurebyte/service/historical_features_and_target.py
featurebyte/service/tile_cache.py
featurebyte/service/tile_manager.py
featurebyte/sql/tile_common.py
featurebyte/sql/tile_generate.py
tests/integration/api/test_event_view_operations.py
tests/unit/conftest.py
tests/unit/routes/test_historical_feature_table.py
tests/unit/service/test_system_metrics.py

This updates historical features metrics to include more detailed tile compute metrics.

[chore] Add more detailed tile compute metrics

---

featurebyte/service/task_manager.py

Revoke child tasks recursively when parent task is revoked

[chore] Fix task revoke not recursive

---

featurebyte/schema/worker/task/target_table.py

Mark `TARGET_TABLE_CREATE` task as cpu task similar to historical features table creation task.

[chore] Mark TARGET_TABLE_CREATE task as cpu task

---

featurebyte/migration/service/deployment.py
featurebyte/migration/service/feature_list.py

This PR bumps migration versions of previous PR (https://github.com/featurebyte/featurebyte/pull/2676) to avoid migration version conflict with `featurebyte-app`. …

[chore] Bump migration version to avoid collision with `featurebyte-app`

---

featurebyte/enum.py

This PR updates existing `DBVarType` enum.

[DEV-3914] Add `FLAT_DICT` to `DBVarType.dictionary_types()`

---

.changelog/DEV-3884.yaml
.changelog/DEV-3913.yaml

Fix change log changed mistakenly

[chore] Fix change log

---

featurebyte/worker/task/catalog_cleanup.py

This PR revises cleanup task to add more logs to the task document.

[chore] Revise catalog cleanup task

---

featurebyte/models/warehouse_table.py
featurebyte/routes/registry.py
featurebyte/service/feature_table_cache.py
featurebyte/service/historical_features.py
featurebyte/service/historical_features_and_target.py
featurebyte/service/tile/tile_task_executor.py
featurebyte/service/tile_cache.py
featurebyte/service/tile_manager.py
featurebyte/service/warehouse_table_service.py
featurebyte/sql/tile_generate.py
tests/integration/api/test_event_view_operations.py
tests/integration/conftest.py
tests/integration/tile/test_generate_tile.py
tests/integration/tile/test_tile_manager.py
tests/unit/service/conftest.py
tests/unit/service/test_historical_features.py
tests/unit/service/test_tile_cache_query_by_observation_table.py
tests/unit/service/test_warehouse_table_service.py
tests/unit/tile/test_unit_snowflake_tile.py
tests/unit/worker/task/test_catalog_cleanup.py

Previously, temporary tile tables were not cleaned up properly when feature computation failed or was cancelled during on-demand tile generation. This PR introduces a `WarehouseTableService` to track created tables in the warehouse and ensure the cleanup of temporary tile tables.
|              `breaking`               |      💥 Breaking Changes …

[DEV-3920] Add WarehouseTableService for temporary tile tables cleanup

---

featurebyte/query_graph/sql/adapter/bigquery.py
featurebyte/query_graph/sql/adapter/snowflake.py
tests/integration/api/test_dict_operations.py

[DEV-3919] Fix materialization of FLAT_DICT type features in BigQuery (main)

---

featurebyte/persistent/base.py
featurebyte/worker/task/catalog_cleanup.py
tests/unit/persistent/test_mongo.py
tests/unit/worker/task/test_catalog_cleanup.py

This PR revises catalog cleanup task so that
* it deletes audit log documents
* it revises cleanup task structure so that it can be extended to handle assets without `catalog_id`
| …

[DEV-3910] Update catalog cleanup to delete audit logs

---

poetry.lock
pyproject.toml

fastapi-users require python-multipart == 0.0.17

[chore] downgrading python-muiltiparttdue to fastapi-users

---

featurebyte/app.py
featurebyte/schema/feature_list.py
featurebyte/schema/worker/task/feature_list_create.py
poetry.lock
pyproject.toml
tests/unit/routes/test_feature_list.py

[chore] bumping starlette

---

featurebyte/api/time_series_table.py
featurebyte/models/periodic_task.py
featurebyte/query_graph/model/feature_job_setting.py
poetry.lock
pyproject.toml
scripts/enforce_import_rules.py
tests/unit/api/test_time_series_table.py
tests/unit/models/test_time_series_table.py
tests/unit/query_graph/model/test_feature_job_setting.py

Update CronFeatureJobSettings to accept cron expression string for parameter `crontab`

[DEV-3918] Support cron expression string for cron-based feature job settings

---

featurebyte/api/time_series_table.py
featurebyte/core/series.py
featurebyte/models/offline_store_ingest_query.py
featurebyte/query_graph/model/feature_job_setting.py
featurebyte/service/feature.py
featurebyte/service/version.py
tests/unit/query_graph/model/test_feature_job_setting.py

This PR introduces `FeatureJobSettingUnion`.

[DEV-3924] Add feature job setting union type

---

featurebyte/api/aggregator/base_aggregator.py
featurebyte/core/accessor/count_dict.py
featurebyte/core/frame.py
featurebyte/query_graph/model/dtype.py
featurebyte/query_graph/node/agg_func.py
featurebyte/query_graph/node/base.py
featurebyte/query_graph/node/binary.py
featurebyte/query_graph/node/count_dict.py
featurebyte/query_graph/node/date.py
featurebyte/query_graph/node/distance.py
featurebyte/query_graph/node/function.py
featurebyte/query_graph/node/generic.py
featurebyte/query_graph/node/input.py
featurebyte/query_graph/node/metadata/operation.py
featurebyte/query_graph/node/mixin.py
featurebyte/query_graph/node/request.py
featurebyte/query_graph/node/schema.py
featurebyte/query_graph/node/string.py
featurebyte/query_graph/node/unary.py
featurebyte/query_graph/node/vector.py
featurebyte/query_graph/sql/adapter/databricks.py
featurebyte/query_graph/sql/tiling.py
tests/unit/models/test_feature.py
tests/unit/query_graph/test_function.py
tests/unit/query_graph/test_metadata_operation.py
tests/unit/query_graph/util.py

This PR update operation structure to include dtype metadata.

[DEV-3925] Update operation structure to include dtype metadata

---

featurebyte/query_graph/model/timestamp_schema.py
featurebyte/query_graph/node/schema.py
featurebyte/query_graph/sql/adapter/bigquery.py
featurebyte/service/base_table_document.py
featurebyte/service/base_table_validation.py
featurebyte/service/scd_table_validation.py
tests/fixtures/query_graph/test_input/scd_varchar_bigquery.sql
tests/fixtures/query_graph/test_input/scd_varchar_tz_column_offset_bigquery.sql
tests/fixtures/query_graph/test_input/scd_varchar_tz_column_timezone_bigquery.sql
tests/fixtures/query_graph/test_input/scd_varchar_utc_bigquery.sql
tests/integration/api/test_scd_view_operations.py
tests/integration/conftest.py
tests/integration/service/test_scd_table_validation.py
tests/unit/api/test_scd_table.py
tests/unit/query_graph/model/test_timestamp_schema.py
tests/unit/service/test_scd_table_validation.py

This PR adds timestamp schema validation logics.

[DEV-3926] Add timestamp schema validation

---

featurebyte/query_graph/model/timestamp_schema.py
featurebyte/query_graph/sql/ast/input.py
featurebyte/service/base_table_validation.py
tests/integration/api/test_scd_view_operations.py
tests/integration/conftest.py

This PR revises time series schema validation logic to check timezone offset metadata.

[DEV-3926] Revise time series schema validation

---

featurebyte/service/base_table_validation.py
tests/integration/api/test_scd_view_operations.py

This PR fixes the broken test due to logical conflict.

[chore] Fix broken test

---

featurebyte/models/time_series_table.py
featurebyte/routes/common/base_table.py
featurebyte/schema/worker/task/table_validation.py
tests/fixtures/request_payloads/time_series_table.json
tests/fixtures/sdk_code/time_series_table.py
tests/unit/api/test_time_series_table.py
tests/unit/conftest.py
tests/unit/models/test_time_series_table.py
tests/unit/routes/test_time_series_table.py

This PR updates semantic tagging rules to include timezone semantic.

[chore] Tag timezone column with timezone semantic

---

featurebyte/models/periodic_task.py
featurebyte/service/task_manager.py
featurebyte/worker/schedulers.py
tests/integration/worker/conftest.py
tests/integration/worker/test_task_manager.py
tests/unit/worker/test_schedulers.py

This PR updates task manager scheduler to support specifying timezone.

[DEV-3937] Update cronjob scheduling to support specifying timezone

---

featurebyte/query_graph/model/window.py
tests/unit/query_graph/model/test_window.py

Add handling for quarter feature window unit that was missing from previous PR.

[DEV-3929] Handle quarter feature window unit

---

featurebyte/enum.py
featurebyte/service/validator/production_ready_validator.py
featurebyte/service/version.py
tests/unit/api/test_feature.py
tests/unit/service/test_version.py

This PR fixes 
* `use_source_setting` parameter logics by handling SCD table & time series table
* aggregation node replacement logic for non-`GroupByNode` …

[chore] Fix feature create new version bug

---

featurebyte/feast/utils/registry_construction.py
featurebyte/models/offline_store_feature_table.py
featurebyte/models/offline_store_ingest_query.py
featurebyte/service/offline_store_feature_table_construction.py
featurebyte/service/offline_store_feature_table_manager.py
tests/unit/api/test_offline_ingest_query_graph.py

This PR updates `OfflineStoreTable` to support `CronFeatureJobSetting`.

[chore] Further update on feature job setting

---

poetry.lock
pyproject.toml

+ python-multipart to allow fastapi-users upgrade
+ jinja

[chore] Bumping vulnerable dependencies

---

featurebyte/api/view.py
featurebyte/common/join_utils.py
featurebyte/models/feature_list.py
featurebyte/models/mixin.py
featurebyte/models/request_input.py
featurebyte/query_graph/model/dtype.py
featurebyte/query_graph/node/generic.py
tests/unit/api/test_time_series_table.py
tests/unit/query_graph/conftest.py
tests/unit/query_graph/test_extract_operation_structure.py

This PR 
* updates view columns subset logic to always include offset column if the timestamp column is selected
* fixes join node operation structure logic to use post joining column name
* updates repo to use cached property …

[chore] Fix timestamp schema containing offset column

---

featurebyte/api/source_table.py
featurebyte/api/time_series_table.py
featurebyte/models/time_series_table.py
featurebyte/query_graph/model/table.py
featurebyte/query_graph/node/input.py
featurebyte/schema/time_series_table.py
tests/fixtures/request_payloads/time_series_table.json
tests/fixtures/sdk_code/time_series_table.py
tests/unit/api/test_time_series_table.py
tests/unit/models/test_time_series_table.py

Reverts featurebyte/featurebyte#2759

Revert "[DEV-3940] Add reference_timezone to time series table"

---

featurebyte/__init__.py
featurebyte/api/event_table.py
featurebyte/api/groupby.py
featurebyte/api/scd_table.py
featurebyte/api/source_table.py
featurebyte/api/time_series_table.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/models/periodic_task.py
featurebyte/query_graph/model/feature_job_setting.py
featurebyte/query_graph/model/time_series_table.py
featurebyte/query_graph/model/timestamp_schema.py
featurebyte/query_graph/model/window.py
tests/unit/common/documentation/test_documentation_layout.py

This PR updates SDK documentation.

[chore] Update SDK documentation

---

featurebyte/core/series.py
featurebyte/query_graph/node/date.py
featurebyte/query_graph/sql/ast/datetime.py
featurebyte/query_graph/sql/ast/generic.py
tests/fixtures/api/test_datetime_operations/timestamp_diff_with_schema.sql
tests/fixtures/request_payloads/time_series_table.json
tests/fixtures/sdk_code/time_series_table.py
tests/unit/api/conftest.py
tests/unit/api/test_time_series_table.py
tests/unit/api/test_time_series_view.py
tests/unit/conftest.py
tests/unit/query_graph/test_sql.py
tests/unit/routes/test_time_series_table.py

This adds handling for timestamp schema information in `DATE_DIFF` node.

[DEV-3950] Handle timestamp schema in date_diff node

---

featurebyte/service/task_manager.py
tests/unit/service/test_task_manager.py

This PR updates task listing interface to consume query filter parameter.

[chore] Add query filter to task listing

---

tests/unit/api/test_datetime_operations.py

Add a missing test file which should have been included in #2763.

[chore] Add missing tests/unit/api/test_datetime_operations.py

---

featurebyte/query_graph/model/timestamp_schema.py
featurebyte/query_graph/node/binary.py
tests/unit/api/test_aggregate_over.py
tests/unit/api/test_time_series_table.py
tests/unit/query_graph/test_extract_operation_structure.py

This PR add `timestamp_dtype` to `TimestampTupleSchema` class.

[chore] Add `dtype` to `TimestampTupleSchema` class

---

featurebyte/query_graph/node/date.py
featurebyte/query_graph/sql/ast/datetime.py
tests/fixtures/query_graph/test_datetime_extract/event_table_no_timezone_offset_bigquery.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_no_timezone_offset_databricks_unity.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_no_timezone_offset_snowflake.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_no_timezone_offset_spark.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_column_bigquery.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_column_databricks_unity.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_column_snowflake.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_column_spark.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_literal_bigquery.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_literal_databricks_unity.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_literal_snowflake.sql
tests/fixtures/query_graph/test_datetime_extract/event_table_timezone_offset_literal_spark.sql
tests/fixtures/query_graph/test_datetime_extract/time_series_table_timezone_offset_literal_bigquery.sql
tests/fixtures/query_graph/test_datetime_extract/time_series_table_timezone_offset_literal_databricks_unity.sql
tests/fixtures/query_graph/test_datetime_extract/time_series_table_timezone_offset_literal_snowflake.sql
tests/fixtures/query_graph/test_datetime_extract/time_series_table_timezone_offset_literal_spark.sql
tests/integration/api/test_time_series_view_operations.py
tests/unit/query_graph/sql/ast/test_datetime_extract.py

This updates sql generation for `DT_EXTRACT` node to handle timestamp schema when present.

[DEV-3943] Handle timestamp schema in DT_EXTRACT node

---

featurebyte/api/feature.py
featurebyte/core/series.py
featurebyte/enum.py
featurebyte/query_graph/model/feature_job_setting.py
featurebyte/query_graph/node/binary.py
tests/unit/api/test_aggregate_over.py
tests/unit/api/test_timestamp_timezone_tuple.py

This PR revises timestamp timezone tuple related datetime operations:
* datetime extract operation
* date difference
* add addition

[DEV-3948] Revise `TIMESTAMP_TZ_TUPLE` related datetime operations

---

featurebyte/api/source_table.py
featurebyte/query_graph/model/table.py
featurebyte/service/time_series_table.py
tests/unit/api/test_time_series_table.py
tests/unit/routes/test_time_series_table.py

This PR updates time series validation logics
* to check whether the time interval is a single unit
* to check whether cron feature job setting's reference timezone is valid …

[chore] Revise time series table validation logic

---

featurebyte/core/accessor/datetime.py
featurebyte/query_graph/node/date.py
featurebyte/query_graph/sql/ast/datetime.py
featurebyte/query_graph/sql/timestamp_helper.py
tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_bigquery.sql
tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_databricks_unity.sql
tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_snowflake.sql
tests/fixtures/query_graph/test_datetime_extract/timestamp_tuple_schema_spark.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_bigquery.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_databricks_unity.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_snowflake.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_offset_spark.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_bigquery.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_databricks_unity.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_snowflake.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/local/varchar_tz_column_timezone_spark.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_bigquery.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_databricks_unity.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_snowflake.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_offset_spark.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_bigquery.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_databricks_unity.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_snowflake.sql
tests/fixtures/query_graph/test_timestamp_handler/convert_timestamp_timezone_tuple/utc/varchar_tz_column_timezone_spark.sql
tests/integration/api/test_time_series_view_operations.py
tests/unit/api/test_timestamp_timezone_tuple.py
tests/unit/query_graph/sql/ast/test_datetime_extract.py
tests/unit/query_graph/sql/test_timestamp_handler.py

This updates the `DT_EXTRACT` node to handle timestamp tuple schema to support date parts extraction on complex timestamp types.

[DEV-3952] Update DT_EXTRACT node to handle timestamp tuple schema

---

featurebyte/service/version.py
tests/unit/api/test_time_series_table.py

This PR revises create new version service to support time series feature.

[DEV-3958] Enable create new version for time series feature

---

featurebyte/schema/worker/task/batch_feature_table.py
featurebyte/schema/worker/task/batch_request_table.py
featurebyte/schema/worker/task/feature_list_batch_feature_create.py
featurebyte/schema/worker/task/observation_table.py

Make some tasks revoccable and rerunnable

[chore] Make some tasks revoccable and rerunnable

---

featurebyte/service/task_manager.py
tests/unit/service/test_task_manager.py

Fix task manager not specifying queue during task submission

[chore] Fix task manager not specifying queue during task submission

---

featurebyte/middleware.py

[chore] Add exception to API log

---

featurebyte/worker/task/catalog_cleanup.py
tests/unit/api/test_offline_ingest_query_graph.py

This PR revises catalog cleanup task to skip cleaning warehouse data if the catalog does not have default feature store IDs.

[chore] Revise cleanup task

---

poetry.lock
pyproject.toml

```
Name                       Version ID                  Fix Versions
-------------------------- ------- ------------------- ------------
snowflake-connector-python 3.12.4  GHSA-2vpq-fh52-j3wv 3.13.1
snowflake-connector-python 3.12.4  GHSA-m4f6-vcj4-w5mx 3.13.1
snowflake-connector-python 3.12.4  GHSA-r2x6-cjg7-8r43 3.13.1
```
| …

[chore] bump snowflake

---

featurebyte/exception.py
featurebyte/models/periodic_task.py
featurebyte/service/cron_helper.py
featurebyte/service/feature_materialize_sync.py
featurebyte/service/task_manager.py
tests/unit/service/test_cron_helper.py
tests/unit/service/test_task_manager.py

This PR aims to fix cron feature job setting scheduled job bug.

[DEV-3962] Fix cron feature job setting scheduled job bug

---

featurebyte/routes/credential/api.py
featurebyte/routes/credential/controller.py
tests/unit/api/test_credential.py
tests/unit/routes/base.py
tests/unit/routes/test_credential.py

This PR revises credential deletion logic to block deletion of the last credential of feature store per user.

[chore] Revise credential deletion logic

---

.changelog/DEV-3974.yaml
featurebyte/__init__.py
featurebyte/api/target.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/enum.py
featurebyte/models/target.py
featurebyte/routes/target/api.py
featurebyte/routes/target/controller.py
featurebyte/schema/target.py
tests/integration/session/test_databricks_unity.py
tests/unit/api/test_target.py
tests/unit/routes/test_target.py

This PR introduces a target_type attribute to the target object, allowing explicit specification and updates of target prediction types. …

[DEV-3974] Introduce `target_type` to target object

---

featurebyte/query_graph/node/input.py
featurebyte/worker/task/catalog_cleanup.py
tests/unit/query_graph/test_node.py

This PR revises catalog cleanup task so that it won't fail when the deserialization fails.

[chore] Minor revision on catalog cleanup task

---

featurebyte/api/catalog.py
featurebyte/config.py
tests/unit/api/test_catalog.py

Fix activate catalog fails when the existing active catalog no longer exists.
This can happen when:
- the catalog is deleted by another client
- switching connection profile …

[chore] Fix activate catalog

---

featurebyte/api/aggregator/forward_aggregator.py
featurebyte/api/aggregator/forward_asat_aggregator.py
featurebyte/api/groupby.py
featurebyte/api/target.py
featurebyte/api/target_namespace.py
featurebyte/api/view.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/common/validator.py
featurebyte/enum.py
featurebyte/models/target.py
featurebyte/models/target_namespace.py
featurebyte/routes/target/api.py
featurebyte/routes/target/controller.py
featurebyte/routes/target_namespace/api.py
featurebyte/routes/target_namespace/controller.py
featurebyte/schema/target.py
featurebyte/schema/target_namespace.py
featurebyte/service/target.py
tests/fixtures/request_payloads/target.json
tests/fixtures/request_payloads/target_namespace.json
tests/unit/api/test_target.py
tests/unit/api/test_target_namespace.py
tests/unit/routes/test_target.py
tests/unit/routes/test_target_namespace.py
tests/unit/test_generate_payload_fixtures.py

This PR aims to move the target type from `TargetModel` to `TargetNamespaceModel`.

[DEV-3974] Move `target_type` from `TargetModel` to `TargetNamespaceModel`

---

.github/workflows/expire-tags.yaml
.github/workflows/publish-dev.yaml
.github/workflows/test-notebooks.yaml
.github/workflows/test.yaml

[chore] publishing of stable branch tags (#2822)

---

featurebyte/enum.py

This PR updates target type to avoid repetitive classification types codes in featurebyte-app.

[chore] Update target type

---

featurebyte/exception.py
featurebyte/models/batch_feature_table.py
featurebyte/routes/batch_feature_table/api.py
featurebyte/routes/batch_feature_table/controller.py
featurebyte/schema/batch_feature_table.py
featurebyte/schema/worker/task/batch_feature_table.py
featurebyte/service/batch_feature_table.py
featurebyte/worker/task/batch_feature_table.py
tests/unit/routes/test_batch_feature_table.py

Add route to recreate existing batch feature table to get latest features 

[DEV-3970] Add route to recreate existing batch feature table

---

featurebyte/exception.py
featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py
tests/fixtures/preview_service/expected_describe_dynamic_batching_queries.sql
tests/integration/api/test_view_describe.py
tests/unit/conftest.py
tests/unit/query_graph/interpreter/test_preview.py
tests/unit/service/test_preview.py

This implements dynamic batching for stats computation in PreviewService by reducing the batch size.

[DEV-3988] Implement dynamic batching for stats computation

---

featurebyte/service/task_manager.py

Add exception handling when creating task document for pending task record in mongo db

[chore] Fix task submission record duplicate 

---

featurebyte/exception.py
featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py
tests/fixtures/preview_service/expected_describe_dynamic_batching_queries.sql
tests/integration/api/test_view_describe.py
tests/unit/conftest.py
tests/unit/query_graph/interpreter/test_preview.py
tests/unit/service/test_preview.py

[DEV-3988] Implement dynamic batching for stats computation (cherry-pick)

---

featurebyte/models/task.py
featurebyte/persistent/base.py
featurebyte/persistent/mongo.py
featurebyte/schema/task.py
featurebyte/service/task_manager.py
tests/unit/service/test_task_manager.py

Cherry-pick these fixes
https://github.com/featurebyte/featurebyte/pull/2831
https://github.com/featurebyte/featurebyte/pull/2834

[chore] Cherry pick task submission fixes

---

.changelog/DEV-3991.yaml
featurebyte/session/base.py
featurebyte/session/base_spark.py
featurebyte/session/bigquery.py
featurebyte/session/databricks_unity.py
featurebyte/session/snowflake.py
featurebyte/session/sqlite.py
tests/unit/api/test_feature_store.py
tests/unit/session/test_base.py
tests/unit/session/test_bigquery_session.py
tests/unit/session/test_databricks_session.py
tests/unit/session/test_snowflake_session.py

Cherry-pick from https://github.com/featurebyte/featurebyte/pull/2838

[chore] Sort database object listings in lexical order (cherry-pick)

---

featurebyte/query_graph/node/generic.py
tests/integration/api/test_change_view_operations.py

[DEV-3990] Fix ChangeView with timestamp schema error when joined with SCDView (cherry-pick)

---

featurebyte/service/task_manager.py

Cherry-pick from:
https://github.com/featurebyte/featurebyte/pull/2840

[chore] Track parent task id in task document during submission (#2840)

---

.changelog/DEV-3993.yaml
featurebyte/api/scd_table.py
featurebyte/api/scd_view.py
featurebyte/query_graph/sql/aggregator/base_lookup.py
featurebyte/query_graph/sql/ast/join.py
featurebyte/query_graph/sql/scd_helper.py
tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table.sql
tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table_missing_column.sql
tests/fixtures/feature_materialize/materialize_features_queries_internal_relationships.sql
tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
tests/fixtures/offline_store_feature_table/cust_id_to_gender_universe.sql
tests/integration/api/test_scd_view_operations.py
tests/integration/conftest.py
tests/integration/session/test_databricks_unity.py
tests/unit/api/test_scd_view.py

[DEV-3993] Fix scd_helper to account for end timestamp column when available

---

featurebyte/query_graph/sql/scd_helper.py
tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table.sql
tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table_missing_column.sql
tests/fixtures/feature_materialize/materialize_features_queries_internal_relationships.sql
tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
tests/fixtures/offline_store_feature_table/cust_id_to_gender_universe.sql
tests/integration/api/test_scd_view_operations.py

[DEV-3993] Add SCD end timestamp handling only when the column is available (cherry-pick)

---

.changelog/DEV-4000-1.yaml
.changelog/DEV-4000.yaml
poetry.lock
pyproject.toml

+ dependencies Bump cryptography package >44.0.1
+ python Deprecating python version 3.9
cryptography package only supports 3.10 and above …

[DEV-4000] bumping snowflake-connector-python to fix cryptography vuln

---

.changelog/DEV-4001.yaml
featurebyte/api/groupby.py
featurebyte/enum.py
featurebyte/query_graph/model/column_info.py
featurebyte/query_graph/node/generic.py
featurebyte/typing.py
scripts/test-docs-setup.py
tests/fixtures/request_payloads/target.json
tests/fixtures/sdk_code/add_timestamp_schema.py
tests/fixtures/sdk_code/forward_aggregate_asat_target_code_generation.py
tests/fixtures/sdk_code/forward_aggregate_target_code_generation.py
tests/integration/api/test_event_view_operations.py
tests/integration/api/test_feature_correctness.py
tests/integration/api/test_forward_aggregate_asat.py
tests/integration/api/test_target_correctness.py
tests/unit/api/aggregator/test_forward_aggregator.py
tests/unit/api/test_aggregate_asat_common.py
tests/unit/api/test_databricks.py
tests/unit/api/test_event_table.py
tests/unit/api/test_forward_aggregate_asat.py
tests/unit/api/test_sdk_code.py
tests/unit/api/test_target.py
tests/unit/conftest.py
tests/unit/routes/test_target.py
tests/unit/service/test_feature_table_cache.py
tests/unit/service/test_info.py

This PR update `forward_aggregate` & `forward_aggregate_asat` method.

[DEV-4001] Make `fill_value` mandatory for `forward_aggregate` & `forward_aggregate_asat`

---

.changelog/DEV-4001.yaml
featurebyte/api/groupby.py
featurebyte/api/view.py
featurebyte/enum.py
featurebyte/exception.py
featurebyte/query_graph/node/generic.py
tests/fixtures/sdk_code/lookup_target_code_generation.py
tests/fixtures/sdk_code/target_scd_lookup.py
tests/integration/api/test_lookup_target_operations.py
tests/integration/session/test_databricks_unity.py
tests/unit/api/aggregator/test_forward_aggregator.py
tests/unit/api/test_databricks.py
tests/unit/api/test_dimension_view.py
tests/unit/api/test_sdk_code.py
tests/unit/api/test_target.py
tests/unit/models/test_target.py
tests/unit/query_graph/test_sdk_code_generation.py

This PR introduces `fill_value` to `as_target` & `as_feature` methods.

[DEV-4001] Introduce `fill_value` to `as_target` and `as_feature` methods

---

featurebyte/typing.py

Documentation changes detected:
```
-<li><strong>fill_value: <em>Union[bool, int, float, str, NoneType, Unset]</em></strong><br>   <strong>default</strong>: <em><featurebyte.typing.Unset object at 0x7fb0a4d20970></em>
+<li><strong>fill_value: <em>Union[bool, int, float, str, NoneType, Unset]</em></strong><br>   <strong>default</strong>: <em><featurebyte.typing.Unset object at 0x7ff3856ee860></em>
```
After:
```
-<div class="autodoc-param-group-multi"><em class="autodoc-param">fill_value</em><span class="autodoc-punctuation">: </span><em class="autodoc-type">Union[bool, int, float, str, NoneType, Unset]</em><span class="autodoc-punctuation">=</span><em class="autodoc-default"><featurebyte.typing.Unset object at 0x7fcb6cb68610></em></div>
+<div class="autodoc-param-group-multi"><em …
```

[chore] Fix documentation changes due to UNSET

---

featurebyte/query_graph/sql/adapter/__init__.py
featurebyte/query_graph/sql/adapter/base.py
featurebyte/query_graph/sql/adapter/databricks_unity.py
featurebyte/query_graph/sql/groupby_helper.py
featurebyte/query_graph/sql/tiling.py
tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_avg.sql
tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_max.sql
tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_simple_average.sql
tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_sum.sql
tests/integration/api/test_vector_aggregation_operations.py
tests/unit/query_graph/sql/adapter/test_databricks_unity.py

This adds support for vector aggregation function in `databricks_unity` implemented using built-in sql functions.

[DEV-4008] Implement vector aggregation functions in databricks_unity

---

featurebyte/session/bigquery.py
featurebyte/session/databricks_unity.py
featurebyte/sql/bigquery/F_VECTOR_COSINE_SIMILARITY.sql
featurebyte/sql/databricks_unity/F_VECTOR_COSINE_SIMILARITY.sql
tests/integration/api/test_vector_aggregation_operations.py
tests/integration/udf/conftest.py
tests/integration/udf/test_vector_aggregate.py
tests/integration/udf/test_vector_cosine_similarity.py
tests/unit/session/test_bigquery_session.py

This adds implementations for `F_VECTOR_COSINE_SIMILARITY` UDF for DataBricks and BigQuery.

[DEV-4009] Implement vector cosine similarity UDF for DataBricks and BigQuery 

---

featurebyte/session/bigquery.py
tests/integration/api/test_vector_aggregation_operations.py

Enable bigquery source type in `tests/integration/api/test_vector_aggregation_operations.py` for more coverage.

[DEV-4013] Enable bigquery source type in test_vector_aggregation_operations.py

---

featurebyte/query_graph/sql/adapter/__init__.py
featurebyte/query_graph/sql/adapter/base.py
featurebyte/query_graph/sql/adapter/databricks_unity.py
featurebyte/query_graph/sql/groupby_helper.py
featurebyte/query_graph/sql/tiling.py
featurebyte/session/bigquery.py
featurebyte/session/databricks_unity.py
featurebyte/sql/bigquery/F_VECTOR_COSINE_SIMILARITY.sql
featurebyte/sql/databricks_unity/F_VECTOR_COSINE_SIMILARITY.sql
tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_avg.sql
tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_max.sql
tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_simple_average.sql
tests/fixtures/adapter/databricks_unity/expected_vector_aggregate_sum.sql
tests/integration/api/test_vector_aggregation_operations.py
tests/integration/session/test_databricks_unity.py
tests/integration/udf/conftest.py
tests/integration/udf/test_vector_aggregate.py
tests/integration/udf/test_vector_cosine_similarity.py
tests/unit/query_graph/sql/adapter/test_databricks_unity.py
tests/unit/session/test_bigquery_session.py

Cherry pick fixes for DataBricks vector aggregation to `stable/v1` (see commits).

[DEV-4008] Cherry pick fixes for DataBricks vector aggregation

---

.changelog/DEV-4017.yaml
featurebyte/common/validator.py
featurebyte/service/base_feature_service.py
tests/unit/service/test_version.py

This PR fixes feature version number generation bug when a previous version is deleted in the same day.

[DEV-4017] Fix feature version code generation bug

---

featurebyte/migration/service/feature_list.py
featurebyte/models/feature_list.py
featurebyte/routes/registry.py
featurebyte/service/feature_list.py
featurebyte/service/version.py
tests/fixtures/migration/feature_namespace
tests/unit/api/test_feature_list.py
tests/unit/models/test_feature_list.py

This PR updates feature list model to track `feature_type` of individual features in the feature list.

[DEV-4016] Add `features_metadata` to feature list model to track `feature_type`

---

featurebyte/core/timedelta.py
featurebyte/routes/common/base_table.py
featurebyte/service/base_table_validation.py
tests/integration/api/test_item_view_operations.py
tests/unit/service/test_base_table_validation.py

This PR revises critical data info update flow to trigger table validation task.

[DEV-4023] Validate table after critical data info update

---

.changelog/DEV-4033.yaml
featurebyte/feast/infra/offline_stores/databricks.py
featurebyte/query_graph/node/schema.py
featurebyte/service/feature_manager.py
featurebyte/session/databricks_unity.py
tests/integration/conftest.py

Remove group_name as field for setting up DataBricks Unity feature store

[DEV-4033] Remove group_name from DataBricks Unity feature store

---

.changelog/DEV-4033.yaml
featurebyte/feast/infra/offline_stores/databricks.py
featurebyte/query_graph/node/schema.py
featurebyte/service/feature_manager.py
featurebyte/session/databricks_unity.py
featurebyte/session/snowflake.py
tests/integration/conftest.py
tests/integration/session/test_base.py

Cherry-pick fixes:
https://github.com/featurebyte/featurebyte/pull/2905
https://github.com/featurebyte/featurebyte/pull/2896

[DEV-4033] Cherry-pick fixes

---

.changelog/DEV-4034.yaml
featurebyte/__init__.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/common/documentation/gen_ref_pages_docs_builder.py
featurebyte/core/datetime.py
featurebyte/query_graph/enum.py
featurebyte/query_graph/node/date.py
featurebyte/query_graph/node/metadata/sdk_code.py
featurebyte/query_graph/sql/ast/datetime.py
tests/fixtures/api/test_datetime_operations/to_timestamp_from_epoch.sql
tests/integration/api/test_datetime.py
tests/unit/api/test_datetime_operations.py

This implements a built-in SDK function `to_timestamp_from_epoch` to convert epoch seconds to timestamps.

[DEV-4034] Add to_timestamp_from_epoch function to convert epoch time to timestamp

---

featurebyte/service/preview.py
tests/unit/service/test_preview.py

This PR fixes the issue where sample data could change the underlying graph.

[chore] Fix sample updates underlying graph

---

.changelog/DEV-4034.yaml
featurebyte/__init__.py
featurebyte/common/documentation/documentation_layout.py
featurebyte/common/documentation/gen_ref_pages_docs_builder.py
featurebyte/core/datetime.py
featurebyte/query_graph/enum.py
featurebyte/query_graph/node/date.py
featurebyte/query_graph/node/metadata/sdk_code.py
featurebyte/query_graph/sql/ast/datetime.py
tests/fixtures/api/test_datetime_operations/to_timestamp_from_epoch.sql
tests/integration/api/test_datetime.py
tests/unit/api/test_datetime_operations.py

[DEV-4034] Add to_timestamp_from_epoch function to convert epoch time to timestamp (cherry-pick)

---

tests/integration/api/test_datetime.py
tests/util/deployment.py

This adds a test helper to test deployment in integration tests which requires quite a few patches to be done correctly.

[chore] Add helper to test deployment in integration tests

---

featurebyte/query_graph/node/input.py
featurebyte/query_graph/sql/ast/input.py
featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py
featurebyte/session/base.py
tests/fixtures/query_graph/expected_filtered_table_primary_table_sampled_data.sql
tests/fixtures/query_graph/expected_item_table_join_event_table_primary_table_sampled_data.sql
tests/fixtures/query_graph/expected_primary_table_sampled_data.sql
tests/unit/query_graph/interpreter/test_preview.py
tests/unit/service/test_preview.py
tests/unit/session/test_base.py

This PR cherry-picks
* https://github.com/featurebyte/featurebyte/pull/2901
* https://github.com/featurebyte/featurebyte/pull/2909

[chore] Revise table sampling logic to cache sampled primary table (cherry-pick)

---

.changelog/DEV-4037.yaml
featurebyte/api/relationship.py
featurebyte/models/relationship.py
featurebyte/routes/relationship_info/api.py
featurebyte/routes/relationship_info/controller.py
featurebyte/schema/relationship_info.py
featurebyte/service/relationship_info.py
featurebyte/service/table_columns_info.py
tests/unit/api/test_relationship.py

This adds support for one-to-one relationship type between entities. The type of a relationship can be manually updated to this new type in the SDK using `update_relationship_type`.
| …

[DEV-4037] Support one-to-one relationship type between entities

---

.changelog/DEV-4042.yaml
featurebyte/common/utils.py
tests/unit/common/test_utils.py

Handle invalid json in `dataframe_from_arrow_table` helper function to make it more robust

[DEV-4042] Handle invalid json in dataframe_from_arrow_table helper function

---

.changelog/DEV-4042.yaml
featurebyte/common/utils.py
featurebyte/core/accessor/datetime.py
featurebyte/session/base_spark.py
featurebyte/session/databricks.py
featurebyte/session/spark.py
tests/integration/session/test_databricks_unity.py
tests/unit/common/test_utils.py

[chore] Cherry-pick pyarrow table handling fixes

---

featurebyte/service/feature_table_cache.py

This updates the locking mechanism in `FeatureTableCacheService` to cover a wider region to ensure serial updates. This prevents a potential columns limit exceeded error when concurrent requests attempt to update the cache for the same observation table at the same time.
| …

[DEV-4045] Fix potential columns limit exceeded error when updating feature table cache

---

featurebyte/service/cron_helper.py
featurebyte/service/feature_table_cache.py

[DEV-4045] Fix potential columns limit exceeded error when updating feature table cache (cherry-pick)

---

.github/workflows/publish-dev.yaml

Reduce time required for gcp to respond to the version present

[chore] reduce dev version lookup time

---

featurebyte/schema/feature_store.py
tests/unit/schema/test_feature_store.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2942

[chore] Revise `FeatureStorePreview` schema (cherry-pick)

---

featurebyte/schema/feature_store.py
tests/unit/schema/test_feature_store.py

This PR revises `FeatureStorePreview` schema to prune & create a copy of the input graph.

[chore] Revise `FeatureStorePreview` schema

---

featurebyte/schema/feature_store.py
tests/unit/schema/test_feature_store.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2942

[chore] Revise `FeatureStorePreview` schema (cherry-pick) (#2943)

---

featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py

Remove oversampling logic to improve sampling runtime.

[chore] Remove oversampling logic for join & filter

---

featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2945

[chore] Remove oversampling logic for join & filter (cherry-pick)

---

featurebyte/service/preview.py
tests/unit/service/test_preview.py

This PR fixes row count used for sample & describe operations.

[chore] Fix row count for sample & describe operation

---

featurebyte/service/preview.py
tests/unit/service/test_preview.py

Cherry-pick: https://github.com/featurebyte/featurebyte/pull/2947

[chore] Fix row count for sample & describe operation (cherry-pick)

---

featurebyte/models/periodic_task.py
featurebyte/query_graph/sql/cron.py
tests/unit/query_graph/conftest.py
tests/unit/query_graph/model/test_feature_job_setting.py
tests/unit/query_graph/sql/test_cron.py

[chore] Fix Crontab comparison to avoid duplicate table name (cherry-pick)

---

featurebyte/models/entity_universe.py
featurebyte/query_graph/sql/aggregator/non_tile_window.py
tests/integration/api/test_event_view_operations.py

This updates non-tile-based count distinct aggregation to apply timestamp schema to the event timestamp column when applicable. 

[DEV-4050] Apply timestamp schema in non-tile-based count distinct aggregation

---

featurebyte/models/entity_universe.py
featurebyte/query_graph/sql/aggregator/non_tile_window.py
tests/integration/api/test_event_view_operations.py

[DEV-4050] Apply timestamp schema in non-tile-based count distinct aggregation (cherry-pick)

---

featurebyte/query_graph/sql/tiling.py
featurebyte/service/feature_table_cache.py
tests/unit/query_graph/test_tiling.py

Cherry-pick:
https://github.com/featurebyte/featurebyte/pull/2954
https://github.com/featurebyte/featurebyte/pull/2953

[chore] Cherry-pick fixes

---

featurebyte/models/tile.py
featurebyte/query_graph/sql/batch_helper.py
featurebyte/query_graph/sql/online_serving.py
featurebyte/service/feature_table_cache.py
featurebyte/service/historical_features.py
featurebyte/service/historical_features_and_target.py
featurebyte/service/target_helper/compute_target.py
featurebyte/service/tile_cache.py
featurebyte/service/tile_manager.py
featurebyte/session/session_helper.py
featurebyte/sql/tile_generate.py
tests/fixtures/get_historical_features/feature_compute_error.sql
tests/fixtures/get_historical_features/tile_compute_error.sql
tests/integration/service/test_feature_table_cache.py
tests/unit/service/test_historical_features.py

[DEV-4048] Add raise_on_error option when computing historical features (cherry-pick)

---

poetry.lock
pyproject.toml

Bump databricks sql connector to latest version that includes recent bug fixes

[chore] Bump databricks sql connector to latest version

---

featurebyte/enum.py
featurebyte/service/feature_type.py
tests/unit/api/test_feature.py
tests/unit/service/test_feature_type.py

This PR revises feature type methods & relax float feature constraint so that user can make it categorical if desired.

[chore] Revise feature type methods & relax float feature constraint

---

featurebyte/query_graph/sql/common.py
tests/unit/routes/test_observation_table.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2967

[chore] Fix SQL bugs when creating table for missing value (#2967)

---

featurebyte/service/historical_features_and_target.py
featurebyte/session/base.py
featurebyte/session/session_helper.py
tests/unit/conftest.py
tests/unit/service/test_feature_materialize.py
tests/unit/service/test_historical_features.py
tests/unit/service/test_online_serving.py
tests/unit/session/test_session_helper.py

This PR revises `drop_tables` method so that it won't submit multiple tasks concurrently.

[chore] Revise `drop_tables` method to exec query one by one

---

featurebyte/models/column_statistics.py
featurebyte/query_graph/sql/feature_compute.py
featurebyte/query_graph/sql/feature_historical.py
featurebyte/query_graph/sql/feature_preview.py
featurebyte/query_graph/sql/specifications/base_aggregate_asat.py
featurebyte/query_graph/sql/specifications/lookup.py
featurebyte/query_graph/sql/specifications/lookup_target.py
featurebyte/query_graph/sql/specifications/non_tile_window_aggregate.py
featurebyte/query_graph/sql/specifications/time_series_window_aggregate.py
featurebyte/query_graph/sql/specs.py
featurebyte/routes/registry.py
featurebyte/service/base_table_validation.py
featurebyte/service/column_statistics.py
featurebyte/service/feature_preview.py
featurebyte/service/feature_table_cache.py
featurebyte/service/historical_features.py
featurebyte/service/historical_features_and_target.py
featurebyte/service/time_series_table_validation.py
tests/fixtures/time_series_table_validation_service/validate_and_update.sql
tests/unit/query_graph/conftest.py
tests/unit/query_graph/test_feature_preview.py
tests/unit/query_graph/test_time_series_window_aggregator.py
tests/unit/service/conftest.py
tests/unit/service/test_base_table_validation.py
tests/unit/service/test_column_statistics.py
tests/unit/service/test_historical_features.py
tests/unit/service/test_time_series_table_validation.py
tests/unit/worker/task/test_catalog_cleanup.py

This updates time series features computation to determine the appropriate join methods using column statistics. This is to handle time series tables with irregular timestamps.
Changes:
* Update table validation task to compute statistics for columns of interest (currently distinct count for the reference datetime column in time series tables)
* Use column statistics information when generating sql query for time series aggregation
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & …

[DEV-4056] Determine appropriate join methods using column statistics in time series

---

tests/unit/service/conftest.py
tests/unit/service/test_base_table_validation.py

[chore] Fix docstring and remove unused fixture

---

featurebyte/models/deployed_tile_table.py
featurebyte/routes/registry.py
featurebyte/service/deploy.py
featurebyte/service/deployed_tile_table.py
featurebyte/service/deployed_tile_table_manager.py
featurebyte/service/feature.py
tests/fixtures/deployed_tile_table/expected_tile_sql_1.sql
tests/fixtures/deployed_tile_table/expected_tile_sql_2.sql
tests/unit/conftest.py
tests/unit/service/test_deployed_tile_table.py
tests/unit/service/test_deployed_tile_table_manager.py
tests/unit/worker/task/test_catalog_cleanup.py

This adds a model `DeployedTileTable` and related services. It will be used to track grouped tile queries in deployed features and eventually replace the existing `TileModel`. …

[DEV-4060] Add DeployedTileTable model and services

---

featurebyte/query_graph/node/nested.py
featurebyte/query_graph/node/request.py
tests/fixtures/on_demand_function/req_col_ttl_and_non_ttl.sql
tests/fixtures/on_demand_function/ttl_and_non_ttl.sql
tests/fixtures/sdk_code/feature_with_request_column.py
tests/unit/api/test_null_filling_value.py
tests/unit/api/test_offline_ingest_query_graph.py
tests/unit/api/test_request_column.py
tests/unit/feast/utils/test_registry_construction.py
tests/unit/query_graph/test_nested_node.py
tests/unit/query_graph/test_request_column_node.py

This PR aims to fix old client backward compatibility.

[chore] Handle client backward compatibility

---

featurebyte/session/base.py
featurebyte/session/bigquery.py
featurebyte/session/databricks.py
featurebyte/session/snowflake.py
featurebyte/session/spark.py
featurebyte/session/sqlite.py
tests/integration/session/test_base.py
tests/unit/api/test_event_table.py
tests/unit/api/test_time_series_table.py
tests/unit/conftest.py
tests/unit/session/test_manager.py

Add execute query function that returns query id for tracking

[chore] Add execute query function that returns query id

---

featurebyte/service/feature_store_warehouse.py
featurebyte/service/managed_view.py
tests/unit/routes/test_managed_view.py
tests/unit/service/test_feature_store_warehouse.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/3002

[chore] Fix table listing filtering for featurebyte schemas (#3002)

---

featurebyte/query_graph/sql/batch_helper.py

This PR makes `NUM_FEATURES_PER_QUERY` configurable via environment variables to facilitate tuning and testing.

chore: Make NUM_FEATURES_PER_QUERY configurable via env var

---

.github/workflows/test.yaml
featurebyte/models/system_metrics.py
featurebyte/query_graph/sql/online_serving.py
featurebyte/routes/system_metrics/api.py
featurebyte/service/feature_materialize.py
featurebyte/service/feature_table_cache.py
featurebyte/service/historical_features.py
featurebyte/service/historical_features_and_target.py
featurebyte/service/online_serving.py
featurebyte/service/target_helper/compute_target.py
featurebyte/service/tile/tile_task_executor.py
featurebyte/service/tile_manager.py
featurebyte/service/warehouse_table_service.py
featurebyte/session/base.py
featurebyte/session/session_helper.py
featurebyte/sql/tile_generate.py
tests/integration/api/test_historical_features.py
tests/integration/tile/test_generate_tile.py
tests/unit/service/conftest.py
tests/unit/service/test_feature_materialize.py
tests/unit/service/test_feature_table_cache.py
tests/unit/service/test_historical_features.py
tests/unit/service/test_online_serving.py
tests/unit/session/test_session_helper.py

This adds `SqlQueryMetrics` to log slow sql queries during tiles and features computation.

[chore] Add SqlQueryMetrics for logging slow queries

---

featurebyte/query_graph/sql/entity_filter.py
tests/fixtures/expected_tile_sql_on_demand_event_timestamp_schema.sql
tests/unit/conftest.py
tests/unit/query_graph/sql/test_tile.py

[DEV-4083] perf: Skip timestamp filtering in entity table when conversion is required (cherry pick)

---

.changelog/DEV-4058.yaml
featurebyte/query_graph/sql/adapter/base.py
tests/fixtures/aggregator/expected_forward_aggregator.sql
tests/fixtures/aggregator/expected_forward_aggregator_offset.sql
tests/fixtures/expected_preview_sql_category.sql
tests/fixtures/expected_preview_sql_category_multiple.sql
tests/unit/query_graph/sql/fixtures/snowflake_double_vector_agg_only.py
tests/unit/query_graph/sql/fixtures/snowflake_vector_agg_with_normal_agg.py
tests/unit/query_graph/sql/test_groupby_helper.py
tests/unit/query_graph/test_asat_aggregator.py
tests/unit/query_graph/test_item_aggregator.py
tests/unit/query_graph/test_item_groupby.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/2977

[DEV-4058] Reduce cap on maximum categories during aggregation to 500

---

featurebyte/schema/context.py
featurebyte/schema/observation_table.py
tests/unit/routes/test_observation_table.py

Cherry-pick https://github.com/featurebyte/featurebyte/pull/3015

[chore][cherry-pick] Fix observation payload issue (primary entity not sorted)

---

.changelog/DEV-4087.yaml
featurebyte/api/deployment.py
featurebyte/common/utils.py
featurebyte/enum.py
featurebyte/exception.py
featurebyte/models/request_input.py
featurebyte/query_graph/node/schema.py
featurebyte/query_graph/sql/adapter/bigquery.py
featurebyte/query_graph/sql/adapter/databricks.py
featurebyte/query_graph/sql/adapter/snowflake.py
featurebyte/routes/batch_feature_table/api.py
featurebyte/routes/batch_feature_table/controller.py
featurebyte/schema/batch_feature_table.py
featurebyte/schema/worker/task/batch_feature_table.py
featurebyte/service/batch_feature_table.py
featurebyte/service/feature_store_warehouse.py
featurebyte/session/base_spark.py
featurebyte/session/bigquery.py
featurebyte/session/snowflake.py
featurebyte/worker/task/batch_feature_table.py
tests/integration/api/test_datetime.py
tests/integration/query_graph/test_online_serving.py
tests/integration/session/test_base.py
tests/unit/common/test_utils.py
tests/unit/conftest.py
tests/unit/query_graph/sql/adapter/test_bigquery.py
tests/unit/query_graph/sql/adapter/test_databricks_unity.py
tests/unit/query_graph/sql/adapter/test_snowflake.py
tests/unit/query_graph/sql/adapter/test_spark.py
tests/unit/routes/test_batch_feature_table.py

Add REST API  and SDK functionality to compute batch features and append to an unmanaged feature table.
Customizable parameters:
- output table location
- snapshot date column name
- snapshot date value
This PR does not include adding POIINT_IN_TIME to the batch features output …

[DEV-4087] Support computing batch features that is appended to unmanaged feature tables

---

poetry.lock
pyproject.toml

[FIX] adding missing aiofiles dependency

---

featurebyte/feast/enum.py

This PR updates `to_feast_primitive_type` to cover all supported `DBVarType`.

[chore] Update `to_feast_primitive_type`

---

featurebyte/query_graph/model/dtype.py
featurebyte/query_graph/sql/interpreter/preview.py
tests/integration/api/test_view_describe.py
tests/integration/api/test_view_sample.py
tests/unit/query_graph/interpreter/conftest.py
tests/unit/query_graph/interpreter/test_interpreter.py

This updates `PreviewService` to handle timestamp schema associated with the timestamp column when sampling with range.

[DEV-4101] Handle timestamp schema in PreviewService when sampling with range

---

featurebyte/api/deployment.py
featurebyte/common/validator.py
featurebyte/routes/batch_feature_table/api.py
featurebyte/routes/batch_feature_table/controller.py
featurebyte/routes/registry.py
featurebyte/schema/batch_feature_table.py
featurebyte/service/batch_external_feature_table.py
featurebyte/service/batch_feature_table.py
featurebyte/service/entity_validation.py
featurebyte/service/feature_store_warehouse.py
featurebyte/session/databricks.py
featurebyte/worker/task/batch_feature_table.py
tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_existing_databricks_table_queries.sql
tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_existing_table_queries.sql
tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_new_databricks_table_queries.sql
tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_new_table_queries.sql
tests/integration/query_graph/test_online_serving.py
tests/unit/routes/test_batch_feature_table.py
tests/util/helper.py

https://github.com/featurebyte/featurebyte/pull/3029
https://github.com/featurebyte/featurebyte/pull/3034

[chore] Cherry-pick recent fixes

---

featurebyte/query_graph/sql/interpreter/preview.py
featurebyte/service/preview.py
tests/fixtures/preview_service/expected_describe_with_partition_column_filters.sql
tests/fixtures/preview_service/expected_sample_with_partition_column_filters.sql
tests/fixtures/preview_service/expected_value_counts_with_partition_column_filters.sql
tests/unit/api/test_event_table.py
tests/unit/conftest.py
tests/unit/service/test_preview.py

Changes:
* Update `PreviewService` to use partition column filters
* Activated when time range filtering is specified with `sample_on_primary_table=True`
* Support time range filtering for `value_counts`
* Fix an issue in `value_counts` where sampling is performed twice
| …

[DEV-4100] Update PreviewService to use partition column filters

---

featurebyte/models/feature.py
featurebyte/query_graph/graph.py
featurebyte/query_graph/sql/batch_helper.py
tests/fixtures/expected_historical_requests_multiple_batches_output_query.sql
tests/unit/api/test_deployment.py
tests/unit/feature_manager/test_unit_snowflake_feature.py
tests/unit/models/test_feature.py
tests/unit/routes/test_feature.py

Cherry-pick recent changes:
* #3022
* #3020

[cherry-pick] Cherry pick recent changes to stable/v3

---

featurebyte/query_graph/sql/online_serving.py
tests/fixtures/expected_get_online_features_partition_column_filters.sql
tests/unit/conftest.py
tests/unit/service/test_online_serving.py

This updates batch features computation to apply partition column filtering when applicable.

[DEV-4102] Apply partition column filtering for batch features

---

.github/workflows/test.yaml
featurebyte/query_graph/sql/ast/input.py
featurebyte/query_graph/sql/common.py
featurebyte/query_graph/sql/partition_filter.py
tests/fixtures/expected_tile_sql_scheduled_partition_column_filters.sql
tests/integration/api/test_view_sample.py
tests/integration/service/test_tile_task_executor.py
tests/unit/query_graph/sql/test_tile.py

This updates scheduled tile sql to apply partition column filtering when available.

[DEV-4103] Apply partition column filtering in scheduled tile sql

---

poetry.lock
pyproject.toml

(cherry picked from commit 65c4532cc547ac601884d762f06622755aa16c65)

[FIX] adding missing aiofiles dependency (#3031)

---

featurebyte/common/documentation/documentation_layout.py

Update docs to include new deployment function

[chore] Update docs

---

.changelog/DEV-4132.yaml
featurebyte/exception.py
featurebyte/models/deployment.py
featurebyte/query_graph/node/schema.py
featurebyte/routes/deployment/controller.py
featurebyte/routes/feature_store/api.py
featurebyte/routes/feature_store/controller.py
featurebyte/schema/deployment.py
featurebyte/schema/feature_store.py
featurebyte/service/deployment.py
featurebyte/service/session_manager.py
featurebyte/session/databricks.py
tests/integration/session/test_base.py
tests/unit/conftest.py
tests/unit/routes/test_deployment.py
tests/unit/routes/test_feature_store.py

Add routes to:
- List compute options for a feature store
- Update compute options for a deployment

[DEV-4132] Add routes to update compute options for deployment

---

featurebyte/models/development_dataset.py
featurebyte/persistent/base.py
featurebyte/persistent/mongo.py
featurebyte/routes/development_dataset/controller.py
featurebyte/schema/development_dataset.py
featurebyte/service/base_document.py
featurebyte/service/development_dataset.py
tests/unit/routes/base.py
tests/unit/routes/test_development_dataset.py
tests/unit/test_generate_payload_fixtures.py

Handle deleted tables in dev datasets:
- include `deleted` field to indicate if table is deleted
- exclude deleted tables from info details …

[DEV-4105] Handle deleted tables in dev datasets

---

featurebyte/service/batch_external_feature_table.py
tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_existing_empty_databricks_table_queries.sql
tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_existing_empty_table_queries.sql
tests/integration/query_graph/test_online_serving.py
tests/unit/routes/test_batch_feature_table.py

[chore] Support using empty existing table for external feature table (#3087)

[chore] Support using empty existing table for external feature table (cherry-pick)

---

featurebyte/models/development_dataset.py
featurebyte/routes/development_dataset/controller.py
featurebyte/schema/development_dataset.py
tests/fixtures/request_payloads/development_dataset.json
tests/unit/routes/test_development_dataset.py

@kchua78 PR to add status, development_ids, sampled_table_ids to development dataset models and schemas.

add status, plan ids to dev dataset models

---

featurebyte/query_graph/sql/parent_serving.py
featurebyte/service/feature_materialize.py
tests/fixtures/query_graph/test_parent_serving/snapshots_table_lookup.sql
tests/integration/api/test_serving_parent_features.py
tests/unit/query_graph/conftest.py
tests/unit/query_graph/test_parent_serving.py

This adds support for serving parent features via SnapshotsTable.

[DEV-4145] Add support for serving parent features via SnapshotsTable

---

featurebyte/migration/service/use_case.py
featurebyte/models/use_case.py
featurebyte/routes/registry.py
tests/fixtures/migration/use_case

This PR refactor use case model to prepare for descriptive use case support.

[DEV-4156] Refactor use case model

---

featurebyte/worker/util/task_progress_updater.py
tests/unit/worker/test_util.py

This PR updates task progress updater to include set progress range context manager.

[chore] Add `set_progress_range` context manager to `TaskProgressUpdater`

---

featurebyte/routes/deployment/api.py
featurebyte/routes/deployment/controller.py
featurebyte/service/deploy.py
featurebyte/worker/task/deployment_create_update.py
tests/unit/service/conftest.py
tests/unit/service/test_deploy.py
tests/unit/service/test_feast_registry.py
tests/unit/service/test_feature_list_status.py
tests/unit/service/test_feature_materialize.py
tests/unit/service/test_feature_table_cache.py
tests/util/helper.py

Refactors deployment related services and routes to make them extensible and enable additional functionalities in the enterprise app (e.g. `model_id`). …

[chore] Refactor deployment services and routes to support extensions

---

featurebyte/persistent/mongo.py
uv.lock

[chore] fixing AgnosticCursor

---

featurebyte/worker/task/batch_feature_table.py

Refactors `BatchFeatureTableTask` to allow using the task to compute a batch feature table without creating a `BatchFeatureTableModel` document. …

[chore] Refactor batch feature table task and add create_document flag
