featurebyte/featurebyte

- README.md
Use absolute urls for images in README so they show up in PyPI page
> Use absolute urls for images in README

- featurebyte/common/utils.py
- tests/unit/common/test_utils.py
Usage of css classes breaks css formatting in documentation pages.
https://featurebyte.atlassian.net/browse/DEV-1686
> [DEV-1686] Use embedded styles for code html formatting

- featurebyte/common/utils.py
- tests/unit/common/test_utils.py
Exclude background color for code string html as it makes text unreadable in documentation in dark mode.
https://featurebyte.atlassian.net/browse/DEV-1686 …
> [DEV-1686] Remove background color for code string html

- featurebyte/common/utils.py
- tests/unit/common/test_utils.py
Usage of css classes breaks css formatting in documentation pages.
Exclude background color for code string html as it makes text unreadable in documentation in dark mode.
Cherry-pick from:
https://github.com/featurebyte/featurebyte/pull/1282
https://github.com/featurebyte/featurebyte/pull/1280 …
> [DEV-1686] Fix Code String HTML formatting breaking documentation pages

- featurebyte/common/documentation/extract_csv.py
- tests/unit/common/documentation/test_extract_csv.py
This adds a simple test to catch methods that are public facing in our documentation, but do not include any examples. 
Ideally, all our methods should have some simple examples on how to use them.
| …
> [chore] docs: add test to catch methods without examples

- CHANGELOG.md
- featurebyte/session/databricks.py
- tests/unit/session/test_databricks_session.py
Implement streamed records fetching for DataBricks session to support download of large tables.
https://featurebyte.atlassian.net/browse/DEV-1684 …
> [DEV-1684] Implement streamed records fetching for DataBricks session

- CHANGELOG.md
- featurebyte/session/base.py
- featurebyte/worker/task/mixin.py
- tests/unit/api/test_source_table.py
This updates the clean up of materialized tables on error to drop the table only when it exists to avoid masking actual errors.
> Drop a materialized table only if it exists when cleaning up on error

- CHANGELOG.md
- featurebyte/models/credential.py
- featurebyte/session/base_spark.py
- tests/unit/models/test_credential.py
- tests/unit/session/test_spark.py
- Connection check is expensive - do it only when registering objects instead of each time a session is created.
- Fix GCS credentials not encrypted for storage
https://featurebyte.atlassian.net/browse/DEV-1699 …
> [DEV-1699] Avoid performing Spark storage connection check for every session creation

- CHANGELOG.md
- featurebyte/api/relationship.py
- tests/unit/api/test_relationship.py
This PR fixes a small bug that was causing an error to be thrown when a `Relationship` was persisted with no `updated_by`. 
https://featurebyte.atlassian.net/browse/DEV-1423 …
> [DEV-1423] relationship: ensure get_by_id works for None updated_by

- featurebyte/api/relationship.py
- tests/unit/api/test_relationship.py
This PR fixes a small bug that was causing an error to be thrown when a Relationship was persisted with no updated_by.
Related Issue: https://featurebyte.atlassian.net/browse/DEV-1423
| …
> [DEV-1423] relationship: ensure get_by_id works for None updated_by (#1308)

- CHANGELOG.md
- featurebyte/api/api_object.py
- featurebyte/api/api_object_util.py
- featurebyte/api/base_table.py
- featurebyte/api/catalog.py
- featurebyte/api/credential.py
- featurebyte/api/deployment.py
- featurebyte/api/entity.py
- featurebyte/api/feature.py
- featurebyte/api/feature_list.py
- featurebyte/api/feature_store.py
- featurebyte/api/periodic_task.py
- featurebyte/api/savable_api_object.py
- featurebyte/common/formatting_util.py
- featurebyte/common/utils.py
- tests/fixtures/feature_info.html
- tests/fixtures/feature_list_info.html
- tests/unit/api/test_catalog.py
- tests/unit/api/test_entity.py
- tests/unit/api/test_event_table.py
- tests/unit/api/test_item_table.py
- tests/unit/common/test_formatting_util.py
- tests/unit/common/test_utils.py
Implement HTML representation for API Object `.info()` result for better readability.
https://featurebyte.atlassian.net/browse/DEV-1712 …
> [DEV-1712] Implement HTML representation for API Object information result

- featurebyte/api/api_object.py
- tests/unit/api/test_feature.py
Fix bug introduced by unreleased implementation of object info html representation https://github.com/featurebyte/featurebyte/pull/1307
The html representation of unsaved API objects returns an empty string. This PR will fix that to return the non-html repr instead.
https://featurebyte.atlassian.net/browse/DEV-1712 …
> [DEV-1712] Ensure html repr for unsaved objects is not empty

- CHANGELOG.md
- featurebyte/api/entity.py
- featurebyte/api/relationship.py
- featurebyte/common/documentation/documentation_layout.py
- tests/unit/api/test_entity.py
- tests/unit/api/test_relationship.py
Expose `catalog_id` for the entity and relationship API objects.
https://featurebyte.atlassian.net/browse/DEV-1505
https://featurebyte.atlassian.net/browse/DEV-1506 …
> expose catalog_id for entity and relationship

- featurebyte/schema/feature_job_setting_analysis.py
- tests/unit/routes/test_feature_job_setting_analysis.py
Current feature_job_analysis route does not expose warehouse info of a feature job analysis. This change exposes warehouse info of feature job analysis without potentially long fields of missing/late job list …
> [DEV-1728] expose warehouse statstics of feature job analysis

- .changelog/DEV-1431.yaml
- .github/workflows/changelog.yml
- Taskfile.yaml
- featurebyte/api/feature_list.py
- featurebyte/schema/info.py
- tests/unit/api/test_feature_list.py
- tests/unit/service/test_info.py
As per title suggests, this PR fixes inconsistencies between `feature.info()` & `feature_list.info()` by minor refactoring feature & feature list info schema. …
> [DEV-1431] Add `default_feature_list_id` to `feature_list.info()` output

- .changelog/changelog-gen.py
- .changelog/chester-starlette-vuln.yaml
- Taskfile.yaml
+ changelog needs pyyaml which might not be present in default env
+ rstrip() on final text render.
> [chore] changelog module dependency and formatting fix

- .changelog/jevon-create-debug-folder-for-docs.yaml
- featurebyte/common/documentation/gen_ref_pages_docs_builder.py
Small fix to docs to create the `debug` folder automatically during initialization.
> docs: create debug folder if it doesn't exist

- .changelog/DEV-1721.yaml
- featurebyte/service/task_manager.py
- featurebyte/worker/task_executor.py
- tests/unit/service/test_task_manager.py
- tests/unit/worker/test_task_executor.py
Periodic tasks scheduled based on intervals can pile up if such task does not complete within the interval.
Changes made in this PR:
- Always specify soft time limit for scheduled tasks (defaults to interval length), can be overriden
- Support enforcement of soft time limit for io-intensive tasks executed in gevent workers (soft limit is not supported by celery for gevent worker pool)
https://featurebyte.atlassian.net/browse/DEV-1721
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & …
> [DEV-1721] Enforce time limits for periodic tasks scheduled based on intervals

- .changelog/DEV-1744.yaml
- featurebyte/api/feature.py
- featurebyte/models/feature.py
- featurebyte/schema/feature.py
- tests/fixtures/request_payloads/feature_iet.json
- tests/fixtures/request_payloads/feature_item_event.json
- tests/fixtures/request_payloads/feature_non_time_based.json
- tests/fixtures/request_payloads/feature_sum_2h.json
- tests/fixtures/request_payloads/feature_sum_30m.json
- tests/unit/api/test_feature.py
- tests/unit/routes/test_feature.py
This PR aims to remove `dtype` from feature creation payload.
> [DEV-1744] Remove `dtype` from feature creation payload

- .changelog/changelog-gen.py
- tests/unit/migration/conftest.py
- tests/unit/migration/test_run.py
This PR aims to fix the test coupling issue due to calling
```
AsyncIOMotorClient(uri, uuidRepresentation="standard")
```
where there exists a running event loop.
Run the following command to reproduce the issue:
```
pytest -vv tests/unit/migration tests/unit/worker --pdb
```
| …
> [chore] Fix migration persistent test fixture

- .changelog/DEV-1753.yaml
- featurebyte/persistent/mongo.py
- featurebyte/utils/persistent.py
- tests/unit/persistent/test_mongo.py
Current global persistent object it not thread-safe. It causes issue when multiple threads attempting to call the same global persistent object. …
> [DEV-1753] Update `get_persistent()` by removing global persistent object

- .changelog/DEV-1749.yaml
- featurebyte/config.py
- tests/unit/test_config.py
Requests handling of 30x redirection can convert POST to GET requests.
To avoid unexpected behavior redirection handling is disabled in the HTTP client.
https://featurebyte.atlassian.net/browse/DEV-1749
| …
> [DEV-1749] Disable redirection in HTTP client

- .github/workflows/changelog_gen.yaml
- .github/workflows/publish-public_gen.yaml
- CONTRIBUTING.md
missing `runs_on` property on public_public workflow.
> [chore] fix publish-public workflow missing runs_on

- .changelog/DEV-1766.yaml
- featurebyte/exception.py
- featurebyte/service/deploy.py
- tests/unit/routes/base.py
- tests/unit/routes/test_batch_feature_table.py
- tests/unit/routes/test_deployment.py
- tests/unit/service/conftest.py
- tests/unit/service/test_deploy.py
- tests/unit/service/test_feature_list_status.py
Current deployment enabling & disabling does not consider the case when multiple deployments sharing the same feature list. One issue is that feature list's `deployed` status is updated to `False` when any of the enabled deployments is disabled without considering there may be other enabled deployment(s). …
> [DEV-1766] Fix multiple deployment sharing the same feature list bug

- featurebyte/query_graph/sql/feature_compute.py
- featurebyte/query_graph/sql/feature_historical.py
- tests/fixtures/expected_historical_requests_multiple_batches_feature_set_0.sql
- tests/fixtures/expected_historical_requests_multiple_batches_feature_set_1.sql
- tests/fixtures/expected_historical_requests_multiple_batches_feature_set_2.sql
- tests/fixtures/expected_historical_requests_multiple_batches_feature_set_3.sql
- tests/fixtures/expected_historical_requests_multiple_batches_output_query.sql
- tests/integration/api/test_event_view_operations.py
- tests/unit/query_graph/conftest.py
- tests/unit/query_graph/test_feature_historical.py
- tests/util/helper.py
This improves the columns batching logic in historical features to account for aggregation parameters so that it is not sensitive to the original ordering of features. The change is to introduce a reordering step in the `split_nodes` function.
The previously measured historical features runtime for [`Features V1`](https://github.com/featurebyte/featurebyte-notebooks/blob/f6e8cd4b352c3550540874e9cdd9001ba47a84f0/notebooks/features/grocery/setup.py#L67) was optimistic because the features were ordered meaningfully in the feature list. The runtime increases from 27m to 42m if the feature list is shuffled randomly. With the changes in this PR, the runtime of the shuffled feature list is 25m.
|        **Pull …
> [DEV-1756] Improve columns batching logic to account for aggregation parameters

- .changelog/DEV-1761.yaml
- featurebyte/service/feature_list_status.py
- featurebyte/service/feature_readiness.py
- tests/unit/api/test_feature.py
- tests/unit/service/test_feature_list_status.py
- tests/unit/service/test_feature_readiness.py
This PR aims to block DRAFT to DEPRECATED transition to prevent misuse of DEPRECATED (delete should be used in this case).
State diagram after this update: …
> enhancement: Block feature readiness & feature list status transition from DRAFT to DEPRECATED

- .changelog/DEV-1763.yaml
- featurebyte/api/feature_list.py
- featurebyte/models/feature_list.py
- featurebyte/service/feature_list.py
- tests/unit/api/test_feature_list.py
- tests/unit/models/test_feature_list.py
- tests/unit/routes/test_feature_list.py
Current feature list save involves feature IDs sorting. This causes feature order not being preserved. This PR aims to remove the sorting part & update feature list retrieval logic to preserve feature order. …
> enchancement: update feature list to preserve feature order

- docker/entrypoint.sh
- featurebyte/__init__.py
- featurebyte/__main__.py
- featurebyte/docker/featurebyte.yml
- featurebyte/docker/manager.py
**Starting the server with playground**
**KRB config written out to /app/krb5.conf**
**Environment Variable Set in running process** …
> [DEV-1773] Playground startup + docker startup to allow user to specify KRB5 params

- .changelog/DEV-1760.yaml
- featurebyte/core/accessor/count_dict.py
- featurebyte/session/snowflake.py
- featurebyte/sql/snowflake/F_GET_RELATIVE_FREQUENCY.sql
- hive-udf/lib/src/main/java/com/featurebyte/hive/udf/CountDictRelativeFrequency.java
- tests/integration/udf/test_get_relative_frequency.py
This updates the UDFs underlying the `get_relative_frequency` method to return 0 when there is no matching label.
> [DEV-1760] Update get_relative_frequency to return 0 when there is no matching label

- docker/docker-compose.yml
- tests/integration/conftest.py
The `spark-thrift-test` container is used by integration tests. When the container is running, it is not possible start the featurebyte spark container since they bind to the same ports. This binds the ports used by `spark-thrift-test` to different ones so these containers can co-exist. This should make development a bit more convenient (no need to stop the featurebyte services before running `task test-setup` and vice versa).
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & Refactoring …
> [chore] Bind spark-thrift-test to different ports to not interfere with docker-dev

- Taskfile.yaml
- poetry.lock
- pyproject.toml
Ignoring pip-audit for cryptography and redis until upstream dependencies are fixed.
`crytography` is blocked by snowflake-connector-python …
> [DEV-1780] Ignore vuln for cryptography and redis

- .changelog/DEV-1793.yaml
- featurebyte/config.py
- featurebyte/service/deploy.py
- tests/unit/test_config.py
Some load balancers do not take into account websocket ping pong packets when enforcing connection timeouts.
To make the websocket connection resilient to this, automatic reconnection is added to re-establish connection while receiving a new message.
https://featurebyte.atlassian.net/browse/DEV-1793 …
> [DEV-1793] Make websocket client more resilient against connection drop

- .changelog/DEV-1795.yaml
- featurebyte/api/feature_list.py
- featurebyte/routes/feature_namespace/controller.py
- featurebyte/service/validator/production_ready_validator.py
- featurebyte/worker/task/batch_feature_create.py
- tests/unit/api/test_feature.py
- tests/unit/routes/base.py
- tests/unit/routes/test_feature.py
- tests/unit/routes/test_feature_namespace.py
- tests/unit/service/validator/test_production_ready_validator.py
Manual default version selection is designed to resolve issue when there are more than 1 feature version which are at the highest readiness version. This PR aims to impose more constraints on the default feature version selection. …
> enhancement: limit manual default version selection to the versions with the highest readiness level only

- featurebyte/enum.py
- featurebyte/migration/service/mixin.py
- featurebyte/service/batch_feature_table.py
- featurebyte/service/batch_request_table.py
- featurebyte/service/historical_feature_table.py
- featurebyte/service/observation_table.py
- featurebyte/session/base.py
- featurebyte/session/snowflake.py
- tests/integration/service/test_working_schema_service.py
When recreating a schema from scratch, all tables in the the working schema are dropped before being reinstated. However, this is not applicable to materialized tables which also reside in the working schema. This updates the process to be aware of materialized tables and not drop them. …
> [DEV-1467] Update schema recreation process to be aware of materialized tables

- featurebyte/session/base.py
- featurebyte/session/base_spark.py
- featurebyte/session/snowflake.py
- tests/integration/service/test_working_schema_service.py
- tests/unit/session/test_base.py
This adds support for resetting working schema for spark. This can be useful for migrating assets in the warehouse.
> [chore] Support resetting working schema for spark

- featurebyte/api/api_object_util.py
- featurebyte/api/feature.py
- featurebyte/api/source_table.py
As parts of the effort to reduce time to save features & feature lists, this PR updates table object constructor logic to skip querying warehouse when running the SDK code in server mode.
With current changes, the time to save 204 features drop from 11.5min to 2min.
| …
> [chore] Skip query warehouse when executing SDK code in server mode

- featurebyte/api/feature.py
- featurebyte/models/context.py
- featurebyte/models/feature.py
- featurebyte/models/feature_list.py
- featurebyte/models/request_input.py
- featurebyte/routes/feature/controller.py
- featurebyte/service/batch_request_table.py
- featurebyte/service/feature.py
- featurebyte/service/observation_table.py
- featurebyte/service/online_enable.py
- featurebyte/service/static_source_table.py
- tests/unit/models/test_feature.py
- tests/unit/models/test_feature_list.py
Recent runtime performance investigation found that it takes long time to serialize & deserialize the model when it contains complicated graphs (loading from persistent, convert to response model). To improve the runtime performance, this PR aims to make these attribute lazy (keeps the original dictionary format when it is not loaded, when accessing the attribute, convert them into expected format & then stored it in the model cache).
With current changes:
* loading save feature list object: reduce from 13 seconds to 1.5 seconds
* create a feature list with 204 saved features & delete the feature list: reduce from 35 seconds to 9-15 seconds
Time to list assets through catalog object:
Before:
```
list_method_name                elapsed
5                  list_feature_lists 0 days …
```
> [chore] make graph related attribute lazy

- .changelog/DEV-1812.yaml
- featurebyte/api/api_object.py
- featurebyte/api/base_table.py
- featurebyte/api/catalog.py
- featurebyte/api/credential.py
- featurebyte/api/entity.py
- featurebyte/api/feature.py
- featurebyte/api/feature_list.py
- featurebyte/api/feature_store.py
- featurebyte/api/source_table.py
- featurebyte/api/view.py
- featurebyte/models/feature_store.py
- featurebyte/query_graph/graph.py
- featurebyte/query_graph/transform/entity_extractor.py
- featurebyte/routes/credential/controller.py
- featurebyte/routes/feature/controller.py
- featurebyte/routes/feature_list/controller.py
- featurebyte/routes/feature_list_namespace/controller.py
- featurebyte/routes/feature_namespace/controller.py
- featurebyte/routes/feature_store/controller.py
- featurebyte/service/base_document.py
- featurebyte/service/base_table_document.py
- featurebyte/service/credential.py
- featurebyte/service/feature.py
- featurebyte/service/feature_list.py
- featurebyte/worker/task/batch_feature_create.py
- tests/unit/api/test_sdk_code.py
- tests/unit/api/test_view.py
This PR aims to fix primary entity identification bug for the time-aggregated-item-aggregated feature. Below is the example of such feature:
```
from bson import ObjectId
from featurebyte import EventTable
from featurebyte import FeatureJobSetting
from featurebyte import ItemTable
item_table = ItemTable.get_by_id(ObjectId("64874aa0f48964db9d3e9847"))
item_view = item_table.get_view(
event_suffix=None,
view_mode="manual",
drop_column_names=[],
column_cleaning_operations=[],
event_drop_column_names=["record_available_at"],
event_column_cleaning_operations=[],
event_join_column_names=["ReportDate", "LabResultGuid", "PatientGuid"],
)
col = item_view["IsAbnormalValue"]
view = item_view.copy()
view["IsAbnormalValueInt"] = (col == "true").astype(int)
col_1 = …
```
> [bug] fix primary entity identification bug

- tests/integration/conftest.py
- tests/integration/query_graph/test_online_serving.py
This fixes a mongo failure that occurs in `tests/integration/query_graph/test_online_serving.py::test_online_serving_sql` because the test is sharing the same instance of persistent between threads.
The error looks like this:
> E       pymongo.errors.OperationFailure: Transaction with { txnNumber: 1 } has been committed., full error: {'ok': 0.0, 'errmsg': 'Transaction with { txnNumber: 1 } has been committed.', 'code': 256, 'codeName': 'TransactionCommitted', '$clusterTime': {'clusterTime': Timestamp(1686796484, 4), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1686796484, 1)}
|        **Pull Request Label** …
> [chore] Fix mongo error in integration tests due to non-threadsafe persistent

- .changelog/DEV-1818.yaml
- featurebyte/api/data_source.py
- featurebyte/api/source_table.py
- tests/unit/api/test_event_table.py
- tests/unit/api/test_table.py
API related to querying data warehouse is expensive. To improve the user experience on using the SDK, this PR removes data warehouse related API calls during table construction. Move the data warehouse table schema API call to `get_source_table` method.
| …
> enhancement: skip calling data warehouse during table construction

- featurebyte/api/feature.py
- featurebyte/api/feature_list.py
- tests/integration/api/test_event_view_operations.py
- tests/integration/query_graph/test_online_serving.py
- tests/unit/service/test_preview.py
This fixes the test `test_get_historical_features__feature_list_not_saved` which fails when run individually. Also fixes a few places where the `by_alias=True` option should have been specified when calling `dict()`. …
> Fix failing unit test test_get_historical_features__feature_list_not_saved

- .changelog/DEV-1788.yaml
- featurebyte/api/catalog.py
- featurebyte/api/target.py
- featurebyte/models/target.py
- featurebyte/schema/target.py
- tests/unit/api/test_catalog.py
- tests/unit/api/test_target.py
- tests/unit/models/test_target.py
This PR adds the basic API object for working with a `Target`. This allows users to create a `Target` via the constructor in the form of
```
fraud_flag_7d = Target.create(
name='Fraudulent CC Transaction after 7 days',
entities='CC Transaction',
horizon="7d",
blind_spot="1d",
)
```
This will also save the `Target`.
Will add more functionality (eg. `series` like functionality) in the future once we get the forward aggregates working.
https://featurebyte.atlassian.net/browse/DEV-1788
| `bug`, …
> [DEV-1788] api/target: add basic API object for Target

- featurebyte/routes/app_container_config.py
- featurebyte/routes/lazy_app_container.py
- featurebyte/routes/registry.py
- tests/unit/routes/test_app_container_config.py
- tests/unit/routes/test_lazy_app_container.py
With the introduction of the `LazyAppContainer`, and the smarter way of building our dependencies, we can actually simplify the API for the app_container, as the registration of dependencies is no longer order dependent (i.e. the order in which the registration happens in `registry.py` can be out of order, whereas previously it couldn't be).
As such, we can also simplify the registration API on the config to just 2 methods - `register_service`, and `register_class`. We still keep a special `register_service` since our services consistently take in a few parameters like user, persistent and catalog_id. 
We also add a new validator to check for cycles in the dependencies when the app_container_config is built. …
> [chore] app_container: refactor app_container to simplify

- .changelog/DEV-1810.yaml
- featurebyte/__init__.py
- featurebyte/config.py
- featurebyte/worker/task_executor.py
- tests/fixtures/config/config.yaml
- tests/integration/backward_compatibility/test_get_route.py
- tests/integration/conftest.py
- tests/integration/worker/conftest.py
- tests/unit/conftest_config.py
- tests/unit/test_config.py
Changes introduced:
1. Remove use of implicit default profile. Profile needs to be specified to connect to the right service.
2. Add `default_profile` section in config file to explicitly specify default profile to use.
https://featurebyte.atlassian.net/browse/DEV-1810
| …
> [DEV-1810] Remove implicit profile selection

- .github/workflows/notify_gen.yaml
Fix new line formatting.
Currently looks like 
which is kinda ugly.
> [chore] workflow/notify: fix new line formatting

- featurebyte/migration/service/mixin.py
- featurebyte/routes/app_container_config.py
- featurebyte/routes/batch_feature_table/controller.py
- featurebyte/routes/batch_request_table/controller.py
- featurebyte/routes/credential/controller.py
- featurebyte/routes/deployment/controller.py
- featurebyte/routes/dimension_table/controller.py
- featurebyte/routes/entity/controller.py
- featurebyte/routes/event_table/controller.py
- featurebyte/routes/feature/controller.py
- featurebyte/routes/feature_job_setting_analysis/controller.py
- featurebyte/routes/feature_list/controller.py
- featurebyte/routes/feature_list_namespace/controller.py
- featurebyte/routes/feature_namespace/controller.py
- featurebyte/routes/feature_store/controller.py
- featurebyte/routes/historical_feature_table/controller.py
- featurebyte/routes/item_table/controller.py
- featurebyte/routes/lazy_app_container.py
- featurebyte/routes/observation_table/controller.py
- featurebyte/routes/registry.py
- featurebyte/routes/relationship_info/controller.py
- featurebyte/routes/semantic/controller.py
- featurebyte/routes/static_source_table/controller.py
- featurebyte/routes/target/controller.py
- featurebyte/routes/temp_data/api.py
- featurebyte/service/online_serving.py
- featurebyte/service/session_manager.py
- featurebyte/service/session_validator.py
- tests/unit/routes/test_app_container_config.py
- tests/unit/routes/test_lazy_app_container.py
Simplify interface further by inferring the name, and dependencies as much as possible.
With these changes, registering a service/class should be as simple as 
`app_container_config.register_class(<class>)` 
for >90% of the cases, compared to 
`app_container_config.register_class(<class_name>, <class>, [<dependencies>])`
which is the current format.
There are some edge cases where we _might_ need to specify overrides:
- classes that don't override a constructor (eg. controller implementations)
- camel case class names that are acronyms (eg. SCDTable -> manually override to `scd_table`. otherwise, we'll infer as `s_c_d_table`) …
> [chore] app_registry: simplify DI service registration interface further

- .changelog/DEV-1846.yaml
- featurebyte/feature_manager/manager.py
- tests/unit/feature_manager/test_unit_snowflake_feature.py
When an aggregation result name is already registered, updating the `ONLINE_STORE_MAPPING` table is unnecessary.
> [DEV-1846] Skip redundant updates of online store mapping table

- featurebyte/routes/catalog/catalog_name_injector.py
- featurebyte/routes/feature_namespace/controller.py
- featurebyte/routes/registry.py
- featurebyte/service/entity.py
- featurebyte/service/feature_list_namespace.py
- featurebyte/service/relationship.py
- featurebyte/service/table_info.py
This PR does a small refactoring to reuse some logic that adds the `catalog_name` field onto documents when reading them. 
> [chore] catalog_name_injector: refactor to reuse logic to add catalog name to documents

- .changelog/DEV-1869.yaml
- featurebyte/models/tile.py
- featurebyte/routes/registry.py
- featurebyte/schema/worker/task/tile.py
- featurebyte/service/feature_manager.py
- featurebyte/service/tile/tile_task_executor.py
- featurebyte/service/tile_manager.py
- featurebyte/service/tile_scheduler.py
- featurebyte/sql/base.py
- featurebyte/sql/tile_common.py
- featurebyte/sql/tile_generate_entity_tracking.py
- featurebyte/sql/tile_schedule_online_store.py
- featurebyte/worker/task/tile_task.py
- tests/integration/tile/conftest.py
- tests/integration/tile/test_schedule_generate_tile.py
- tests/integration/tile/test_tile_scheduler.py
- tests/unit/tile/test_unit_snowflake_tile.py
This refactors `TileGenerateSchedule` which gets called in the tile task to use dependency injection and rename it to something clearer: `TileTaskExecutor`. This also refactors the tile task to avoid using importlib and json for deserialisation which is unnecessary by using pydantic properly. …
> [DEV-1869] Refactor tile task to use dependency injection

- .changelog/DEV-1875.yaml
- featurebyte/models/tile.py
- featurebyte/service/tile/tile_task_executor.py
- featurebyte/service/tile_manager.py
- featurebyte/sql/tile_generate.py
- featurebyte/sql/tile_monitor.py
- featurebyte/sql/tile_registry.py
- tests/integration/tile/test_generate_tile.py
- tests/integration/tile/test_monitor_tile.py
- tests/integration/tile/test_schedule_generate_tile.py
- tests/unit/service/conftest.py
- tests/unit/service/tile/test_tile_task_executor.py
This fixes a bug where incorrect point-in-time value was passed to `TileScheduleOnlineStore` in the scheduled tile task. The timestamp should be the scheduled job timestamp, not the tile end timestamp adjusted for blind spot. …
> [DEV-1875] Fix incorrect point-in-time value when updating online store tables

- docker/migration.py
- featurebyte/migration/run.py
- featurebyte/migration/service/data_warehouse.py
- featurebyte/migration/service/mixin.py
- featurebyte/routes/lazy_app_container.py
- featurebyte/routes/registry.py
- featurebyte/service/base_document.py
- featurebyte/service/base_table_document.py
- featurebyte/service/credential.py
- featurebyte/service/session_manager.py
- featurebyte/service/user_defined_function.py
- featurebyte/service/working_schema.py
- tests/integration/conftest.py
- tests/integration/migration/test_data_warehouse_migration.py
- tests/integration/service/test_working_schema_service.py
- tests/unit/migration/test_run.py
- tests/unit/routes/test_lazy_app_container.py
- tests/unit/service/test_base_document.py
This should make it easier to reuse services across the migration framework too.
Will also make it less annoying to add dependencies to existing services that might be used in these migration services.
Changed to traditional constructors so that it's easier to see what the dependencies are in each of the classes, instead of having them declared all over the place.
|       `build`, `ci`, `testing`        |    📦 Build …
> [chore] data_migrations: update to use injection via config

- .changelog/DEV-1896.yaml
- featurebyte/sql/base.py
- featurebyte/sql/tile_registry.py
This fixes the `SHOW COLUMNS` command error in Spark 3.2 by using an alternative way to retrieve column names.
> [DEV-1896] Avoid using SHOW COLUMNS to support Spark 3.2

- Taskfile.yaml
Temporarily add `--ignore-vuln GHSA-9jx5-6pgf-crrp`. While the fix should be in since scipy 1.10.0, I tried to specify that but got some other poetry errors. Since that doesn't seem straightforward I added this to unblock main first. …
> [chore] Add --ignore-vuln GHSA-9jx5-6pgf-crrp

- .changelog/DEV-1895.yaml
- featurebyte/query_graph/sql/adapter.py
- tests/fixtures/expected_preview_sql_databricks.sql
The Databricks flavoured `DATEADD` function is only available since Spark 3.3. To support older versions of Spark, this updates the adapter to perform timestamp addition by casting timestamps to seconds.
| …
> [DEV-1895] Fix DATEADD undefined function error in Spark 3.2

- .changelog/chester-python-version.yaml
- poetry.lock
- pyproject.toml
+ `scipy` bumped to version ^1.10.0
+ This requires constraining featurebyte supported python version from [3.8,4.0) to [3.8,3.13)
+ Bumped smaller dependencies in poetry.lock …
> [chore] Bumping dependencies to fix scipy security vuln

- .changelog/DEV-1899.yaml
- featurebyte/sql/base.py
- featurebyte/sql/tile_monitor.py
- featurebyte/sql/tile_schedule_online_store.py
This removes unnecessary usage of SQL functions: `ILIKE` and `DATEADD` which are incompatible with Spark 3.2.
> [DEV-1899][DEV-1902] Remove usage of ILIKE and DATEADD which are incompatible with Spark 3.2

- .changelog/DEV-1895.yaml
- featurebyte/query_graph/sql/adapter.py
- tests/fixtures/expected_preview_sql_databricks.sql
- tests/integration/api/test_event_view_operations.py
This is a fix up for https://github.com/featurebyte/featurebyte/pull/1489 where the sub-second component was not being handled properly. This also reenables the `test_datetime_operations` integration test for spark. …
> [DEV-1895] Fix microseconds incorrectly discarded in spark dateadd_microsecond

- .changelog/DEV-1909.yaml
- featurebyte/api/catalog.py
- featurebyte/api/catalog_get_by_id_mixin.py
- featurebyte/api/target.py
- featurebyte/api/target_table.py
- tests/unit/api/test_catalog.py
- tests/unit/api/test_target_table.py
- tests/unit/conftest.py
Add a `TargetTable` API object, and stub out some of the `compute_target` endpoints in the `Target` API object.
This will submit the task to create the target table. We'll finish up the implementation of the task in a follow-up PR to reduce the size of this one.
https://featurebyte.atlassian.net/browse/DEV-1909 …
> [DEV-1909] target_table: add API object

- .changelog/DEV-1894.yaml
- featurebyte/query_graph/sql/adapter.py
- featurebyte/query_graph/sql/ast/string.py
- featurebyte/query_graph/sql/expression.py
- tests/integration/api/test_event_view_operations.py
- tests/unit/core/accessor/test_string.py
This fixes an error when using the string contains operation with Spark 3.2 because the `CONTAINS` function is not available in older versions of Spark. …
> [DEV-1894] Fix compatibility of string contains operation with Spark 3.2

- .changelog/DEV-1892.yaml
- featurebyte/session/base.py
- featurebyte/session/base_spark.py
- featurebyte/session/snowflake.py
- featurebyte/session/spark.py
- tests/unit/session/test_base.py
- tests/unit/session/test_databricks_session.py
This fixes the listing of databases and schemas in Spark 3.2 and older versions since newer syntaxes like `SHOW CATALOGS` were not yet supported. …
> [DEV-1892][DEV-1893] Fix listing of databases and schemas in Spark 3.2

- featurebyte/__init__.py
- tests/unit/test_init.py
Add `register_tutorial_api_token` SDK command.
We should be able to place this at the top of the notebook
```
import featurebyte as fb
fb.register_tutorial_api_token("<api_token>")
```
and this will store the token in the config file, and change to the `tutorial` profile.
https://featurebyte.atlassian.net/browse/DEV-1857 …
> [DEV-1857][chore] init: add register_tutorial_api_token SDK command

- .changelog/DEV-1919.yaml
- featurebyte/api/target.py
- featurebyte/core/series.py
- tests/unit/api/test_target.py
Add validation check when trying to perform setitem. Binary series operations already have a validation check https://github.com/featurebyte/featurebyte/blob/55e8650e3b875925e4bf3ae6efd0c9066087bf64/featurebyte/core/series.py#L58-L77
https://featurebyte.atlassian.net/browse/DEV-1919
|              `breaking`               |      💥 Breaking Changes …
> [DEV-1919] series: add validation check in setitem

- featurebyte/models/online_store.py
- featurebyte/query_graph/sql/online_serving.py
- featurebyte/query_graph/sql/online_store_compute_query.py
- tests/unit/query_graph/test_online_serving.py
This splits the `online_serving.py` into two modules for cleaner dependencies. The new `online_store_compute_query.py` is responsible for constructing `OnlineStoreComputeQueryModel` and has less dependencies than the original `online_serving.py`. This is required to avoid a circular dependency issue for an upcoming change. …
> [chore] Split online_serving.py for cleaner dependencies

- featurebyte/api/feature.py
- featurebyte/api/item_view.py
- featurebyte/core/accessor/count_dict.py
- featurebyte/core/generic.py
- featurebyte/models/feature.py
- featurebyte/query_graph/graph.py
- featurebyte/query_graph/node/metadata/operation.py
- featurebyte/query_graph/sql/interpreter/base.py
- featurebyte/query_graph/sql/interpreter/preview.py
- featurebyte/query_graph/sql/online_serving.py
- featurebyte/query_graph/transform/operation_structure.py
- featurebyte/service/context.py
- featurebyte/service/preview.py
- tests/unit/api/aggregator/test_forward_aggregator.py
- tests/unit/core/accessor/test_count_dict.py
- tests/unit/query_graph/test_extract_operation_structure.py
- tests/unit/query_graph/test_function.py
- tests/unit/query_graph/test_graph_node.py
- tests/unit/query_graph/test_graph_pruning.py
- tests/unit/query_graph/test_nested_graph_pruning.py
Update `OperationStructureExtractor`'s `keep_all_source_columns` parameter handling so that it is `True` for all cases except when using to derive feature/target info's `metadata` field.
The rationale of this change is due to https://featurebyte.atlassian.net/browse/DEV-1943. Currently, `keep_all_source_columns` is `False` by default. This is very risky as it may drops those columns that contributes only to the changes of the row index lineage. To prevent similar issue happens in the future, this PR makes `keep_all_source_columns` to be `True` for most cases.
| …
> [chore] Update `extract_operation_structure`'s `keep_all_source_columns` parameter

- .changelog/DEV-1938.yaml
- featurebyte/sql/tile_monitor.py
- tests/integration/tile/conftest.py
- tests/integration/tile/test_monitor_tile.py
- tests/integration/tile/test_schedule_generate_tile.py
This disables tile monitoring by default which is currently not user facing. The current implementation incurs significant cost when many features are deployed. …
> [DEV-1938] Disable tile monitoring by default

- .changelog/DEV-1943.yaml
- featurebyte/api/item_view.py
- featurebyte/query_graph/graph.py
- featurebyte/query_graph/node/generic.py
- featurebyte/query_graph/node/metadata/operation.py
- tests/integration/api/test_scd_view_operations.py
- tests/unit/api/test_feature_store.py
- tests/unit/api/test_scd_view.py
- tests/unit/conftest.py
- tests/unit/query_graph/test_extract_operation_structure.py
- tests/unit/query_graph/test_graph_pruning.py
- tests/unit/query_graph/test_metadata_operation.py
- tests/unit/session/test_snowflake_session.py
This PR aims to fix the bug when the feature is created with multiple SCD join. Due to the bug in `JoinNode`, wrong operation structure extraction causes improper graph pruning. This causes invalid graph is constructed after the graph is pruned. …
> [DEV-1943] Fix `JoinNode` operation structure extraction bug

- .changelog/DEV-1845.yaml
- featurebyte/models/feature.py
- featurebyte/query_graph/sql/online_store_compute_query.py
- featurebyte/service/feature_manager.py
- tests/integration/conftest.py
- tests/integration/feature_manager/test_feature_manager.py
- tests/unit/api/test_feature.py
- tests/unit/models/test_feature.py
- tests/unit/query_graph/test_online_serving.py
This fixes an issue where `OnlineStoreComputeQuery` can sometimes be prematurely deleted when still in use by other features. The `FeatureModel` is updated to keep track of the list of `aggregation_result_names` associated with the feature. …
> [DEV-1845] Fix OnlineStoreComputeQuery prematurely deleted when still in use by other features

- .changelog/DEV-1946.yaml
- featurebyte/models/feature.py
- featurebyte/query_graph/sql/online_store_compute_query.py
- featurebyte/service/feature.py
- featurebyte/service/namespace_handler.py
- tests/unit/models/test_feature.py
- tests/unit/query_graph/test_online_serving.py
- tests/unit/routes/test_feature.py
This updates the logic in `FeatureService.prepare_feature_model()` and `NamespaceHandler.prepare_graph_to_store()` to ensure that FeatureModel's derived attributes are derived from a fully pruned graph. 
| …
> [DEV-1946] Ensure FeatureModel's derived attributes are derived from pruned graph

- Taskfile.yaml
Add --ignore-vuln PYSEC-2023-112 temporarily to unblock publish workflow.
> [chore] Add --ignore-vuln PYSEC-2023-112 temporarily

- .changelog/DEV-1954.yaml
- featurebyte/service/feature_manager.py
This fixes an error when disabling features created before OnlineStoreComputeQueryService is introduced.
> [DEV-1964] Fix error when disabling features created before OnlineStoreComputeQueryService

- .changelog/DEV-1959.yaml
- featurebyte/query_graph/sql/adapter/base.py
- tests/unit/api/test_event_view.py
- tests/unit/api/test_source_table.py
- tests/unit/query_graph/test_adapter.py
This fixes an error that occurs when creating observation table using a very small sample percentage. When the sample percentage is formatted using scientific notation, it causes a syntax error in Spark.
| …
> [DEV-1959] Fix TABLESAMPLE syntax error in Spark for very small sample percentage

- .changelog/DEV-1914.yaml
- featurebyte/routes/registry.py
- featurebyte/schema/common/feature_or_target.py
- featurebyte/schema/feature_list.py
- featurebyte/schema/target.py
- featurebyte/service/historical_features.py
- featurebyte/service/target.py
- featurebyte/service/target_helper/base_feature_or_target_computer.py
- featurebyte/service/target_helper/compute_target.py
- featurebyte/worker/task/historical_feature_table.py
- featurebyte/worker/task/target_table.py
- tests/unit/service/test_historical_features.py
Refactor some of the common logic used between `compute_target` and `compute_historical_features`.
Also moves the `compute_target` function out of the target document service.
https://featurebyte.atlassian.net/browse/DEV-1914 …
> [DEV-1914] service/target: refactor compute target and compute historical features

- featurebyte/common/documentation/documentation_layout.py
Small refactor to move some common used doc items to a helper function for reuse and consistency.
> [chore] documentation_layout: refactor some commonly used types

- featurebyte/routes/feature_store/api.py
- featurebyte/routes/feature_store/controller.py
- featurebyte/service/session_manager.py
- featurebyte/service/session_validator.py
We can simplify the get_credential logic during feature store creation, as we no longer look at the config for credentials. Instead, everything is passed in during the method call to create feature store, and we persist the credentials into mongo.
One longer term benefit of this, is that we can reduce the passing around of `get_credential`s through a lot of function calls, as the credentials should now always be accessible via the `MongoBackedCredentialProvider`. This is the first set of changes, as it is the most logically substantive one. Will follow-up with a few more PRs to remove further uses of `get_credential` if this looks good. …
> [chore] simplify logic around get_credentials during feature store creation

- .changelog/DEV-1967.yaml
- featurebyte/migration/model.py
- featurebyte/models/base.py
- featurebyte/models/online_store_compute_query.py
- featurebyte/models/online_store_table_version.py
- featurebyte/models/tile_registry.py
- featurebyte/persistent/audit.py
- featurebyte/persistent/base.py
- featurebyte/service/base_document.py
- tests/unit/persistent/test_mongo.py
- tests/unit/service/test_base_document.py
This adds the option to disable audit logging for internally used documents. Audit logging incurs non-trivial runtime cost and can cause write conflict errors for concurrent operations so it should be disabled unless necessary. A few internally used collections are marked as non-auditable: `OnlineStoreTableVersion`, `OnlineStoreComputeQueryModel`, `TileModel`.
|       `build`, `ci`, `testing`        |    📦 Build System & …
> [DEV-1967] Add option to disable audit logging for internal documents

- .changelog/DEV-1973.yaml
- featurebyte/service/online_enable.py
This skips creating a data warehouse session when online disabling a feature because that is now unnecessary. This handles cases when the session cannot be created such as when the warehouse is not reachable. …
> [DEV-1973] Skip creating session when online disabling a feature

- tests/unit/api/test_target_table.py
- tests/unit/conftest.py
- tests/unit/test_generate_payload_fixtures.py
- tests/unit/worker/task/test_feature_job_setting_analysis.py
- tests/unit/worker/task/test_feature_job_setting_analysis_backtest.py
Pin object IDs to fixed ones so that all the json's don't get regenerated with new IDs everytime we run the task command to generate fixtures.
There are still a few more IDs that need to be pinned, but this should cover most of them for now. …
> [chore] test_generate_payload_fixtures: pin object IDs 

- .changelog/DEV-1976.yaml
- featurebyte/api/event_view.py
- tests/unit/api/test_event_view.py
- tests/unit/conftest.py
This fixes a bug in `add_feature()` where `entity_id` was incorrectly attached to the derived column. One consequence of the bug was that `add_feature()` errored the second time it's called on the same view when entity column is not specified. …
> [DEV-1976] Fix incorrect entity_id for columns derived from add_feature()

- .changelog/DEV-1976.yaml
- featurebyte/api/event_view.py
- tests/unit/api/test_event_view.py
- tests/unit/conftest.py
Cherry pick #1562 to release/0.4.
This fixes a bug in add_feature() where entity_id was incorrectly attached to the derived column. One consequence of the bug was that add_feature() errored the second time it's called on the same view when entity column is not specified.
| …
> [0.4][DEV-1976] Fix incorrect entity_id for columns derived from add_feature() (#1562)

- .changelog/DEV-1974.yaml
- featurebyte/service/feature_manager.py
- featurebyte/service/online_enable.py
- tests/integration/feature_manager/test_feature_manager.py
- tests/unit/feature_manager/test_unit_snowflake_feature.py
This updates the logic when online disabling a feature to drop the associated online store table(s) when no longer needed.
> [DEV-1974] Drop online store table when no longer needed

- .changelog/DEV-1987.yaml
- featurebyte/query_graph/sql/online_serving.py
- tests/integration/query_graph/test_online_serving.py
- tests/unit/routes/test_deployment.py
- tests/unit/service/test_online_serving.py
This ensures that the row ordering of online serving output DataFrame is the same as the input data.
> [DEV-1987] Fix online serving output row ordering

- .changelog/DEV-1849.yaml
- featurebyte/api/feature.py
- tests/unit/api/test_feature.py
The `row_index_lineage` alignment check is applicable to Columns but not Features. Features are joined into a common table and can freely interact with each other regardless of the lineage.
This overrides the `row_index_lineage` property for Feature class as a way to bypass the alignment checks. By doing this, we can support things like conditionally updating a feature using a mask derived from other features.
| …
> [DEV-1849] Support conditionally updating a feature using a mask derived from other feature(s)

- featurebyte/models/tile_job_log.py
- featurebyte/service/tile/tile_task_executor.py
- tests/integration/tile/test_schedule_generate_tile.py
This adds a new field `duration` to track the runtime of different steps that occur in scheduled tile tasks to facilitate troubleshooting and testing. …
> [chore] Track duration in tile job log collection

- featurebyte/common/documentation/autodoc_processor.py
There are currently some broken links in the documentation pages that will go to a 404.
Eg. https://docs.featurebyte.com/0.3/reference/featurebyte.Feature.cd.unique_count/ - clicking on the method name will go to a 404.
These links don't seem particularly useful since it should just point to the current page they're on. These were probably previously added when we had some main pages that displayed all the methods for a class. We don't have those pages anymore, so these links should not be needed.
|       `enhancement`, `feature`        |          🚀 Features …
> [chore] docs: rm links from method names

- featurebyte/routes/common/base_table.py
- featurebyte/schema/table.py
- tests/unit/routes/base.py
Fix the change in https://github.com/featurebyte/featurebyte/pull/1586 that breaks backward compatibility with older python clients.
The option to update column info from the column update route is deprecated and will be removed in the next major release (0.5.0)
https://featurebyte.atlassian.net/browse/DEV-1985
https://featurebyte.atlassian.net/browse/DEV-2000
|       `build`, `ci`, `testing`        |    📦 Build System & …
> [DEV-1985] make table update service backward compatible to earlier clients

- .changelog/DEV-2026.yaml
- featurebyte/query_graph/model/table.py
- featurebyte/query_graph/node/generic.py
- tests/fixtures/sdk_code/complex_event_item_feature.py
- tests/fixtures/sdk_code/feature_fraction.py
- tests/fixtures/sdk_code/feature_item_cosine_similarity.py
- tests/unit/api/test_item_view.py
- tests/unit/api/test_timezone_offset.py
This changes the join type to "inner" when joining event and item tables. The result is equivalent since the join key should always match between such tables. This allows an upcoming change to apply date range filter on event table at the lowest level in scheduled tile job.
| …
> [DEV-2026] User inner join when joining event and item tables

- .changelog/ISSUES-1598.yaml
- featurebyte/common/env_util.py
In Colab get_ipython().__class__.__name__ returns just "Shell" instead of "ZMQInteractiveShell" like other Notebook evnironments do. So handle both cases since we are already guarded against not being in a notebook with the name exception. …
> [ISSUES-1598] Update is_notebook to support Google Colab and Databricks

- .changelog/DEV-2024.yaml
- featurebyte/api/aggregator/base_aggregator.py
- featurebyte/api/aggregator/forward_aggregator.py
- featurebyte/api/feature.py
- featurebyte/api/feature_or_target_mixin.py
- tests/unit/api/aggregator/test_forward_aggregator.py
- tests/unit/api/test_groupby.py
Currently, if you fill_value on a forward_aggregate, the target name is lost. I wrongly assumed that we didn't need to also update the name, but have come to realize that the last node needs to be a project or alias for the computation to pick up the name correctly.
We can reuse the logic w/ feature to keep this consistent. …
> [DEV-2024] target: fix fill_value by also updating name

- .changelog/DEV-2026-2.yaml
- featurebyte/models/user_defined_function.py
- featurebyte/query_graph/sql/ast/base.py
- featurebyte/query_graph/sql/ast/input.py
- featurebyte/query_graph/sql/ast/join_feature.py
- featurebyte/query_graph/sql/builder.py
- featurebyte/query_graph/sql/interpreter/tile.py
- featurebyte/query_graph/sql/specs.py
- tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
- tests/fixtures/expected_tile_sql_feature_with_lag.sql
- tests/fixtures/expected_tile_sql_feature_without_lag.sql
- tests/integration/api/test_event_view_operations.py
- tests/unit/conftest.py
- tests/unit/feature_manager/test_model.py
- tests/unit/query_graph/sql/test_tile.py
- tests/unit/query_graph/test_sql.py
This adds a filter on EventTable directly based on tile date range when possible. This is safe to do when there is no lag operations in the applied transforms. This mainly benefits the cases where a feature involves complex joins and the existing top level filter cannot be pushed down automatically. 
In testing, the speedup for the tile building query ranges from 1x (simple features based on EventTable only that won't benefit from this change) to more than 6x (features involving Event-Item-SCD joins + double aggregation; 2m 14s before vs 21s after).
| …
> [DEV-2026] Filter EventTable by tile date range directly when possible

- .changelog/DEV-2031.yaml
- featurebyte/query_graph/transform/base.py
Speed up operation structure extraction by caching the result of `_extract()` in `BaseGraphExtractor`.
Timing comparison using the problematic SDK code: 1m 27s (before) vs 2s (after).
| …
> [DEV-2031] Speed up operation structure extraction by caching the result of _extract()

- .changelog/DEV-2031.yaml
- featurebyte/query_graph/transform/base.py
Cherry pick #1610 to release/0.4.
Speed up operation structure extraction by caching the result of _extract() in BaseGraphExtractor.
Timing comparison using the problematic SDK code: 1m 27s (before) vs 2s (after). …
> [0.4][DEV-2031] Speed up operation structure extraction by caching the result of _extract()

- Taskfile.yaml
- tests/integration/api/test_online_enable.py
- tests/integration/session/test_thread_safety.py
The test suite hangs on teardown of the app fixture:
```
...
File "/home/runner/work/featurebyte/featurebyte/.venv/lib/python3.8/site-packages/pytest_asyncio/plugin.py", line 291, in finalizer
event_loop.run_until_complete(async_finalizer())
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
self.run_forever()
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
self._run_once()
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
handle._run()
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File …
```
> [chore] Fix hanging snowflake integration test

- .changelog/ISSUES-1598.yaml
- featurebyte/common/env_util.py
…ks (#1599)
* Update is_notebook to support Google Colab
In Colab get_ipython().__class__.__name__ returns just "Shell" instead of "ZMQInteractiveShell" like other Notebook evnironments do. So handle both cases since we are already guarded against not being in a notebook with the name exception.
* Fix linter failures
* Also add special case for Databricks
|       `build`, `ci`, `testing`        |    📦 Build System & …
> [ISSUES-1598] Cherrypick is_notebook fix to release/0.4

- notebooks/prebuilt_catalogs.py
Use the right method on the catalog to retrieve a table if it already exists.
> [chore] prebuilt_catalogs: use get_table instead of get_source_table

- featurebyte/worker/task/base.py
- tests/unit/worker/test_task_executor.py
Allow task commands to be overridden with a warning to make library more extensible 
> [chore] Allow task commands to be overridden

- .changelog/DEV-2048.yaml
- featurebyte/query_graph/sql/ast/aggregate.py
- featurebyte/query_graph/sql/ast/base.py
- featurebyte/query_graph/sql/ast/generic.py
- tests/integration/api/test_item_view_operations.py
- tests/unit/api/test_dimension_view.py
- tests/unit/query_graph/sql/ast/test_special_operations.py
- tests/unit/query_graph/test_sql.py
This fixes an error in feature materialisation due to ambiguous internal column names. Previously, the internal column names generated were not sufficiently unique as operations such as filtering were not accounted for. …
> [DEV-2048] Fix feature materialisation error due to ambiguous internal column names

- .changelog/DEV-2044.yaml
- featurebyte/models/feature.py
- featurebyte/routes/common/feature_metadata_extractor.py
- featurebyte/routes/feature/controller.py
- featurebyte/routes/target/controller.py
- tests/unit/api/conftest.py
- tests/unit/api/test_scd_view.py
Backport #1630 to release/0.4.
This fixes an error when generating info for features in some edge cases caused by the behaviour of the keep_all_source_columns flag. This is a workaround that prevents the error and will be cleaned up later. …
> [0.4][DEV-2044] Fix error when retrieving feature info for some features

- .changelog/DEV-2048.yaml
- featurebyte/query_graph/sql/ast/aggregate.py
- featurebyte/query_graph/sql/ast/base.py
- featurebyte/query_graph/sql/ast/generic.py
- tests/integration/api/test_item_view_operations.py
- tests/unit/api/test_dimension_view.py
- tests/unit/query_graph/sql/ast/test_special_operations.py
- tests/unit/query_graph/test_sql.py
Cherry pick #1635 to release/0.4.
This fixes an error in feature materialisation due to ambiguous internal column names. Previously, the internal column names generated were not sufficiently unique as operations such as filtering were not accounted for.
| …
> [0.4][DEV-2048] Fix feature materialisation error due to ambiguous internal column names

- .changelog/DEV-2063.yaml
- hive-udf/lib/src/main/java/com/featurebyte/hive/udf/BaseVectorAggregate.java
- hive-udf/lib/src/main/java/com/featurebyte/hive/udf/VectorAggregateMax.java
- hive-udf/lib/src/main/java/com/featurebyte/hive/udf/VectorAggregateSum.java
- hive-udf/lib/src/test/java/com/featurebyte/hive/udf/BaseVectorAggregateListTest.java
- hive-udf/lib/src/test/java/com/featurebyte/hive/udf/VectorAggregateMaxTest.java
- hive-udf/lib/src/test/java/com/featurebyte/hive/udf/VectorAggregateSumTest.java
Add two UDAFs - max and sum - for use in the vector aggregation. We will add the UDAF for average in a follow-up PR.
We will also register these UDAFs for use with the SDK in a separate PR.
https://featurebyte.atlassian.net/browse/DEV-2063
https://featurebyte.atlassian.net/browse/DEV-2064 …
> [DEV-2063][DEV-2064] hive/udf: add vector aggregate max and sum

- .changelog/DEV-2065.yaml
- hive-udf/lib/src/main/java/com/featurebyte/hive/udf/VectorAggregateAverage.java
- hive-udf/lib/src/test/java/com/featurebyte/hive/udf/VectorAggregateAverageTest.java
Add average java UDAF for spark. The input here is assumed to be two columns:
- one column which represents the sum list (which will be calculated via the sum UDAF which was added previously), and
- one column which represents the count (number of vectors that we summed over)
https://featurebyte.atlassian.net/browse/DEV-2065
| …
> [DEV-2065] hive/udf: add vector aggregate average udf

- .changelog/DEV-2067.yaml
- featurebyte/query_graph/sql/adapter/databricks.py
- featurebyte/query_graph/sql/adapter/snowflake.py
- featurebyte/query_graph/sql/ast/aggregate.py
- featurebyte/query_graph/sql/ast/tile.py
- featurebyte/query_graph/sql/query_graph_util.py
- featurebyte/query_graph/sql/specifications/lookup.py
- featurebyte/query_graph/sql/specifications/lookup_target.py
- featurebyte/query_graph/sql/specs.py
- featurebyte/query_graph/sql/tiling.py
- featurebyte/session/base_spark.py
- tests/unit/query_graph/sql/test_query_graph_util.py
- tests/unit/query_graph/test_adapter.py
- tests/unit/query_graph/test_tiling.py
This PR makes a few changes
- registers the `VECTOR_AGGREGATE_MAX` and `VECTOR_AGGREGATE_AVG` udaf for spark
- passes `parent_dtype` into the `get_aggregator` function so that we can pick up the correct aggregator depending on the parents dtype
- updates `construct_specs` to take in a graph as a parameter too
- registers datatypes for arrays in snowflake and spark
This PR doesn't yet include the changes to the `groupby_helper`. That will be done in a follow-up.
https://featurebyte.atlassian.net/browse/DEV-2067
https://featurebyte.atlassian.net/browse/DEV-2073
https://featurebyte.atlassian.net/browse/DEV-2080
https://featurebyte.atlassian.net/browse/DEV-2081
|        **Pull Request Label**         | **Category …
> [DEV-2067] vector_aggregate: register new UDAF; pass parent_dtype around; update construct specs

- .changelog/DEV-2082.yaml
- hive-udf/lib/src/main/java/com/featurebyte/hive/udf/VectorAggregateSimpleAverage.java
- hive-udf/lib/src/test/java/com/featurebyte/hive/udf/VectorAggregateSimpleAverageTest.java
Add simple average spark UDAF. This will be used for simple / non-tiling aggregates in groupby functions.
https://featurebyte.atlassian.net/browse/DEV-2082 …
> [DEV-2082] hive/udf: add simple average spark udaf

- .changelog/DEV-2051.yaml
- featurebyte/api/item_table.py
- featurebyte/schema/historical_feature_table.py
Make item table default job setting a property so it can be synchronized frequently from the event table.
https://featurebyte.atlassian.net/browse/DEV-2051 …
> [DEV-2051][DEV-2079] Fix item table default job setting not synchronized with event table

- featurebyte/api/source_table.py
> [chore] source_table: fix typo in create_scd_table docs

- .changelog/DEV-2129.yaml
- featurebyte/models/periodic_task.py
- tests/unit/models/test_periodic_task.py
The celery beat scheduler already indexes this column.
Remove redundant mongodb index on periodic task name to avoid conflict.
https://featurebyte.atlassian.net/browse/DEV-2129 …
> [DEV-2129] Remove mongodb index on periodic task name 

- .changelog/DEV-2051.yaml
- featurebyte/api/item_table.py
- featurebyte/schema/historical_feature_table.py
Fix item table default job setting not synchronized with event table (#1649)
Cherry-pick from https://github.com/featurebyte/featurebyte/pull/1649
* make item table default job setting a property so it can be synchronized frequently from the event table
* update changelog
| …
> [DEV-2051]Fix item table default job setting not synchronized (release 0.4)

- .changelog/DEV-2134.yaml
- featurebyte/worker/__init__.py
- tests/unit/worker/test_worker.py
Ensure mongo uri is compatible with celery beat scheduler
https://featurebyte.atlassian.net/browse/DEV-2134
> [DEV-2134] Some mongdb URI does not work well with scheduler

- featurebyte/service/base_document.py
- tests/unit/service/test_base_document.py
Support case insensitive substring search on asset names
https://featurebyte.atlassian.net/browse/DEV-2137
> [DEV-2137] Support case insensitive substring search on asset names

- .changelog/DEV-2140.yaml
- featurebyte/core/accessor/datetime.py
- tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
- tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
- tests/fixtures/sdk_code/scd_table.py
- tests/unit/api/test_change_view.py
- tests/unit/api/test_scd_table.py
- tests/unit/api/test_scd_view.py
- tests/unit/api/test_timezone_offset.py
- tests/unit/conftest.py
This fixes a bug where timezone offset column was incorrectly identified in the datetime accessor.
Fixes errors such as :
> RecordRetrievalException: 100132 (P0000): JavaScript execution error: Uncaught Error: Invalid timezone offset format: 36 in F_TIMEZONE_OFFSET_TO_SECOND at '    throw new Error("Invalid timezone offset format: " + OFFSET_STRING);' position 4
stackstrace: 
F_TIMEZONE_OFFSET_TO_SECOND line: 10
| …
> [DEV-2140] Fix logic for determining timezone offset column in datetime accessor

- featurebyte/query_graph/sql/aggregator/asat.py
- featurebyte/query_graph/sql/aggregator/forward.py
- featurebyte/query_graph/sql/aggregator/item.py
- featurebyte/query_graph/sql/ast/groupby.py
- featurebyte/query_graph/sql/groupby_helper.py
- tests/unit/query_graph/sql/test_groupby_helper.py
Small refactor to mv `parent_dtype` into `GroupbyColumn`. This removes the assumption that all the input columns have the same `parent_dtype` which was invalid. …
> [chore] aggregators: mv parent_dtype into GroupbyColumn

- .changelog/DEV-2165.yaml
- featurebyte/sql/tile_schedule_online_store.py
This ensures that columns are casted to the expected type when creating online store tables. This is to prevent the default type being too restrictive and causing subsequent insert statements to fail when they produce data that doesn't fit within the initial schema.
| …
> [DEV-2165] Cast online store columns to expected types when creating tables

- .changelog/DEV-2169.yaml
- featurebyte/query_graph/sql/interpreter/tile.py
- tests/fixtures/graph/PRODUCT_vs_PRODUCTGROUP_item_TotalCost_across_customer_PostalCodes_28d.json
- tests/unit/query_graph/interpreter/test_interpreter.py
This PR aims to fix tile SQL generation bug due to wrong query graph is used to construction operation structure.
> [DEV-2169] Fix feature saving issue due to tile sql generation bug

- .changelog/DEV-2173.yaml
- featurebyte/sql/common.py
- featurebyte/sql/tile_schedule_online_store.py
- tests/unit/conftest.py
- tests/unit/feature_manager/test_unit_snowflake_feature.py
- tests/unit/sql/test_common.py
This splits the online store compute and insert query into multiple statements to minimise table locking. It the issue persists, this allows us to retry the insert without having to recompute the results. …
> [DEV-2173] Split online store compute and insert query into multiple statements

- featurebyte/__init__.py
- featurebyte/common/documentation/documentation_layout.py
- featurebyte/common/documentation/gen_ref_pages_docs_builder.py
- featurebyte/list_utility.py
Add the `fb.list_deployments` function into docs. We move the method out of the `__init__.py` file as it's not possible for our docs scraper to pick up docstrings from that file. 
https://featurebyte.atlassian.net/browse/DEV-2174 …
> [DEV-2174][chore] docs: add list_deployment docs

- .changelog/DEV-2083.yaml
- .changelog/DEV-2177.yaml
- featurebyte/common/utils.py
- featurebyte/query_graph/sql/groupby_helper.py
- featurebyte/session/snowflake.py
- featurebyte/sql/snowflake/F_VECTOR_AGGREGATE_SIMPLE_AVERAGE.sql
- tests/integration/api/test_vector_aggregation_operations.py
- tests/integration/udf/test_vector_aggregate.py
- tests/unit/query_graph/sql/test_groupby_helper.py
- tests/unit/session/test_snowflake_session.py
Update the snowflake session handler to do some post processing if we see some snowflake data that contains an array column. The current default handler just returns the array as a string. As such, we convert the type to a list in the resultant dataframe.
Also update some of the average UDTFs in preparation for work to be done with the tiling aggregates.
https://featurebyte.atlassian.net/browse/DEV-2177
https://featurebyte.atlassian.net/browse/DEV-2083
| `bug`, `refactoring`, `bugfix`, `fix` …
> [DEV-2177] vector_agg/snowflake: return vector values should be of list type instead of str

- featurebyte/query_graph/sql/groupby_helper.py
- tests/unit/query_graph/sql/adapter/test_snowflake.py
- tests/unit/query_graph/sql/fixtures/snowflake_double_vector_agg_only.py
- tests/unit/query_graph/sql/fixtures/snowflake_double_vector_agg_only_no_value_by.py
- tests/unit/query_graph/sql/fixtures/snowflake_vector_agg_with_normal_agg.py
- tests/unit/query_graph/sql/test_groupby_helper.py
Make a small change here to remove quotes around the aggregated value alias. This is to keep the aliases consistent with table tile names.
Will be using this change as part of the work to get vector_aggs for tiling aggregates, but decided to split it out to make sure that there're no regressions w/ other aggregations that have already been implemented, and are covered by existing integration tests.
|       `build`, `ci`, …
> [chore] groupby_helper: rm quotes around alias to keep consistent w/ tiles

- .changelog/chore-python-constraint.yaml
- .changelog/chore-vuln.yaml
- .github/workflows/publish-dev_gen.yaml
- Taskfile.yaml
- poetry.lock
- pyproject.toml
scipy upgrade requires either [3.8,3.12) or [3.9,3.13). Choosing the former as the version constraint.
> [chore] updated scipy dependency, reduced python valid range to >=3.8,<3.12

- featurebyte/query_graph/sql/adapter/base.py
- featurebyte/query_graph/sql/aggregator/window.py
- featurebyte/query_graph/sql/ast/tile.py
- featurebyte/query_graph/sql/groupby_helper.py
Small refactor to use adapter for groupby queries in tile and window operations. Making a bunch of small changes in this final stretch to make sure I don't break anything.
Also make a small refactor to retrieving the sql_func for vector aggregations as we'll be adding some logic there in a subsequent PR.
https://featurebyte.atlassian.net/browse/DEV-2167
|       `build`, `ci`, `testing`        |    📦 Build System & CI/CD …
> [chore] tile/window: refactor to use adapter for groupby

- .changelog/DEV-2207.yaml
- featurebyte/query_graph/sql/ast/base.py
- tests/integration/api/test_features.py
Fixes an invalid identifier error in sql when feature involves a mix of filtered and non-filtered versions of the same view.
Related to https://github.com/featurebyte/featurebyte/pull/1635.
| …
> [DEV-2207] Fix invalid sql generation in some cases when using filtered views

- featurebyte/worker/task/batch_feature_create.py
- tests/unit/worker/task/test_batch_feature_create.py
Fix batch feature create task description showing wrong feature count.
> [chore] Fix batch feature create task description

- featurebyte/session/hive.py
Hive connection not provided correct database parameter. 
It works well when spark_catalog is the default catalog but breaks otherwise. …
> [chore] Fx hive connection for service where spark is not default catalog

- featurebyte/query_graph/sql/adapter/snowflake.py
- tests/unit/query_graph/sql/adapter/base_adapter_test.py
- tests/unit/query_graph/sql/adapter/test_snowflake.py
In scenarios where the keys passed in are just identifiers, and not expressions, we can use the `identifiers.quoted` parameter to determine if we should quote the aliases. This will allow us to be more consistent with the callers. 
This was reported by viktor where we had this query
```
merge into TILE_F86400_M79811_B600_88B38744550A87992403BB95438F70F83CBB3064 a using (
select
index,
"EmployeeId", value_max_b261e7ab1fdf1754f7bfcbd9584c6490b13b8077,
current_timestamp() as created_at
from (SELECT
VECTOR_T0."index" AS index,
VECTOR_T0."EmployeeId" AS EmployeeId,
VECTOR_T0."value_max_b261e7ab1fdf1754f7bfcbd9584c6490b13b8077" AS value_max_b261e7ab1fdf1754f7bfcbd9584c6490b13b8077
FROM (
SELECT
INITIAL_DATA."index" AS "index",
INITIAL_DATA."EmployeeId" AS "EmployeeId",
AGG_0."VECTOR_AGG_RESULT" …
```
> [chore] adapter/snowflake: respect quotes from identifer passed in

- featurebyte/session/hive.py
Make spark connection for non-default catalog work when featurebyte schema does not exist
> [chore] Fix spark connection for non-default catalog

- featurebyte/models/task.py
- featurebyte/schema/worker/task/base.py
- featurebyte/service/task_manager.py
- tests/unit/models/test_index.py
- tests/unit/service/test_task_manager.py
- tests/unit/worker/test_task_executor.py
Track scheduled tasks by injecting a field into the payload to identify tasks that are triggered by scheduler.
> [chore] Track scheduled tasks

- featurebyte/models/observation_table.py
Change to return none instead of throwing an error so that this is truly no-op.
> [chore] observation_table: change TargetInput to return None for no-op

- .changelog/DEV-2285.yaml
- featurebyte/query_graph/sql/interpreter/preview.py
- featurebyte/schema/feature_store.py
- featurebyte/service/preview.py
- tests/fixtures/expected_describe_request.sql
- tests/fixtures/query_graph/expected_describe_snowflake.sql
- tests/fixtures/query_graph/expected_describe_spark.sql
- tests/fixtures/query_graph/expected_describe_stats_names.sql
- tests/fixtures/query_graph/expected_value_counts.sql
- tests/unit/query_graph/interpreter/conftest.py
- tests/unit/query_graph/interpreter/test_preview.py
- tests/unit/service/conftest.py
- tests/unit/service/test_preview.py
This adds support for extracting value counts and customised statistics (a subset of the supported stats to reduce unneeded work) in PreviewService. This is mainly to support feature ideation work but it can also be exposed in the SDK later. …
> [DEV-2285] Support value counts and customised statistics in PreviewService

- .changelog/DEV-2293.yaml
- featurebyte/api/api_object.py
This fixes a race condition that arises when accessing cached values in ApiObject's `get_by_id()`.
Example error:
```
File "/opt/venv/lib/python3.8/site-packages/featurebyte/api/api_object.py", line 347, in get_by_id
return cls._get_by_id(id)
File "/opt/venv/lib/python3.8/site-packages/featurebyte/api/api_object.py", line 296, in _get_by_id
return cls.from_persistent_object_dict(cls._cache[key].dict(by_alias=True))
File "/opt/venv/lib/python3.8/site-packages/cachetools/__init__.py", line 416, in __getitem__
return self.__missing__(key)
File "/opt/venv/lib/python3.8/site-packages/cachetools/__init__.py", line 97, in __missing__
raise KeyError(key)
KeyError: ('entity', ObjectId('6507f3bea4e7c32abee8659b'))
``` …
> [DEV-2293] Fix race condition when accessing cache in ApiObject's get_by_id()

- featurebyte/app.py
- featurebyte/routes/base_router.py
- featurebyte/routes/catalog/api.py
- featurebyte/routes/catalog/controller.py
- featurebyte/routes/common/base.py
- featurebyte/routes/context/api.py
- featurebyte/routes/context/controller.py
- featurebyte/routes/credential/api.py
- featurebyte/routes/credential/controller.py
Refactor the common CRUD operations into a `BaseApiRouter` so that in the future, we can easily create a whole suite of basic API routes without having too many overrides, and duplicated code.
Similar to this PR in featurebyte-app - https://github.com/featurebyte/featurebyte-app/pull/627 …
> [chore] routes: refactor API routes into a BaseRouter

- .changelog/DEV-2254.yaml
- featurebyte/api/item_table.py
- featurebyte/api/view.py
- featurebyte/common/join_utils.py
- featurebyte/query_graph/model/table.py
- featurebyte/query_graph/node/generic.py
- tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
- tests/fixtures/sdk_code/event_view_with_tz_offset_column.py
- tests/unit/api/test_join_utils.py
- tests/unit/api/test_scd_view.py
- tests/unit/api/test_view.py
- tests/unit/query_graph/test_graph_pruning.py
This adds a `rprefix` parameter to the `join()` method for views. It behaves similarly as `rsuffix` but modifies the right columns by adding a prefix.
https://featurebyte.atlassian.net/browse/DEV-2254
| …
> [DEV-2254] Support rprefix parameter when joining views

- featurebyte/routes/deployment/api.py
- featurebyte/routes/deployment/controller.py
- featurebyte/service/deploy.py
- featurebyte/service/online_enable.py
- featurebyte/service/online_serving.py
- featurebyte/worker/task/batch_feature_table.py
- featurebyte/worker/task/deployment_create_update.py
- tests/unit/service/conftest.py
- tests/unit/service/test_deploy.py
- tests/unit/service/test_feature_list_status.py
- tests/unit/service/test_online_serving.py
Remove the unused `get_credential` param as we now read the credential from the mongo backed credential provider.
> [chore] deployment: rm unused get_credential param

- featurebyte/sql/tile_generate_entity_tracking.py
- tests/integration/tile/test_tile_cache.py
This avoids adding columns such as `__FB_ENTITY_TABLE_END_DATE` and `__FB_ENTITY_TABLE_START_DATE` to the entity tracking tables. It's not required to persist these columns and they are actually never updated after table creation. …
> [chore] Remove unnecessary columns from entity tracking tables

- featurebyte/app.py
- featurebyte/routes/feature_store/api.py
- featurebyte/routes/feature_store/controller.py
- featurebyte/service/feature_store_warehouse.py
- featurebyte/worker/task/base.py
- featurebyte/worker/task/mixin.py
- featurebyte/worker/task_executor.py
- tests/integration/api/test_feature_store_operations.py
- tests/integration/conftest.py
- tests/unit/api/test_feature_list.py
- tests/unit/conftest.py
- tests/unit/worker/task/base.py
- tests/unit/worker/task/test_batch_feature_create.py
- tests/unit/worker/task/test_batch_feature_table.py
- tests/unit/worker/task/test_batch_request_table.py
- tests/unit/worker/task/test_deployment_create_update.py
- tests/unit/worker/task/test_feature_job_setting_analysis.py
- tests/unit/worker/task/test_feature_job_setting_analysis_backtest.py
- tests/unit/worker/task/test_feature_list_batch_feature_create.py
- tests/unit/worker/task/test_historical_feature_table.py
- tests/unit/worker/task/test_materialized_table_delete.py
- tests/unit/worker/task/test_observation_table.py
- tests/unit/worker/task/test_online_store_cleanup.py
- tests/unit/worker/task/test_static_source_table.py
- tests/unit/worker/task/test_target_table.py
- tests/unit/worker/task/test_tile_task.py
- tests/unit/worker/test_task_executor.py
Fully cleanup and remove `get_credential` from tasks since they aren't needed directly.
After this PR, we should mostly only see `get_credential` appear in the code paths that are close to where it's used. For example, this would be in areas where we are trying to get a session (eg. `SessionManagerService`), or trying to use the credential to create a feature store and we use the credential to test the connection to the feature store.
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & …
> [chore] get_credential: rm from task, and request.state

- .changelog/DEV-2326.yaml
- featurebyte/api/target.py
- featurebyte/api/target_namespace.py
- tests/unit/api/test_target.py
This change keeps `Target#list` similar to `Feature#list` in which the class method version of list will list the namespace. For targets, this will also include targets that have not been created via an aggregation. …
> [DEV-2326] target: list should include namespace items

- featurebyte/routes/lazy_app_container.py
- featurebyte/routes/registry.py
- tests/unit/routes/test_lazy_app_container.py
This PR demonstrates how we can now register the `MongoDBImpl` class as `persistent`, similar to how we register other classes. We can't remove this parameter entirely from the construction of the `LazyAppContainer` as it's widely used. We can slowly clean up the callers in follow-ups! …
> [chore] app/registry: register persistent directly and make optional

- .changelog/DEV-2364.yaml
- featurebyte/api/target.py
- featurebyte/query_graph/graph.py
- tests/unit/api/test_target.py
We have the window stored in the `TargetNamespace` now, so we can clean up this todo and use the window from there.
> [DEV-2364] api/target: use window from namespace instead 

- .changelog/DEV-2318.yaml
- featurebyte/api/source_table.py
- featurebyte/api/target.py
- featurebyte/api/view.py
- featurebyte/schema/observation_table.py
- featurebyte/schema/target_table.py
- featurebyte/service/observation_table.py
- featurebyte/worker/task/observation_table.py
- featurebyte/worker/task/target_table.py
- tests/integration/api/test_event_view_operations.py
- tests/integration/api/test_observation_table.py
Add validation into the observation_table creation path to ensure that entities are present when creating the observation table. 
> [DEV-2318] observation_table: validate entities are present on creation

- featurebyte/api/base_table.py
- featurebyte/api/batch_feature_table.py
- featurebyte/api/batch_request_table.py
- featurebyte/api/historical_feature_table.py
- featurebyte/api/materialized_table.py
- featurebyte/api/observation_table.py
- featurebyte/api/source_table.py
- featurebyte/api/static_source_table.py
- featurebyte/api/view.py
- featurebyte/core/mixin.py
Upper docstring to indicate upper bound of 10k rows in sample.
https://featurebyte.atlassian.net/browse/DEV-2365
> [chore][DEV-2365] sample: update docs to indicate upper bound of 10k rows

- featurebyte/common/documentation/documentation_layout.py
Move table#catalog_id to be under the `Table` > `Lineage` section instead.
https://featurebyte.atlassian.net/browse/DEV-1502
> [chore][DEV-1502] docs: mv table#catalog_id to table>lineage

- .changelog/DEV-2393.yaml
- featurebyte/models/observation_table.py
- featurebyte/schema/observation_table.py
- featurebyte/worker/task/observation_table.py
- tests/fixtures/request_payloads/observation_table.json
- tests/unit/routes/test_observation_table.py
Add another field into the `ObservationTable` model to keep track of the purpose of the table.
This will be used when creating observation tables from the UI.
https://featurebyte.atlassian.net/browse/DEV-2393 …
> [DEV-2393] observation_table: add purpose into model

- .changelog/DEV-2398.yaml
- featurebyte/api/view.py
- tests/unit/api/test_view.py
This fixes a bug where the join validation logic did not account for rprefix and incorrectly led to RepeatedColumnNamesError.
> [DEV-2383] Fix join validation logic to account for rprefix

- .changelog/DEV-2399.yaml
- featurebyte/models/observation_table.py
- featurebyte/query_graph/sql/materialisation.py
- featurebyte/service/observation_table.py
- featurebyte/worker/task/observation_table.py
- featurebyte/worker/task/target_table.py
- tests/integration/api/test_observation_table.py
- tests/unit/service/test_observation_table.py
Track the earliest point in time, and the unique entity counts for entities in the observation table.
https://featurebyte.atlassian.net/browse/DEV-2399 …
> [DEV-2399] observation_table: track earliest point in time and entity count

- featurebyte/query_graph/sql/materialisation.py
- featurebyte/service/observation_table.py
- tests/unit/service/test_observation_table.py
Replace the `point_in_time_stats` query to utilize the min and max stats query from the describe function.
> [chore] observation_table: combine stats into single query

- Taskfile.yaml
- featurebyte/query_graph/sql/interpreter/preview.py
- featurebyte/routes/deployment/api.py
- featurebyte/routes/deployment/controller.py
- featurebyte/schema/info.py
- featurebyte/service/online_serving.py
- poetry.lock
- pyproject.toml
- tests/integration/conftest.py
- tests/unit/api/test_deployment.py
- tests/unit/routes/test_deployment.py
Implement route to retrieve sample entity_serving_names for a deployment.
This can be used to support preview functionalities for deployments …
> [chore] Implement route to retrieve sample entity_serving_names for a deployment

- featurebyte/service/online_serving.py
- tests/unit/routes/test_deployment.py
Fix bug in sample_entity_serving_names route when request counts exceed unique values
> [chore] Fix sample_entity_serving_names request counts exceed unique values

- featurebyte/worker/registry.py
- featurebyte/worker/task/base.py
- featurebyte/worker/task_executor.py
- tests/integration/conftest.py
- tests/integration/worker/test_task_manager.py
- tests/unit/conftest.py
- tests/unit/worker/test_registry.py
- tests/unit/worker/test_task_executor.py
This PR refactors the dynamically built `TASK_MAP` to a statically defined `TASK_REGISTRY_MAP`. 
The statically defined option should be easier to read, and make it easier to trace through code. We can also remove some of the validation that logs out when tasks with duplicate payload commands are used. I've added a test that will fail if a developer adds a new task but doesn't register it in the registry.
Down the line, this should also allow us to simplify how tasks are initialized as well since we can remove the override of the special magic `__init_subclass__` method that was used to dynamically build the `TASK_MAP` previously. …
> [chore] task: refactor TASK_MAP to TASK_REGISTRY_MAP

- .changelog/DEV-2430.yaml
- featurebyte/api/view.py
- tests/unit/api/conftest.py
- tests/unit/api/test_scd_view.py
- tests/unit/api/test_view.py
- tests/unit/conftest.py
This updates the repeated columns validation logic to handle excluded columns during join. With this, we can for example join an event view with an SCD view where the event timestamp column and effective timestamp column have the same name. …
> [DEV-2430] Update repeated columns validation logic to handle excluded columns

- .changelog/DEV-2435_1.yaml
- featurebyte/exception.py
- featurebyte/models/observation_table.py
- featurebyte/routes/observation_table/controller.py
- featurebyte/schema/observation_table.py
- featurebyte/service/observation_table.py
- tests/unit/routes/test_observation_table.py
Part 1 of the requirement to enable observation table with multiple use cases. 
This PR implements the requirement from the endpoints …
> [DEV-2345] Enable ObservationTable with multiple use cases - Part 1

- featurebyte/routes/lazy_app_container.py
- featurebyte/worker/task_executor.py
- tests/integration/tile/test_tile_scheduler.py
- tests/unit/worker/test_task_executor.py
This PR passes the app container into the task executor, instead of initializing the app container inside the constructor.
This makes the code a bit easier to extend, and is a step to getting the task executor constructed via the container as well. Also also is one step closer in allowing the child implementation in featurebyte-app to call the parent constructor more easily as well. Overall, improves dependency injection and makes the code more soliD.
| `bug`, `refactoring`, `bugfix`, `fix` | …
> [chore] task_executor: pass app container into constructor

- featurebyte/routes/batch_feature_table/api.py
- featurebyte/routes/batch_request_table/api.py
- featurebyte/routes/common/base_materialized_table.py
- featurebyte/routes/historical_feature_table/api.py
- featurebyte/routes/observation_table/api.py
- featurebyte/routes/static_source_table/api.py
- featurebyte/routes/target_table/api.py
- tests/unit/routes/base.py
Add routes to download materialized tables as parquet files
> [chore] Add routes to download materialized tables as parquet files

- featurebyte/schema/observation_table.py
- featurebyte/worker/task/observation_table_upload.py
- tests/fixtures/request_payloads/observation_table.json
- tests/unit/routes/test_observation_table.py
- tests/unit/test_generate_payload_fixtures.py
- tests/unit/worker/task/test_observation_table.py
- tests/unit/worker/task/test_observation_table_upload.py
Use permanent table for uploaded observation tables so they persist after session is closed
> [chore] Use permanent table for uploaded observation tables

- featurebyte/api/feature.py
- featurebyte/api/lag.py
- featurebyte/common/doc_util.py
- featurebyte/core/accessor/count_dict.py
- featurebyte/core/accessor/datetime.py
- featurebyte/core/accessor/string.py
- featurebyte/core/series.py
- featurebyte/core/timedelta.py
- featurebyte/core/util.py
This removes the `unary_op_series_params` and `binary_op_series_params` methods in Series which are now unnecessary. Previously, these methods were used to collect the list of entity ids in Feature operations, but that information is now directly derived from the query graph.
Removing these methods improves performance because each call to Feature's `entity_ids` property incurs an API request, especially for unsaved objects. After this change such API requests during series operations should be eliminated.
|       `enhancement`, `feature`        |          🚀 …
> [chore] Remove unary_op_series_params and binary_op_series_params methods

- .changelog/DEV-2473.yaml
- featurebyte/service/observation_table.py
- tests/unit/service/test_observation_table.py
Bug fix to check if primary entities provided are present in file. 
the checks are currently independent, meaning that it checks if
- if the entity passed is in a primary entity, and
- there are entities in the file uploaded
but doesn't check that the entities passed in are the ones present.
This PR fixes that bug. …
> [DEV-2473] observation_table: check if entities provided are present in file

- featurebyte/models/observation_table.py
Sort the primary entity IDs when storing them in mongo.
> [chore] obs_table: sort primary entity ids when storing

- featurebyte/routes/common/base_table.py
- featurebyte/service/base_document.py
- featurebyte/service/context.py
- featurebyte/service/credential.py
- featurebyte/service/table.py
- featurebyte/service/table_columns_info.py
- featurebyte/service/table_facade.py
- tests/unit/service/test_base_document.py
- tests/unit/service/test_relationship.py
- tests/unit/service/test_table_document.py
This PR updates block modification logic so that it won't throw error when users update description only.
> [DEV-2475] Do not block modification when updating asset description

- .changelog/DEV-2431.yaml
- featurebyte/api/aggregator/forward_aggregator.py
- tests/integration/api/test_target_correctness.py
- tests/unit/api/aggregator/test_forward_aggregator.py
This was incorrectly doing an assert for value_column to never be `None`, though it should be allowed when the aggregate function is `COUNT`. This is actually handled correctly in the helper method - https://github.com/featurebyte/featurebyte/blob/7522f0de6191060978e9025d9ea2d6eb2506bc6b/featurebyte/api/aggregator/base_aggregator.py#L79-L84
This removes the extra unnecessary assert, and adds a test to ensure that the aggregation works as intended.
https://featurebyte.atlassian.net/browse/DEV-2431
|       `enhancement`, `feature`        |          🚀 Features …
> [DEV-2431] forward_aggregate: suport value_column=None for forward agg operations

- tests/integration/api/test_change_view_operations.py
- tests/integration/api/test_dimension_view_operations.py
- tests/integration/api/test_event_view_operations.py
Remove source_type parameter to run for all source types by default.
> [chore] rm unnecessary source_type overrides

- .changelog/DEV-2482.yaml
- featurebyte/api/observation_table.py
- featurebyte/models/observation_table.py
- featurebyte/schema/observation_table.py
- featurebyte/worker/task/observation_table_upload.py
- tests/integration/api/test_observation_table.py
- tests/unit/api/test_observation_table.py
- tests/unit/routes/test_observation_table.py
- tests/unit/worker/task/test_observation_table_upload.py
Persist the filename that the observation table was created from.
> [DEV-2482] obs_table_upload: track uploaded filename

- featurebyte/api/source_table.py
- featurebyte/schema/observation_table.py
- tests/unit/api/test_source_table.py
- tests/unit/conftest.py
- tests/unit/test_logger.py
Make primary entity optional for observation table creation for now to maintain backward compatibility
> [chore] Make primary entity optional for observation table creation

- .changelog/DEV-2503.yaml
- featurebyte/api/use_case.py
- tests/unit/api/conftest.py
- tests/unit/api/test_context.py
- tests/unit/api/test_use_case.py
Currently, creating a use case with a descriptive target throws an error since there’s no actual target version object.
We made some changes to store the target namespace ID in the use case, but never updated this create function to handle that correctly. This PR fixes that.
https://featurebyte.atlassian.net/browse/DEV-2503 …
> [DEV-2503] use_case: look up target namespace instead of target

- featurebyte/api/feature_or_target_mixin.py
- featurebyte/core/mixin.py
- featurebyte/schema/feature_store.py
- featurebyte/schema/preview.py
- featurebyte/service/feature_preview.py
- featurebyte/service/observation_table.py
- featurebyte/service/preview.py
- tests/unit/routes/test_feature.py
- tests/unit/routes/test_feature_store.py
- tests/unit/routes/test_target.py
- tests/unit/service/test_preview.py
Simplify preview payloads to not require feature store name, and instead retrieve this from the database in the routes
> [chore] Simplify preview payloads to not require feature store name

- featurebyte/migration/run.py
- featurebyte/routes/registry.py
- featurebyte/worker/task_executor.py
- tests/integration/conftest.py
- tests/unit/conftest.py
- tests/unit/routes/relationship_info/test_api.py
- tests/unit/routes/test_lazy_app_container.py
- tests/unit/service/conftest.py
Small refactor to register the `get_temp_storage` and `get_celery` factory methods, and move callers to use instance map instead. Longer term, using the instance map should help simplify the construction of app containers, making them easier to be reused across the codebase. Ideally, the instance maps should be shared as much as possible as well.
| …
> [chore] app_container: register get_temp_storage, and mv to instance map

- .changelog/DEV-2487.yaml
- featurebyte/api/target.py
- featurebyte/routes/target_table/controller.py
- featurebyte/schema/target_table.py
- featurebyte/worker/task/target_table.py
- tests/unit/routes/test_target.py
- tests/unit/schema/test_target_table.py
- tests/unit/worker/task/test_target_table.py
Update endpoint to make graph and node names optional, but make target ID required. This way, we can lookup the graph and node from the persisted target if needed. …
> [DEV-2487] target: allow users to add target with just target id

- featurebyte/routes/observation_table/controller.py
- featurebyte/schema/observation_table.py
- featurebyte/schema/worker/task/observation_table_upload.py
- featurebyte/service/observation_table.py
- tests/unit/routes/test_observation_table.py
Move the `uploaded_file_name` param into the task upload schema only, so that it doesn't need to be provided as part of the API upload request. …
> [chore] obs_table_upload: refactor to not require filename as part of upload

- .changelog/DEV-2571.yaml
- featurebyte/core/frame.py
- featurebyte/query_graph/node/generic.py
- tests/unit/api/test_scd_view.py
- tests/unit/query_graph/test_graph_pruning.py
This PR attempts to fix a join node parameters pruning graph that causes the generated feature not savable due to graph inconsistency issue. …
> [DEV-2571] Fix a join node pruning bugs that causes generated feature not savable

- .gitignore
- featurebyte/models/base.py
- tests/integration/api/test_features.py
If data frame contains array column (which is the case for DLT with embedding), feature preview fails during json serialisation: 
```
TypeError: Object of type 'ndarray' is not JSON serializable
```
Previews created from featurelist + observation tables work fine.
[DEV-2540](https://featurebyte.atlassian.net/browse/DEV-2540)
| …
> [DEV-2540] Feature preview with array column in dataframe

- featurebyte/routes/feature_list_namespace/controller.py
- featurebyte/schema/feature_list_namespace.py
This PR aims to fix current feature list namespace endpoints which break release/0.6 featurebyte client.
> [chore] Add `dtype_distribution` to `FeatureListNamespaceModelResponse`

- .changelog/DEV-2611.yaml
- featurebyte/exception.py
- featurebyte/middleware.py
- featurebyte/session/manager.py
- tests/integration/conftest.py
- tests/unit/session/test_manager.py
Data warehouse session creation can take a long time for some providers when the compute cluster is waking up from sleep. This fix will prevent the session creation from rendering the REST API unresponsive, and raises a timeout error when it takes too long.
https://featurebyte.atlassian.net/browse/DEV-2611 …
> [DEV-2611] Make data warehouse session creation asynchronous

- .github/workflows/dependencies_gen.yaml
+ Reduce workflow to only when `pyproject.toml` changes
+ Always print the changes [if exists]
+ If dependency label is added, do not fail if there are a change between required dependencies. This is to provide visibility for developers on the explicit changes required when new users install `featurebyte` …
> [workflow] Always show dependency changes

- .changelog/DEV-2591.yaml
- featurebyte/api/observation_table.py
- featurebyte/common/documentation/documentation_layout.py
- featurebyte/schema/observation_table.py
- tests/unit/api/test_observation_table.py
Expose a simple function to allow users to update purpose of the observation table.
https://featurebyte.atlassian.net/browse/DEV-2591 …
> [DEV-2591] observation_table: add way to update purpose

- .changelog/DEV-2626.yaml
- featurebyte/routes/context/controller.py
- featurebyte/routes/historical_feature_table/api.py
- featurebyte/routes/historical_feature_table/controller.py
- featurebyte/routes/observation_table/api.py
- featurebyte/routes/observation_table/controller.py
- featurebyte/routes/use_case/controller.py
- featurebyte/schema/context.py
- featurebyte/schema/historical_feature_table.py
- featurebyte/schema/observation_table.py
- featurebyte/schema/use_case.py
- featurebyte/service/observation_table.py
- tests/unit/routes/test_context.py
- tests/unit/routes/test_historical_feature_table.py
- tests/unit/routes/test_observation_table.py
- tests/unit/routes/test_use_case.py
Support renaming of context, use case, observation table and historical feature table
> [DEV-2626] Support renaming of context, use case, observation table and historical feature table

- featurebyte/service/version.py
- tests/unit/api/test_feature.py
Current feature's create new version service does not regenerate those graph derived attributes. This PR aims to fix this bug.
> Fix `feature.create_new_version` bug

- featurebyte/models/catalog.py
- tests/unit/routes/test_catalog.py
This PR excludes soft-deleted catalog from the catalog namespace so that user is allowed to create a new catalog with the same name. …
> [DEV-2639] Exclude soft-deleted catalog from the namespace

- .changelog/DEV-2569.yaml
- .github/workflows/test-notebooks_gen.yaml
- Taskfile.yaml
- featurebyte/api/target.py
- featurebyte/routes/target_table/api.py
- featurebyte/routes/target_table/controller.py
- featurebyte/schema/target_table.py
- featurebyte/worker/task/target_table.py
- tests/unit/routes/test_target.py
- tests/unit/schema/test_target_table.py
- tests/unit/worker/task/test_target_table.py
In order to get test coverage on changes that break backwards compatibility we can use the published version of the SDK when running the notebook tests. …
> [DEV-2569] Use published featurebyte SDK in notebook tests

- featurebyte/models/task.py
Add 30-day expiry to celery tasks documents to clean up mongo storage
> [chore] Add expiry to celery tasks documents

- .changelog/DEV-2643.yaml
- featurebyte/models/request_input.py
- tests/unit/api/test_event_view.py
- tests/unit/api/test_source_table.py
This fixes an issue in observation table creation where the sampling is not uniform over the full available time range. 
Previously in the sampling query, the tablesample clause can potentially return ordered data and cause some rows to be prematurely truncated by the limit clause. To prevent that issue, this shuffles the output of tabesample so that rows are randomly selected before truncation.
|       `build`, `ci`, …
> [DEV-2643] Fix observation table sampling not uniform

- featurebyte/session/base_spark.py
- tests/unit/session/test_databricks_session.py
Unlike in Spark, DESCRIBE TABLE in DataBricks does not include an empty row between column details and table metadata.
This can cause column information to be detected wrongly when table metadata such as partitioning is available.
This PR fixes this.
| …
> [chore] Handle databricks describe table output format

- .changelog/DEV-2679.yaml
- featurebyte/routes/observation_table/controller.py
- tests/unit/routes/test_observation_table.py
This fixes an error when uploading files to create observation tables in the SDK. Also added handling for cases where the file content cannot be parsed properly.
Error:
```
15:39:02 | ERROR    | {"detail":""}
---------------------------------------------------------------------------
RecordCreationException                   Traceback (most recent call last)
[... skipping hidden 1 frame]
...
fb.ObservationTable.upload("my_table.parquet", "Observation Table From File")
RecordCreationException: {"detail":""}
```
|       `enhancement`, `feature`        |          🚀 …
> [DEV-2679] Fix observation table file upload error

- featurebyte/api/base_table.py
- tests/unit/api/base_table_test.py
Add missing `typechecked` decorator for several SDK table column update methods.
> [chore] Add missing typechecked decorator

- featurebyte/common/documentation/documentation_layout.py
DBVarType is missing from documentation layout 
[DEV-2629](https://featurebyte.atlassian.net/browse/DEV-2629)
[DEV-2629]: …
> [DEV-2629] add DBVarType to docs layout

- .changelog/DEV-2714.yaml
- featurebyte/query_graph/sql/online_serving.py
- featurebyte/routes/registry.py
- featurebyte/service/feature_materialize.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/service/conftest.py
- tests/unit/service/test_feature_materialize.py
This implements FeatureMaterializeService to prepare features for publishing. It retrieves currently online enabled features that should be materialised together and generates a feature table to be published to offline store. The sql query to generate the feature table is derived from the ingest graphs. …
> [DEV-2714] Implement FeatureMaterializeService to prepare features for publishing

- featurebyte/models/feature.py
- featurebyte/service/feature_materialize.py
- tests/unit/service/test_feature_materialize.py
This updates OfflineStoreIngestQueryGraph to include dtype information of the output column.
> [DEV-2714] Add dtype information in OfflineStoreIngestQueryGraph

- featurebyte/api/user_defined_function.py
- featurebyte/common/documentation/documentation_layout.py
Add fb.UserDefinedFunction.get to docs
[DEV-2734](https://featurebyte.atlassian.net/browse/DEV-2734)
[DEV-2734]: …
> [DEV-2734] Add fb.UserDefinedFunction.get to docs

- featurebyte/service/base_document.py
- featurebyte/service/feature_readiness.py
Add retry decorator to `update_documents` method to attempt to handle mongo operation errors.
> [DEV-2728] Add retry to `update_documents` method in base document service

- featurebyte/exception.py
- featurebyte/routes/common/base_table.py
- tests/fixtures/sdk_code/scd_view_aggregate_asat.py
- tests/unit/api/test_aggregate_asat.py
- tests/unit/api/test_change_view.py
- tests/unit/api/test_scd_view.py
- tests/unit/conftest.py
- tests/unit/routes/test_scd_table.py
Ban SCD surrogate keys from entity tagging
[DEV-2665](https://featurebyte.atlassian.net/browse/DEV-2665)
[DEV-2665]: …
> [DEV-2665] Ban SCD surrogate keys from entity tagging

- featurebyte/service/feature_materialize.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/service/test_feature_materialize.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This updates OfflineStoreFeatureTableManagerService to trigger feature columns initialization using FeatureMaterializeService when handling online enabled features. …
> [DEV-2770] Trigger feature columns initialization in OfflineStoreFeatureTableManagerService

- featurebyte/worker/task/target_table.py
inherit purpose when creating observation table
[DEV-2801](https://featurebyte.atlassian.net/browse/DEV-2801)
[DEV-2801]: …
> [DEV-2801] inherit purpose when creating observation table

- featurebyte/api/api_object_util.py
- tests/unit/service/test_offline_store_feature_table_manager.py
Calling logging in `ProgressThread` appears to cause some tests to hang due to interactions between alive_bar and logging.
> [chore] Fix hanging tests due to interactions between alive_bar and logging

- featurebyte/models/deployment.py
- featurebyte/service/deploy.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/conftest.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/service/test_feature_materialize.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This updates deployment service to invoke offline store feature table manager to create or update feature store tables. Currently this is disabled by default and only enabled in tests.
| …
> [DEV-2806] Invoke offline store feature table manager on deployment

- Taskfile.yaml
- featurebyte/feast/service/feature_store.py
- featurebyte/feast/utils/on_demand_view.py
- featurebyte/routes/deployment/controller.py
- featurebyte/service/online_serving.py
- tests/fixtures/offline_store_feature_table/feature_cluster_disabled_one_feature.json
- tests/fixtures/offline_store_feature_table/feature_cluster_one_feature.json
- tests/fixtures/offline_store_feature_table/feature_cluster_two_features.json
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/service/conftest.py
- tests/unit/service/test_feature_materialize.py
- tests/unit/service/test_offline_store_feature_table_manager.py
- tests/unit/service/test_online_serving_feast.py
- tests/util/helper.py
This updates online serving route to use feast to retrieve online features when enabled.
> [DEV-2828] Update online serving route to use feast when enabled

- .changelog/DEV-2831.yaml
- featurebyte/service/deploy.py
- tests/unit/service/test_deploy.py
This fixes an issue where periodic tasks were not disabled when reverting a failed deployment.
> [DEV-2831] Fix periodic tasks not disabled when reverting failed deployment

- featurebyte/feast/service/feature_store.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This updates feast registry creation to use catalog id as project name to ensure uniqueness of keys in the online store.
> [chore] Use catalog id as feast project name

- featurebyte/service/feature_materialize.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/fixtures/feature_materialize/drop_columns.sql
- tests/unit/service/conftest.py
- tests/unit/service/test_feature_materialize.py
- tests/unit/service/test_offline_store_feature_table_manager.py
- tests/unit/service/test_online_serving_feast.py
This updates offline store feature table manager to drop corresponding columns in the feature table after features are online disabled. Feature table is dropped if all features are online disabled.
| …
> [DEV-2832] Drop columns in offline store feature table after online disabling features

- featurebyte/feast/utils/registry_construction.py
- featurebyte/models/offline_store_feature_table.py
- featurebyte/query_graph/transform/offline_store_ingest.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/conftest.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This adds support for features without entity in feast integration. When constructing the feast registry, a special entity recognised by feast will be used for such features. …
> [DEV-2791] Support features without entity in feast integration

- featurebyte/query_graph/sql/adapter/databricks.py
- featurebyte/query_graph/sql/interpreter/preview.py
- featurebyte/session/databricks.py
- tests/fixtures/expected_describe_request.sql
- tests/fixtures/query_graph/expected_describe_count_based_stats_only.sql
- tests/fixtures/query_graph/expected_describe_databricks.sql
- tests/fixtures/query_graph/expected_describe_snowflake.sql
- tests/fixtures/query_graph/expected_describe_spark.sql
- tests/integration/api/test_view_describe.py
- tests/unit/query_graph/interpreter/test_preview.py
- tests/unit/query_graph/sql/test_groupby_helper.py
This replaces the usage of `OBJECT_AGG` hive udf with spark's built-in functions. This allows us to transition to databricks with unity catalog. …
> [DEV-2877] Replace OBJECT_AGG hive udf with built-in functions in spark and databricks

- featurebyte/models/entity_universe.py
- featurebyte/models/feature.py
- featurebyte/models/offline_store_feature_table.py
- featurebyte/models/sqlglot_expression.py
- featurebyte/query_graph/sql/template.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/fixtures/offline_store_feature_table/aggregate_asat_feature_universe.sql
- tests/fixtures/offline_store_feature_table/lookup_feature_universe.sql
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/api/test_offline_ingest_query_graph.py
- tests/unit/conftest.py
- tests/unit/feast/service/test_registry.py
- tests/unit/feast/utils/test_register_construction.py
- tests/unit/models/test_entity_universe.py
- tests/unit/models/test_sqlglot_expression.py
- tests/unit/service/test_feature_materialize_scheduler.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This adds support for non-window aggregate features in feast integration: lookup features and aggregate as-at features. The main change is a generalised entity universe model which determines the entities for features computation. It will be used when materialising new features and existing features in scheduled tasks.
Support for item aggregates will be added in a follow up PR.
|       `build`, `ci`, `testing`        | …
> [DEV-2902] Support non-window aggregate features in feast integration

- .github/workflows/test_gen.yaml
- tests/integration/session/test_spark.py
- tests/integration/tile/test_tile_scheduler.py
- tests/integration/udf/test_timestamp_to_index.py
- tests/integration/udf/test_timezone_offset_to_second.py
- tests/integration/udf/test_vector_cosine_similarity.py
Switch over remaining databricks integration tests to databricks_unity when applicable. `test-integration-databricks` job is now disabled as there is no test to be collected. …
> [chore] Switch over remaining databricks integration tests

- featurebyte/common/string.py
- featurebyte/feast/service/registry.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/fixtures/feature_materialize/initialize_new_columns_new_table_databricks.sql
- tests/integration/conftest.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/service/test_feature_materialize.py
This updates feature materialize service to add primary key constraints for offline store feature tables created in databricks with unity catalog. The feast integration test is also refactored into smaller tests since it's getting too long. …
> [DEV-2807] Add primary key constraints for feature tables on databricks unity

- featurebyte/service/feature_materialize.py
- tests/integration/feature_store_integration/test_feature_materialize.py
Adding a test case on scheduled feature materialize task for a non-ttl feature table.
> [chore] Add scheduled materialize non-ttl integration test case and fixes

- featurebyte/query_graph/node/base.py
- featurebyte/query_graph/node/count_dict.py
- featurebyte/query_graph/node/date.py
- featurebyte/query_graph/node/distance.py
- featurebyte/query_graph/node/nested.py
- featurebyte/query_graph/node/request.py
- featurebyte/query_graph/node/string.py
- featurebyte/query_graph/node/unary.py
- featurebyte/query_graph/node/vector.py
- tests/fixtures/on_demand_function/req_col_ttl_and_non_ttl.sql
- tests/unit/api/test_offline_ingest_query_graph.py
- tests/unit/api/test_request_column.py
- tests/unit/query_graph/on_demand_function/conftest.py
- tests/unit/query_graph/on_demand_function/test_binary.py
- tests/unit/query_graph/on_demand_function/test_count_dict.py
- tests/unit/query_graph/on_demand_function/test_date.py
- tests/unit/query_graph/on_demand_function/test_distance.py
- tests/unit/query_graph/on_demand_function/test_generic.py
- tests/unit/query_graph/on_demand_function/test_string.py
- tests/unit/query_graph/on_demand_function/test_unary.py
- tests/unit/query_graph/on_demand_function/test_vector.py
- tests/unit/query_graph/util.py
- tests/util/helper.py
This PR is a following PR of (https://github.com/featurebyte/featurebyte/pull/2027), it covers the query graph nodes in
* `unary.py`
* `string.py`
* `date.py`
* `count_dict.py`
* `distance.py`
* `vector.py` …
> [DEV-2904] Add support to convert query graph to DataBricks UDF (part-2)

- featurebyte/routes/deployment/api.py
- tests/unit/routes/test_deployment.py
Add feature list id filter to list deployments
[DEV-2721](https://featurebyte.atlassian.net/browse/DEV-2721)
[DEV-2721]: …
> [DEV-2721] add feature list id filter to list deployments

- featurebyte/service/deploy.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/unit/service/test_offline_store_feature_table_manager.py
- tests/util/helper.py
This fixes an issue where required feature services are not created in feast registry in some cases. Specifically, that happens when all the underlying features of a feature list were already online enabled. …
> [DEV-2914] Fix feature service not created in feast registry

- featurebyte/service/feature_materialize.py
- tests/fixtures/feature_materialize/initialize_new_columns_new_table_databricks.sql
The primary key constraint for feature timestamp column should be tagged with the `TIMESERIES` keyword.
> [DEV-2807] Fix primary key constraint for feature timestamp column

- .changelog/DEV-2929.yaml
- featurebyte/session/snowflake.py
- tests/unit/session/test_snowflake_session.py
Set user role during Snowflake session initialization to ensure the right role is used.
> [DEV-2929] Set user role during Snowflake session initialization

- .changelog/DEV-2931.yaml
- featurebyte/api/user_defined_function.py
- featurebyte/routes/user_defined_function/api.py
- featurebyte/routes/user_defined_function/controller.py
- featurebyte/schema/user_defined_function.py
- featurebyte/service/user_defined_function.py
- tests/fixtures/request_payloads/user_defined_function.json
- tests/unit/api/test_user_defined_function.py
- tests/unit/routes/test_user_defined_function.py
- tests/unit/service/test_user_defined_function.py
Simplify user defined function route creation schema to exclude feature_store_id and catalog_id
https://featurebyte.atlassian.net/browse/DEV-2931 …
> [DEV-2931 Simplify user defined function route creation schema

- featurebyte/feast/model/online_store.py
- featurebyte/feast/service/feature_store.py
- featurebyte/models/online_store.py
- featurebyte/routes/deployment/controller.py
- featurebyte/service/feature_materialize.py
- tests/integration/conftest.py
- tests/unit/feast/model/test_online_store.py
- tests/unit/service/conftest.py
- tests/unit/service/test_feature_materialize.py
- tests/unit/service/test_online_serving_feast.py
This updates external feature store integration to respect the online store configuration specified in the catalog.
> [DEV-2913] Use online store configuration specified in catalog

- featurebyte/feast/utils/on_demand_view.py
- featurebyte/feast/utils/registry_construction.py
- tests/unit/feast/utils/test_register_construction.py
Current `importlib` used in on demand feature view may cause integration test failures due to not detecting the existence of the module. To bypass this issue, we change the `importlib` to `exec`.
| …
> [chore] Remove `importlib` in on demand feature view creation

- featurebyte/feast/model/feature_store.py
- featurebyte/session/snowflake.py
- tests/unit/session/test_snowflake_session.py
This fixes issues related to role specification when creating a Snowflake session:
- `USE ROLE` should be issued before working schema initialization where we create internal assets
- Feast offline store config for Snowflake should specify the same role
| …
> [DEV-2929] Fix snowflake session role specification

- featurebyte/api/materialized_table.py
- featurebyte/query_graph/sql/materialisation.py
- featurebyte/routes/feature_store/api.py
- featurebyte/service/feature_store_warehouse.py
- featurebyte/service/preview.py
- tests/integration/api/test_observation_table.py
- tests/unit/routes/base.py
- tests/unit/service/conftest.py
- tests/unit/service/test_preview.py
Previously, the logic of removing row index column when previewing, sampling and downloading materialized tables is in the SDK client. The downside is that the column is still visible elsewhere such as in the UI.
To fix that, this PR moves such logic to the backend so that the API routes return consistent result. This also adds sorting by row index column when downloading materialised table if such a column is available. …
> [DEV-2955] Move table row index handling of materialized tables to backend

- featurebyte/query_graph/transform/on_demand_view.py
- tests/unit/api/test_offline_ingest_query_graph.py
- tests/unit/feast/utils/test_registry_construction.py
This adds a final step in on-demand feature views transformations to convert any `None` values in the output to `np.nan`. Without this, `get_online_features()` can sometimes raise a "Couldn't infer value type from empty value" error. …
> [DEV-2973] Replace None with np.nan in on-demand feature view's output

- featurebyte/worker/task/materialized_table_delete.py
Improve materialized table deletion logic to keep mongo record intact until table in the warehouse is successfully dropped.
> [chore] Delete mongo documents only if table is deleted at datawarehouse

- tests/unit/service/conftest.py
This fixes the `mock_offline_store_feature_manager_dependencies` fixture to disable the mocks properly on teardown. Without this, it can affect other tests. …
> [chore] Fix mock_offline_store_feature_manager_dependencies fixture improper teardown

- featurebyte/service/feature_materialize.py
- tests/fixtures/feature_materialize/drop_columns.sql
This updates the column dropping query in FeatureMaterializeService to use if exists keyword to make it more robust against bad state. …
> [chore] Drop column only if exists in FeatureMaterializeService

- featurebyte/models/feature_list_store_info.py
- featurebyte/query_graph/sql/entity.py
- featurebyte/query_graph/sql/online_serving.py
- featurebyte/service/feature_materialize.py
- tests/fixtures/feature_materialize/initialize_features_no_entity_databricks_unity.sql
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/service/test_feature_materialize.py
This adds special handling for features without entity for databricks unity by adding a dummy entity column in the feature table.
> [DEV-2986] Special handling for features without entity for databricks unity

- featurebyte/feast/patch.py
- featurebyte/service/online_serving.py
- tests/integration/feature_store_integration/test_feature_materialize.py
This PR fix Feast's `augment_response_with_on_demand_transforms` method by casting the result to expected type (rather than inferring the type from the response). …
> [chore] Patch Feast feature store's `augment_response_with_on_demand_transforms` method

- Taskfile.yaml
- featurebyte/feast/utils/materialize_helper.py
Add time-to-live to feast snowflake session cache to avoid getting stuck with stale session
> [DEV-3000] Add ttl to feast snowflake session cache

- featurebyte/service/feature_list.py
- tests/unit/service/test_feature_list.py
Remove redundant entries in `FeatureListModel`'s  `features_entity_lookup_info` by keeping features that require additional entity lookup steps. …
> [chore] Remove redundant entries in FeatureListModel features_entity_lookup_info

- featurebyte/query_graph/graph.py
- featurebyte/query_graph/transform/decompose_point.py
- tests/unit/query_graph/transform/test_decompose_point.py
Previous PR (https://github.com/featurebyte/featurebyte/commit/0ed93eb374164982f66b3602752af1bff0ccb3d3) causes unnecessarily extraction of decompose graph, it causes performance issue when calling `graph.get_entity_ids(...)`. …
> [chore] Fix performance issue of `get_entity_ids`

- featurebyte/worker/task/batch_feature_create.py
- featurebyte/worker/task/feature_list_batch_feature_create.py
- featurebyte/worker/util/batch_feature_creator.py
- tests/unit/worker/task/test_batch_creator.py
This PR uses much longer API cache when task executing SDK code to reduce number of API calls.
> [chore] Use longer TTL (`APIObject` cache) for batch feature & feature list saving

- featurebyte/query_graph/model/graph.py
This PR aims to cache the property to reduce query graph operation runtime.
> [chore] Cache query graph `propery` method

- featurebyte/persistent/base.py
- featurebyte/persistent/mongo.py
Make `aggregate_find` interface more extensible
> [chore] Make persistent aggregate_find interface more extensible

- featurebyte/api/api_object_util.py
- featurebyte/api/feature.py
- featurebyte/api/savable_api_object.py
- featurebyte/common/utils.py
- featurebyte/config.py
Runtime performance of saving a feature by issuing `pytest -vv tests/unit/api/test_feature.py -k test_feature_or_view_column_name_contains_quote -s ` (using this branch: https://github.com/featurebyte/featurebyte/tree/senbong/print-node).
```
----> Reconfiguring loggers in get_client: 0.020622730255126953 seconds
----> Quick prune for payload: 0.001547098159790039 seconds
----> Reconfiguring loggers in get_client: 0.02048182487487793 seconds
----> Prepare task payload (api server): 0.001299142837524414 seconds
----> Quick prune for definition (BatchFeatureCreate.create_feature): 0.0013282299041748047 seconds
------> View construction (prepare_graph_to_store): 0.01244974136352539 seconds
------> Prune graph & node parameters (prepare_graph_to_store): 0.0038080215454101562 seconds
------> …
```
> [DEV-3031] Optimize feature saving runtime

- .changelog/DEV-3037.yaml
- featurebyte/query_graph/sql/specifications/base_lookup.py
- tests/fixtures/expected_preview_sql_scd_lookup_with_offset.sql
- tests/integration/api/test_scd_view_operations.py
This fixes a bug that causes ambiguous column name error in the generated queries. The error is triggered when a feature list contains SCD lookup features from the same source table but with different offsets. …
> [DEV-3037] Fix ambiguous column name error for SCD lookup features with offset

- featurebyte/query_graph/sql/interpreter/base.py
- tests/unit/api/test_event_view.py
Fix failure when getting the shape of a view column with
```
view["column_name"].shape()
```
Traceback
```
[PARSE_SYNTAX_ERROR] Syntax error at or near '`GroceryInvoiceGuid`'. SQLSTATE: 42601 (line 2, pos 2)
== SQL ==
WITH data AS (
`GroceryInvoiceGuid`
--^^^
)
SELECT
COUNT(*) AS `count`
FROM data
``` …
> [DEV-3042] Fix bug with view column shape

- featurebyte/service/deploy.py
- featurebyte/worker/task/deployment_create_update.py
- tests/unit/service/test_deploy.py
- tests/unit/service/test_feature_list_status.py
Current deployment object `enabled` status is updated first before running other operations. This behaviour gives users wrong impression that the deployment create/update task has completed. This PR revises existing deployment enabled status update logic.
| …
> [DEV-3044] Update deployment `enabled` status only when task almost finished

- featurebyte/models/entity_lookup_feature_table.py
- featurebyte/models/feature_list.py
- featurebyte/schema/feature_list.py
- featurebyte/service/deploy.py
- featurebyte/service/online_serving.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/api/test_feature_list.py
- tests/unit/models/test_feature_list.py
- tests/unit/service/test_deploy.py
- tests/unit/service/test_feature_materialize.py
- tests/unit/service/test_offline_feature_store_comment.py
- tests/unit/service/test_offline_store_feature_table_manager.py
- tests/unit/service/test_online_serving.py
- tests/util/helper.py
Previously, lookup tables are created in such a way that all the serving entities enumerated in FeatureList's `supported_serving_entity_ids` can be served. This can potentially create many unnecessary entity lookup tables.
This PR updates the entity lookup feature tables creation logic to materialize only the lookup tables that are required by the currently enabled deployments. This should limit the number of lookup tables created.
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & …
> [DEV-3029] Limit number of materialized lookup tables based on deployment use case

- featurebyte/service/deploy.py
- tests/unit/service/test_offline_store_feature_table_manager.py
Follow up of https://github.com/featurebyte/featurebyte/pull/2149: re-enabling a test case after fixing the handling.
> [chore] Re-enable test case on enabled_serving_entity_ids

- featurebyte/app.py
- featurebyte/feast/model/registry.py
- featurebyte/feast/schema/registry.py
- featurebyte/feast/service/registry.py
- featurebyte/service/deploy.py
- featurebyte/storage/base.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/integration/feature_store_integration/test_update_online_store.py
- tests/unit/feast/model/test_registry.py
- tests/unit/service/test_feast_registry.py
- tests/unit/service/test_offline_store_feature_table_manager.py
- tests/util/helper.py
Due to the 16MB Mongo record limitation, this PR move Feast registry protobuf from Mongo record to remote storage.
> [DEV-3046] Move Feast registry protobuf from Mongo record to remote storage

- featurebyte/feast/service/registry.py
- featurebyte/migration/service/feature.py
- featurebyte/migration/service/feature_list.py
- featurebyte/models/persistent.py
- featurebyte/persistent/audit.py
- featurebyte/persistent/base.py
- featurebyte/persistent/mongo.py
- featurebyte/service/base_document.py
- featurebyte/service/feature.py
- featurebyte/service/feature_list.py
- featurebyte/service/online_store_compute_query_service.py
- featurebyte/service/online_store_table_version.py
- featurebyte/service/task_manager.py
- featurebyte/service/user_defined_function.py
- tests/unit/service/test_base_document.py
- tests/unit/worker/task/test_feature_job_setting_analysis.py
- tests/unit/worker/test_task_executor.py
- tests/unit/worker/test_util.py
Iterate cursor directly to avoid multiple mongo queries
> [chore] remove paging and multiple queries from document iterator

- .changelog/DEV-3070.yaml
- featurebyte/__init__.py
- featurebyte/config.py
- tests/unit/test_init.py
Automatically generate a profile from registered secrets in DataBricks workspaces to simplify access.
Registering the following secrets in DataBricks to use the featurebyte library without creating a profile
```
databricks secrets put-secret featurebyte api-url --string-value [api-url]
databricks secrets put-secret featurebyte api-token --string-value  [api-token]
```
|       `build`, `ci`, `testing`        |    📦 Build …
> [DEV-3070] Support auto generated featurebyte profile from databricks secrets

- featurebyte/service/feature_table_cache.py
- tests/integration/service/test_feature_table_cache.py
- tests/unit/service/test_feature_table_cache.py
This fixes the following issues when creating historical feature tables from cache:
1. Columns ordering in historical feature tables to follow original columns ordering of the observation table
2. Incorrect output when there are duplicated definition hashes
| …
> [chore] Fix columns ordering in historical feature tables

- featurebyte/exception.py
- featurebyte/service/entity_validation.py
- featurebyte/service/parent_serving.py
- tests/unit/service/conftest.py
- tests/unit/service/test_entity_validation.py
- tests/unit/service/test_parent_serving.py
Currently the validation logic for parent entity lookup can raise false alarms in some cases. To prevent that, simplifies the validation logic by removing the `AmbiguousEntityRelationshipError`. There isn't a situation where we want to rely on this behaviour, and we should aim to guard against such invalid relationships on entity tagging time rather than when serving features.
|       `build`, `ci`, `testing`        | …
> [DEV-3071] Fix incorrect parent entity serving validation error

- featurebyte/api/feature_list.py
- featurebyte/models/historical_feature_table.py
- featurebyte/routes/batch_feature_table/controller.py
- featurebyte/routes/common/feature_or_target_table.py
- featurebyte/routes/historical_feature_table/controller.py
- featurebyte/routes/registry.py
- featurebyte/schema/info.py
- featurebyte/service/entity_validation.py
- featurebyte/service/feature_list.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/feature_preview.py
- featurebyte/service/feature_table_cache.py
- featurebyte/service/historical_features.py
- featurebyte/service/online_serving.py
- featurebyte/service/target_helper/base_feature_or_target_computer.py
- tests/unit/service/test_entity_validation.py
This attempts to improve the efficiency of entity validation and feature clusters handling:
1. In entity validation, provide a fast path to retrieve required entities through a FeatureListModel rather than always from the graph which is more CPU expensive (graph processing).
2. For saved feature lists, avoid calling `derive_feature_clusters()` to re-generate feature clusters since it is already available. Deriving feature clusters from scratch is expensive.
Testing using feature list with about 300 features, timing of `POST /historical_feature_table` before: 14s, after: 0.3s.
|:-------------------------------------:|:-------------------- …
> [chore] Improve entity validation and feature clusters handling

- featurebyte/exception.py
- featurebyte/feast/utils/registry_construction.py
- featurebyte/models/entity_lookup_feature_table.py
- featurebyte/models/entity_universe.py
- featurebyte/models/parent_serving.py
- featurebyte/query_graph/sql/parent_serving.py
- featurebyte/service/entity.py
- featurebyte/service/entity_lookup_feature_table.py
- featurebyte/service/entity_validation.py
- featurebyte/service/parent_serving.py
- tests/unit/models/test_entity_universe.py
- tests/unit/query_graph/conftest.py
- tests/unit/service/conftest.py
- tests/unit/service/test_entity.py
- tests/unit/service/test_parent_serving.py
This is a refactoring to parent entity lookup related logic. Main changes:
1. Refactor and simplify ParentEntityLookupService to use EntityRelationshipInfo and EntityLookupPlanner 
3. Consolidate JoinStep and EntityLookupStep classes which contain similar information
This will prepare us to transition to using frozen relationships for parent entity lookup.
|       `build`, `ci`, `testing`        |    📦 Build System & …
> [chore] Refactor ParentEntityLookupService to use EntityRelationshipInfo 

- featurebyte/models/entity_universe.py
- tests/integration/api/test_scd_view_operations.py
- tests/unit/conftest.py
- tests/unit/models/test_entity_universe.py
This fixes incorrect entity universe for aggregated asat features without an entity.
> [chore] Fix entity universe for aggregate asat features without entity

- featurebyte/service/feature_preview.py
- tests/unit/routes/test_feature_list.py
This PR prevents previewing feature list with more than 30 number of features. This is to prevent API server becomes unresponsive when previewing large feature list. …
> [chore] Limit number of features for feature list preview

- featurebyte/models/entity_universe.py
- featurebyte/models/user_defined_function.py
- featurebyte/query_graph/sql/ast/aggregate.py
- featurebyte/query_graph/sql/ast/base.py
- featurebyte/query_graph/sql/ast/join_feature.py
- featurebyte/query_graph/sql/ast/tile.py
- featurebyte/query_graph/sql/builder.py
- featurebyte/query_graph/sql/common.py
- featurebyte/query_graph/sql/feature_compute.py
- featurebyte/query_graph/sql/interpreter/tile.py
- featurebyte/query_graph/sql/parent_serving.py
- featurebyte/query_graph/sql/specifications/base_lookup.py
- featurebyte/query_graph/sql/specifications/lookup.py
- featurebyte/query_graph/sql/specifications/lookup_target.py
- featurebyte/query_graph/sql/specs.py
- tests/unit/query_graph/sql/aggregator/test_forward.py
- tests/unit/query_graph/test_asat_aggregator.py
- tests/unit/query_graph/test_feature_common.py
- tests/unit/query_graph/test_feature_compute.py
- tests/unit/query_graph/test_item_aggregator.py
- tests/unit/query_graph/test_lookup.py
- tests/unit/query_graph/test_lookup_aggregator.py
- tests/unit/query_graph/test_sql.py
This refactors and simplifies the Aggregate sql ast node to reduce code duplication. The handling of all aggregation node types is now consolidated into a single class. The refactored logic should also be more efficient since `update_feature_specs` doesn't have to re-extract aggregation specifications from graph again. …
> [chore] Refactor and simplify Aggregate sql ast node

- .changelog/DEV-3083.yaml
- featurebyte/schema/worker/task/historical_feature_table.py
- featurebyte/service/feature_table_cache.py
- tests/integration/api/test_event_view_operations.py
- tests/unit/conftest.py
- tests/unit/service/test_feature_table_cache.py
- tests/util/helper.py
This updates the historical features table creation task to be revokable. The task itself already handles deletion of temporary tables on exception, except a potential discrepancy when checking the existence of feature cache table which is fixed in this PR. 
| …
> [DEV-3083] Support cancellation for historical features table creation task

- featurebyte/session/base.py
- featurebyte/session/base_spark.py
- featurebyte/session/databricks_unity.py
- featurebyte/session/snowflake.py
- featurebyte/session/sqlite.py
- featurebyte/tile/tile_cache.py
This sets a longer timeout for `list_tables()` where it is expected to take longer in the get historical features task.
> [chore] Specify longer timeout when calling list_tables from tile_cache

- featurebyte/models/offline_store_feature_table.py
- featurebyte/service/entity_validation.py
- featurebyte/service/feature_materialize.py
- tests/fixtures/feature_materialize/materialize_features_queries_internal_relationships.sql
- tests/fixtures/offline_store_feature_table/feature_cluster_disabled_one_feature.json
- tests/fixtures/offline_store_feature_table/feature_cluster_one_feature.json
- tests/fixtures/offline_store_feature_table/feature_cluster_two_features.json
- tests/fixtures/offline_store_feature_table/feature_cluster_with_internal_relationships.json
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/conftest.py
- tests/unit/service/test_feature_materialize.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This updates feature computation for offline store feature tables to use frozen relationships. Main changes:
1. Populate `feature_node_relationships_info` in the feature cluster for offline feature table models
2. Update `EntityValidationService` to be aware of offline store feature table models when constructing the ParentServingPreparation object …
> [chore] Use frozen relationships for offline store feature tables

- featurebyte/models/entity_lookup_feature_table.py
- featurebyte/models/offline_store_feature_table.py
- featurebyte/models/parent_serving.py
- featurebyte/service/entity_validation.py
- featurebyte/service/offline_store_feature_table_construction.py
- featurebyte/service/parent_serving.py
- tests/integration/conftest.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/service/test_parent_serving.py
This updates remaining places to use frozen relationships, more specifically using feature list relationships to lookup feature list primary entities from serving entities. …
> [chore] Use frozen feature list relationships

- .changelog/DEV-3093.yaml
- featurebyte/__init__.py
- featurebyte/api/materialized_table.py
- scripts/enforce_import_rules.py
Using `globals` to get DataBricks runtime variables does not work.
Use the `databricks.sdk.runtime` module to get these variables instead. …
> [DEV-3093] Fix databricks integration in SDK

- .changelog/DEV-3095.yaml
- featurebyte/query_graph/sql/aggregator/base_lookup.py
- featurebyte/query_graph/sql/deduplication.py
- featurebyte/query_graph/sql/scd_helper.py
- tests/fixtures/expected_combined_sql_with_relationships.sql
- tests/fixtures/expected_historical_requests_multiple_batches_feature_set_1.sql
- tests/fixtures/expected_historical_requests_multiple_batches_feature_set_2.sql
- tests/fixtures/expected_online_feature_retrieval_scd_current_flag.sql
- tests/fixtures/expected_preview_sql_all_types.sql
- tests/fixtures/expected_preview_sql_event_lookup.sql
- tests/fixtures/expected_preview_sql_lookup.sql
- tests/fixtures/expected_preview_sql_scd_lookup.sql
- tests/fixtures/expected_preview_sql_scd_lookup_with_offset.sql
- tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
- tests/fixtures/expected_preview_sql_with_parent_serving_preparation.sql
- tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
- tests/fixtures/feature_materialize/materialize_features_queries_internal_relationships.sql
- tests/integration/api/test_dimension_view_operations.py
- tests/integration/api/test_scd_view_operations.py
- tests/integration/conftest.py
- tests/unit/api/test_dimension_view.py
- tests/unit/query_graph/test_join.py
- tests/unit/query_graph/test_lookup_aggregator.py
- tests/unit/query_graph/test_parent_serving.py
This adds handling for duplicate rows when computing lookup features or joining with SCD tables. This ensures that the output has the correct number of rows without duplications.
| …
> [DEV-3095] Handle duplicate rows when looking up SCD and dimension tables

- tests/integration/conftest.py
- tests/integration/service/test_feature_table_cache.py
The test can sometimes fail because the number of rows is not exactly 50.
> Update comparison in test_feature_table_cache.py to avoid flakiness

- .changelog/DEV-3136.yaml
- featurebyte/query_graph/sql/adapter/base.py
- featurebyte/query_graph/sql/ast/tile.py
- featurebyte/query_graph/sql/interpreter/base.py
- featurebyte/query_graph/sql/interpreter/preview.py
- featurebyte/query_graph/sql/interpreter/tile.py
- tests/unit/query_graph/sql/ast/test_special_operations.py
This improves the efficiency of `construct_tile_gen_sql` when used by `TileCache`, specifically in the `_get_unique_tile_infos` method.
The problem is that `GraphInterpreter` repeatedly flattens the same query graph when processing each node, but graph flattening is expensive and we should avoid doing that. Profiling shows the issue:
To fix the issue, this refactors `GraphInterpreter` to flatten the graph once and reuse the result when processing different nodes. It also removes some of the deep copies made by sqlglot when constructing the sql which are not necessary and affect runtime.
Timing comparison using a large graph with about 5000 nodes and calling `TileCache::_get_unique_tile_infos` on 100 nodes: 60.5s (before) vs 1.3s (after).
Label this pull request to place it under the …
> [DEV-3136] Improve efficiency of construct_tile_gen_sql in TileCache

- featurebyte/session/base.py
- featurebyte/session/base_spark.py
- featurebyte/session/snowflake.py
- featurebyte/session/sqlite.py
- featurebyte/sql/tile_registry.py
- tests/unit/session/test_base.py
Allow overriding the default timeout for session list_table_schema method and set a higher value when called from TileRegistry.
> [DEV-3137] Set a longer timeout for list_table_schema in tile registry

- featurebyte/service/feature_table_cache.py
- featurebyte/service/historical_features.py
- featurebyte/service/target_helper/base_feature_or_target_computer.py
- featurebyte/service/target_helper/compute_target.py
- featurebyte/session/base.py
- featurebyte/worker/task/historical_feature_table.py
- featurebyte/worker/task/materialized_table_delete.py
- featurebyte/worker/task/mixin.py
- featurebyte/worker/task/target_table.py
- tests/integration/api/test_event_view_operations.py
- tests/integration/service/test_feature_table_cache.py
- tests/unit/service/test_feature_table_cache.py
This updates feature table cache service to fallback to creating a table instead when creating a view failed. This can happen due to limitations such as the maximum view definition size in Snowflake.
| …
> [chore] Handle view creation error in feature table cache service

- .changelog/DEV-3160.yaml
- featurebyte/session/base_spark.py
- tests/unit/session/test_databricks_session.py
- tests/unit/session/test_snowflake_session.py
- tests/unit/session/test_spark.py
Fix spark to dtype conversion for map types.
Before the fix: MAP types are detected as "UNKNOWN"
After the fix: MAP types are detected as "DICT" …
> [DEV-3160] Fix spark to dtype conversion for map types

- tests/integration/storage/test_azure_storage.py
`prefix` is handled on our end and not by Azure client:
https://github.com/featurebyte/featurebyte/blob/aa3cc98212fdeb76075bdd0da311f8697ca321d6/featurebyte/storage/azure.py#L41-L60
so listing blobs probably will list everything under the container regardless of prefix, causing interference between tests: 
https://github.com/featurebyte/featurebyte/blob/e3704e04634867c6134f949f4e2dd804d26d3399/tests/integration/storage/test_azure_storage.py#L40-L43
Clean up should only delete files created within the test session, which can be filtered using the prefix.
| …
> [chore] Fix possible cause of flakiness in azure storage tests

- .changelog/changelog-gen.py
- .github/workflows/changelog_gen.yaml
- .pre-commit-config.yaml
- Taskfile.yaml
Fixing: changelog task to prevent failure on task deletion in pre-commit-hook
> [cicd] Changelog task update to prevent failures on deletion

- featurebyte/session/base.py
- featurebyte/session/snowflake.py
Previously data warehouse connection is not closed explicitly because the `__exit__` method is never triggered.
> [chore] Fix closing of data warehouse connection

- featurebyte/session/databricks_unity.py
If the DataBricks schema has been created, the volume creation will be skipped. This PR removes this assumption by moving volume creation logic into `register_missing_objects`. …
> [chore] Move volume creation from `create_schema` to `register_missing_objects`

- featurebyte/session/base.py
- featurebyte/session/databricks_unity.py
- featurebyte/session/manager.py
- tests/unit/conftest.py
- tests/unit/session/test_manager.py
This PR updates session caching logic to invalidate the session cache when the latest query execution encountered exception. By doing this, bad cached session will be removed immediately once it hits query execution exception. …
> [chore] Invalidate session cache when SQL execution fails

- featurebyte/exception.py
- featurebyte/session/base.py
- tests/integration/session/test_base.py
This reworks the logic in session `drop_table` to surface original error message on failures.
> [chore] Surface original error on drop_table failures

- featurebyte/models/entity_lookup_feature_table.py
- featurebyte/models/offline_store_feature_table.py
- featurebyte/models/precomputed_lookup_feature_table.py
- featurebyte/service/entity_lookup_feature_table.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/offline_store_feature_table.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/fixtures/offline_store_feature_table/cust_id_to_gender_universe.sql
- tests/fixtures/offline_store_feature_table/transaction_id_to_cust_id_universe.sql
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/service/test_offline_store_feature_table_manager.py
- tests/util/helper.py
This updates offline store feature table manager to start creating a new kind of offline store feature table to support precomputed parent entity lookup in feature tables. Materialization of such tables will be added in an upcoming PR. …
> [DEV-3230] Create precomputed lookup feature table records 

- featurebyte/query_graph/model/column_info.py
- featurebyte/routes/common/base_table.py
- featurebyte/routes/dimension_table/api.py
- featurebyte/routes/event_table/api.py
- featurebyte/routes/item_table/api.py
- featurebyte/routes/item_table/controller.py
- featurebyte/routes/scd_table/api.py
- featurebyte/schema/table.py
- tests/unit/routes/base.py
- tests/unit/routes/test_context.py
- tests/unit/routes/test_deployment.py
- tests/unit/routes/test_event_table.py
- tests/unit/routes/test_feature.py
- tests/unit/routes/test_feature_list.py
- tests/unit/routes/test_item_table.py
- tests/unit/routes/test_target.py
- tests/unit/service/conftest.py
- tests/unit/service/test_context.py
- tests/unit/service/test_info.py
- tests/unit/test_generate_payload_fixtures.py
This PR removes `entity_id` and `critical_data_info` from `columns_info` in table registration. By doing those, entity ID & critical data info will not be set during table registration.
| …
> [chore] Remove `entity_id` & `critical_data_info` from table registration

- featurebyte/service/feature_materialize.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table.sql
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/conftest.py
- tests/unit/service/test_feature_materialize.py
Follow up to #2295.
When a feature list is deployed for a different use case, there can be a scenario where a source feature table already exists when its precomputed lookup feature tables are being created. Such precomputed lookup feature tables need to be initialized differently. This PR adds handling for that. …
> [DEV-3230] Add initialization for new precomputed lookup feature tables

- .changelog/DEV-3255.yaml
- featurebyte/session/snowflake.py
- tests/unit/session/test_snowflake_session.py
Set default schema for snowflake session.
The following error can appear when initializing a session without the fix
```
090106 (22000): Cannot perform CREATE TABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name."
```
| …
> [DEV-3255] Set default schema for snowflake session

- .github/workflows/test.yaml
- Taskfile.yaml
- featurebyte/feast/model/registry.py
- featurebyte/models/base.py
- featurebyte/models/feature_list.py
- featurebyte/models/offline_store_feature_table.py
- featurebyte/service/base_document.py
- tests/util/helper.py
This refactors delete_document to not load document as model. This makes it less strict and allows deletion of documents that are no longer compatible with the current model schema.
| …
> [chore] Refactor delete_document to not load document as model

- .github/workflows/test.yaml
- Taskfile.yaml
These are some changes in attempt to improve CI iteration speed mainly for databricks-unity:
1. Disable [fail-fast](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) property for test split matrix. We don't want a failed job in a test split to cancel other jobs (e.g. https://github.com/featurebyte/featurebyte/actions/runs/8720212793/job/23921320141?pr=2299).
2. Increase pytest timeout for databricks-unity from 900s to 1350s since it's expected to take longer.
|       `enhancement`, `feature`        | …
> [chore] Disable fail-fast property for test split matrix

- .changelog/DEV-3283.yaml
- featurebyte/service/offline_store_feature_table_manager.py
This fixes an error when disabling old deployments due to a backward compatibility issue caused by the new "precomputed_lookup_feature_table_info" key in offline store feature table documents.
| …
> [DEV-3283] Fix precomputed_lookup_feature_table_info KeyError when online disabling 

- featurebyte/exception.py
- featurebyte/service/observation_table.py
- tests/unit/routes/test_observation_table.py
- tests/unit/service/test_observation_table.py
Update the validation logic for specifying target column during observation table creation to disallow using targets with definitions. 
Observation table with  target values for such targets should be computed instead. E.g. :
```
observation_table_with_tgt = target.compute_target_table(
observation_table_without_tgt, 
"training obs for 30d spend projection"
)
```
|       `build`, `ci`, `testing`        |    📦 Build …
> [chore] Disallow targets with definition to be specified for target column in observation tables

- featurebyte/worker/task_executor.py
- tests/unit/worker/test_task_executor.py
- Add health check for the asyncio event loop in io workers
- Detects long blocking events and shuts down the worker
- Kill asyncio tasks on cancellation to avoid necessary computation
The changes here will make the io worker resilient to blocking events (in the code base or dependencies) that prevents the running loop from handling tasks effectively. When such events occur the next task will not be executed. Instead the gevent celery worker will be terminated, and the new request will be served in another worker. The terminated worker will be automatically replaced with a new one by kubernetes. …
> [chore] Add event loop health check for io worker

- .changelog/DEV-3284.yaml
- featurebyte/api/target_namespace.py
- featurebyte/enum.py
- featurebyte/schema/target_namespace.py
- tests/fixtures/request_payloads/target_namespace.json
- tests/integration/api/test_serving_parent_features.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/api/test_observation_table.py
- tests/unit/api/test_target.py
- tests/unit/api/test_target_namespace.py
- tests/unit/api/test_use_case.py
- tests/unit/test_generate_payload_fixtures.py
A descriptive target without specific definition can be created using `TargetNamespace.create` but the dtype specified is not mandatory. When the dtype is not specified there is no way to validate the dtype of a target column provided in an observation table. This can result in different observation table associating a column of the same target but with inconsistent dtypes.
To avoid this issue, the changes made here will make dtype mandatory during the creation of a descriptive target.
| …
> [DEV-3284] Make dtype mandatory during target namespace creation

- featurebyte/service/feature_table_cache.py
- tests/unit/service/test_feature_table_cache.py
Update feature cache table service to allow reading of additional columns to support accessing manually supplied target values in observation tables. …
> [chore] Update feature cache table service to allow reading of additional columns

- featurebyte/service/feature_materialize.py
- tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup_ttl.sql
- tests/unit/service/conftest.py
- tests/unit/service/test_feature_materialize.py
This fixes the precomputed lookup feature table entity universe for ttl features. Without this, the features are precomputed for only new entities between feature materialization intervals, but this should be done for all entities regardless of the intervals for ttl features.
| …
> [DEV-3230] Fix precomputed lookup feature table universe for ttl features 

- featurebyte/routes/deployment/controller.py
- featurebyte/service/entity_serving_names.py
Update deployment's sample entity serving names logic to rely on `serving_entity_ids` but not feature list's primary entity ids.
> [chore] Fix deployment's sample entity serving names

- featurebyte/service/feature_materialize.py
- tests/unit/service/conftest.py
- tests/unit/service/test_feature_materialize.py
This adds batching by columns when materializing online features.
> [DEV-3314] Batch by columns when materializing online features

- featurebyte/service/online_serving.py
- tests/unit/conftest.py
- tests/unit/service/conftest.py
- tests/unit/service/test_online_serving_feast.py
This fixes a ValueError that is raised by feast get_online_features method in some cases. The error is triggered when a feature uses a feature table with composite entity that undergoes precomputed entity lookup (e.g. state x product to customer x product, where state is a parent of customer).  …
> [DEV-3331] Fix feast get online features error for composite entities

- featurebyte/service/feature.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/unit/service/conftest.py
- tests/unit/service/test_feature_materialize.py
This updates the online disable handling for offline feature store tables to be more robust to unexpected / previous errors. 
Changes:
1. When updating offline store feature table documents, obtain the most up to date features that should have been offline disabled, instead of just the current list of features to be disabled. This way it can correct the states if a previous online disabling action failed unexpectedly.
2. When cleaning up offline store feature tables in the data warehouse, handle and log unexpected errors to allow the disabling process to continue instead of being terminated. …
> [DEV-3232] Make online disable handling more robust to unexpected failures

- featurebyte/models/entity_universe.py
- featurebyte/service/deploy.py
- featurebyte/service/offline_store_feature_table.py
- featurebyte/service/offline_store_feature_table_construction.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This adds saving of debug info for troubleshooting on entity universe creation failure. The deployment disabling logic is also updated to remove feature tables that do not have any associated feature ids (likely a result of failed deployment). …
> [chore] Save debug info for troubleshooting on entity universe creation failure 

- .changelog/DEV-3365.yaml
- featurebyte/feature_manager/model.py
- featurebyte/models/tile.py
- featurebyte/models/tile_registry.py
- featurebyte/service/feature_manager.py
- featurebyte/service/feature_table_cache.py
- featurebyte/service/historical_features.py
- featurebyte/service/historical_features_and_target.py
- featurebyte/service/tile_registry_service.py
- featurebyte/tile/tile_cache.py
- tests/fixtures/feature_manager/enable_new_feature.sql
- tests/fixtures/feature_manager/enable_second_feature_later_date.sql
- tests/fixtures/feature_manager/enable_second_feature_much_later_date.sql
- tests/fixtures/feature_manager/enable_with_backfill_metadata.sql
- tests/fixtures/feature_manager/enable_with_required_tiles_available.sql
- tests/fixtures/feature_manager/enable_without_last_run_metadata.sql
- tests/integration/conftest.py
- tests/integration/feature_manager/test_feature_manager.py
- tests/integration/query_graph/test_online_serving.py
- tests/unit/conftest.py
- tests/unit/feature_manager/test_model.py
- tests/unit/feature_manager/test_unit_snowflake_feature.py
- tests/unit/service/test_feature_manager.py
- tests/unit/service/test_feature_table_cache.py
- tests/unit/service/test_historical_features.py
- tests/unit/tile/test_unit_snowflake_tile.py
This updates the tiles backfill process when enabling a deployment to reduce unnecessary tiles computation. Changes:
1. When enabling a deployment, backfill only the tiles that are required to compute the current features for the offline store tables. This is determined by a combination of feature job settings and feature derivation window.
2. When computing historical features, always run on-demand tiles generation regardless of whether the feature list is deployed.
| `bug`, `refactoring`, …
> [DEV-3365] Backfill only required tiles for offline store tables on deploying

- .changelog/DEV-3383.yaml
- featurebyte/query_graph/node/binary.py
- featurebyte/query_graph/sql/feature_compute.py
- tests/fixtures/expected_feature_sql_combined_simple_aggregate_and_window_aggregate.sql
- tests/fixtures/expected_get_online_features_multiple_queries_batch_request_table.sql
- tests/fixtures/expected_get_online_features_multiple_queries_dataframe.sql
- tests/fixtures/expected_historical_requests_multiple_batches_feature_set_0.sql
- tests/fixtures/expected_online_feature_retrieval_filled_versions.sql
- tests/fixtures/expected_online_feature_retrieval_filled_versions_multiple_groups.sql
- tests/fixtures/expected_online_feature_retrieval_mixed.sql
- tests/fixtures/expected_online_feature_retrieval_request_subquery.sql
- tests/fixtures/expected_preview_sql_aggregate_asat.sql
- tests/fixtures/expected_preview_sql_aggregate_asat_offset.sql
- tests/fixtures/expected_preview_sql_all_types.sql
- tests/fixtures/expected_preview_sql_item_groupby.sql
- tests/fixtures/feature_materialize/initialize_features_no_entity_databricks_unity.sql
- tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
- tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
This applies explicit casting for features with integer dtype to BIGINT. This is to ensure predictable data types for the columns in the feature table and facilitate code generation for databricks on demand functions. …
> [DEV-3383] Apply casting for features with int dtype in feature query

- featurebyte/service/exception.py
- featurebyte/service/offline_store_feature_table_construction.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This adds handling for offline stores feature table in a bad state when disabling a deployment. This is to ensure that the process of disabling a deployment can always complete to free up resources.
| …
> [DEV-3312] Handle offline store feature table bad state when disabling a deployment

- featurebyte/schema/worker/task/online_store_initialize.py
The `CATALOG_ONLINE_STORE_UPDATE` task should be a cpu task since it involves features materialization, similar to the `SCHEDULED_FEATURE_MATERIALIZE` task. …
> [chore] Update online store update task to be cpu task

- .changelog/DEV-3382.yaml
- featurebyte/query_graph/sql/interpreter/preview.py
- tests/fixtures/query_graph/expected_describe_batches_0.sql
- tests/fixtures/query_graph/expected_describe_databricks.sql
- tests/fixtures/query_graph/expected_describe_snowflake.sql
- tests/fixtures/query_graph/expected_describe_spark.sql
- tests/fixtures/query_graph/expected_describe_stats_names.sql
- tests/integration/api/test_view_describe.py
- tests/unit/service/test_observation_table.py
This fixes an error when attempting to run describe on timestamp columns with invalid values. Longer term, there should be validation to inform users on such issues but for now this should prevent the error from occurring. …
> [DEV-3382] Fix describe error on timestamp columns with invalid values

- Taskfile.yaml
The new cmd syntax doesn't work for older versions of task.
> [chore] Use compatible cmds syntax for test-teardown task

- featurebyte/feast/patch.py
- featurebyte/service/online_serving.py
This PR patches `BaseFeatureView.with_projection` method to avoid `O(N^2)` validation checks.
Settings: 
* Deployment of a feature list of ~750 features
* Online store: Redis
Time to retrieve online features
Before: 19s
After: 5s …
> [DEV-3321] Patch `BaseFeatureView.with_projection` to improve runtime performance

- featurebyte/_overrides/typechecked_override.py
- featurebyte/app.py
- featurebyte/feast/patch.py
This PR patches `typechecked` in `Feast` package to improve online features retrieval performance.
Settings: 
* Deployment of a feature list of ~750 features
* Online store: Redis
Time to retrieve online features (`Feast get_online_features`, after Feast feature store is cached)
Before: 5s
After: 3.8s …
> [chore] Patch `typechecked` in Feast

- featurebyte/models/entity_lookup_feature_table.py
- featurebyte/models/entity_universe.py
- featurebyte/models/item_table.py
- featurebyte/models/parent_serving.py
- featurebyte/models/precomputed_lookup_feature_table.py
- featurebyte/routes/registry.py
- featurebyte/service/item_table.py
- featurebyte/service/parent_serving.py
- tests/fixtures/offline_store_feature_table/item_id_to_item_type_universe.sql
- tests/integration/conftest.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/conftest.py
- tests/unit/service/test_offline_store_feature_table_manager.py
- tests/unit/service/test_parent_serving.py
This updates the item table lookup universe to filter by event timestamps using previous materialization timestamp. This prevents unnecessary materialization for item ids that have already been materialized. …
> [DEV-3028] Update item table lookup universe to filter by event timestamps

- featurebyte/query_graph/node/generic.py
- featurebyte/query_graph/sql/aggregator/forward.py
- tests/fixtures/aggregator/expected_forward_aggregator.sql
- tests/fixtures/aggregator/expected_forward_aggregator_offset.sql
- tests/fixtures/request_payloads/target.json
- tests/unit/api/aggregator/test_forward_aggregator.py
- tests/unit/query_graph/sql/aggregator/test_forward.py
- tests/unit/query_graph/test_definition.py
- tests/unit/service/test_feature_table_cache.py
This adds support for offset parameter in forward aggregate node in query graph. This is to support defining forward aggregation target with an offset, which will be added in a next PR.
| …
> [DEV-3408] Add offset parameter in forward aggregate node

- .changelog/DEV-3408.yaml
- featurebyte/api/aggregator/forward_aggregator.py
- featurebyte/api/groupby.py
- featurebyte/query_graph/node/generic.py
- tests/fixtures/sdk_code/forward_aggregate_target_code_generation.py
- tests/integration/api/test_target_correctness.py
- tests/unit/api/aggregator/test_forward_aggregator.py
- tests/unit/api/test_target.py
This adds offset parameter to forward_aggregate method to support creating forward aggregation target with a shifted window.
> [DEV-3408] Add offset parameter to forward_aggregate method

- featurebyte/session/base_spark.py
This updates `register_table` method in `BaseSparkSession` to use a simpler select from parquet syntax.
> [chore] Simplify creation of table from parquet file in BaseSparkSession

- featurebyte/schema/feature_job_setting_analysis.py
This PR fixes backward compatibility issue for feature job setting analysis payload schema to support older payload format.
> [chore] Fix backward compatibility issue for feature job setting analysis backtest endpoint schema

- featurebyte/query_graph/sql/feature_historical.py
- featurebyte/query_graph/sql/online_serving.py
- featurebyte/session/base.py
- featurebyte/session/base_spark.py
- featurebyte/session/databricks_unity.py
- featurebyte/session/snowflake.py
- featurebyte/session/sqlite.py
- featurebyte/worker/task/observation_table_upload.py
- tests/integration/api/test_change_view_operations.py
- tests/integration/api/test_distance_operations.py
- tests/integration/api/test_observation_table.py
- tests/integration/api/test_scd_view_operations.py
- tests/integration/api/test_serving_parent_features.py
- tests/integration/api/test_vector_aggregation_operations.py
- tests/integration/conftest.py
- tests/integration/session/test_base.py
- tests/integration/session/test_comment.py
- tests/integration/session/test_spark.py
- tests/integration/tile/test_tile_cache.py
- tests/integration/udf/test_object_agg.py
- tests/unit/session/test_databricks_session.py
- tests/util/helper.py
This removes a few unused options in BaseSession:
1. `temporary` flag in `register_table()` which is always set to False in non-test code paths
2. `register_table_with_query()` which is unused
| …
> [chore] Remove temporary parameter in register_table

- CHANGELOG.md
- featurebyte/__init__.py
- featurebyte/config.py
- pyproject.toml
- tests/unit/test_config.py
Use workspace home as default config path in databricks environment.
> [chore] Use workspace home as default config path in databricks environment

- featurebyte/schema/scd_table.py
- tests/unit/api/test_change_view.py
- tests/unit/api/test_scd_table.py
- tests/unit/test_generate_payload_fixtures.py
This PR updates SCDTable registration logic to set default feature job setting during table registration.
> [DEV-3506] Set default feature job setting during SCDTable registration

- tests/integration/udf/test_object_agg.py
Seeing some strange flaky tests recently:
E.g. https://github.com/featurebyte/featurebyte/actions/runs/9475724079/job/26107489803
This could be a possible source of flakiness (same table name was used for event table in integration tests) though I was not able to reproduce the same error locally. …
> [chore] Use a different test table name to avoid collision

- featurebyte/__init__.py
- scripts/enforce_import_rules.py
- tests/unit/api/test_feature_store.py
- tests/unit/test_init.py
Make sdk version check less stringent, only display warning on minor version mismatch.
> [chore] Make sdk version check less stringent

- featurebyte/service/base_document.py
- tests/unit/service/test_base_document.py
This PR updates `update_document` method of base document service so that it behaves properly when the update document object contains field with alias. …
> [chore] Revise `update_document` by setting `by_alias=True`

- featurebyte/service/base_document.py
- tests/unit/service/test_base_document.py
Update BaseDocumentService `create_many` to not error on empty list.
> [chore] Fix create_many error when input is empty list

- .github/workflows/test.yaml
- Taskfile.yaml
`pytest-xdist` worker in snowflake integration tests is crashing very often:
```
...
[gw0] node down: Not properly terminated
[gw0] [ 21%] FAILED tests/integration/feature_store_integration/test_feature_materialize.py::test_feature_tables_expected[snowflake] 
replacing crashed worker gw0
...
```
This splits snowflake integration tests into two jobs and within each job runs tests sequentially.
|       `build`, `ci`, …
> [chore] Split snowflake integration tests and run tests sequentially

- featurebyte/models/feature_store.py
- tests/unit/api/base_table_test.py
This PR introduces `table_primary_key_entity_ids` to the main table types.
> [chore] Add table primary key entity ids property to all table models

- .changelog/DEV-3539.yaml
- featurebyte/core/accessor/count_dict.py
- featurebyte/query_graph/sql/ast/util.py
- featurebyte/typing.py
- tests/integration/api/test_dimension_view_operations.py
- tests/unit/conftest.py
- tests/unit/core/accessor/test_count_dict.py
Before this fix, using a request column derived key in dictionary feature operations triggers an error that looks like this:
```
ValidationError: 4 validation errors for GetValueFromDictionaryNode
parameters -> value
value is not a valid integer (type=type_error.integer)
parameters -> value
value is not a valid float (type=type_error.float)
parameters -> value
str type expected (type=type_error.str)
parameters -> value
value could not be parsed to a boolean (type=type_error.bool)
```
| `bug`, …
> [DEV-3539] Fix error when using request column as key in dictionary feature operations 

- featurebyte/query_graph/sql/interpreter/preview.py
- featurebyte/service/preview.py
- tests/fixtures/query_graph/expected_value_counts.sql
- tests/fixtures/query_graph/expected_value_counts_no_casting.sql
- tests/unit/query_graph/interpreter/test_preview.py
- tests/unit/service/test_preview.py
This updates the value counts query to not convert keys to string as we need to preserve the original type.
> [DEV-3538] Do not convert keys to string in value counts

- featurebyte/service/preview.py
- tests/unit/service/test_preview.py
This adds a `drop_all_null_stats` option to the describe method which disables dropping statistics will all null values. This behaviour is for producing human readable output in interactive usage, but can be inconvenient when the service is used internally for other purposes.
| …
> [chore] Add drop_all_null_stats option to PreviewService describe method

- .changelog/DEV-3559.yaml
- featurebyte/api/utils.py
Some arrow batch can have no rows that causes the client to stop the download prematurely.
> [DEV-3559] Fix materialized table download failure

- featurebyte/models/entity_universe.py
- tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
- tests/fixtures/feature_materialize/initialize_new_columns_existing_table_empty.sql
- tests/fixtures/feature_materialize/initialize_new_columns_new_table.sql
- tests/fixtures/feature_materialize/initialize_new_columns_new_table_databricks.sql
- tests/fixtures/feature_materialize/materialize_features_queries.sql
- tests/fixtures/feature_materialize/materialize_features_queries_composite_entity.sql
- tests/fixtures/feature_materialize/materialize_features_queries_composite_entity_batch.sql
- tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup_ttl.sql
- tests/fixtures/feature_materialize/scheduled_materialize_features_queries.sql
- tests/fixtures/offline_store_feature_table/latest_aggregation_with_window_universe.sql
- tests/fixtures/offline_store_feature_table/latest_aggregation_without_window_universe.sql
- tests/unit/models/test_entity_universe.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This applies casting for entity columns based on the dtype information when constructing the entity universe. This is necessary to avoid schema mismatch when looking up feature tables externally in databricks. …
> [chore] Cast entity column type based on dtype in entity universe

- featurebyte/query_graph/sql/aggregator/range_join.py
- featurebyte/query_graph/sql/aggregator/window.py
This extracts the range join logic in window aggregator as a helper function. It can be reused later for aggregation without tiles.
> [chore] Refactor range join helper for reuse

- featurebyte/session/databricks_unity.py
- tests/integration/session/test_databricks_unity.py
Include table descriptions when getting table listing  in DataBricks Unity session
> [chore] Include table descriptions in databricks session list_tables

- featurebyte/models/base.py
- featurebyte/models/catalog.py
- featurebyte/routes/catalog/controller.py
- featurebyte/schema/catalog.py
- featurebyte/schema/common/base.py
- featurebyte/service/base_document.py
- featurebyte/service/catalog.py
- tests/unit/api/test_credential.py
- tests/unit/api/test_dimension_table.py
- tests/unit/api/test_entity.py
- tests/unit/api/test_event_table.py
- tests/unit/api/test_feature.py
- tests/unit/api/test_feature_list.py
- tests/unit/api/test_feature_store.py
- tests/unit/api/test_item_table.py
- tests/unit/api/test_online_store.py
- tests/unit/api/test_scd_table.py
- tests/unit/models/test_dimension_table.py
- tests/unit/models/test_entity.py
- tests/unit/models/test_event_table.py
- tests/unit/models/test_feature.py
- tests/unit/models/test_feature_list.py
- tests/unit/models/test_scd_table.py
- tests/unit/routes/test_deployment.py
- tests/unit/routes/test_target.py
- tests/unit/routes/test_target_table.py
- tests/unit/service/test_base_document.py
- tests/unit/service/test_catalog.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This PR moves soft-delete implementation from catalog service to base document service.
> [chore] Refactor base document service to support soft-delete

- poetry.lock
- pyproject.toml
+ numpy>2.0 does not work with pandas / featurebyte
+ fixing the version constraint
> [chore] adding explicit numpy version

- .changelog/DEV-3583.yaml
- featurebyte/api/aggregator/base_aggregator.py
- featurebyte/api/aggregator/base_asat_aggregator.py
- featurebyte/api/aggregator/forward_aggregator.py
- featurebyte/api/aggregator/simple_aggregator.py
- scripts/test-docs-setup.py
- tests/unit/api/aggregator/test_forward_aggregator.py
- tests/unit/api/test_aggregate_asat.py
- tests/unit/api/test_aggregate_asat_common.py
- tests/unit/api/test_forward_aggregate_asat.py
This adds more validation to raise proper error message when using the latest method in unsupported aggregation types.
> [DEV-3583] Fix validation when latest aggregation method is not supported

- featurebyte/models/offline_store_feature_table.py
- featurebyte/service/offline_store_feature_table.py
- featurebyte/service/offline_store_feature_table_construction.py
- tests/unit/service/test_offline_store_feature_table.py
- tests/unit/service/test_offline_store_feature_table_manager.py
This updates `OfflineStoreFeatureTableModel` to track `aggregation_ids` associated with the features in the feature table. This is needed to support tile tasks and feature materialization tasks coordination. …
> [DEV-3585] Track aggregation_ids in offline store feature table documents

- .changelog/DEV-3597.yaml
- featurebyte/session/base_spark.py
- featurebyte/session/databricks_unity.py
Schema and table listing fails when information schema table is missing from a catalog (happens for some external catalogs)
In such cases we will fallback to using SHOW statements to avoid schema not found errors. …
> [DEV-3597] update databricks session manager schema and table listing

- tests/conftest.py
For this environment variable to have effect, it has to be set before any feast imports.
> [chore] Disable feast usage before feast imports

- featurebyte/models/offline_store_feature_table.py
- featurebyte/service/offline_store_feature_table_construction.py
- tests/integration/feature_store_integration/test_feature_materialize.py
The `aggregation_ids` of an offline store feature table should be determined from the offline ingest graphs instead of from the features directly. …
> [chore] Fix extraction of aggregation ids for offline store feature table

- featurebyte/service/feature_materialize_scheduler.py
- featurebyte/service/feature_materialize_sync.py
- featurebyte/service/task_manager.py
- featurebyte/service/tile/tile_task_executor.py
- tests/integration/conftest.py
- tests/unit/conftest.py
- tests/unit/service/test_feature_materialize_scheduler.py
- tests/unit/service/test_feature_materialize_sync.py
- tests/unit/service/test_offline_store_feature_table_manager.py
- tests/unit/service/test_task_manager.py
This updates the feature materialize scheduler to schedule the new FeatureMaterializeSyncTask on deployment. The task handles coordination between dependent tasks and ensures feature materialize runs after required tiles are computed. …
> [DEV-3588] Schedule FeatureMaterializeSyncTask on deployment

- featurebyte/models/credential.py
- featurebyte/query_graph/node/schema.py
- featurebyte/utils/messaging.py
- tests/unit/api/test_view.py
- tests/unit/models/test_credential.py
- tests/unit/routes/test_feature_store.py
Update gcs credential format to accept service account info as either dict or json string
> [chore] Update gcs credential format

- featurebyte/routes/lazy_app_container.py
- tests/unit/routes/test_lazy_app_container.py
This refactors the `_get_key` method in `LazyAppContainer` to do DFS and instance building in one go. It is simpler and more efficient without expensive operations such as membership check using list, etc.
Profiling result from app unit tests below.
Before:
After:
| …
> [chore] Refactor and speed up app container get key method

- featurebyte/models/feature_materialize_run.py
- featurebyte/routes/deployment/api.py
- featurebyte/routes/deployment/controller.py
- featurebyte/routes/registry.py
- featurebyte/schema/deployment.py
- featurebyte/service/base_document.py
- featurebyte/service/feature_job_history_service.py
- featurebyte/service/feature_list.py
- featurebyte/service/feature_materialize_run.py
- featurebyte/service/feature_materialize_sync.py
- tests/unit/routes/test_deployment.py
- tests/unit/service/fixtures_feature_materialize_runs.py
- tests/unit/service/test_feature_job_history.py
- tests/unit/service/test_feature_materialize_run.py
- tests/unit/service/test_feature_materialize_sync.py
This adds an API route to retrieve deployment feature job history.
> [DEV-3607] Add route to retrieve deployment feature job history

- featurebyte/models/feature_list.py
- featurebyte/service/feature_job_history_service.py
- tests/unit/api/test_feature_list.py
- tests/unit/models/test_feature_list.py
- tests/unit/service/fixtures_feature_materialize_runs.py
- tests/unit/service/test_feature_job_history.py
This updates the `incomplete_tile_tasks_count` field in deployment feature job history to include failed tile tasks relevant to the deployment. …
> [DEV-3607] Filter incomplete tile tasks by aggregation id

- featurebyte/schema/deployment.py
- featurebyte/service/feature_job_history_service.py
- tests/unit/routes/test_deployment.py
- tests/unit/service/test_feature_job_history.py
This rework the structure of `DeploymentJobHistory` to group job runs by feature table so the output is easier to consume.
> [chore] Group job runs by feature table in /deployment/job_history

- docker/docker-compose.yml
- featurebyte/query_graph/sql/interpreter/preview.py
- featurebyte/service/preview.py
- tests/fixtures/expected_describe_request.sql
- tests/fixtures/query_graph/expected_describe_batches_0.sql
- tests/fixtures/query_graph/expected_describe_batches_1.sql
- tests/fixtures/query_graph/expected_describe_count_based_stats_only.sql
- tests/fixtures/query_graph/expected_describe_databricks.sql
- tests/fixtures/query_graph/expected_describe_date_range_and_size.sql
- tests/fixtures/query_graph/expected_describe_snowflake.sql
- tests/fixtures/query_graph/expected_describe_spark.sql
- tests/fixtures/query_graph/expected_describe_stats_names.sql
- tests/fixtures/query_graph/expected_value_counts.sql
- tests/fixtures/query_graph/expected_value_counts_no_casting.sql
- tests/unit/query_graph/interpreter/test_preview.py
- tests/unit/routes/test_feature_store.py
- tests/unit/service/test_observation_table.py
This updates describe queries to sample input data once and then reuse it.
> [DEV-3627] Reuse sampled data when executing describe queries

- docker/docker-compose.yml
- featurebyte/query_graph/sql/interpreter/preview.py
- featurebyte/service/preview.py
- tests/fixtures/expected_describe_request.sql
- tests/fixtures/query_graph/expected_describe_batches_0.sql
- tests/fixtures/query_graph/expected_describe_batches_1.sql
- tests/fixtures/query_graph/expected_describe_count_based_stats_only.sql
- tests/fixtures/query_graph/expected_describe_databricks.sql
- tests/fixtures/query_graph/expected_describe_date_range_and_size.sql
- tests/fixtures/query_graph/expected_describe_snowflake.sql
- tests/fixtures/query_graph/expected_describe_spark.sql
- tests/fixtures/query_graph/expected_describe_stats_names.sql
- tests/fixtures/query_graph/expected_value_counts.sql
- tests/fixtures/query_graph/expected_value_counts_no_casting.sql
- tests/unit/query_graph/interpreter/test_preview.py
- tests/unit/routes/test_feature_store.py
- tests/unit/service/test_observation_table.py
Cherry pick https://github.com/featurebyte/featurebyte/pull/2475.
> [cherry-pick][DEV-3627] Reuse sampled data when executing describe queries

- featurebyte/routes/feature_store/controller.py
- featurebyte/service/preview.py
- tests/unit/routes/test_feature_store.py
- tests/unit/service/test_preview.py
- tests/unit/service/test_specialized_dtype.py
This updates PreviewService to allow long running queries by default. It is disabled for interactive queries triggered by feature store routes. …
> [DEV-3641] Update PreviewService to allow long running queries by default

- featurebyte/query_graph/sql/interpreter/preview.py
- featurebyte/service/preview.py
- tests/fixtures/query_graph/expected_value_counts_sampled_data.sql
- tests/unit/query_graph/interpreter/test_preview.py
This updates PreviewService to do value counts without sorting full table by providing the `total_row_num` parameter when constructing the sample sql. …
> [DEV-3642] Update PreviewService to do value counts without sorting full table

- featurebyte/query_graph/sql/parent_serving.py
- tests/unit/query_graph/test_parent_serving.py
Allows specifying a `table_details` for the request table when calling `construct_request_table_with_parent_entities`.
> [chore] Support fully qualified request table name for join parent entities helper

- featurebyte/service/query_cache.py
- featurebyte/service/query_cache_manager.py
- tests/unit/service/test_query_cache_manager.py
Add time buffer when retrieving stale cache records for cleanup. This is to ensure that the cached table name is not being used during cleanup.  …
> [DEV-3644] Add time buffer when retrieving stale cache records for cleanup

- featurebyte/query_graph/sql/ast/join.py
- tests/fixtures/expected_feature_sql_combined_simple_aggregate_and_window_aggregate.sql
- tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
- tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
- tests/integration/api/test_dimension_view_operations.py
- tests/integration/api/test_item_view_operations.py
- tests/integration/api/test_view_sample.py
- tests/unit/api/test_item_view.py
- tests/unit/api/test_timezone_offset.py
- tests/unit/models/test_entity_universe.py
- tests/unit/query_graph/test_join.py
This adds deduplication of right table in simple joins to avoid explosion when joining with tables with incorrect primary key (e.g. bad dimension table). …
> [DEV-3657] Deduplicate right table in simple join

- featurebyte/query_graph/sql/parent_serving.py
- tests/unit/query_graph/test_parent_serving.py
Allows specifying a `table_details` for the request table when calling `construct_request_table_with_parent_entities`.
Cherry pick: #2504 …
> [chore] Support fully qualified request table name for join parent entities helper (main)

- .github/workflows/test-notebooks.yaml
- .github/workflows/test.yaml
- poetry.lock
- pyproject.toml
- tests/integration/api/test_event_view_operations.py
- tests/integration/api/test_feature_correctness.py
- tests/unit/common/test_validator.py
+ Allow using pandas 2.
+ Fix workflow warnings
+ Breaking / Deprecation
+ `pd.Timedelta("1y")`
+ no more automatic conversion `pd.Series[pd.Timestamp] - pd.Series[pd.Timestamp] => pd.Series[timedelta]`
For most of our execution, we are doing a translation to the SQL equivalent code.  However, there are instances that we do create python UDF's that will execute the generated code. Not sure how prevalent those are, but it would be breaking.
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes …
> [chore] Bumping pandas to support 2.0

- .changelog/DEV-3673.yaml
- featurebyte/api/item_table.py
- featurebyte/query_graph/model/table.py
- tests/unit/api/test_item_view.py
This PR revises `ItemTable.get_view()` to avoid throwing column name conflict error when no parameters is provided.
> [DEV-3673] Resolve conflict column name in `ItemTable.get_view()` by default

- Taskfile.yaml
- tests/integration/conftest.py
This updates the custom `pytest_collection_modifyitems` handler to conditionally skip tests to better handle source types that are still work in progress. …
> [chore] Update pytest collection to handle work in progress source types

- featurebyte/query_graph/sql/adapter/__init__.py
- featurebyte/query_graph/sql/adapter/bigquery.py
- tests/integration/conftest.py
- tests/integration/udf/test_object_agg.py
- tests/unit/query_graph/test_adapter.py
This adds support for the OBJECT_AGG aggregation function for BigQuery.
> [DEV-3680] Support OBJECT_AGG aggregation function for BigQuery

- featurebyte/service/feature_table_cache.py
- featurebyte/service/feature_table_cache_metadata.py
- featurebyte/sql/tile_generate_entity_tracking.py
- tests/integration/api/test_historical_features.py
- tests/unit/service/test_feature_table_cache.py
This fixes the handling of feature table cache to support concurrent historical features requests on the same observation table. Similar to tile tables, empty feature cache tables will be created first and then be merged into. …
> [DEV-3676] Fix feature table cache handling for concurrent requests

- featurebyte/service/feature_table_cache.py
- featurebyte/service/feature_table_cache_metadata.py
- featurebyte/sql/tile_generate_entity_tracking.py
- tests/integration/api/test_historical_features.py
- tests/integration/conftest.py
- tests/unit/service/test_feature_table_cache.py
This fixes the handling of feature table cache to support concurrent historical features requests on the same observation table. Similar to tile tables, empty feature cache tables will be created first and then be merged into.
Cherry pick: #2530 …
> [DEV-3676] Fix feature table cache handling for concurrent requests (main)

- featurebyte/query_graph/sql/adapter/bigquery.py
- featurebyte/session/bigquery.py
- tests/integration/conftest.py
Fix detection of array dtype when listing table schema / constructing a source table object.
> [DEV-3686] BigQuery: Fix detection of array dtype when listing table schema

- featurebyte/migration/service/data_warehouse.py
- featurebyte/migration/service/mixin.py
- featurebyte/session/base.py
- tests/unit/session/test_base.py
Add retry to sql execution on timeout for better resilience when compute cluster has heavy load
> [DEV-3682] Add retry to sql execution on timeout

- featurebyte/query_graph/sql/adapter/base.py
- featurebyte/query_graph/sql/adapter/bigquery.py
- featurebyte/query_graph/sql/ast/tile.py
- featurebyte/query_graph/sql/scd_helper.py
- featurebyte/query_graph/sql/tile_compute.py
- featurebyte/sql/base.py
- featurebyte/tile/tile_cache.py
- tests/fixtures/expected_preview_sql.sql
- tests/fixtures/expected_preview_sql_all_types.sql
- tests/fixtures/expected_preview_sql_category.sql
- tests/fixtures/expected_preview_sql_complex_feature.sql
- tests/fixtures/expected_preview_sql_databricks.sql
- tests/fixtures/expected_preview_sql_double_aggregation.sql
- tests/fixtures/expected_preview_sql_item_groupby.sql
- tests/fixtures/expected_preview_sql_latest_aggregation.sql
- tests/fixtures/expected_preview_sql_latest_aggregation_no_window.sql
- tests/fixtures/expected_preview_sql_multiple_nodes.sql
- tests/fixtures/expected_preview_sql_on_demand_features.sql
- tests/fixtures/expected_preview_sql_with_missing_value_imputation.sql
- tests/fixtures/expected_preview_sql_with_parent_serving_preparation.sql
- tests/fixtures/expected_preview_window_offset.sql
- tests/integration/api/test_scd_view_operations.py
- tests/integration/conftest.py
This adds support for SCD view operations in BigQuery. Changes:
1. Add `lag_ignore_nulls` adapter override since BigQuery `LAG` window function doesn't support the `IGNORE NULLS` option. This is needed to support SCD joins.
2. Fix compatibility for various datetime operations
| …
> [DEV-3697] BigQuery: Support SCD view operations

- .github/workflows/documentation.yaml
- .github/workflows/test.yaml
- Taskfile.lint.yaml
A new `actions/upload-artifact@v4.4.0` version ignores hidden file by default
```diff
- name: Upload coverage results
uses: actions/upload-artifact@v4.4.0
with:
name: python-${{ matrix.python-version }}-.coverage.2
path: .coverage.2
+         include-hidden-files: true
```
| …
> [bug] fixing artifact publish action defaulting to not adding hidden file

- featurebyte/query_graph/sql/adapter/base.py
- featurebyte/query_graph/sql/adapter/bigquery.py
- featurebyte/query_graph/sql/adapter/databricks.py
- featurebyte/query_graph/sql/adapter/snowflake.py
- featurebyte/sql/bigquery/F_GET_VALUE.sql
- featurebyte/tile/tile_cache.py
- tests/integration/api/test_dimension_view_operations.py
- tests/integration/conftest.py
- tests/unit/session/test_bigquery_session.py
This adds support for more dictionary operations in BigQuery.
> [DEV-3707] BigQuery: Support more dictionary operations

- featurebyte/models/request_input.py
- featurebyte/query_graph/sql/adapter/base.py
- featurebyte/query_graph/sql/adapter/bigquery.py
- tests/fixtures/request_input/materialize_bigquery.sql
- tests/integration/api/test_view_sample.py
- tests/integration/conftest.py
- tests/unit/conftest.py
- tests/unit/models/test_request_input.py
Fix an observation table creation error for BigQuery because the table sample clause is not supported for views. We will use a different random sampling method for BigQuery. …
> [DEV-3711] BigQuery: Fix observation table creation by sampling from view

- featurebyte/query_graph/sql/ast/count_dict.py
- tests/integration/conftest.py
- tests/unit/query_graph/test_sql.py
This adds explicit casting of key to string in `get_rank` and `get_relative_frequency` operations. Previously this was relying on the implicit casting to string behaviour while the UDFs were expecting the specified key to be of string type. …
> [DEV-3721] BigQuery: Cast key to string in get_rank and get_relative_frequency

- featurebyte/query_graph/sql/adapter/base.py
- featurebyte/query_graph/sql/adapter/bigquery.py
- tests/fixtures/adapter/bigquery_random_sample.sql
- tests/fixtures/request_input/materialize_bigquery.sql
- tests/unit/query_graph/sql/adapter/test_bigquery.py
Sorting is unnecessary when random sampling for bigquery since the `RAND` function doesn't support seed.
> [DEV-3722] BigQuery: Disable unnecessary sort in random_sample

- featurebyte/session/base.py
- featurebyte/sql/base.py
- tests/integration/conftest.py
- tests/unit/feature_manager/test_unit_snowflake_feature.py
Previously, legitimate errors that cause table creation to fail were not surfaced properly when the `exists` flag is set. This adds validation in `create_table_as` to prevent that.
| …
> [DEV-3723] Validate table existence when create_table_as fails with exists flag

- .changelog/DEV-3718.yaml
- featurebyte/api/change_view.py
- featurebyte/api/dimension_view.py
- featurebyte/api/event_view.py
- featurebyte/api/item_table.py
- featurebyte/api/item_view.py
- featurebyte/api/scd_table.py
- featurebyte/api/scd_view.py
- featurebyte/api/source_table.py
- featurebyte/api/view.py
- featurebyte/models/entity_universe.py
- featurebyte/models/event_table.py
- featurebyte/models/item_table.py
- featurebyte/models/scd_table.py
- featurebyte/query_graph/model/table.py
- featurebyte/routes/item_table/controller.py
- featurebyte/schema/event_table.py
- featurebyte/schema/info.py
- featurebyte/schema/item_table.py
- featurebyte/schema/scd_table.py
- tests/unit/api/test_event_table.py
- tests/unit/api/test_item_table.py
- tests/unit/api/test_scd_table.py
- tests/unit/api/test_view.py
Allow some special columns (event_id, item_id, scd natural keys) to be optional during  table registration.
> [DEV-3718] Make event_id, item_id, scd natural_key_column optional for table registration

- featurebyte/session/bigquery.py
- tests/unit/session/test_bigquery_session.py
Handle non json-serializable types in bigquery RECORD fields
> [chore] Handle non json-serializable types in bigquery RECORD fields

- featurebyte/service/feature_materialize.py
- tests/fixtures/feature_materialize/initialize_new_columns_existing_table.sql
- tests/fixtures/feature_materialize/initialize_new_columns_existing_table_empty.sql
This fixes the usage of platform specific `to_timestamp` and make it compatible with BigQuery.
> [DEV-3714] BigQuery: Fix to_timestamp usage in FeatureMaterializeService for deployment

- featurebyte/query_graph/sql/ast/count_dict.py
- tests/unit/query_graph/test_sql.py
The key needs to be of string type and BigQuery doesn't perform implicit type conversion.
> [DEV-3732] BigQuery: Cast key to string in get_value

- featurebyte/session/bigquery.py
- tests/integration/api/test_datetime.py
Changes:
1. Fix an error that arises when previewing a view with DATE data type in BigQuery
2. Add a test on calculating differences between timestamp series of different underlying data types
| …
> [DEV-3731] BigQuery: Handle date type preview and add datetime diff tests

- featurebyte/query_graph/sql/adapter/bigquery.py
- featurebyte/session/bigquery.py
- featurebyte/sql/bigquery/F_GET_VALUE.sql
- tests/integration/udf/test_get_value.py
Changes:
1. Handle null dictionaries in `F_GET_VALUE` UDF
2. Specify wide number mode to avoid error in `PARSE_JSON`
> [DEV-3734] BigQuery: Fix errors in F_GET_VALUE and PARSE_JSON

- .changelog/DEV-3727.yaml
- featurebyte/api/obs_table/utils.py
- featurebyte/api/source_table.py
- featurebyte/api/view.py
- featurebyte/models/observation_table.py
- featurebyte/models/request_input.py
- featurebyte/query_graph/sql/common.py
- featurebyte/schema/observation_table.py
- featurebyte/worker/task/observation_table.py
- tests/fixtures/request_payloads/observation_table.json
- tests/integration/api/test_observation_table.py
- tests/unit/api/observation_table/test_utils.py
- tests/unit/models/test_request_input.py
- tests/unit/routes/test_target_table.py
Add support for sampling by time range during registration of observation tables from source table or view.
> [DEV-3727] Add support for sampling by time range during observation table registration

- featurebyte/feast/patch.py
- featurebyte/service/online_serving.py
- tests/unit/feast/test_patch.py
Previous Feast upgrade PR (https://github.com/featurebyte/featurebyte/pull/2588) drops `get_transformed_features_df` patch as the method has been removed from Feast. After testing the online features request performance, the online features request for a feature list with 380+ features increase from 3s to 2 minutes. This PR adds a `transform_arrow` patch that functions similar to `get_transformed_features_df` in previous version. With this patch, the online request performance is comparable with the performance before recent Feast upgrade.
|       `enhancement`, …
> [DEV-3743] Add transform_arrow patch to fix performance issue

- featurebyte/query_graph/sql/aggregator/window.py
- featurebyte/query_graph/sql/specs.py
- featurebyte/query_graph/sql/tiling.py
- tests/unit/query_graph/test_feature_common.py
- tests/unit/query_graph/test_feature_compute.py
- tests/unit/query_graph/test_tiling.py
This updates the `merge` methods in `tiling.py` to return `Expression` type instead of str type and use fully qualified names when calling UDFs for vector aggregation. …
> [DEV-3737] BigQuery: Fix UDF calls in tiling.py to use fully qualified names

- .changelog/DEV-3751.yaml
- featurebyte/routes/item_table/controller.py
- featurebyte/service/item_table.py
- tests/unit/api/test_item_table.py
- tests/unit/routes/test_item_table.py
- tests/unit/service/conftest.py
Add validation for event ID column data types between item and event table during item table registration.
> [DEV-3751] Add validation for event ID column dtypes

- featurebyte/api/aggregator/util.py
- tests/unit/api/aggregator/test_forward_aggregator.py
- tests/util/helper.py
This PR addresses `skip_fill_na` warnings thrown during tests running.
> [chore] Fix `skip_fill_na` deprecation warning

- featurebyte/query_graph/node/input.py
- featurebyte/query_graph/sql/adapter/base.py
- featurebyte/query_graph/sql/adapter/bigquery.py
- featurebyte/query_graph/sql/ast/input.py
- featurebyte/query_graph/sql/interpreter/preview.py
- tests/fixtures/adapter/bigquery_random_sample.sql
- tests/fixtures/query_graph/expected_sample_sql_disable_sort_by_prob.sql
- tests/fixtures/request_input/materialize_bigquery.sql
- tests/unit/query_graph/interpreter/test_preview.py
This updates the random sampling for BigQuery to perform sorting by prob by default unless explicitly disabled. The sorting is needed to correct for oversampling bias.
Cherry pick #2604 
| …
> [DEV-3761] BigQuery: Enable sorting by probability by default when sampling (cherry-pick)

- .changelog/DEV-3744.yaml
- featurebyte/api/base_table.py
- featurebyte/api/entity.py
- featurebyte/models/entity.py
- featurebyte/routes/registry.py
- featurebyte/schema/entity.py
- featurebyte/service/table_columns_info.py
- tests/conftest.py
- tests/integration/api/test_vector_aggregation_operations.py
- tests/integration/conftest.py
- tests/unit/api/test_dimension_view.py
- tests/unit/api/test_entity.py
- tests/unit/api/test_event_table.py
- tests/unit/api/test_feature.py
- tests/unit/api/test_feature_list.py
- tests/unit/api/test_item_view.py
- tests/unit/api/test_offline_ingest_query_graph.py
- tests/unit/api/test_table.py
- tests/unit/conftest.py
- tests/unit/models/test_entity.py
- tests/unit/service/test_online_serving_feast.py
- tests/unit/service/test_table_columns_info.py
This PR implements entity dtype validation. When entity is associated with a table column,
* it will initiate entity dtype if the entity has been used by another table column;
* it will throw error if entity dtype inconsistency is detected (user has to resolve the inconsistency first before using it in any other table column);
* checks whether the dtype of the column to be associated is consistent with existing column(s) of the same entity.
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes …
> [chore] Implement entity dtype validation to enforce dtype consistency

- featurebyte/query_graph/sql/ast/util.py
- tests/integration/conftest.py
- tests/unit/query_graph/test_sql.py
This fixes binary operations with a scalar timestamp that can fail in BigQuery if the timestamp column is `TIMESTAMP` and not `DATETIME`. …
> [DEV-3714] BigQuery: Fix binary operations with a scalar timestamp

- featurebyte/session/bigquery.py
- tests/integration/session/test_bigquery.py
This fixes an error in BigQuery session's `register_table` when a timestamp column contains native datetime objects.
> [DEV-3766] BigQuery: Fix handling native datetime objects in session register_table

- Taskfile.lint.yaml
Do use use `--diff` option in ruff style check commands since that can cause the exit code be 0 in some cases even when there are violations. (e.g. the violation that this commit https://github.com/featurebyte/featurebyte/pull/2612/commits/e26989aa141dcd0494306041b03b3da30c7dd781 would fix but `task lint:style-ruff` didn't detect that violation).
| …
> [chore] Do not use --diff option in ruff style checks

- featurebyte/app.py
- featurebyte/models/system_metrics.py
- featurebyte/routes/common/base.py
- featurebyte/routes/registry.py
- featurebyte/routes/system_metrics/api.py
- featurebyte/routes/system_metrics/controller.py
- featurebyte/schema/system_metrics.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/feature_table_cache.py
- featurebyte/service/historical_features.py
- featurebyte/service/historical_features_and_target.py
- featurebyte/service/system_metrics.py
- featurebyte/service/target_helper/base_feature_or_target_computer.py
- featurebyte/service/target_helper/compute_target.py
- featurebyte/service/tile/tile_task_executor.py
- featurebyte/worker/task/historical_feature_table.py
- tests/fixtures/backward_compatibility/get_routes.txt
- tests/integration/api/test_event_view_operations.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/integration/tile/test_schedule_generate_tile.py
- tests/unit/service/test_feature_table_cache.py
- tests/unit/service/test_system_metrics.py
- tests/util/helper.py
This adds a new service and API to allow tracking and programatically retrieving of internal system metrics.
Currently metrics are tracked in these tasks: historical features computation tasks, scheduled tile tasks, scheduled feature materialize tasks.
| …
> [chore] Add service and API to track internal system metrics

- .changelog/DEV-3735.yaml
- featurebyte/query_graph/sql/online_serving.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/feature_preview.py
- featurebyte/service/feature_table_cache.py
- featurebyte/service/historical_features_and_target.py
- featurebyte/service/online_serving.py
- featurebyte/service/preview.py
- featurebyte/service/target_helper/compute_target.py
- featurebyte/service/tile_manager.py
- featurebyte/session/session_helper.py
- featurebyte/tile/tile_cache.py
- featurebyte/utils/async_helper.py
- tests/unit/conftest.py
- tests/unit/session/test_session_helper.py
Enforce application-wide concurrency limit on long running SQL execution to avoid overwhelming the feature store.
> [DEV-3735] Enforce application-wide concurrency limit on long running SQL execution

- .changelog/DEV-3790.yaml
- featurebyte/models/credential.py
- featurebyte/schema/credential.py
- tests/fixtures/request_payloads/credential.json
- tests/unit/api/test_credential.py
- tests/unit/conftest.py
- tests/unit/routes/test_credential.py
Implementing group based featurestore credentials for easier management of secrets.
> [DEV-3790] Supporting credentials to group

- Taskfile.yaml
Update default spark version for local test env to 3.5.0 to match with CI.
> [chore] Update default spark version for local test env to 3.5.0

- .changelog/DEV-3765.yaml
- featurebyte/routes/common/base_materialized_table.py
- featurebyte/routes/historical_feature_table/api.py
- featurebyte/routes/historical_feature_table/controller.py
- featurebyte/service/feature_store_warehouse.py
- tests/unit/routes/test_historical_feature_table.py
Add route to preview feature in historical feature table.
> [DEV-3765] Add route to preview feature in historical feature table

- .changelog/DEV-3802.yaml
- featurebyte/exception.py
- featurebyte/routes/task/api.py
- featurebyte/routes/task/controller.py
- featurebyte/schema/task.py
- featurebyte/schema/worker/task/base.py
- featurebyte/service/task_manager.py
- featurebyte/worker/test_util/random_task.py
- tests/unit/conftest.py
- tests/unit/routes/test_task.py
- tests/unit/service/test_query_cache_manager.py
- tests/unit/service/test_task_manager.py
- tests/unit/worker/test_task_executor.py
Implement functionality for resubmission of an unsuccessful worker task 
> [DEV-3802] Support rerunning of some tasks

- featurebyte/tile/tile_cache.py
Use long running query timeout when listing tables in tile cache to avoid timeout errors on many concurrent queries.
> [chore] Use long running query timeout when listing tables in tile cache

- featurebyte/models/task.py
- tests/unit/models/test_task.py
This PR updates `LogMessage` model to handle the case where `message` attribute is missing in progress history.
> [chore] Update log message model to handle log without message

- featurebyte/schema/deployment.py
- tests/unit/service/fixtures_feature_materialize_runs.py
- tests/unit/service/test_feature_job_history.py
The duration type in `FeatureTableJobRun` can be non-integers.
> [chore] Fix duration type in FeatureTableJobRun

- featurebyte/service/feature_table_cache.py
- tests/unit/service/test_feature_table_cache.py
This adds support for providing feature definition hashes directly in FeatureTableCacheService. In some cases (e.g. EDA), it is much faster to use the already derived definition hashes instead of deriving the hashes again from the graph. …
> [DEV-3811] Support providing definition hashes directly in FeatureTableCacheService

- .changelog/DEV-3810.yaml
- featurebyte/service/relationship.py
- tests/unit/service/test_relationship.py
Fix the issue where entity untagging removed the path that can be reached by other parents.
> [DEV-3810] Fix entity untagging bug when multiple paths exist

- featurebyte/models/feature_store.py
- featurebyte/routes/common/base_table.py
- featurebyte/service/base_table_validation.py
- tests/integration/api/test_scd_view_operations.py
- tests/unit/routes/test_event_table.py
- tests/unit/service/test_base_table_validation.py
Add a `updated_at` field in `TableValidation` model.
> [DEV-3800] Track updated timestamp in table validation field

- featurebyte/schema/worker/task/historical_feature_table.py
Make historical feature table compute rerunnable
> [chore] Make historical feature table compute rerunnable

- featurebyte/models/tile_cache.py
- featurebyte/routes/registry.py
- featurebyte/service/tile_cache.py
- featurebyte/service/tile_cache_query_by_entity.py
- tests/integration/api/test_event_view_operations.py
- tests/integration/tile/test_tile_cache.py
- tests/unit/service/test_historical_features.py
- tests/unit/service/tile/test_tile_cache.py
This refactors TileCache as a proper service and rename it to TileCacheQueryByEntityService. Will add a new tile cache implementation that is observation table specific in a next PR.
| …
> [chore] Refactor TileCache as a proper service

- featurebyte/service/query_cache_cleanup.py
- tests/unit/service/test_query_cache_manager.py
This adds error handling in query cache cleanup task to prevent orphaned tables / objects on cleanup errors.
> [chore] Add error handling and logging in query cache cleanup task

- .changelog/DEV-3827.yaml
- featurebyte/service/tile_cache_query_by_entity.py
- tests/integration/tile/test_tile_cache.py
This updates the tile cache working table query to use equal operator instead of `IS NOT DISTINCT FROM` as the join condition to improve efficiency. This was causing the query to timeout in BigQuery.
| …
> [DEV-3827] Improve tile cache working table query efficiency in BigQuery

- .changelog/DEV-3832.yaml
- featurebyte/query_graph/sql/tiling.py
- tests/integration/api/test_event_view_operations.py
- tests/integration/conftest.py
- tests/unit/query_graph/test_tiling.py
Min/max aggregations on timestamp columns were failing because the tile column types were not set correctly.
> [DEV-3832] Fix error in min/max aggregations on timestamp columns for historical features

- featurebyte/models/system_metrics.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/feature_table_cache.py
- featurebyte/service/historical_features_and_target.py
- tests/integration/api/test_event_view_operations.py
- tests/unit/service/test_system_metrics.py
Add `total_seconds` to track end to end timing. Also update `feature_compute_seconds` to exclude tile compute time.
> [chore] Add total seconds for historical features and scheduled materialize metriccs

- featurebyte/models/observation_table_tile_cache.py
- featurebyte/routes/registry.py
- featurebyte/service/observation_table_tile_cache.py
- tests/unit/service/test_observation_table_tile_cache.py
Add `ObservationTableTileCacheService` to keep track of tiles that have been generated for a given observation table.
There is no functional changes yet. This will be used in a next PR to change the way tile cache behaves when materialising historical features based on an observation table. …
> [DEV-3847] Add ObservationTableTileCacheService

- featurebyte/service/feature_table_cache_metadata.py
- featurebyte/utils/async_helper.py
- featurebyte/utils/redis.py
This updates feature table cache metadata service to acquire a lock before creating or updating cache metadata documents in order to handle concurrent queries.
Without this, multiple cache metadata documents might be created unnecessarily and causes tests failures such as 
> FAILED tests/integration/api/test_historical_features.py::test_get_historical_feature_tables_parallel[databricks_unity] - AssertionError: assert 4 == 3
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & Refactoring …
> [DEV-3807] Use lock in get_or_create_feature_table_cache

- featurebyte/feature_manager/model.py
- featurebyte/models/tile.py
- tests/unit/feature_manager/test_model.py
Reverts featurebyte/featurebyte#2668
The attribute is actually still used, just not within this codebase.
> Revert "[chore] Remove a parameter that is not required in TileSpec"

- .changelog/DEV-3903.yaml
- featurebyte/service/tile/tile_task_executor.py
- tests/integration/tile/test_schedule_generate_tile.py
This fixes an error in scheduled tile tasks due to a missing `tile_compute_query` parameter that should be provided when constructing the `TileGenerate` object in the task. …
> [DEV-3903] Fix scheduled tile task error due to missing tile_compute_query

- featurebyte/query_graph/sql/tile_compute_combine.py
- tests/fixtures/query_graph/expected_combined_tile_query_complex_0.sql
- tests/fixtures/query_graph/expected_combined_tile_query_complex_1.sql
- tests/unit/query_graph/sql/test_tile_compute_combine.py
Impose a constraint on the number of output columns per combined tile query.
> [DEV-3904] Limit number of output columns when combining tile compute queries

- featurebyte/worker/__init__.py
Update Celery options to reduce chance of duplicate tasks since our tasks are typically long running. 
1. Increase `visibility_timeout` to avoid premature redelivery of tasks (https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/redis.html#id2)
2. Disable tasks prefetching by setting `worker_prefetch_multiplier` to 1 (https://docs.celeryq.dev/en/stable/userguide/optimizing.html#prefetch-limits)
From celery docs:
> If you have many tasks with a long duration you want the multiplier value to be one: meaning it’ll only reserve one task per worker process at a time. …
> [chore] Update Celery options to better handle long running tasks

- .changelog/DEV-3890.yaml
- featurebyte/api/deployment.py
- featurebyte/migration/service/deployment.py
- featurebyte/migration/service/feature_list.py
- featurebyte/models/deployment.py
- featurebyte/models/feature_list.py
- featurebyte/models/feature_list_store_info.py
- featurebyte/routes/deployment/controller.py
- featurebyte/routes/registry.py
- featurebyte/schema/feature_list.py
- featurebyte/service/deploy.py
- featurebyte/service/deployment.py
- featurebyte/service/feature_list.py
- featurebyte/service/offline_store_feature_table_manager.py
- tests/fixtures/migration/deployment
- tests/fixtures/migration/feature_list
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/unit/api/test_databricks.py
- tests/unit/api/test_feature_list.py
- tests/unit/models/test_feature_list.py
- tests/unit/routes/test_deployment.py
- tests/unit/service/test_deploy.py
`store_info` attribute is used to construct DataBricks feature specs definition. Currently, the attribute is stored at feature list level and it can cause issue when the feature list is deployed more than 1 with different serving entities. To address the issue, this PR moves the attribute from feature list model to deployment model.
| …
> [DEV-3890] Move `store_info` attribute from feature list to deployment model

- featurebyte/migration/service/feature_list.py
This PR revises feature list migration script to add back `feast_enabled` attribute after migration.
> [chore] Revise feature list migration script

- docker/entrypoint.sh
- featurebyte/common/env_util.py
- featurebyte/service/session_manager.py
- featurebyte/session/bigquery.py
- tests/integration/conftest.py
- tests/integration/session/test_bigquery.py
Fix the issue where bigquery session creation hangs when running in IO workers due to gevent.
> [DEV-3912] Disable bigquery storage client when running in io workers

- .changelog/DEV-3913.yaml
- featurebyte/models/observation_table.py
- featurebyte/models/request_input.py
- featurebyte/query_graph/sql/feature_historical.py
- featurebyte/service/observation_table.py
- featurebyte/worker/task/observation_table.py
- scripts/enforce_import_rules.py
- tests/fixtures/request_input/materialize_bigquery.sql
- tests/integration/api/test_observation_table.py
- tests/unit/api/test_event_view.py
- tests/unit/api/test_source_table.py
- tests/unit/models/test_request_input.py
This PR makes the following changes during observation table materialization:
- Cast `sample_from_timestamp` and `sample_to_timestamp` to UTC timestamps without timezone info
- Exclude rows where mapped columns contain NULL values
- Exclude rows where `POINT_IN_TIME` is too recent for feature materialization …
> [DEV-3913] Fix observation table creation failure when datetime values or sampling contain timezone info

- docker/entrypoint.sh
- featurebyte/common/env_util.py
- featurebyte/session/bigquery.py
- tests/integration/session/test_bigquery.py
> [DEV-3912] Disable bigquery storage client when running in io workers (cherry-pick)

- featurebyte/enum.py
- featurebyte/query_graph/sql/adapter/bigquery.py
- featurebyte/query_graph/sql/adapter/snowflake.py
- tests/integration/api/test_dict_operations.py
Fix materialization of FLAT_DICT type features in BigQuery.
> [DEV-3919] Fix materialization of FLAT_DICT type features in BigQuery

- featurebyte/worker/task/catalog_cleanup.py
This PR adds try-catch to model deserialization in catalog cleanup task. By doing so, older records that break backward compatibility won't block the catalog cleanup task. …
> [chore] Add try-catch to model deserialization (catalog cleanup task)

- featurebyte/common/documentation/documentation_layout.py
Add missing docs for `create_time_series_table`
> [chore] Add missing docs

- featurebyte/query_graph/enum.py
- featurebyte/query_graph/model/window.py
- featurebyte/query_graph/node/generic.py
- tests/unit/query_graph/conftest.py
- tests/unit/query_graph/test_extract_operation_structure.py
This adds a new query graph node type `TIME_SERIES_WINDOW_AGGREGATE` for window aggregates on time series tables.
> [DEV-3928] Add TIME_SERIES_WINDOW_AGGREGATE node type

- tests/unit/api/conftest.py
- tests/unit/api/test_event_view.py
- tests/unit/api/test_source_table.py
- tests/unit/api/test_time_series_view.py
- tests/unit/conftest.py
Workaround to avoid these errors when running the tests locally:
```
FAILED tests/unit/api/test_source_table.py::test_create_observation_table - featurebyte.exception.RecordCreationException: Unable to generate pydantic-core schema for <class 'datetime.datetime'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to full...
FAILED tests/unit/api/test_source_table.py::test_create_observation_table_with_sample_rows - featurebyte.exception.RecordCreationException: Unable to generate pydantic-core schema for <class 'datetime.datetime'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to full...
```
Label this pull request to …
> [chore] Avoid freezegun causing pydantic error when running tests locally

- featurebyte/api/time_series_table.py
- featurebyte/enum.py
- featurebyte/models/time_series_table.py
- featurebyte/query_graph/model/feature_job_setting.py
- tests/unit/query_graph/model/test_feature_job_setting.py
- Limit cron schedule for feature job settings to a max frequency of once per hour
- Remove support for TIMESTAMP_TZ dtype for reference datetime in time series table …
> [chore] Update cron validation to add some limitations

- .changelog/DEV-3933.yaml
- featurebyte/service/feature_table_cache.py
- tests/integration/api/test_historical_features.py
This fixes an error that can occur on concurrent materialization of feature lists with overlapping features. The fix ensures that we only insert non-existing columns when updating the columns of a feature cache table. …
> [DEV-3933] Fix concurrent materialization of feature lists with overlapping features

- featurebyte/session/base.py
`drop_table` is typically only called in long running tasks and should use a longer execute query timeout by default to avoid spurious errors. …
> [chore] Use long timeout for drop_table by default

- featurebyte/query_graph/model/timestamp_schema.py
- featurebyte/service/time_series_table.py
- tests/unit/routes/test_time_series_table.py
- Remove format_string from TimeZoneColumn 
- Add more validation for Time Series Table reference datetime schema to ensure timestamp does not contain timezone information …
> [chore] Add more validation for Time Series Table reference datetime schema

- tests/unit/conftest.py
- tests/unit/service/test_feature_materialize.py
- tests/util/helper.py
When `tests/unit/service/test_feature_materialize.py` is run standalone, some of the tests were hanging / failing.
> [chore] Fix tests in test_feature_materialize.py when run standalone

- featurebyte/models/periodic_task.py
- featurebyte/query_graph/model/feature_job_setting.py
- featurebyte/query_graph/sql/cron.py
- featurebyte/service/cron_helper.py
- tests/integration/service/test_cron_helper.py
- tests/unit/query_graph/sql/test_cron.py
- tests/unit/service/test_cron_helper.py
This updates `CronHelper` so that it can be more easily used in `get_historical_features` in a subsequent PR.
> [DEV-3930] Rework CronHelper to match usage pattern in get_historical_features

- .github/workflows/publish-dev.yaml
Invalid variable reference in publish-dev workflow
> [chore] fxing bad publish message

- featurebyte/api/aggregator/window_aggregator.py
- featurebyte/enum.py
- tests/unit/api/test_aggregate_over.py
This adds validation in `aggregate_over` on TimeSeriesView to check that the window unit is compatible with TimeSeriesTable's time interval. …
> [DEV-3945] Validate calendar window unit is compatible with time interval

- featurebyte/api/aggregator/base_aggregator.py
- featurebyte/api/aggregator/util.py
- featurebyte/core/series.py
- featurebyte/exception.py
- featurebyte/query_graph/model/timestamp_schema.py
- tests/unit/api/conftest.py
- tests/unit/api/test_aggregate_over.py
This PR prevents user to aggregate on timestamp column referencing on other offset column.
> [chore] Block user aggregating timestamp with referencing to other offset column

- featurebyte/api/source_table.py
- featurebyte/api/time_series_table.py
- featurebyte/models/time_series_table.py
- featurebyte/query_graph/model/table.py
- featurebyte/query_graph/node/input.py
- featurebyte/schema/time_series_table.py
- tests/fixtures/request_payloads/time_series_table.json
- tests/fixtures/sdk_code/time_series_table.py
- tests/unit/api/test_time_series_table.py
- tests/unit/models/test_time_series_table.py
This PR introduces `reference_timezone` parameter to time series table.
> [DEV-3940] Add reference_timezone to time series table

- featurebyte/service/feature_table_cache.py
- tests/fixtures/feature_table_cache/feature_query_sampled.sql
- tests/unit/service/test_feature_table_cache.py
Add an option to get sampled rows from feature table cache
> [DEV-3955] Add sampling option for reading from feature table cache

- featurebyte/api/aggregator/window_aggregator.py
- featurebyte/query_graph/model/timestamp_schema.py
- featurebyte/query_graph/node/schema.py
- tests/unit/api/test_aggregate_over.py
- tests/unit/query_graph/model/test_timestamp_schema.py
This adds the following validation for time series table / view:
1. Validate window unit is the same as offset unit in `aggregate_over`
2. Validate `format_string` is not provided for non-string types
| …
> [DEV-3959] Validate compatibility of window and offset unit and format_string

- featurebyte/query_graph/node/generic.py
- tests/fixtures/sdk_code/ts_window_aggregate_feature.py
- tests/unit/api/test_aggregate_over.py
- tests/unit/api/test_timestamp_timezone_tuple.py
Fix missing `reference_timezone` field in the generated code for `CronFeatureJobSetting` which can cause inconsistent feature definitions error. …
> [chore] Fix missing reference_timezone field in generated code

- tests/integration/conftest.py
Set `SNOWFLAKE_PRIVATE_KEY_PASSPHRASE` to an empty string to use a private key without passphrase in integration test.
> [chore] Add support for private key without passphrase in integration test

- featurebyte/common/progress.py
- featurebyte/worker/task/catalog_cleanup.py
- tests/unit/common/test_progress.py
This PR fixes catalog cleanup task error when the number of catalogs to be clean more than 100.
> [DEV-3963] Fix catalog cleanup task error

- featurebyte/service/table_facade.py
- tests/unit/service/test_table_facade.py
This PR updates table facade service to handle non-event-table default feature job setting update.
> [chore] Update table facade service

- featurebyte/routes/common/base.py
- featurebyte/service/base_document.py
- tests/unit/routes/test_feature_store.py
This PR fixes feature store deletion logic by considering soft deleted catalogs.
> [DEV-3967] Fix feature store deletion logic

- tests/integration/session/test_databricks_unity.py
Fix failing test:
```
FAILED tests/integration/session/test_databricks_unity.py::test_list_tables[databricks_unity] - AssertionError: assert [***'descriptio...roduct'***, ...] == [***'descriptio...stomer'***, ...]
At index 0 diff: ***'name': '__grocerycustomer', 'description': None*** != ***'name': 'invoiceitems', 'description': 'The grocery item details within each invoice, including the quantity, total cost, discount applied, and product ID.'***
Full diff:
[
+  ***'description': None, 'name': '__grocerycustomer'***,
+  ***'description': None, 'name': '__groceryinvoice'***,
+  ***'description': None, 'name': '__invoiceitems'***,
+  ***'description': 'Customer details, including their name, address, and date of '
+                  'birth.',
+   'name': 'grocerycustomer'***,
+ …
```
> [chore] Fix test_list_tables for databricks_unity

- featurebyte/service/cron_helper.py
- tests/integration/session/test_databricks_unity.py
- tests/unit/service/test_cron_helper.py
This updates `get_cron_job_schedule` to not use a hardcoded interval when determining the earliest simulated job schedule. This reduces the number of redundant time points in its output.
| …
> [chore] Reduce redundant time points in get_cron_job_schedule

- .changelog/DEV-3978.yaml
- featurebyte/session/databricks_unity.py
Fix bug in databricks unity schema listing when the user does not have access to the catalog INFORMATION_SCHEMA
> [DEV-3978] Fix bug in Databricks Unity session schema and table listing

- featurebyte/session/session_helper.py
- featurebyte/utils/async_helper.py
- tests/unit/session/test_session_helper.py
Add a `return_exceptions` option in `run_coroutines` to allow exceptions to be returned and handled by the caller. This is needed to support dynamic batching in query execution. …
> [DEV-3983] Add return_exceptions option in run_coroutines

- featurebyte/models/task.py
- featurebyte/persistent/base.py
- featurebyte/persistent/mongo.py
- featurebyte/schema/task.py
- featurebyte/service/task_manager.py
- tests/unit/service/test_task_manager.py
- Track pending (queued but not received by workers) tasks in persistent so they are visible in task listings
- Support revoking of pending tasks …
> [chore] Track queued tasks in persistent and support revoke

- featurebyte/query_graph/node/generic.py
- tests/integration/api/test_change_view_operations.py
This fixes an error related to ChangeView with timestamp schema with joined with another SCDView.
In `TRACK_CHANGES` node, special columns with timestamp schema are already converted to timestamp types. However, the timestamp columns of the ChangeView are still associated with the original timestamp schema, causing incorrect conversions in downstream operations.
To fix this, the dtype info is overwritten accordingly in the `TRACK_CHANGES` node to ensure correct handling.
| `bug`, …
> [DEV-3990] Fix ChangeView with timestamp schema error when joined with SCDView

- .changelog/DEV-3989.yaml
- featurebyte/query_graph/node/cleaning_operation.py
- featurebyte/routes/common/base_table.py
- tests/unit/api/test_event_table.py
This PR updates the columns info update logic to reset column semantic if the timestamp schema cleaning operation is added.
> [chore] Reset semantic if add timestamp schema operation is added

- .changelog/DEV-3992.yaml
- featurebyte/core/series.py
- tests/fixtures/sdk_code/feature_fraction.py
- tests/unit/api/aggregator/test_forward_aggregator.py
This updates the `__setitem__` method in `Series` to preserve the original object's name after mutable operations such as `fillna`. Without this, doing `fillna` on a `Target` object without setting name explicitly causes issues in the generated sql. There is an assumption that feature / target objects should always have PROJECT or ALIAS node types. …
> [chore] Preserve original name in mutable operations

- .changelog/DEV-3993.yaml
- featurebyte/api/scd_table.py
- featurebyte/api/scd_view.py
- featurebyte/query_graph/sql/aggregator/base_lookup.py
- featurebyte/query_graph/sql/ast/join.py
- featurebyte/query_graph/sql/scd_helper.py
- tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
- tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
- tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
- tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table.sql
- tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table_missing_column.sql
- tests/fixtures/feature_materialize/materialize_features_queries_internal_relationships.sql
- tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
- tests/fixtures/offline_store_feature_table/cust_id_to_gender_universe.sql
- tests/integration/api/test_scd_view_operations.py
- tests/integration/conftest.py
- tests/integration/session/test_databricks_unity.py
- tests/unit/api/test_scd_view.py
This fixes an issue in `scd_helper` (i.e. SCD joins and lookup features) to use the end timestamp column information when available. …
> [DEV-3993] Fix scd_helper to account for end timestamp column when available

- featurebyte/routes/common/base_table.py
- tests/unit/api/test_time_series_table.py
This PR revises column cleaning validation logic to block adding `AddTimestampSchema` cleaning operation to any special columns of a table. …
> [chore] Revise column cleaning validation logic

- featurebyte/query_graph/sql/scd_helper.py
- tests/fixtures/expected_preview_sql_timezone_offset_item_view_joined_scd_view.sql
- tests/fixtures/expected_tile_sql_complex_feature_push_down_eligible.sql
- tests/fixtures/feature_materialize/initialize_new_columns_precomputed_lookup.sql
- tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table.sql
- tests/fixtures/feature_materialize/initialize_precomputed_lookup_feature_table_missing_column.sql
- tests/fixtures/feature_materialize/materialize_features_queries_internal_relationships.sql
- tests/fixtures/feature_materialize/scheduled_materialize_features_precomputed_lookup.sql
- tests/fixtures/offline_store_feature_table/cust_id_to_gender_universe.sql
- tests/integration/api/test_scd_view_operations.py
This updates SCD end timestamp handling to skip the filter when the column is not available for any unexpected reasons.
Also fixes the handling for null values in the end timestamp column (treated to be valid records). …
> [DEV-3993] Add SCD end timestamp handling only when the column is available

- featurebyte/api/aggregator/window_aggregator.py
- featurebyte/api/groupby.py
- featurebyte/models/entity_universe.py
- featurebyte/query_graph/node/generic.py
- featurebyte/query_graph/sql/aggregator/time_series_window.py
- tests/integration/api/test_event_view_operations.py
- tests/unit/api/test_aggregate_over.py
This adds support for calendar aggregation for event tables:
* When `windows` is provided as a list of `CalendarWindow`, it activates calendar aggregation for event tables
* `feature_job_setting` must be an instance of `CronFeatureJobSetting`
* The constructed node type for the feature will be `TIME_SERIES_WINDOW_AGGREGATE`  where the underlying table is an event table instead of a time series table
|       `build`, …
> [DEV-3995] Support calendar aggregation for event tables

- featurebyte/api/aggregator/window_aggregator.py
- featurebyte/api/event_table.py
- featurebyte/api/event_view.py
- featurebyte/api/source_table.py
- featurebyte/models/entity_universe.py
- featurebyte/models/event_table.py
- featurebyte/query_graph/model/table.py
- featurebyte/query_graph/sql/ast/input.py
- featurebyte/query_graph/sql/ast/tile.py
- featurebyte/query_graph/sql/common.py
- featurebyte/query_graph/sql/entity_filter.py
- featurebyte/query_graph/sql/interpreter/tile.py
- featurebyte/query_graph/sql/tile_compute_spec.py
- featurebyte/schema/event_table.py
- tests/fixtures/request_payloads/event_table.json
- tests/integration/api/test_event_view_operations.py
- tests/integration/api/test_scd_view_operations.py
- tests/integration/conftest.py
- tests/integration/feature_store_integration/test_feature_materialize.py
- tests/integration/query_graph/test_timestamp_handler.py
- tests/unit/api/test_event_table.py
- tests/unit/api/test_event_view.py
- tests/unit/conftest.py
- tests/unit/models/test_event_table.py
This adds support for specifying a timestamp schema for the event timestamp column in a way that is consistent with `SCDTable` and `TimeSeriesTable`. …
> [DEV-3998] Support timestamp schema for event timestamp column

- featurebyte/models/batch_feature_table.py
- featurebyte/routes/batch_feature_table/controller.py
- featurebyte/schema/worker/task/batch_feature_table.py
- featurebyte/service/batch_feature_table.py
- featurebyte/worker/task/batch_feature_table.py
- tests/unit/routes/test_batch_feature_table.py
Batch feature table recreate tries to get name from parent table which can fail if the parent table is deleted.
This PR make the following changes:
- Store the name of the parent batch feature table instead of the identifier so the original parent table does not need to exist to generate the name of the new batch feature table
- Update the uniqueness constraints of batch feature table name so that the name only needs to be unique for a specific deployment
| `bug`, `refactoring`, `bugfix`, …
> [chore] Fix batch feature table recreate fails when parent table is deleted

- .changelog/DEV-3998.yaml
- featurebyte/models/entity_universe.py
- featurebyte/query_graph/enum.py
- featurebyte/query_graph/model/node_hash_util.py
- featurebyte/query_graph/model/table.py
- featurebyte/query_graph/node/input.py
- tests/fixtures/offline_store_feature_table/feature_cluster_disabled_one_feature.json
- tests/fixtures/offline_store_feature_table/feature_cluster_one_feature.json
- tests/fixtures/offline_store_feature_table/feature_cluster_two_features.json
- tests/fixtures/request_payloads/feature_iet.json
- tests/fixtures/request_payloads/feature_item_event.json
- tests/fixtures/request_payloads/feature_store_sample.json
- tests/fixtures/request_payloads/feature_sum_2h.json
- tests/fixtures/request_payloads/feature_sum_30m.json
- tests/fixtures/request_payloads/historical_feature_table.json
- tests/fixtures/request_payloads/target.json
- tests/unit/api/test_event_table.py
- tests/unit/api/test_event_view.py
- tests/unit/conftest.py
- tests/unit/models/test_entity_universe.py
- tests/unit/query_graph/conftest.py
- tests/unit/query_graph/model/test_table_data.py
- tests/unit/query_graph/test_query_graph.py
- tests/unit/routes/test_context.py
This updates `EventTableInputNodeParameters` to include the `event_timestamp_schema` field. Hashing logic is updated to exclude the field if None for backward compatibility. …
> [DEV-3998] Add event_timestamp_schema to EventTableInputNodeParameters

- featurebyte/routes/credential/controller.py
- tests/unit/api/test_credential.py
FeatureStore credentials are still holding a dangling reference to a non-existent featurestore.
We intend to do a cleanup job in the future but at the moment we are going to allow deletion and it is up to the user to cleanup any orphaned resources. …
> [chore] allow credentials to be deleted

- featurebyte/routes/credential/controller.py
- tests/unit/api/test_credential.py
#2861 
+ Allow Credentials to be deleted after featurestore is deleted
> [chore] cherry pick #2861

- featurebyte/models/observation_table.py
- featurebyte/routes/observation_table/controller.py
- featurebyte/routes/use_case/controller.py
- tests/unit/api/test_event_view.py
- tests/unit/api/test_source_table.py
- tests/unit/api/test_time_series_view.py
- tests/unit/conftest.py
- tests/unit/routes/conftest.py
- tests/unit/routes/test_target_table.py
- tests/unit/routes/test_use_case.py
- tests/unit/worker/task/test_catalog_cleanup.py
This PR blocks invalid observation table to be used as default preview table & default EDA table.
> [chore] Block invalid observation table to be used as default preview table & default EDA table

- .changelog/DEV-3999.yaml
- featurebyte/api/aggregator/window_aggregator.py
- featurebyte/api/event_table.py
- featurebyte/api/event_view.py
- featurebyte/api/item_table.py
- featurebyte/api/item_view.py
- featurebyte/exception.py
- featurebyte/models/event_table.py
- featurebyte/query_graph/model/feature_job_setting.py
- featurebyte/query_graph/model/graph.py
- featurebyte/query_graph/model/node_hash_util.py
- featurebyte/query_graph/node/generic.py
- featurebyte/schema/event_table.py
- featurebyte/service/event_table.py
- tests/unit/api/conftest.py
- tests/unit/api/test_aggregate_over.py
- tests/unit/api/test_event_table.py
- tests/unit/api/test_event_view.py
- tests/unit/api/test_item_view.py
- tests/unit/query_graph/model/test_feature_job_setting.py
This adds support for setting a cron based default feature job setting for EventTable.
Changes:
* Allow default feature job setting to have `CronFeatureJobSetting` type
* Validate that the cron based feature job setting can be converted to `FeatureJobSetting` during table update
* In `aggregate_over`, convert `CronFeatureJobSetting` to `FeatureJobSetting` for non-calendar aggregation
|       `build`, `ci`, `testing` …
> [DEV-3999] Support cron based default feature job setting for EventTable

- featurebyte/schema/info.py
- tests/unit/api/test_event_table.py
Previously `EventTable.info()` would error when the default feature job setting is cron based.
> [DEV-4019] Fix EventTable.info() for cron based default feature job setting

- featurebyte/service/version.py
- tests/unit/conftest.py
- tests/unit/service/test_version.py
Replacing `CronFeatureJobSetting` with `FeatureJobSetting` in aggregation nodes directly is not supported when creating new feature versions. This adds handling to prevent the error from occurring.
| …
> [DEV-4018] Handle cron job setting in create_new_feature_version_using_source_settings

- featurebyte/session/snowflake.py
- tests/integration/session/test_base.py
Ignore timestamp precision truncation in snowflake session retrieve as it causes query to fail 
> [chore] Ignore timestamp precision truncation in snowflake session retrieve

- featurebyte/query_graph/node/date.py
- tests/fixtures/on_demand_function/req_col_ttl_and_non_ttl.sql
- tests/unit/api/test_offline_ingest_query_graph.py
- tests/unit/query_graph/on_demand_function/test_date.py
This PR revises on demand feature view codes generation.
> [chore] Update `pd.to_datetime` to include `utc=True` in on demand feature view codes

- featurebyte/query_graph/model/feature_job_setting.py
- tests/unit/query_graph/model/test_feature_job_setting.py
Add validation for `blind_spot` in `CronFeatureJobSetting` when the field is provided as a string.
> [chore] Validate blind_spot field in cron feature job setting

- featurebyte/core/accessor/datetime.py
- featurebyte/session/base_spark.py
- featurebyte/session/databricks.py
- featurebyte/session/spark.py
- tests/integration/session/test_databricks_unity.py
Fix pyarrow conversion for decimal types in databricks when the precision is not defined.
> [chore] Fix pyarrow conversion for decimal in databricks

- featurebyte/common/env_util.py
- featurebyte/service/historical_features_and_target.py
Adds a development option to disable cleaning up of temporary tables used by feature query for debugging purposes. The  behaviour is controlled by the environment variable `FEATUREBYTE_FEATURE_QUERY_DEBUG` (set to "1" to enable). …
> [chore] Skip cleaning up of temp tables on debug mode

- featurebyte/enum.py
- tests/unit/service/test_feature_type.py
Fix feature type detection for non-embedding arrays and dict dtypes.
- Features of ARRAY type should not be detected as EMBEDDING feature since they do not have fixed lengths or contain only float values.
- Features of DICT and FLATDICT type (including deprecated MAP, STRUCT) should not be detected as  DICT feature since they may not be flat and may not have string keys or numeric values
|       `build`, `ci`, `testing` …
> [chore] Fix feature type detection for non-embedding arrays

- featurebyte/service/feature_table_cache.py
- featurebyte/service/feature_table_cache_metadata.py
- tests/unit/service/test_feature_table_cache.py
- tests/unit/service/test_feature_table_cache_metadata.py
Update `get_or_create_feature_table_cache` to:
* Check the actual number of columns in the cache table before proceeding
* Account for row index column and other columns in the observation table when checking for the columns limit
This is to handle any inconsistent metadata that are out of sync with the cache tables on the warehouse.
| …
> [DEV-4045] Check actual number of cached columns in cache table

- featurebyte/models/periodic_task.py
- featurebyte/query_graph/sql/cron.py
- tests/unit/query_graph/conftest.py
- tests/unit/query_graph/model/test_feature_job_setting.py
- tests/unit/query_graph/sql/test_cron.py
Normalize all Crontab fields to strings when comparing and hashing. This prevents duplicate CTE name errors during time series feature materialization caused by Crontab definitions with mixed types.
| …
> [chore] Fix Crontab comparison to avoid duplicate table name

- featurebyte/service/feature_table_cache.py
Skip running add columns query to feature table cache if there are no columns to insert. This might occur on concurrent requests with overlapping feature lists. …
> [chore] Skip running add columns query if no columns to insert

- featurebyte/query_graph/sql/tiling.py
- tests/unit/query_graph/test_tiling.py
Cast columns to double before std computation
> [DEV-4049] Cast columns to double before std computation

- .changelog/DEV-4052.yaml
- featurebyte/session/base.py
- featurebyte/session/bigquery.py
- featurebyte/session/databricks.py
- featurebyte/session/spark.py
- tests/integration/session/test_databricks_unity.py
Long SQL queries on Azure hosted DataBricks seem to run into a situation where connection session is lost
```
databricks.sql.exc.DatabaseError: Invalid SessionHandle: SessionHandle [165008b9-a099-48aa-95f4-42544134405c]
```
This PR introduces a re-initialization of the session and retry of the failed query when this happens …
> [DEV-4052] Re-initialize invalid session during query execution for DataBricks

- featurebyte/service/base_table_validation.py
The `num_records` parameter was not used when validating timezone information. This causes the validation to run on the full table.
> [chore] Limit number of rows when validation timezone in table validation

- featurebyte/query_graph/node/generic.py
- featurebyte/query_graph/node/metadata/sdk_code.py
- tests/fixtures/sdk_code/ts_window_aggregate_feature.py
- tests/unit/api/test_aggregate_over.py
- tests/unit/api/test_timestamp_timezone_tuple.py
Previously, feature saving would fail if the `Crontab` in the default feature job setting contains stringified integers.
> [chore] Fix inconsistent feature definition error due to crontab

- featurebyte/utils/messaging.py
- featurebyte/worker/task_executor.py
- featurebyte/worker/util/task_progress_updater.py
- tests/integration/conftest.py
- tests/integration/tile/test_tile_scheduler.py
- tests/unit/conftest.py
- tests/unit/worker/task/base.py
- tests/unit/worker/test_util.py
Use asynchronous redis client in progress updater to avoid blocking event loop
> [chore] Use async redis client in progress updater

- featurebyte/query_graph/sql/common.py
- tests/unit/routes/test_observation_table.py
This PR fixes the SQL bug when constructing missing value table.
> [chore] Fix SQL bugs when creating table for missing value

- featurebyte/service/query_cache_manager.py
Use unique remote filename when caching dataframe to avoid conflicts.
> [chore] Use unique remote filename when caching dataframe

- .github/workflows/test.yaml
- Taskfile.yaml
- tests/integration/conftest.py
Run task manager integration tests as a separate job. This allows:
1. `session` scoped fixtures (event tables, time series tables, etc) in `integration/conftest.py` to be setup with the task manager properly mocked. This allows better test coverage. Otherwise, background tasks such as table validation are skipped during the fixtures setup.
2. Quicker test re-runs since some of the task manager integration tests can be flaky.
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & Refactoring …
> [chore] Split task manager integration tests as separate job

- featurebyte/service/scd_table_validation.py
- tests/fixtures/scd_table_validation/no_end_timestamp.sql
- tests/fixtures/scd_table_validation/with_end_timestamp.sql
- tests/integration/service/test_scd_table_validation.py
Exclude null values in natural key column when running the analysis for scd table validation to tolerate an issue that might be common. …
> [chore] Update scd table validation to exclude null values in natural key column

- .changelog/DEV-4063.yaml
- featurebyte/query_graph/sql/adapter/bigquery.py
- featurebyte/query_graph/sql/adapter/databricks.py
- featurebyte/query_graph/sql/adapter/snowflake.py
- tests/integration/api/test_target_correctness.py
- tests/unit/query_graph/sql/adapter/base_adapter_test.py
- tests/unit/query_graph/sql/adapter/test_bigquery.py
- tests/unit/query_graph/sql/adapter/test_databricks_unity.py
- tests/unit/query_graph/sql/adapter/test_snowflake.py
- tests/unit/query_graph/sql/adapter/test_spark.py
This fixes a bug where features / targets with boolean dtype are materialized as string type in the data warehouse.
> [DEV-4063] Fix conversion of bool dtype to physical data type

- featurebyte/worker/__init__.py
- featurebyte/worker/loader.py
Use custom loader to remove prefetch behavior in celery workers
> [chore] Use custom loader to remove prefetch behavior in celery workers

- .github/workflows/dependencies.yaml
- .github/workflows/documentation.yaml
- .github/workflows/lint.yaml
- .github/workflows/publish-dev.yaml
- .github/workflows/publish-public.yaml
- .github/workflows/test-notebooks.yaml
- .github/workflows/test.yaml
Not respecting python version usage leading to `poetry install` failure in some packages
```
Run actions/setup-python@v5
with:
python-version: 3.10.14
check-latest: false
token: ***
update-environment: true
allow-prereleases: false
freethreaded: false
```
| …
> [chore] poetry workflow is currently using the system python

- Taskfile.yaml
- featurebyte/service/table_columns_info.py
- tests/integration/api/test_entity_tagging.py
- tests/integration/conftest.py
- tests/unit/api/test_event_table.py
- tests/unit/service/test_table_columns_info.py
> [chore] Relax entity dtype validation except for bigquery (cherry-pick)

- featurebyte/query_graph/model/common_table.py
- featurebyte/routes/managed_view/controller.py
- featurebyte/schema/managed_view.py
- featurebyte/schema/table.py
- featurebyte/service/managed_view.py
- featurebyte/session/base.py
- tests/fixtures/request_payloads/dimension_table.json
- tests/fixtures/request_payloads/event_table.json
- tests/fixtures/request_payloads/item_table.json
- tests/fixtures/request_payloads/managed_view.json
- tests/fixtures/request_payloads/scd_table.json
- tests/fixtures/request_payloads/time_series_table.json
- tests/unit/api/test_event_table.py
- tests/unit/api/test_time_series_table.py
- tests/unit/models/test_dimension_table.py
- tests/unit/models/test_event_table.py
- tests/unit/models/test_scd_table.py
- tests/unit/models/test_time_series_table.py
- tests/unit/routes/test_managed_view.py
Populate managed views column info in service since it will not be available before the view is created
> [chore] Populate managed views column info in service

- featurebyte/models/catalog.py
- featurebyte/schema/catalog.py
- featurebyte/schema/worker/task/online_store_initialize.py
- featurebyte/service/catalog.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/offline_store_feature_table.py
- featurebyte/worker/task/catalog_online_store_update.py
- tests/fixtures/feature_materialize/initialize_features_no_entity_databricks_unity.sql
- tests/integration/feature_store_integration/test_update_online_store.py
- tests/unit/api/test_catalog.py
- tests/unit/routes/test_catalog.py
- tests/unit/service/conftest.py
- tests/unit/service/test_feature_materialize.py
This adds a catalog setting `populate_offline_feature_tables` to determine whether to populate offline feature tables in deployments when there is no associated online store. …
> [DEV-4080] Add catalog setting to disable populating offline feature tables

- .changelog/DEV-4058.yaml
- featurebyte/query_graph/sql/adapter/base.py
- tests/fixtures/aggregator/expected_forward_aggregator.sql
- tests/fixtures/aggregator/expected_forward_aggregator_offset.sql
- tests/fixtures/expected_preview_sql_category.sql
- tests/fixtures/expected_preview_sql_category_multiple.sql
- tests/unit/query_graph/sql/fixtures/snowflake_double_vector_agg_only.py
- tests/unit/query_graph/sql/fixtures/snowflake_vector_agg_with_normal_agg.py
- tests/unit/query_graph/sql/test_groupby_helper.py
- tests/unit/query_graph/test_asat_aggregator.py
- tests/unit/query_graph/test_item_aggregator.py
- tests/unit/query_graph/test_item_groupby.py
Reduce cap on maximum categories during aggregation to 500 to avoid creating very large feature tables
> [DEV-4058] Reduce cap on maximum categories during aggregation to 500

- featurebyte/session/databricks_unity.py
Since none of `DatabricksSession` nor `BaseSparkSession` implements `list_schemas()`, the fallback `list_schema` call triggers the same method and leads to infinite recursion. …
> fix: DatabricksUnitySession _list_schemas fallback infinite recursion

- featurebyte/query_graph/sql/entity_filter.py
- tests/fixtures/expected_tile_sql_on_demand_event_timestamp_schema.sql
- tests/unit/conftest.py
- tests/unit/query_graph/sql/test_tile.py
Filtering by timestamp when the conditions require conversion such as timestamp parsing can be expensive. This updates the filtering to exclude timestamp from filtering conditions in such cases. This affects historical features computation for tile based features.
| …
> [DEV-4083] perf: Skip timestamp filtering in entity table when conversion is required

- featurebyte/query_graph/graph.py
- featurebyte/query_graph/sql/batch_helper.py
- tests/fixtures/expected_historical_requests_multiple_batches_output_query.sql
This updates `split_nodes` to sort features by source table by including primary table ids as a key when sorting.
> [chore] Sort features by source table in split_nodes

- featurebyte/schema/table.py
- tests/unit/api/test_event_table.py
Limit partition column to only one per table
> [DEV-4092] Limit partition column to only one per table

- featurebyte/service/query_cache.py
- tests/unit/service/test_query_cache_manager.py
Increase default query cache duration to 21 days and make it configurable via an environment variable.
> [chore] Increase default query cache duration to 21 days

- featurebyte/service/preview.py
- tests/fixtures/preview_service/expected_scd_join_with_partition_column_filters.sql
- tests/unit/service/test_preview.py
Follow up to #3033: make sure partition columns filtering is applied only on the primary table. This was already the case due to `sample_on_primary_table`, but this PR updates `_get_partition_column_filters` to do so explicitly. …
> [DEV-4100] Update partition column filters to include only primary table

- featurebyte/query_graph/sql/ast/tile.py
Handle the case where `dtype_metadata` is set but all fields are empty (currently can occur for datetime partition column).
> [chore] Handle empty dtype metadata in get_tile_compute_spec

- featurebyte/query_graph/sql/online_serving.py
- featurebyte/service/feature_materialize.py
- featurebyte/service/online_serving.py
- scripts/enforce_import_rules.py
Set column statistics info when computing batch features. This allows better queries to be generated based on the column statistics, which currently has an effect on time series features.
| …
> [chore] Set column statistics info when computing batch features

- featurebyte/query_graph/sql/ast/input.py
- featurebyte/query_graph/sql/common.py
- featurebyte/query_graph/sql/entity_filter.py
- featurebyte/query_graph/sql/partition_filter.py
- featurebyte/query_graph/sql/partition_filter_helper.py
- tests/fixtures/expected_tile_sql_on_demand_event_timestamp_schema.sql
- tests/fixtures/query_graph/test_partition_filter/varchar_2d_bigquery.sql
- tests/fixtures/query_graph/test_partition_filter/varchar_2d_databricks_unity.sql
- tests/fixtures/query_graph/test_partition_filter/varchar_2d_snowflake.sql
- tests/fixtures/query_graph/test_partition_filter/varchar_2m_bigquery.sql
- tests/fixtures/query_graph/test_partition_filter/varchar_2m_databricks_unity.sql
- tests/fixtures/query_graph/test_partition_filter/varchar_2m_snowflake.sql
- tests/unit/query_graph/sql/test_partition_filter.py
- tests/unit/query_graph/sql/test_partition_filter_helper.py
Changes:
* Use string timestamp filtering for event tables tile computation when timestamp conversion is required 
* Refactor and move handling of buffer periods to `get_partition_filter` for more convenient usage …
> [DEV-4106] Use string timestamp filtering for event tables tile computation

- CHANGELOG.md
- pyproject.toml
Release error on 3.1.1.
Publishing 3.1.2 instead
> [chore][release] yanking 3.1.1 releasing 3.1.2

- featurebyte/service/batch_external_feature_table.py
- tests/fixtures/batch_feature_table_task/expected_batch_external_feature_table_new_databricks_table_queries.sql
Use snapshot date as last primary key for external feature table
> [chore] Use snapshot date as last primary key for external feature table

- featurebyte/api/base_table.py
- featurebyte/api/event_table.py
- featurebyte/api/time_series_table.py
- featurebyte/common/validator.py
- featurebyte/models/event_table.py
- featurebyte/models/time_series_table.py
- featurebyte/query_graph/model/common_table.py
- featurebyte/query_graph/model/dtype.py
- featurebyte/query_graph/sql/ast/input.py
- featurebyte/schema/info.py
- featurebyte/schema/table.py
- featurebyte/service/table_info.py
- featurebyte/session/base_spark.py
- tests/fixtures/query_graph/test_input/partition_column_filters_no_dtype_metadata.sql
- tests/fixtures/request_payloads/time_series_table.json
- tests/integration/session/test_spark.py
- tests/unit/api/test_dimension_table.py
- tests/unit/api/test_event_table.py
- tests/unit/api/test_item_table.py
- tests/unit/api/test_scd_table.py
- tests/unit/api/test_time_series_table.py
- tests/unit/models/test_dimension_table.py
- tests/unit/models/test_event_table.py
- tests/unit/models/test_scd_table.py
- tests/unit/models/test_time_series_table.py
- tests/unit/query_graph/sql/ast/test_input.py
- tests/unit/session/test_databricks_session.py
[DEV-4136] Apply partition column filters only when dtype_metadata exists (#3085)
[chore] Include datetime partition details in table get response (#3084) …
> [chore] Cherry-pick recent fixes

- featurebyte/service/feature_store_warehouse.py
- tests/unit/routes/test_feature_store.py
Fix database listing caching not including keyword arguments in hash
> [chore] Fix bug with database listing caching

- featurebyte/service/feature_table_cache.py
- featurebyte/service/target_helper/base_feature_or_target_computer.py
- featurebyte/worker/task/historical_feature_table.py
Fixes premature 100% progress updates in historical feature table creation. Progress now reaches 100% only when all operations are actually complete. …
> [chore] Refine progress tracking in historical feature table creation

- featurebyte/models/development_dataset.py
- tests/unit/models/test_development_dataset.py
@kchua78 A small PR for dev dataset to force EMPTY status If status is set to ACTIVE but there are no tables.
> Dev Dataset: If status is set to ACTIVE but there are no tables, force EMPTY

- featurebyte/service/feature_store_table_cleanup.py
- featurebyte/sql/tile_generate.py
- tests/unit/service/test_feature_store_table_cleanup.py
Fix error in feature store cleanup task by correcting parameter name when calling `drop_table`: use `if_exists` instead of invalid `exists`. …
> [chore] Fix feature store table cleanup task drop_table calls

- featurebyte/worker/task/observation_table.py
- featurebyte/worker/task/target_table.py
- tests/unit/routes/test_observation_table.py
- Add missing default eda table tagging logic to target table
- Observation table must have matching target namespace
> [chore] Fix use case default eda table auto tagging logic

- featurebyte/service/observation_table.py
- tests/unit/routes/test_observation_table.py
Auto tag default preview table for context and use case only if observation table purpose is tagged as "preview"
> [chore] Fix default preview table auto tagging logic during observation table creation

- .changelog/DEV-4170.yaml
- featurebyte/query_graph/node/count_dict.py
- tests/unit/api/test_feature.py
Fix dtype derivation for count_dict.get_value when the parent aggregation yields an OBJECT dictionary column by normalizing to FLOAT to prevent incorrect dtype propagation. …
> [DEV-4170] Fix dtype derivation for `count_dict.get_value`
